# Lote 4 · Ley 40/2015 (L40), Título preliminar: disposiciones generales, órganos, potestad sancionadora,
# responsabilidad patrimonial y convenios (arts. 1-37 y 47-53) · bloque III
# Se excluyen el art. 50 (nombres de ministerios desfasados) y el art. 52.2 (incisos declarados inconstitucionales).
# Formato: (bloque, tipo, artículo, pregunta, respuesta correcta, [3 distractores], ancla de la cita en el texto del BOE)
NORMA, LOTE, INICIO = 'L40', 'lote-004', 4001
PREGUNTAS = [
('III', 'test', 'a2', 'Según el artículo 2.2, ¿cuál de los siguientes NO integra el sector público institucional?', 'Las Entidades que integran la Administración Local',
 ['Las Universidades públicas', 'Las entidades de derecho privado vinculadas o dependientes de las Administraciones Públicas', 'Los organismos públicos y entidades de derecho público vinculados o dependientes de las Administraciones Públicas'],
 r're:El sector público institucional se integra por: a\).*?c\) Las Universidades públicas'),
('III', 'test', 'a2', '¿Cuál de las siguientes entidades NO tiene la consideración de Administración Pública según el artículo 2.3?', 'Las entidades de derecho privado vinculadas o dependientes de las Administraciones Públicas',
 ['La Administración General del Estado', 'Las Entidades que integran la Administración Local', 'Los organismos públicos y entidades de derecho público vinculados o dependientes de las Administraciones Públicas'],
 'Tienen la consideración de Administraciones Públicas la Administración General del Estado'),
('III', 'test', 'a2', 'Según el artículo 2.2.c), las Universidades públicas se rigen:', 'Por su normativa específica y supletoriamente por las previsiones de la Ley 40/2015',
 ['Exclusivamente por la Ley 40/2015', 'Por la legislación de contratos del sector público', 'Exclusivamente por el Derecho privado'],
 'Las Universidades públicas que se regirán por su normativa específica y supletoriamente por las previsiones de la presente Ley'),
('III', 'test', 'a3', '¿Cuál de los siguientes NO figura entre los principios que las Administraciones Públicas deben respetar en su actuación y relaciones según el artículo 3.1?', 'Seguridad jurídica',
 ['Buena fe, confianza legítima y lealtad institucional', 'Simplicidad, claridad y proximidad a los ciudadanos', 'Responsabilidad por la gestión pública'],
 r're:Deberán respetar en su actuación y relaciones los siguientes principios: a\).*?k\) Cooperación, colaboración y coordinación entre las Administraciones Públicas'),
('III', 'test', 'a3', 'Según el artículo 3.4, cada una de las Administraciones Públicas actúa para el cumplimiento de sus fines con:', 'Personalidad jurídica única',
 ['Personalidad jurídica propia de cada uno de sus órganos', 'Autonomía financiera plena', 'Personalidad jurídica múltiple'], 'actúa para el cumplimiento de sus fines con personalidad jurídica única'),
('III', 'test', 'a3', 'Según el artículo 3.2, las Administraciones Públicas se relacionarán entre sí y con sus órganos, organismos públicos y entidades vinculados o dependientes a través de:', 'Medios electrónicos',
 ['Correo postal certificado', 'Medios electrónicos o en papel, a su elección', 'Correo ordinario, salvo urgencia'], 'a través de medios electrónicos, que aseguren la interoperabilidad'),
('III', 'test', 'a4', 'Según el artículo 4.1, las Administraciones Públicas que establezcan medidas que limiten el ejercicio de derechos deberán aplicar el principio de proporcionalidad y elegir:', 'La medida menos restrictiva',
 ['La medida más eficaz', 'La medida de menor coste económico', 'La medida que determine el órgano superior'], 'deberán aplicar el principio de proporcionalidad y elegir la medida menos restrictiva'),
('III', 'test', 'a5', 'Según el artículo 5.1, son órganos administrativos las unidades administrativas a las que se atribuyan funciones que tengan efectos jurídicos frente a terceros, o:', 'Cuya actuación tenga carácter preceptivo',
 ['Que dispongan de presupuesto propio', 'Que estén integradas por tres o más personas', 'Cuyo titular tenga rango de Director general'], 'o cuya actuación tenga carácter preceptivo'),
('III', 'test', 'a5', '¿Cuál de los siguientes NO es un requisito mínimo para la creación de un órgano administrativo según el artículo 5.3?', 'El informe favorable del Consejo de Estado',
 ['La delimitación de sus funciones y competencias', 'La dotación de los créditos necesarios para su puesta en marcha y funcionamiento', 'La determinación de su forma de integración en la Administración Pública y su dependencia jerárquica'],
 r're:exigirá, al menos, el cumplimiento de los siguientes requisitos: a\).*?c\) Dotación de los créditos necesarios para su puesta en marcha y funcionamiento'),
('III', 'test', 'a5', 'Según el artículo 5.4, no podrán crearse nuevos órganos que supongan duplicación de otros ya existentes si al mismo tiempo no:', 'Se suprime o restringe debidamente la competencia de estos',
 ['Se obtiene autorización del Consejo de Ministros', 'Se informa a las Cortes Generales', 'Se publica la creación en el «Boletín Oficial del Estado»'], 'si al mismo tiempo no se suprime o restringe debidamente la competencia de estos'),
('III', 'test', 'a6', '¿Mediante qué pueden los órganos administrativos dirigir las actividades de sus órganos jerárquicamente dependientes?', 'Mediante instrucciones y órdenes de servicio',
 ['Mediante encomiendas de gestión', 'Mediante convenios', 'Mediante reales decretos'], 'mediante instrucciones y órdenes de servicio'),
('III', 'test', 'a6', 'Según el artículo 6.2, el incumplimiento de las instrucciones u órdenes de servicio:', 'No afecta por sí solo a la validez de los actos dictados, sin perjuicio de la responsabilidad disciplinaria',
 ['Determina la nulidad de pleno derecho de los actos dictados', 'Determina la anulabilidad de los actos dictados', 'No puede dar lugar a responsabilidad disciplinaria'],
 'El incumplimiento de las instrucciones u órdenes de servicio no afecta por sí solo a la validez'),
('III', 'test', 'a8', 'Según el artículo 8.1, la competencia es:', 'Irrenunciable',
 ['Renunciable, con autorización del superior jerárquico', 'Libremente transferible a cualquier órgano', 'Delegable en todo caso'], 'La competencia es irrenunciable'),
('III', 'test', 'a8', 'Según el artículo 8, ¿cuál de las siguientes figuras puede afectar a la titularidad de la competencia, y no solo a su ejercicio?', 'La desconcentración',
 ['La delegación de competencias', 'La encomienda de gestión', 'La delegación de firma'],
 r're:La delegación de competencias, las encomiendas de gestión, la delegación de firma y la suplencia no suponen alteración de la titularidad de la competencia.*?La titularidad y el ejercicio de las competencias atribuidas a los órganos administrativos podrán ser desconcentradas'),
('III', 'test', 'a8', 'Si una disposición atribuye la competencia a una Administración sin especificar el órgano que debe ejercerla, la facultad de instruir y resolver corresponde a:',
 'Los órganos inferiores competentes por razón de la materia y del territorio',
 ['El órgano superior de esa Administración', 'El titular del Departamento ministerial', 'El órgano que designe el Consejo de Ministros'],
 'corresponde a los órganos inferiores competentes por razón de la materia y del territorio'),
('III', 'test', 'a9', 'Según el artículo 9.2, ¿cuál de las siguientes competencias figura entre las que en ningún caso pueden ser objeto de delegación?', 'La adopción de disposiciones de carácter general',
 ['La resolución de procedimientos sancionadores', 'La firma de convenios con particulares', 'La contratación de suministros'], 'La adopción de disposiciones de carácter general'),
('III', 'test', 'a9', 'Según el artículo 9.2.c), no puede delegarse la resolución de recursos:', 'En los órganos administrativos que hayan dictado los actos objeto de recurso',
 ['En los órganos superiores jerárquicos', 'En los organismos públicos vinculados', 'En ningún otro órgano de la misma Administración'],
 'La resolución de recursos en los órganos administrativos que hayan dictado los actos objeto de recurso'),
('III', 'test', 'a9', 'Las delegaciones de competencias y su revocación:', 'Deberán publicarse en el boletín oficial que corresponda según la Administración a que pertenezca el órgano delegante',
 ['No requieren publicación para su validez', 'Solo deben notificarse a los interesados', 'Deben ser autorizadas por el Consejo de Estado'], 'Las delegaciones de competencias y su revocación deberán publicarse'),
('III', 'test', 'a9', 'Las resoluciones administrativas que se adopten por delegación se considerarán dictadas por:', 'El órgano delegante',
 ['El órgano delegado', 'El superior jerárquico común', 'Ambos órganos conjuntamente'], 'se considerarán dictadas por el órgano delegante'),
('III', 'test', 'a9', 'Salvo autorización expresa de una Ley, ¿pueden delegarse las competencias que se ejerzan por delegación?', 'No',
 ['Sí, con autorización del órgano delegante', 'Sí, si el nuevo delegado es jerárquicamente dependiente', 'Sí, siempre que se publique en el boletín oficial'],
 'Salvo autorización expresa de una Ley, no podrán delegarse las competencias que se ejerzan por delegación'),
('III', 'test', 'a9', 'La delegación de competencias será revocable:', 'En cualquier momento por el órgano que la haya conferido',
 ['Solo transcurrido un año desde su otorgamiento', 'Solo por el superior jerárquico del órgano delegante', 'Solo con el consentimiento del órgano delegado'], 'La delegación será revocable en cualquier momento por el órgano que la haya conferido'),
('III', 'test', 'a9', 'El acuerdo de delegación de competencias atribuidas a órganos colegiados, para cuyo ejercicio se requiera un quórum o mayoría especial:', 'Deberá adoptarse observando, en todo caso, dicho quórum o mayoría',
 ['Puede adoptarse por mayoría simple', 'Está prohibido', 'Requiere unanimidad'], 'deberá adoptarse observando, en todo caso, dicho quórum o mayoría'),
('III', 'test', 'a10', 'Contra el acuerdo de avocación:', 'No cabe recurso, aunque podrá impugnarse en el que se interponga contra la resolución del procedimiento',
 ['Cabe recurso de alzada', 'Cabe recurso potestativo de reposición', 'Cabe recurso contencioso-administrativo directo e independiente'], 'Contra el acuerdo de avocación no cabrá recurso'),
('III', 'test', 'a10', 'En los supuestos de delegación de competencias en órganos no dependientes jerárquicamente, ¿quién puede avocar el conocimiento de un asunto?', 'Únicamente el órgano delegante',
 ['El superior jerárquico común', 'El órgano delegado', 'Cualquier órgano superior'], 'el conocimiento de un asunto podrá ser avocado únicamente por el órgano delegante'),
('III', 'test', 'a10', 'El acuerdo motivado de avocación deberá notificarse a los interesados en el procedimiento, si los hubiere:', 'Con anterioridad o simultáneamente a la resolución final que se dicte',
 ['Con posterioridad a la resolución final', 'En el plazo de diez días desde su adopción', 'Solo si lo solicitan expresamente'], 'con anterioridad o simultáneamente a la resolución final que se dicte'),
('III', 'test', 'a11', 'La encomienda de gestión tiene por objeto la realización de actividades de carácter:', 'Material o técnico',
 ['Normativo', 'Jurisdiccional', 'Sancionador'], 'La realización de actividades de carácter material o técnico'),
('III', 'test', 'a11', 'Según el artículo 11.2, la encomienda de gestión:', 'No supone cesión de la titularidad de la competencia ni de los elementos sustantivos de su ejercicio',
 ['Supone la cesión de la titularidad de la competencia', 'Traslada al órgano encomendado la responsabilidad de dictar los actos jurídicos que le den soporte', 'Puede tener por objeto prestaciones propias de los contratos'],
 'La encomienda de gestión no supone cesión de la titularidad de la competencia ni de los elementos sustantivos de su ejercicio'),
('III', 'test', 'a11', 'En una encomienda de gestión, el órgano o entidad encomendado tendrá, respecto de los datos personales a los que pueda acceder, la condición de:', 'Encargado del tratamiento',
 ['Responsable del tratamiento', 'Delegado de protección de datos', 'Corresponsable del tratamiento'], 'tendrá la condición de encargado del tratamiento'),
('III', 'test', 'a11', 'La encomienda de gestión entre órganos y Entidades de Derecho Público de distintas Administraciones se formalizará mediante:', 'La firma del correspondiente convenio entre ellas',
 ['Acuerdo del Consejo de Ministros', 'Resolución unilateral del órgano encomendante', 'Orden ministerial conjunta'], 'se formalizará mediante firma del correspondiente convenio entre ellas'),
('III', 'test', 'a12', 'Para su validez, la delegación de firma:', 'No necesita publicación',
 ['Debe publicarse en el «Boletín Oficial del Estado»', 'Debe notificarse a todos los interesados', 'Requiere la aprobación previa del órgano ministerial'],
 'La delegación de firma no alterará la competencia del órgano delegante y para su validez no será necesaria su publicación'),
('III', 'test', 'a13', 'Si no se designa suplente, la competencia del órgano administrativo se ejercerá por:', 'Quien designe el órgano administrativo inmediato superior de quien dependa',
 ['El funcionario de mayor antigüedad del órgano', 'El órgano inferior jerárquico', 'El Subsecretario del Departamento'],
 'Si no se designa suplente, la competencia del órgano administrativo se ejercerá por quien designe el órgano administrativo inmediato superior de quien dependa'),
('III', 'test', 'a13', '¿En qué supuestos pueden ser suplidos temporalmente los titulares de los órganos administrativos?', 'Vacante, ausencia o enfermedad, y cuando haya sido declarada su abstención o recusación',
 ['Solo en caso de enfermedad', 'Solo en caso de vacante', 'Cuando lo solicite cualquier interesado en el procedimiento'],
 'en los supuestos de vacante, ausencia o enfermedad, así como en los casos en que haya sido declarada su abstención o recusación'),
('III', 'test', 'a14', 'Los conflictos de atribuciones sólo podrán suscitarse entre:', 'Órganos de una misma Administración no relacionados jerárquicamente',
 ['Órganos de distintas Administraciones Públicas', 'Órganos de una misma Administración relacionados jerárquicamente', 'Cualesquiera órganos, aunque haya finalizado el procedimiento'],
 'Los conflictos de atribuciones sólo podrán suscitarse entre órganos de una misma Administración no relacionados jerárquicamente'),
('III', 'test', 'a14', 'El órgano administrativo que se estime incompetente para la resolución de un asunto:', 'Remitirá directamente las actuaciones al órgano que considere competente, notificándolo a los interesados',
 ['Archivará el expediente', 'Devolverá la solicitud al interesado para que la presente ante el órgano competente', 'Planteará un conflicto ante el Consejo de Estado'], 'remitirá directamente las actuaciones al órgano que considere competente'),
('III', 'test', 'a16', 'En los órganos colegiados, ¿a quién corresponde velar por la legalidad formal y material de sus actuaciones?', 'Al Secretario',
 ['Al Presidente', 'Al Vicepresidente', 'Al miembro de mayor antigüedad'], 'Corresponderá al Secretario velar por la legalidad formal y material'),
('III', 'test', 'a17', 'Para la válida constitución de un órgano colegiado se requiere la asistencia, presencial o a distancia, del Presidente y del Secretario, o de quienes les suplan, y de:', 'La mitad, al menos, de sus miembros',
 ['Dos tercios de sus miembros', 'Un tercio de sus miembros', 'Todos sus miembros'], 'y la de la mitad, al menos, de sus miembros'),
('III', 'test', 'a17', '¿Puede ser objeto de deliberación o acuerdo de un órgano colegiado un asunto que no figure en el orden del día?', 'Solo si asisten todos los miembros y se declara la urgencia del asunto por el voto favorable de la mayoría',
 ['Nunca', 'Sí, siempre que lo decida el Presidente', 'Sí, si lo solicita un tercio de los miembros'],
 'salvo que asistan todos los miembros del órgano colegiado y sea declarada la urgencia del asunto por el voto favorable de la mayoría'),
('III', 'test', 'a17', 'Los acuerdos de los órganos colegiados serán adoptados por:', 'Mayoría de votos',
 ['Unanimidad', 'Mayoría de dos tercios', 'Mayoría de tres quintos'], 'Los acuerdos serán adoptados por mayoría de votos'),
('III', 'test', 'a17', 'Cuando se asista a distancia, los acuerdos del órgano colegiado se entenderán adoptados:', 'En el lugar donde tenga la sede el órgano colegiado y, en su defecto, donde esté ubicada la presidencia',
 ['En el lugar donde se encuentre el Secretario', 'En el lugar donde se encuentre la mayoría de los miembros', 'En la sede del Ministerio de adscripción'], 'los acuerdos se entenderán adoptados en el lugar donde tenga la sede'),
('III', 'test', 'a17', 'Los miembros de un órgano colegiado que voten en contra o se abstengan:', 'Quedarán exentos de la responsabilidad que, en su caso, pueda derivarse de los acuerdos',
 ['Responderán solidariamente de los acuerdos adoptados', 'Deberán formular obligatoriamente voto particular', 'Perderán su condición de miembros'],
 'Cuando los miembros del órgano voten en contra o se abstengan, quedarán exentos de la responsabilidad'),
('III', 'test', 'a18', '¿Quién levanta el acta de cada sesión que celebre el órgano colegiado?', 'El Secretario',
 ['El Presidente', 'El miembro de menor edad', 'El Vicepresidente'], 'se levantará acta por el Secretario'),
('III', 'test', 'a18', 'El acta de cada sesión del órgano colegiado podrá aprobarse:', 'En la misma reunión o en la inmediata siguiente',
 ['Solo en la reunión inmediata siguiente', 'Solo en la misma reunión', 'En el plazo máximo de un mes'], 'El acta de cada sesión podrá aprobarse en la misma reunión o en la inmediata siguiente'),
('III', 'plazo', 'a19', 'Antelación mínima con la que los miembros de los órganos colegiados de la Administración General del Estado deben recibir la convocatoria con el orden del día', '2 días',
 ['1 día', '3 días', '5 días'], 'Recibir, con una antelación mínima de dos días, la convocatoria'),
('III', 'test', 'a19', 'En los órganos colegiados de la Administración General del Estado, ¿a quién corresponde dirimir con su voto los empates?', 'Al Presidente',
 ['Al Secretario', 'Al Vicepresidente', 'Al miembro de mayor antigüedad'], 'Dirimir con su voto los empates'),
('III', 'test', 'a19', 'En caso de vacante, ausencia o enfermedad, el Presidente de un órgano colegiado de la Administración General del Estado será sustituido por el Vicepresidente que corresponda y, en su defecto, por:',
 'El miembro de mayor jerarquía, antigüedad y edad, por este orden',
 ['El Secretario del órgano', 'El miembro de menor edad', 'El miembro que designe el Ministro'], 'por el miembro del órgano colegiado de mayor jerarquía, antigüedad y edad, por este orden'),
('III', 'test', 'a19', 'El Secretario de un órgano colegiado de la Administración General del Estado que no sea miembro del mismo asiste a las reuniones:', 'Con voz pero sin voto',
 ['Con voz y voto', 'Sin voz ni voto', 'Con voto pero sin voz'], 'Asistir a las reuniones con voz pero sin voto'),
('III', 'plazo', 'a19', 'Formulación por escrito del voto particular por los miembros que discrepen del acuerdo mayoritario (órganos colegiados de la Administración General del Estado)', '2 días',
 ['3 días', '5 días', '10 días'], 'podrán formular voto particular por escrito en el plazo de dos días'),
('III', 'test', 'a19', '¿Quiénes no podrán abstenerse en las votaciones de los órganos colegiados de la Administración General del Estado?',
 'Las autoridades o personal al servicio de las Administraciones Públicas que sean miembros natos en virtud del cargo que desempeñan',
 ['Los representantes de organizaciones representativas de intereses sociales', 'Los miembros designados por su experiencia o conocimientos', 'Ningún miembro, pues todos pueden abstenerse'],
 'No podrán abstenerse en las votaciones quienes por su cualidad de autoridades'),
('III', 'test', 'a20', 'Según el artículo 20.1, los órganos colegiados de la Administración General del Estado están integrados por:', 'Tres o más personas',
 ['Dos o más personas', 'Cinco o más personas', 'Siete o más personas'], 'integrados por tres o más personas'),
('III', 'test', 'a21', '¿Cómo se denomina el órgano colegiado de la Administración General del Estado cuyos miembros proceden de diferentes Ministerios?', 'Órgano colegiado interministerial',
 ['Órgano colegiado ministerial', 'Órgano colegiado interadministrativo', 'Grupo o comisión de trabajo'], 'Órganos colegiados interministeriales, si sus miembros proceden de diferentes Ministerios'),
('III', 'test', 'a22', 'La norma de creación de un órgano colegiado interministerial con competencias decisorias cuyo Presidente tenga rango superior al de Director general debe revestir la forma de:', 'Real Decreto',
 ['Orden ministerial conjunta', 'Orden ministerial', 'Resolución del Subsecretario'],
 'deberá revestir la forma de Real Decreto en el caso de los órganos colegiados interministeriales cuyo Presidente tenga rango superior al de Director general'),
('III', 'test', 'a22', 'Respecto de los grupos o comisiones de trabajo de la Administración General del Estado, el artículo 22.3 establece que:', 'Sus acuerdos no podrán tener efectos directos frente a terceros',
 ['Requieren norma específica publicada en el «Boletín Oficial del Estado»', 'Pueden tener competencias decisorias', 'Solo pueden crearse por Real Decreto'], 'Sus acuerdos no podrán tener efectos directos frente a terceros'),
('III', 'test', 'a23', '¿Cuál de los siguientes es motivo de abstención según el artículo 23.2?', 'Tener parentesco de consanguinidad dentro del cuarto grado con cualquiera de los interesados',
 ['Tener parentesco de consanguinidad dentro del quinto grado con cualquiera de los interesados', 'Tener parentesco de afinidad dentro del tercer grado con cualquiera de los interesados', 'Haber coincidido con un interesado en una actividad formativa'],
 'el parentesco de consanguinidad dentro del cuarto grado o de afinidad dentro del segundo'),
('III', 'test', 'a23', '¿Hasta qué grado de parentesco por afinidad con cualquiera de los interesados es motivo de abstención?', 'Dentro del segundo grado',
 ['Dentro del primer grado', 'Dentro del tercer grado', 'Dentro del cuarto grado'], 'parentesco de consanguinidad dentro del cuarto grado o de afinidad dentro del segundo, con cualquiera de los interesados'),
('III', 'test', 'a23', 'Haber prestado servicios profesionales a una persona interesada directamente en el asunto es motivo de abstención si se han prestado en:', 'Los dos últimos años',
 ['El último año', 'Los tres últimos años', 'Los cinco últimos años'], 'haberle prestado en los dos últimos años servicios profesionales'),
('III', 'test', 'a23', 'Quien se encuentre en un motivo de abstención se abstendrá de intervenir en el procedimiento y lo comunicará a:', 'Su superior inmediato, quien resolverá lo procedente',
 ['Los interesados en el procedimiento', 'El Secretario del órgano colegiado', 'La Oficina de Conflictos de Intereses'], 'lo comunicarán a su superior inmediato, quien resolverá lo procedente'),
('III', 'test', 'a23', 'La actuación de autoridades y personal en quienes concurran motivos de abstención:', 'No implicará, necesariamente y en todo caso, la invalidez de los actos en que hayan intervenido',
 ['Determina siempre la nulidad de pleno derecho de los actos', 'Determina siempre la anulabilidad de los actos', 'No da lugar a responsabilidad alguna'], 'no implicará, necesariamente, y en todo caso, la invalidez'),
('III', 'test', 'a24', '¿En qué momento pueden los interesados promover la recusación?', 'En cualquier momento de la tramitación del procedimiento',
 ['Solo en el trámite de audiencia', 'Dentro de los diez días siguientes al inicio del procedimiento', 'Solo antes de la propuesta de resolución'],
 'podrá promoverse recusación por los interesados en cualquier momento de la tramitación del procedimiento'),
('III', 'plazo', 'a24', 'Manifestación del recusado a su inmediato superior sobre si se da o no en él la causa alegada', 'En el día siguiente',
 ['En los 3 días siguientes', 'En los 5 días siguientes', 'En los 10 días siguientes'], 'En el día siguiente el recusado manifestará a su inmediato superior'),
('III', 'plazo', 'a24', 'Resolución del superior cuando el recusado niega la causa de recusación', '3 días',
 ['1 día', '5 días', '10 días'], 'el superior resolverá en el plazo de tres días'),
('III', 'test', 'a24', 'Contra las resoluciones adoptadas en materia de recusación:', 'No cabe recurso, sin perjuicio de alegar la recusación al recurrir el acto que ponga fin al procedimiento',
 ['Cabe recurso de alzada', 'Cabe recurso potestativo de reposición', 'Cabe recurso extraordinario de revisión'], 'Contra las resoluciones adoptadas en esta materia no cabrá recurso'),
('III', 'test', 'a25', 'La potestad sancionadora de las Administraciones Públicas se ejercerá cuando haya sido expresamente reconocida por:', 'Una norma con rango de Ley',
 ['Un reglamento', 'Una orden ministerial', 'Una instrucción u orden de servicio'], 'cuando haya sido expresamente reconocida por una norma con rango de Ley'),
('III', 'test', 'a25', 'Según el artículo 25.3, los principios de la potestad sancionadora son extensivos al ejercicio por las Administraciones Públicas de:', 'Su potestad disciplinaria respecto del personal a su servicio',
 ['Su potestad tributaria', 'Su potestad expropiatoria', 'Sus facultades de dirección en los contratos del sector público'], 'serán extensivas al ejercicio por las Administraciones Públicas de su potestad disciplinaria'),
('III', 'test', 'a25', 'Los principios de la potestad sancionadora NO se aplican respecto de quienes estén vinculados a las Administraciones por relaciones reguladas por:', 'La legislación de contratos del sector público o la legislación patrimonial de las Administraciones Públicas',
 ['La legislación de función pública', 'La legislación tributaria', 'La legislación de tráfico'],
 'por relaciones reguladas por la legislación de contratos del sector público o por la legislación patrimonial'),
('III', 'test', 'a26', 'Las disposiciones sancionadoras producirán efecto retroactivo:', 'En cuanto favorezcan al presunto infractor o al infractor',
 ['En ningún caso', 'Siempre', 'Solo cuando lo acuerde el órgano sancionador'], 'producirán efecto retroactivo en cuanto favorezcan al presunto infractor'),
('III', 'test', 'a27', 'Las infracciones administrativas se clasificarán por la Ley en:', 'Leves, graves y muy graves',
 ['Leves y graves', 'Menos graves, graves y muy graves', 'Leves, menos graves y graves'], 'se clasificarán por la Ley en leves, graves y muy graves'),
('III', 'test', 'a27', 'Las normas definidoras de infracciones y sanciones:', 'No serán susceptibles de aplicación analógica',
 ['Podrán aplicarse por analogía si favorecen al infractor', 'Podrán aplicarse por analogía si lo prevé un reglamento', 'Se interpretarán siempre de forma extensiva'], 'no serán susceptibles de aplicación analógica'),
('III', 'test', 'a28', 'Según el artículo 28.1, sólo pueden ser sancionados por infracciones administrativas quienes resulten responsables de las mismas a título de:', 'Dolo o culpa',
 ['Dolo exclusivamente', 'Responsabilidad objetiva, sin necesidad de culpa', 'Culpa grave exclusivamente'], 'que resulten responsables de los mismos a título de dolo o culpa'),
('III', 'test', 'a28', 'Cuando el cumplimiento de una obligación establecida por una norma con rango de Ley corresponda a varias personas conjuntamente, responderán de las infracciones y sanciones:', 'De forma solidaria',
 ['De forma mancomunada', 'Solo la persona con mayor grado de participación', 'De forma subsidiaria'], 'responderán de forma solidaria de las infracciones'),
('III', 'test', 'a29', 'Como criterio de graduación de la sanción, la reincidencia exige la comisión, en el término de un año, de:', 'Más de una infracción de la misma naturaleza, cuando así haya sido declarado por resolución firme en vía administrativa',
 ['Una sola infracción de cualquier naturaleza', 'Más de una infracción de cualquier naturaleza, aunque no haya resolución firme', 'Tres o más infracciones leves'],
 'La reincidencia, por comisión en el término de un año de más de una infracción de la misma naturaleza cuando así haya sido declarado por resolución firme en vía administrativa'),
('III', 'test', 'a29', 'Cuando de la comisión de una infracción derive necesariamente la comisión de otra u otras:', 'Se impondrá únicamente la sanción correspondiente a la infracción más grave cometida',
 ['Se impondrán todas las sanciones de forma acumulada', 'Se impondrá la sanción de la infracción menos grave', 'Se impondrá la sanción más grave incrementada en un grado'],
 'se deberá imponer únicamente la sanción correspondiente a la infracción más grave cometida'),
('III', 'test', 'a29', 'El establecimiento de sanciones pecuniarias deberá prever que la comisión de las infracciones tipificadas:', 'No resulte más beneficiosa para el infractor que el cumplimiento de las normas infringidas',
 ['Se sancione siempre en su grado máximo', 'Se gradúe únicamente según la capacidad económica del infractor', 'Se exija siempre por la vía de apremio'],
 'no resulte más beneficioso para el infractor que el cumplimiento de las normas infringidas'),
('III', 'test', 'a29', 'La realización de una pluralidad de acciones u omisiones que infrinjan el mismo o semejantes preceptos administrativos, en ejecución de un plan preconcebido o aprovechando idéntica ocasión, será sancionable como:', 'Infracción continuada',
 ['Infracción permanente', 'Reincidencia', 'Infracción muy grave en todo caso'], 'Será sancionable, como infracción continuada'),
('III', 'plazo', 'a30', 'Prescripción de las infracciones muy graves, si las leyes que las establecen no fijan plazo', '3 años',
 ['2 años', '4 años', '5 años'], 'las infracciones muy graves prescribirán a los tres años'),
('III', 'plazo', 'a30', 'Prescripción de las infracciones graves, si las leyes que las establecen no fijan plazo', '2 años',
 ['1 año', '3 años', '4 años'], 'las graves a los dos años y las leves a los seis meses'),
('III', 'plazo', 'a30', 'Prescripción de las infracciones leves, si las leyes que las establecen no fijan plazo', '6 meses',
 ['1 mes', '3 meses', '9 meses'], 'las infracciones muy graves prescribirán a los tres años, las graves a los dos años y las leves a los seis meses'),
('III', 'plazo', 'a30', 'Prescripción de las sanciones impuestas por faltas leves, si las leyes que las establecen no fijan plazo', '1 año',
 ['2 años', '3 años', '4 años'], 'las impuestas por faltas leves al año'),
('III', 'plazo', 'a30', 'Prescripción de las sanciones impuestas por faltas graves, si las leyes que las establecen no fijan plazo', '2 años',
 ['1 año', '3 años', '4 años'], 'las impuestas por faltas graves a los dos años'),
('III', 'test', 'a30', 'En el caso de infracciones continuadas o permanentes, el plazo de prescripción comenzará a correr:', 'Desde que finalizó la conducta infractora',
 ['Desde el día en que se inició la conducta infractora', 'Desde que la Administración tuvo conocimiento de la infracción', 'Desde la incoación del procedimiento sancionador'], 'comenzará a correr desde que finalizó la conducta infractora'),
('III', 'plazo', 'a30', 'Paralización del expediente sancionador, por causa no imputable al presunto responsable, que hace que se reinicie el plazo de prescripción de la infracción', 'Más de 1 mes',
 ['Más de 2 meses', 'Más de 3 meses', 'Más de 6 meses'], 'si el expediente sancionador estuviera paralizado durante más de un mes'),
('III', 'test', 'a31', 'No podrán sancionarse los hechos que lo hayan sido penal o administrativamente, en los casos en que se aprecie identidad de:', 'Sujeto, hecho y fundamento',
 ['Sujeto y hecho', 'Hecho y fundamento', 'Sujeto, hecho y órgano sancionador'], 'en los casos en que se aprecie identidad del sujeto, hecho y fundamento'),
('III', 'test', 'a32', 'Según el artículo 32.2, para ser indemnizable el daño alegado habrá de ser:', 'Efectivo, evaluable económicamente e individualizado con relación a una persona o grupo de personas',
 ['Efectivo y reconocido por sentencia firme', 'Evaluable económicamente y causado por un funcionamiento anormal', 'Individualizado y superior a la cuantía mínima fijada reglamentariamente'],
 'el daño alegado habrá de ser efectivo, evaluable económicamente e individualizado'),
('III', 'test', 'a32', 'Según el artículo 32.1, los particulares tienen derecho a ser indemnizados por las lesiones que sean consecuencia del funcionamiento de los servicios públicos:', 'Normal o anormal, salvo fuerza mayor o daños que el particular tenga el deber jurídico de soportar',
 ['Solo anormal', 'Normal o anormal, incluidos los casos de fuerza mayor', 'Solo anormal y cuando haya culpa del funcionario'],
 'consecuencia del funcionamiento normal o anormal de los servicios públicos salvo en los casos de fuerza mayor'),
('III', 'test', 'a32', 'La anulación en vía administrativa o por el orden contencioso-administrativo de los actos o disposiciones administrativas:', 'No presupone, por sí misma, derecho a la indemnización',
 ['Da derecho automáticamente a indemnización', 'Da derecho a indemnización solo si el acto era nulo de pleno derecho', 'Impide reclamar cualquier indemnización'], 'no presupone, por sí misma, derecho a la indemnización'),
('III', 'test', 'a33', 'Cuando de la gestión dimanante de fórmulas conjuntas de actuación entre varias Administraciones se derive responsabilidad, las Administraciones intervinientes responden frente al particular:', 'En todo caso, de forma solidaria',
 ['De forma mancomunada', 'En proporción a su participación en la financiación', 'Solo la Administración competente por razón de la materia'], 'responderán frente al particular, en todo caso, de forma solidaria'),
('III', 'plazo', 'a33', 'Exposición de lo procedente por las restantes Administraciones implicadas, consultadas en un procedimiento de responsabilidad patrimonial concurrente', '15 días',
 ['10 días', '20 días', '30 días'], 'en el plazo de quince días, éstas puedan exponer'),
('III', 'test', 'a34', 'No serán indemnizables los daños que se deriven de hechos o circunstancias que no se hubiesen podido prever o evitar según:', 'El estado de los conocimientos de la ciencia o de la técnica existentes en el momento de producción de aquéllos',
 ['La jurisprudencia del Tribunal Supremo', 'El criterio del órgano instructor', 'La normativa vigente en el momento de la reclamación'], 'según el estado de los conocimientos de la ciencia o de la técnica'),
('III', 'test', 'a34', 'La cuantía de la indemnización por responsabilidad patrimonial se calculará con referencia al día:', 'En que la lesión efectivamente se produjo',
 ['En que se presentó la reclamación', 'En que se dicte la resolución', 'En que se inició el procedimiento'], 'se calculará con referencia al día en que la lesión efectivamente se produjo'),
('III', 'test', 'a34', 'La cuantía de la indemnización se actualizará a la fecha en que se ponga fin al procedimiento con arreglo a:', 'El Índice de Garantía de la Competitividad',
 ['El Índice de Precios de Consumo', 'El interés legal del dinero', 'El índice de referencia del mercado hipotecario'], 'con arreglo al Índice de Garantía de la Competitividad'),
('III', 'test', 'a34', 'La indemnización podrá sustituirse por una compensación en especie o abonarse mediante pagos periódicos:', 'Cuando resulte más adecuado y convenga al interés público, siempre que exista acuerdo con el interesado',
 ['Por decisión unilateral de la Administración', 'Solo cuando la cuantía supere los 600.000 euros', 'En ningún caso'], 'siempre que exista acuerdo con el interesado'),
('III', 'plazo', 'a34', 'Daños indemnizables, anteriores a la publicación de la sentencia, cuando la lesión deriva de una norma con rango de ley declarada inconstitucional o contraria al Derecho de la Unión Europea', 'Los 5 años anteriores',
 ['Los 3 años anteriores', 'Los 4 años anteriores', 'Los 10 años anteriores'], 'serán indemnizables los daños producidos en el plazo de los cinco años anteriores'),
('III', 'test', 'a36', 'Para hacer efectiva la responsabilidad patrimonial por daños causados por las autoridades y el personal al servicio de las Administraciones, los particulares exigirán las indemnizaciones:', 'Directamente a la Administración Pública correspondiente',
 ['Directamente a la autoridad o empleado causante del daño', 'Ante la jurisdicción civil frente al empleado público', 'A la Administración y al empleado, de forma solidaria'], 'los particulares exigirán directamente a la Administración Pública correspondiente'),
('III', 'test', 'a36', 'La Administración que hubiera indemnizado a los lesionados exigirá de oficio a sus autoridades y demás personal la responsabilidad en que hubieran incurrido por:', 'Dolo, o culpa o negligencia graves',
 ['Cualquier grado de culpa', 'Dolo exclusivamente', 'Culpa o negligencia leves'], 'la responsabilidad en que hubieran incurrido por dolo, o culpa o negligencia graves'),
('III', 'plazo', 'a36', 'Alegaciones en el procedimiento para exigir responsabilidad patrimonial a las autoridades y personal al servicio de las Administraciones', '15 días',
 ['5 días', '10 días', '20 días'], 'Alegaciones durante un plazo de quince días'),
('III', 'plazo', 'a36', 'Audiencia en el procedimiento para exigir responsabilidad patrimonial a las autoridades y personal al servicio de las Administraciones', '10 días',
 ['5 días', '15 días', '20 días'], 'Audiencia durante un plazo de diez días'),
('III', 'test', 'a36', 'La resolución declaratoria de responsabilidad de las autoridades y personal al servicio de las Administraciones:', 'Pondrá fin a la vía administrativa',
 ['Es recurrible en alzada', 'Requiere dictamen del Consejo de Estado para ser firme', 'Solo es ejecutiva tras sentencia judicial'], 'La resolución declaratoria de responsabilidad pondrá fin a la vía administrativa'),
('III', 'test', 'a37', 'La exigencia de responsabilidad penal del personal al servicio de las Administraciones Públicas:', 'No suspenderá los procedimientos de responsabilidad patrimonial, salvo que la determinación de los hechos en el orden penal sea necesaria para fijarla',
 ['Suspende siempre los procedimientos de responsabilidad patrimonial', 'Extingue la responsabilidad patrimonial de la Administración', 'Impide iniciar procedimientos de responsabilidad patrimonial'],
 'no suspenderá los procedimientos de reconocimiento de responsabilidad patrimonial'),
('III', 'test', 'a47', '¿Tienen la consideración de convenios los Protocolos Generales de Actuación que comporten meras declaraciones de intención de contenido general?', 'No, siempre que no supongan la formalización de compromisos jurídicos concretos y exigibles',
 ['Sí, en todo caso', 'Sí, si se publican en el «Boletín Oficial del Estado»', 'Sí, cuando los suscriba la Administración General del Estado'], 'No tienen la consideración de convenios, los Protocolos Generales de Actuación'),
('III', 'test', 'a47', '¿Cómo se denominan los convenios firmados entre organismos públicos y entidades de derecho público vinculados o dependientes de una misma Administración Pública?', 'Convenios intradministrativos',
 ['Convenios interadministrativos', 'Encomiendas de gestión', 'Protocolos generales de actuación'], 'Convenios intradministrativos firmados entre organismos públicos'),
('III', 'test', 'a47', 'Según el artículo 47.1, los convenios no podrán tener por objeto:', 'Prestaciones propias de los contratos',
 ['La utilización de medios y servicios de otra Administración', 'Un fin común de las partes', 'Compromisos financieros'], 'Los convenios no podrán tener por objeto prestaciones propias de los contratos'),
('III', 'test', 'a48', 'Según el artículo 48.1, la suscripción de convenios por las Administraciones Públicas:', 'No puede suponer cesión de la titularidad de la competencia',
 ['Supone la cesión de la titularidad de la competencia', 'Supone la transferencia del personal adscrito', 'Requiere en todo caso una ley habilitante'], 'sin que ello pueda suponer cesión de la titularidad de la competencia'),
('III', 'test', 'a48', 'Los convenios se perfeccionan por:', 'La prestación del consentimiento de las partes',
 ['Su publicación en el «Boletín Oficial del Estado»', 'Su inscripción en el Registro Electrónico estatal de Órganos e Instrumentos de Cooperación', 'Su aprobación por el Consejo de Ministros'],
 'Los convenios se perfeccionan por la prestación del consentimiento de las partes'),
('III', 'plazo', 'a48', 'Inscripción de los convenios de la Administración General del Estado en el Registro Electrónico estatal de Órganos e Instrumentos de Cooperación, desde su formalización', '5 días hábiles',
 ['3 días hábiles', '10 días hábiles', '15 días hábiles'], 'en el plazo de 5 días hábiles desde su formalización'),
('III', 'plazo', 'a48', 'Publicación en el «Boletín Oficial del Estado» de los convenios de la Administración General del Estado, desde su formalización', '10 días hábiles',
 ['5 días hábiles', '15 días hábiles', '20 días hábiles'], 'serán publicados en el plazo de 10 días hábiles desde su formalización'),
('III', 'test', 'a48', 'Las aportaciones financieras que se comprometan a realizar los firmantes de un convenio:', 'No podrán ser superiores a los gastos derivados de la ejecución del convenio',
 ['Deberán ser iguales para todos los firmantes', 'Podrán superar los gastos si se justifica en la memoria', 'No podrán superar en ningún caso los 600.000 euros'], 'no podrán ser superiores a los gastos derivados de la ejecución del convenio'),
('III', 'test', 'a49', 'A falta de regulación expresa, la modificación del contenido de un convenio requerirá:', 'Acuerdo unánime de los firmantes',
 ['Acuerdo de la mayoría de los firmantes', 'Autorización del Consejo de Ministros', 'Decisión de la comisión de seguimiento'], 'la modificación del contenido del convenio requerirá acuerdo unánime de los firmantes'),
('III', 'test', 'a51', 'Según el artículo 51.1, los convenios se extinguen:', 'Por el cumplimiento de las actuaciones que constituyen su objeto o por incurrir en causa de resolución',
 ['Por el transcurso de cuatro años en todo caso', 'Por la revocación unilateral de cualquiera de las partes', 'Por el cese del titular del órgano que lo firmó'],
 'Los convenios se extinguen por el cumplimiento de las actuaciones que constituyen su objeto'),
('III', 'test', 'a51', '¿Cuál de las siguientes NO es causa de resolución de los convenios según el artículo 51.2?', 'El cambio de titular del órgano firmante',
 ['El acuerdo unánime de todos los firmantes', 'La decisión judicial declaratoria de la nulidad del convenio', 'El transcurso del plazo de vigencia sin haberse acordado la prórroga'],
 r're:Son causas de resolución: a\).*?d\) Por decisión judicial declaratoria de la nulidad del convenio'),
('III', 'plazo', 'a53', 'Remisión electrónica al Tribunal de Cuentas de los convenios cuyos compromisos económicos superen 600.000 euros, desde su suscripción', '3 meses',
 ['1 mes', '2 meses', '6 meses'], 'Dentro de los tres meses siguientes a la suscripción'),
('III', 'test', 'a53', 'Deben remitirse al Tribunal de Cuentas u órgano externo de fiscalización autonómico los convenios cuyos compromisos económicos asumidos superen:', '600.000 euros',
 ['150.000 euros', '300.000 euros', '1.000.000 de euros'], 'cuyos compromisos económicos asumidos superen los 600.000 euros'),
]
