# Lote 15 · Ley 40/2015: funcionamiento electrónico del sector público (arts. 38-46 bis, bloque II, tema II.3
# «Administración electrónica») y relaciones interadministrativas (arts. 140-158, bloque III, tema III.3).
NORMA, LOTE, INICIO = 'L40', 'lote-015', 15001
T, P = 'test', 'plazo'
PREGUNTAS = [
('II', T, 'a38', 'Según el artículo 38 de la Ley 40/2015, la sede electrónica es:', 'La dirección electrónica, disponible para los ciudadanos a través de redes de telecomunicaciones, cuya titularidad corresponde a una Administración Pública u organismo o entidad de Derecho Público',
 ['Cualquier página web que contenga información administrativa', 'El registro electrónico general de cada Administración', 'El punto de acceso electrónico que permite acceder a la información publicada'],
 'La sede electrónica es aquella dirección electrónica, disponible para los ciudadanos a través de redes de telecomunicaciones'),
('II', T, 'a38', 'El establecimiento de una sede electrónica conlleva la responsabilidad del titular respecto de:', 'La integridad, veracidad y actualización de la información y los servicios accesibles a través de ella',
 ['Solo la seguridad de las comunicaciones', 'La disponibilidad de Internet de los ciudadanos', 'El contenido de las páginas enlazadas de terceros'],
 'conlleva la responsabilidad del titular respecto de la integridad, veracidad y actualización de la información'),
('II', T, 'a38', 'En todo caso, en la sede electrónica deberá garantizarse:', 'La identificación del órgano titular de la sede y los medios disponibles para formular sugerencias y quejas',
 ['La publicación de los datos personales de los empleados', 'El acceso sin identificación a todos los expedientes', 'La disponibilidad de atención telefónica permanente'],
 'En todo caso deberá garantizarse la identificación del órgano titular de la sede'),
('II', T, 'a38', 'Para identificarse y garantizar una comunicación segura, las sedes electrónicas utilizarán:', 'Certificados reconocidos o cualificados de autenticación de sitio web o medio equivalente',
 ['El DNI electrónico del titular del órgano', 'Un código seguro de verificación', 'Una contraseña de acceso única'],
 'utilizarán, para identificarse y garantizar una comunicación segura con las mismas, certificados reconocidos o cualificados de autenticación de sitio web'),
('II', T, 'a39', 'El punto de acceso electrónico cuya titularidad corresponde a una Administración y que permite acceder por Internet a la información publicada y, en su caso, a la sede electrónica, es:', 'El portal de internet',
 ['La sede electrónica', 'El registro electrónico', 'La carpeta ciudadana'], 'Se entiende por portal de internet el punto de acceso electrónico'),
('II', T, 'a40', 'Las Administraciones Públicas pueden identificarse mediante:', 'Un sello electrónico basado en un certificado electrónico reconocido o cualificado',
 ['La firma manuscrita digitalizada de su titular', 'Una dirección de correo electrónico oficial', 'El número de registro de entrada'],
 'Las Administraciones Públicas podrán identificarse mediante el uso de un sello electrónico'),
('II', T, 'a40', 'Se entiende identificada la Administración Pública respecto de la información que publique como propia en:', 'Su portal de internet',
 ['Cualquier red social', 'El Boletín Oficial del Estado exclusivamente', 'Los medios de comunicación'], 'Se entenderá identificada la Administración Pública respecto de la información que se publique como propia en su portal de internet'),
('II', T, 'a41', 'La actuación administrativa automatizada es cualquier acto o actuación realizada íntegramente por medios electrónicos en un procedimiento administrativo y en la que:', 'No haya intervenido de forma directa un empleado público',
 ['Haya intervenido un empleado público con firma electrónica', 'El interesado haya actuado por medios electrónicos', 'Se haya utilizado un registro electrónico'],
 'en la que no haya intervenido de forma directa un empleado público'),
('II', T, 'a41', 'En caso de actuación administrativa automatizada debe indicarse previamente, entre otros extremos:', 'El órgano que debe ser considerado responsable a efectos de impugnación',
 ['El nombre del programador del sistema', 'La empresa que suministró el programa', 'El coste del sistema de información'],
 'se indicará el órgano que debe ser considerado responsable a efectos de impugnación'),
('II', T, 'a42', 'En la actuación administrativa automatizada, cada Administración puede utilizar como sistemas de firma electrónica:', 'El sello electrónico y el código seguro de verificación',
 ['La firma manuscrita escaneada', 'El certificado personal del ciudadano', 'Únicamente la firma del titular del órgano'],
 r're:podrá determinar los supuestos de utilización de los siguientes sistemas de firma electrónica: a\) Sello electrónico.*?b\) Código seguro de verificación'),
('II', T, 'a43', 'Por razones de seguridad pública, los sistemas de firma electrónica del personal de las Administraciones podrán referirse solo a:', 'El número de identificación profesional del empleado público',
 ['El nombre de la unidad administrativa', 'El DNI del empleado', 'El código del puesto de trabajo'], 'podrán referirse sólo el número de identificación profesional del empleado público'),
('II', T, 'a44', 'Cuando los participantes en un entorno cerrado de comunicaciones pertenezcan a distintas Administraciones, las condiciones y garantías se establecen mediante:', 'Convenio suscrito entre ellas',
 ['Real Decreto del Consejo de Ministros', 'Resolución unilateral de la Administración emisora', 'Orden del Ministro competente'],
 'las condiciones y garantías citadas en el apartado anterior se establecerán mediante convenio suscrito entre aquellas'),
('II', T, 'a46', 'Según el artículo 46, los documentos utilizados en las actuaciones administrativas se almacenarán:', 'Por medios electrónicos, salvo cuando no sea posible',
 ['En papel y, adicionalmente, en soporte electrónico', 'En el soporte que elija cada unidad', 'Solo en archivos centrales en papel'],
 'Todos los documentos utilizados en las actuaciones administrativas se almacenarán por medios electrónicos, salvo cuando no sea posible'),
('II', T, 'a46', 'Los medios o soportes en que se almacenen documentos electrónicos deberán contar con medidas de seguridad de acuerdo con:', 'El Esquema Nacional de Seguridad',
 ['El Esquema Nacional de Interoperabilidad exclusivamente', 'La Ley de Patrimonio Histórico', 'El Reglamento del Registro Mercantil'],
 'deberán contar con medidas de seguridad, de acuerdo con lo previsto en el Esquema Nacional de Seguridad'),
('II', T, 'a4-2', 'Los sistemas de información para la gestión del censo electoral, los padrones municipales y los datos de los usuarios del sistema nacional de salud deberán ubicarse y prestarse:', 'Dentro del territorio de la Unión Europea',
 ['Dentro del territorio español exclusivamente', 'En cualquier país con convenio con España', 'En los servidores de la Administración General del Estado'],
 'deberán ubicarse y prestarse dentro del territorio de la Unión Europea'),
# Relaciones interadministrativas
('III', T, 'a140', '¿Cuál de los siguientes NO figura entre los principios de las relaciones interadministrativas del artículo 140?', 'Jerarquía entre Administraciones territoriales',
 ['Lealtad institucional', 'Solidaridad interterritorial', 'Eficiencia en la gestión de los recursos públicos'],
 r're:de acuerdo con los siguientes principios: a\) Lealtad institucional\..*?i\) Solidaridad interterritorial de acuerdo con la Constitución'),
('III', T, 'a140', 'El principio por el que dos o más Administraciones, de manera voluntaria y en ejercicio de sus competencias, asumen compromisos específicos en aras de una acción común es el de:', 'Cooperación',
 ['Colaboración', 'Coordinación', 'Lealtad institucional'], 'd) Cooperación, cuando dos o más Administraciones Públicas, de manera voluntaria'),
('III', T, 'a140', 'El deber de actuar con el resto de Administraciones Públicas para el logro de fines comunes corresponde al principio de:', 'Colaboración',
 ['Cooperación', 'Coordinación', 'Responsabilidad'], 'c) Colaboración, entendido como el deber de actuar con el resto de Administraciones Públicas para el logro de fines comunes'),
('III', T, 'a140', 'El principio en virtud del cual una Administración, singularmente la AGE, tiene la obligación de garantizar la coherencia de las actuaciones de las diferentes Administraciones afectadas por una misma materia es el de:', 'Coordinación',
 ['Cooperación', 'Colaboración', 'Eficiencia'], 'e) Coordinación, en virtud del cual una Administración Pública'),
('III', T, 'a141', 'La asistencia y colaboración requerida a otra Administración puede negarse, entre otros casos, cuando:', 'La información solicitada tenga carácter confidencial o reservado',
 ['La Administración solicitante sea de otro nivel territorial', 'La solicitud se presente por medios electrónicos', 'No exista convenio previo'],
 'o cuando la información solicitada tenga carácter confidencial o reservado'),
('III', T, 'a141', 'La negativa a prestar la asistencia solicitada por otra Administración:', 'Se comunicará motivadamente a la Administración solicitante',
 ['No necesita comunicarse', 'Debe autorizarla el Consejo de Ministros', 'Solo puede acordarse por ley'], 'La negativa a prestar la asistencia se comunicará motivadamente a la Administración solicitante'),
('III', T, 'a143', 'La formalización de relaciones de cooperación entre Administraciones requiere:', 'La aceptación expresa de las partes, en acuerdos de órganos de cooperación o en convenios',
 ['Una ley de las Cortes Generales', 'La aprobación del Consejo de Ministros en todo caso', 'La mera comunicación de una de las partes'],
 'La formalización de relaciones de cooperación requerirá la aceptación expresa de las partes'),
('III', T, 'a144', 'Cada Administración Pública mantendrá actualizado un registro electrónico de:', 'Los órganos de cooperación en los que participe y de los convenios que haya suscrito',
 ['Todos los empleados públicos de las demás Administraciones', 'Las subvenciones recibidas de otras Administraciones', 'Las sentencias que le afecten'],
 'Cada Administración Pública mantendrá actualizado un registro electrónico de los órganos de cooperación en los que participe y de convenios que haya suscrito'),
('III', T, 'a145', 'Los órganos de cooperación en los que participe la AGE deben inscribirse, para que sea válida su sesión constitutiva, en:', 'El Registro estatal de Órganos e Instrumentos de Cooperación',
 ['El Registro Central de Personal', 'El Inventario de Entidades del Sector Público', 'El Registro de Convenios del Tribunal de Cuentas'],
 'deberán inscribirse en el Registro estatal de Órganos e Instrumentos de Cooperación para que resulte válida su sesión constitutiva'),
('III', T, 'a146', 'La Conferencia de Presidentes está presidida por:', 'El Presidente del Gobierno',
 ['El Ministro de Política Territorial', 'El Presidente del Senado', 'El Presidente de la Comunidad Autónoma más antigua'],
 'está formada por el Presidente del Gobierno, que la preside'),
('III', T, 'a146', 'El Comité preparatorio de la Conferencia de Presidentes está formado por:', 'Un Ministro del Gobierno, que lo preside, y un Consejero de cada Comunidad Autónoma',
 ['Los Delegados del Gobierno', 'Los Secretarios de Estado y Subsecretarios', 'Los Presidentes de los Parlamentos autonómicos'],
 'un Comité preparatorio del que forman parte un Ministro del Gobierno, que lo preside, y un Consejero de cada Comunidad Autónoma'),
('III', T, 'a147', 'La Conferencia Sectorial es un órgano de cooperación de composición:', 'Multilateral y ámbito sectorial determinado',
 ['Bilateral y ámbito general', 'Multilateral y ámbito general', 'Bilateral y ámbito sectorial'], 'La Conferencia Sectorial es un órgano de cooperación, de composición multilateral y ámbito sectorial determinado'),
('III', T, 'a147', 'Preside la Conferencia Sectorial:', 'El miembro del Gobierno competente por razón de la materia',
 ['El Presidente del Gobierno', 'El Consejero autonómico de mayor antigüedad', 'El Secretario de Estado competente'],
 'que reúne, como Presidente, al miembro del Gobierno que, en representación de la Administración General del Estado, resulte competente por razón de la materia'),
('III', T, 'a148', 'Las Conferencias Sectoriales pueden ejercer funciones:', 'Consultivas, decisorias o de coordinación',
 ['Exclusivamente consultivas', 'Legislativas', 'Jurisdiccionales'], 'Las Conferencias Sectoriales pueden ejercer funciones consultivas, decisorias o de coordinación'),
('III', T, 'a149', 'El Ministro que presida la Conferencia Sectorial acordará la convocatoria de sus reuniones por iniciativa propia al menos:', 'Una vez al año',
 ['Una vez al semestre', 'Una vez al trimestre', 'Una vez cada dos años'], 'por iniciativa propia, al menos una vez al año'),
('III', T, 'a149', 'La reunión de la Conferencia Sectorial también se convocará cuando lo solicite, al menos:', 'La tercera parte de sus miembros',
 ['La mitad de sus miembros', 'La cuarta parte de sus miembros', 'Cualquiera de sus miembros'], 'o cuando lo soliciten, al menos, la tercera parte de sus miembros'),
('III', T, 'a150', 'El secretario de la Conferencia Sectorial asiste a sus reuniones:', 'Con voz pero sin voto',
 ['Con voz y voto', 'Sin voz ni voto', 'Con voto de calidad'], 'a) Preparar las reuniones y asistir a ellas con voz pero sin voto'),
('III', T, 'a150', 'El secretario de cada Conferencia Sectorial es designado por:', 'El Presidente de la Conferencia Sectorial',
 ['El pleno de la Conferencia por mayoría', 'El Consejo de Ministros', 'La Comisión Sectorial'], 'Cada Conferencia Sectorial tendrá un secretario que será designado por el Presidente de la Conferencia Sectorial'),
('III', T, 'a151', 'En la Conferencia Sectorial, la votación para adoptar decisiones se produce:', 'Por la representación que cada Administración Pública tenga y no por los distintos miembros de cada una',
 ['Por cada uno de los miembros presentes', 'Por mayoría de población representada', 'Por unanimidad en todo caso'],
 'Esta votación se producirá por la representación que cada Administración Pública tenga y no por los distintos miembros de cada una de ellas'),
('III', T, 'a151', 'La decisión de la Conferencia Sectorial que supone un compromiso de actuación, de obligado cumplimiento y directamente exigible (salvo para quienes hayan votado en contra) es:', 'El Acuerdo',
 ['La Recomendación', 'El Informe', 'El Dictamen'], 'a) Acuerdo: supone un compromiso de actuación en el ejercicio de las respectivas competencias'),
('III', T, 'a151', 'Si un miembro de la Conferencia Sectorial se aparta de una Recomendación que no votó en contra, deberá:', 'Motivarlo e incorporar la justificación en el correspondiente expediente',
 ['Abandonar la Conferencia', 'Pagar una compensación', 'Someterlo al Tribunal Constitucional'], 'Si algún miembro se aparta de la Recomendación, deberá motivarlo'),
('III', T, 'a152', 'La Comisión Sectorial, órgano de trabajo y apoyo de la Conferencia Sectorial, está presidida por:', 'El Secretario de Estado u órgano superior de la AGE designado por el Ministro correspondiente',
 ['El propio Ministro', 'Un Consejero autonómico elegido por turno', 'El Director General competente'],
 'estando constituida por el Secretario de Estado u órgano superior de la Administración General del Estado designado al efecto por el Ministro correspondiente, que la presidirá'),
('III', T, 'a153', 'Las Comisiones Bilaterales de Cooperación reúnen, por un número igual de representantes, a:', 'Miembros del Gobierno y miembros del Consejo de Gobierno de la Comunidad Autónoma o representantes de Ceuta o Melilla',
 ['Diputados y senadores', 'Alcaldes y Presidentes de Diputación', 'Delegados y Subdelegados del Gobierno'],
 'reúnen, por un número igual de representantes, a miembros del Gobierno'),
('III', T, 'a154', 'Las Comisiones Territoriales de Coordinación pueden crearse entre Administraciones:', 'Cuyos territorios sean coincidentes o limítrofes',
 ['De cualquier parte del territorio nacional', 'Solo entre Comunidades Autónomas', 'Solo entre la AGE y las Comunidades Autónomas'],
 'entre Administraciones cuyos territorios sean coincidentes o limítrofes'),
('III', P, 'a155', 'Plazo de la Administración cedente de datos para oponerse motivadamente al tratamiento ulterior que pretenda la cesionaria para una finalidad que estime compatible', '10 días',
 ['15 días', '5 días', '1 mes'], 'La Administración Pública cedente podrá, en el plazo de diez días oponerse motivadamente'),
('III', T, 'a155', 'No se considera incompatible con los fines iniciales el tratamiento ulterior de los datos personales con fines de:', 'Archivo en interés público, investigación científica e histórica o estadísticos',
 ['Publicidad institucional', 'Comercialización a empresas', 'Elaboración de perfiles comerciales'],
 'no se considerará incompatible con los fines iniciales el tratamiento ulterior de los datos personales con fines de archivo en interés público'),
('III', T, 'a156', 'El conjunto de criterios y recomendaciones en materia de seguridad, conservación y normalización de la información, formatos y aplicaciones para garantizar la interoperabilidad es:', 'El Esquema Nacional de Interoperabilidad',
 ['El Esquema Nacional de Seguridad', 'El Plan de Transformación Digital', 'El Catálogo de Procedimientos'],
 'El Esquema Nacional de Interoperabilidad comprende el conjunto de criterios y recomendaciones'),
('III', T, 'a156', 'El Esquema Nacional de Seguridad tiene por objeto:', 'Establecer la política de seguridad en la utilización de medios electrónicos',
 ['Regular la seguridad física de los edificios públicos', 'Regular la protección de datos personales', 'Fijar los formatos de los documentos electrónicos'],
 'El Esquema Nacional de Seguridad tiene por objeto establecer la política de seguridad en la utilización de medios electrónicos'),
('III', T, 'a157', 'Antes de adquirir o desarrollar una aplicación, las Administraciones deben consultar si existen soluciones reutilizables en:', 'El directorio general de aplicaciones dependiente de la AGE',
 ['El Inventario de Entidades del Sector Público', 'La Plataforma de Contratación del Sector Público', 'El Registro de la Propiedad Intelectual'],
 'deberán consultar en el directorio general de aplicaciones, dependiente de la Administración General del Estado'),
('III', T, 'a157', 'Si existe una solución disponible para su reutilización, las Administraciones Públicas:', 'Están obligadas a su uso, salvo que la decisión de no reutilizarla se justifique en términos de eficiencia',
 ['Pueden ignorarla libremente', 'Deben pagar su coste completo en todo caso', 'Necesitan autorización del Consejo de Ministros para usarla'],
 'las Administraciones Públicas estarán obligadas a su uso, salvo que la decisión de no reutilizarla se justifique en términos de eficiencia'),
('III', T, 'a157', 'Las aplicaciones de las Administraciones podrán declararse de fuentes abiertas cuando:', 'Se derive una mayor transparencia en el funcionamiento de la Administración o se fomente la incorporación de los ciudadanos a la Sociedad de la información',
 ['Lo solicite cualquier empresa', 'Su coste sea inferior a 15.000 euros', 'Hayan transcurrido cinco años desde su desarrollo'],
 'podrán ser declaradas como de fuentes abiertas'),
]
