# Lote 21 · Ley 7/1985, reguladora de las Bases del Régimen Local, arts. 1-44 · bloque I (tema I.10: la
# Administración local; entidades que la integran; la provincia, el municipio y la isla).
NORMA, LOTE, INICIO = 'LBRL', 'lote-021', 21001
T, P = 'test', 'plazo'
PREGUNTAS = [
('I', T, 'a1', 'Según la Ley 7/1985, son entidades básicas de la organización territorial del Estado y cauces inmediatos de participación ciudadana en los asuntos públicos:', 'Los Municipios',
 ['Las Provincias', 'Las Comarcas', 'Las Comunidades Autónomas'], 'Los Municipios son entidades básicas de la organización territorial del Estado y cauces inmediatos de participación ciudadana'),
('I', T, 'a3', '¿Cuál de las siguientes NO es una Entidad Local territorial según el artículo 3.1 de la Ley 7/1985?', 'La Comarca',
 ['El Municipio', 'La Provincia', 'La Isla en los archipiélagos balear y canario'],
 'Son Entidades Locales territoriales: a) El Municipio. b) La Provincia. c) La Isla en los archipiélagos balear y canario'),
('I', T, 'a3', 'Las Mancomunidades de Municipios, según la Ley 7/1985:', 'Gozan de la condición de Entidades Locales, sin ser Entidades Locales territoriales',
 ['Son Entidades Locales territoriales', 'No son Entidades Locales', 'Son órganos desconcentrados de la Provincia'],
 r're:Gozan, asimismo, de la condición de Entidades Locales:.*?c\) Las Mancomunidades de Municipios'),
('I', T, 'a4', '¿Cuál de las siguientes potestades corresponde en todo caso a los municipios, las provincias y las islas?', 'La potestad de revisión de oficio de sus actos y acuerdos',
 ['La potestad legislativa', 'La potestad jurisdiccional', 'La potestad de indulto'], 'g) La potestad de revisión de oficio de sus actos y acuerdos'),
('I', T, 'a6', 'El control de legalidad de los acuerdos y actos de las entidades locales lo ejercen:', 'Los Tribunales',
 ['Las Delegaciones del Gobierno', 'Las Diputaciones provinciales', 'El Ministerio de Hacienda'], 'Los Tribunales ejercen el control de legalidad de los acuerdos y actos de las entidades locales'),
('I', T, 'a7', 'Las competencias de las Entidades Locales son:', 'Propias o atribuidas por delegación',
 ['Exclusivas, compartidas o concurrentes', 'Solo propias', 'Solo delegadas por el Estado'], 'Las competencias de las Entidades Locales son propias o atribuidas por delegación'),
('I', T, 'a7', 'Las competencias propias de los Municipios, las Provincias y las Islas solo pueden ser determinadas por:', 'Ley',
 ['Reglamento orgánico municipal', 'Orden ministerial', 'Acuerdo del Pleno de la Diputación'],
 'Las competencias propias de los Municipios, las Provincias, las Islas y demás Entidades Locales territoriales solo podrán ser determinadas por Ley'),
('I', T, 'a11', 'Son elementos del Municipio:', 'El territorio, la población y la organización',
 ['El territorio, el Padrón y el Alcalde', 'La población, el presupuesto y el Pleno', 'El término municipal, los vecinos y la Diputación'],
 'Son elementos del Municipio el territorio, la población y la organización'),
('I', T, 'a12', 'Según la Ley 7/1985, cada municipio pertenecerá:', 'A una sola provincia',
 ['A una o varias provincias', 'A una sola comarca', 'A una sola mancomunidad'], 'Cada municipio pertenecerá a una sola provincia'),
('I', T, 'a13', 'La alteración de términos municipales:', 'No puede suponer en ningún caso modificación de los límites provinciales',
 ['Puede modificar los límites provinciales si lo aprueba la Comunidad Autónoma', 'Corresponde regularla en exclusiva al Estado', 'No requiere audiencia de los municipios interesados'],
 'sin que la alteración de términos municipales pueda suponer, en ningún caso, modificación de los límites provinciales'),
('I', T, 'a13', 'La creación de nuevos municipios solo puede realizarse sobre la base de núcleos de población territorialmente diferenciados de al menos:', '4.000 habitantes',
 ['1.000 habitantes', '5.000 habitantes', '20.000 habitantes'], 'de al menos 4.000 habitantes'),
('I', P, 'a13', 'Tiempo, desde la adopción del convenio de fusión, durante el que el municipio resultante de una fusión no puede segregarse', '10 años',
 ['5 años', '4 años', '20 años'], 'no podrá segregarse hasta transcurridos diez años desde la adopción del convenio de fusión'),
('I', T, 'a14', 'Los cambios de denominación de los Municipios solo tienen carácter oficial cuando, tras ser anotados en el Registro estatal de entidades locales:', 'Se publiquen en el «Boletín Oficial del Estado»',
 ['Los apruebe el Senado', 'Los ratifique el Consejo de Estado', 'Se publiquen en el boletín de la provincia'],
 'se publiquen en el «Boletín Oficial del Estado»'),
('I', T, 'a15', 'Quien viva en varios municipios debe inscribirse en el Padrón:', 'Únicamente del municipio en que habite durante más tiempo al año',
 ['De todos ellos', 'Del municipio en que haya nacido', 'Del municipio que elija libremente'],
 'Quien viva en varios municipios deberá inscribirse únicamente en el que habite durante más tiempo al año'),
('I', T, 'a15', 'La condición de vecino de un municipio se adquiere:', 'En el mismo momento de la inscripción en el Padrón',
 ['Tras un año de residencia', 'Al obtener la autorización del Alcalde', 'Al pagar el primer impuesto municipal'],
 'La condición de vecino se adquiere en el mismo momento de su inscripción en el Padrón'),
('I', T, 'a16', 'Las certificaciones de los datos del Padrón municipal tienen carácter de:', 'Documento público y fehaciente para todos los efectos administrativos',
 ['Documento privado', 'Simple información sin valor probatorio', 'Prueba de la nacionalidad española'],
 'tendrán carácter de documento público y fehaciente para todos los efectos administrativos'),
('I', P, 'a16', 'Periodicidad de renovación de la inscripción padronal de los extranjeros no comunitarios sin autorización de residencia de larga duración', 'Cada 2 años',
 ['Cada año', 'Cada 5 años', 'Cada 4 años'], 'deberá ser objeto de renovación periódica cada dos años'),
('I', T, 'a17', 'La formación, mantenimiento, revisión y custodia del Padrón municipal corresponde:', 'Al Ayuntamiento',
 ['Al Instituto Nacional de Estadística', 'A la Diputación Provincial', 'A la Comunidad Autónoma'],
 'La formación, mantenimiento, revisión y custodia del Padrón municipal corresponde al Ayuntamiento'),
('I', T, 'a18', 'La inscripción de los extranjeros en el padrón municipal:', 'No constituye prueba de su residencia legal en España',
 ['Constituye prueba de su residencia legal en España', 'Les atribuye la nacionalidad tras cinco años', 'Les otorga el derecho de sufragio en las elecciones generales'],
 'La inscripción de los extranjeros en el padrón municipal no constituirá prueba de su residencia legal en España'),
('I', T, 'a18', '¿Cuál de los siguientes es un derecho de los vecinos según el artículo 18 de la Ley 7/1985?', 'Pedir la consulta popular en los términos previstos en la ley',
 ['Nombrar a los Tenientes de Alcalde', 'Aprobar las ordenanzas municipales', 'Elegir al Secretario del Ayuntamiento'],
 'f) Pedir la consulta popular en los términos previstos en la ley'),
('I', T, 'a19', 'Salvo en los municipios en régimen de Concejo Abierto, el gobierno y la administración municipal corresponden:', 'Al ayuntamiento, integrado por el Alcalde y los Concejales',
 ['Al Pleno de la Diputación', 'A la asamblea vecinal', 'Al Alcalde en exclusiva'],
 'corresponde al ayuntamiento, integrado por el Alcalde y los Concejales'),
('I', T, 'a19', 'Según la Ley 7/1985, el Alcalde es elegido:', 'Por los Concejales o por los vecinos, en los términos de la legislación electoral general',
 ['Por el Pleno de la Diputación', 'Por el Delegado del Gobierno', 'Por la Comunidad Autónoma'],
 'el Alcalde es elegido por los Concejales o por los vecinos'),
('I', T, 'a20', '¿Qué órganos existen en todos los ayuntamientos?', 'El Alcalde, los Tenientes de Alcalde y el Pleno',
 ['El Alcalde, la Junta de Gobierno Local y el Pleno', 'El Alcalde y la Comisión Especial de Sugerencias y Reclamaciones', 'El Pleno y los órganos territoriales de gestión desconcentrada'],
 'El Alcalde, los Tenientes de Alcalde y el Pleno existen en todos los ayuntamientos'),
('I', T, 'a20', 'La Junta de Gobierno Local existe en todos los municipios con población superior a:', '5.000 habitantes',
 ['1.000 habitantes', '20.000 habitantes', '50.000 habitantes'], 'La Junta de Gobierno Local existe en todos los municipios con población superior a 5.000 habitantes'),
('I', T, 'a20', 'La Comisión Especial de Cuentas existe:', 'En todos los municipios',
 ['Solo en los municipios de gran población', 'Solo en los municipios de más de 5.000 habitantes', 'Solo cuando lo acuerde el Pleno'],
 'La Comisión Especial de Cuentas existe en todos los municipios'),
('I', T, 'a21', '¿Cuál de las siguientes es una atribución del Alcalde?', 'Dictar bandos',
 ['Aprobar las ordenanzas', 'Aprobar los presupuestos', 'Aprobar la plantilla de personal'], 'd) Dirigir, inspeccionar e impulsar los servicios y obras municipales. e) Dictar bandos'),
('I', T, 'a21', 'En las sesiones del Pleno que preside, el Alcalde decide los empates:', 'Con voto de calidad',
 ['Por sorteo', 'Repitiendo la votación hasta tres veces', 'Remitiendo el asunto a la Junta de Gobierno Local'], 'y decidir los empates con voto de calidad'),
('I', T, 'a21', 'La jefatura de la Policía Municipal corresponde:', 'Al Alcalde',
 ['Al Pleno', 'Al Delegado del Gobierno', 'A la Junta de Gobierno Local'], 'i) Ejercer la jefatura de la Policía Municipal'),
('I', T, 'a22', '¿Cuál de las siguientes atribuciones corresponde al Pleno municipal?', 'La aprobación del reglamento orgánico y de las ordenanzas',
 ['Dictar bandos', 'Ejercer la jefatura de la Policía Municipal', 'Desempeñar la jefatura superior de todo el personal'],
 'd) La aprobación del reglamento orgánico y de las ordenanzas'),
('I', T, 'a22', 'La declaración de lesividad de los actos del Ayuntamiento corresponde:', 'Al Pleno',
 ['Al Alcalde', 'A la Junta de Gobierno Local', 'Al Secretario municipal'], 'k) La declaración de lesividad de los actos del Ayuntamiento'),
('I', T, 'a23', 'La Junta de Gobierno Local se integra por el Alcalde y un número de Concejales:', 'No superior al tercio del número legal de los mismos',
 ['No superior a la mitad del número legal de los mismos', 'Igual al de Tenientes de Alcalde más dos', 'No inferior a la cuarta parte del número legal'],
 'un número de Concejales no superior al tercio del número legal de los mismos'),
('I', T, 'a23', 'Los Tenientes de Alcalde son designados y removidos:', 'Libremente por el Alcalde de entre los miembros de la Junta de Gobierno Local',
 ['Por el Pleno por mayoría absoluta', 'Por los vecinos en elección directa', 'Por la Junta de Gobierno Local'],
 'siendo libremente designados y removidos por éste de entre los miembros de la Junta de Gobierno Local'),
('I', T, 'a24bis', 'Los entes de ámbito territorial inferior al Municipio regulados conforme al artículo 24 bis de la Ley 7/1985:', 'Carecen de personalidad jurídica',
 ['Tienen personalidad jurídica plena', 'Son Entidades Locales territoriales', 'Los crea el Estado'], 'que carecerán de personalidad jurídica'),
('I', T, 'a26', '¿Cuál de los siguientes servicios deben prestar todos los Municipios?', 'Alumbrado público',
 ['Biblioteca pública', 'Transporte colectivo urbano de viajeros', 'Instalaciones deportivas de uso público'],
 'a) En todos los Municipios: alumbrado público'),
('I', T, 'a26', 'Los Municipios con población superior a 5.000 habitantes deben prestar, además de los servicios mínimos generales:', 'Parque público, biblioteca pública y tratamiento de residuos',
 ['Transporte colectivo urbano de viajeros', 'Prevención y extinción de incendios', 'Medio ambiente urbano'],
 'b) En los Municipios con población superior a 5.000 habitantes, además: parque público, biblioteca pública y tratamiento de residuos'),
('I', T, 'a26', 'El transporte colectivo urbano de viajeros es un servicio obligatorio en los Municipios con población superior a:', '50.000 habitantes',
 ['5.000 habitantes', '20.000 habitantes', '100.000 habitantes'],
 'd) En los Municipios con población superior a 50.000 habitantes, además: transporte colectivo urbano de viajeros y medio ambiente urbano'),
('I', T, 'a26', 'En los municipios con población inferior a 20.000 habitantes, coordina la prestación de servicios como la recogida de residuos o el alumbrado público:', 'La Diputación provincial o entidad equivalente',
 ['La Comunidad Autónoma', 'La Delegación del Gobierno', 'La mancomunidad más próxima'],
 'será la Diputación provincial o entidad equivalente la que coordinará la prestación de los siguientes servicios'),
('I', P, 'a27', 'Duración mínima de la delegación de competencias del Estado o de las Comunidades Autónomas en los Municipios', '5 años',
 ['2 años', '4 años', '10 años'], 'que no podrá ser inferior a cinco años'),
('I', T, 'a29', 'La constitución en Concejo Abierto de un municipio por su localización geográfica u otras circunstancias requiere decisión favorable del Ayuntamiento por mayoría de:', 'Dos tercios de sus miembros',
 ['Tres quintos de sus miembros', 'La mitad más uno de sus miembros', 'Tres cuartas partes de sus miembros'],
 'decisión favorable por mayoría de dos tercios de los miembros del Ayuntamiento'),
('I', T, 'a29', 'En el régimen de Concejo Abierto, el gobierno y la administración municipales corresponden a:', 'Un Alcalde y una asamblea vecinal de la que forman parte todos los electores',
 ['Un Alcalde y una Junta de Gobierno Local', 'La Diputación provincial', 'Un Pleno de cinco concejales'],
 'corresponden a un Alcalde y una asamblea vecinal de la que forman parte todos los electores'),
('I', T, 'a29', 'Pueden convocar a sus vecinos a Concejo Abierto para decisiones de especial trascendencia los alcaldes de municipios de menos de:', '100 residentes',
 ['500 residentes', '1.000 residentes', '250 residentes'], 'los alcaldes de las corporaciones de municipios de menos de 100 residentes'),
('I', T, 'a31', 'La Provincia es una entidad local determinada por:', 'La agrupación de Municipios',
 ['La agrupación de Comarcas', 'La división de una Comunidad Autónoma por ley estatal', 'La agrupación de Islas'],
 'La Provincia es una entidad local determinada por la agrupación de Municipios'),
('I', T, 'a31', 'El gobierno y la administración autónoma de la Provincia corresponden a:', 'La Diputación u otras Corporaciones de carácter representativo',
 ['La Subdelegación del Gobierno', 'La Comunidad Autónoma', 'El Gobernador civil'],
 'El gobierno y la administración autónoma de la Provincia corresponden a la Diputación u otras Corporaciones de carácter representativo'),
('I', T, 'a32', '¿Qué órganos existen en todas las Diputaciones?', 'El Presidente, los Vicepresidentes, la Junta de Gobierno y el Pleno',
 ['El Presidente y el Pleno solamente', 'El Presidente, el Pleno y la Comisión Especial de Sugerencias', 'El Gobernador, el Pleno y la Junta de Portavoces'],
 'El Presidente, los Vicepresidentes, la Junta de Gobierno y el Pleno existen en todas las Diputaciones'),
('I', T, 'a33', 'La aprobación de los planes de carácter provincial corresponde:', 'Al Pleno de la Diputación',
 ['Al Presidente de la Diputación', 'A la Junta de Gobierno', 'A la Comunidad Autónoma'], 'd) La aprobación de los planes de carácter provincial'),
('I', T, 'a36', 'La Diputación garantizará en todo caso la prestación de los servicios de secretaría e intervención en los municipios de menos de:', '1.000 habitantes',
 ['5.000 habitantes', '20.000 habitantes', '500 habitantes'], 'En todo caso garantizará en los municipios de menos de 1.000 habitantes la prestación de los servicios de secretaría e intervención'),
('I', T, 'a36', 'La Diputación asume la prestación del servicio de prevención y extinción de incendios, cuando éstos no lo presten, en los municipios de menos de:', '20.000 habitantes',
 ['5.000 habitantes', '1.000 habitantes', '50.000 habitantes'], 'y de prevención y extinción de incendios en los de menos de 20.000 habitantes'),
('I', T, 'a40', 'Las Comunidades Autónomas uniprovinciales y la Foral de Navarra:', 'Asumen las competencias, medios y recursos que corresponden en el régimen ordinario a las Diputaciones Provinciales',
 ['Mantienen una Diputación Provincial separada', 'Carecen de competencias provinciales', 'Ceden las competencias provinciales al Estado'],
 'asumen las competencias, medios y recursos que corresponden en el régimen ordinario a las Diputaciones Provinciales'),
('I', T, 'a41', 'Son órganos de gobierno, administración y representación de cada isla en Canarias:', 'Los Cabildos Insulares',
 ['Los Consejos Insulares', 'Las Diputaciones Provinciales', 'Las Mancomunidades interinsulares'],
 'Los Cabildos Insulares Canarios, como órganos de gobierno, administración y representación de cada isla'),
('I', T, 'a42', 'No puede crearse una comarca si se oponen expresamente:', 'Las dos quintas partes de los Municipios que debieran agruparse en ella, si representan al menos la mitad del censo electoral del territorio',
 ['La mitad de los Municipios afectados, cualquiera que sea su población', 'La Diputación provincial', 'Un solo Municipio afectado'],
 'no podrá crearse la comarca si a ello se oponen expresamente las dos quintas partes de los Municipios que debieran agruparse en ella'),
('I', T, 'a43', 'Las áreas metropolitanas se crean, modifican y suprimen:', 'Por las Comunidades Autónomas mediante Ley',
 ['Por el Estado mediante real decreto', 'Por acuerdo de los Ayuntamientos afectados', 'Por las Diputaciones provinciales'],
 'podrán crear, modificar y suprimir, mediante Ley, áreas metropolitanas'),
('I', T, 'a44', 'Los estatutos de una mancomunidad de municipios los aprueban:', 'Los Plenos de todos los ayuntamientos',
 ['La Diputación provincial', 'La Comunidad Autónoma por decreto', 'Los Alcaldes de los municipios promotores'],
 'c) Los Plenos de todos los ayuntamientos aprueban los estatutos'),
('I', T, 'a44', '¿Pueden integrarse en la misma mancomunidad municipios de distintas comunidades autónomas?', 'Sí, siempre que lo permitan las normativas de las comunidades autónomas afectadas',
 ['No, en ningún caso', 'Sí, con autorización del Senado', 'Solo si pertenecen a la misma provincia'],
 'Podrán integrarse en la misma mancomunidad municipios pertenecientes a distintas comunidades autónomas, siempre que lo permitan las normativas'),
]
