# Lote 8 · LCSP (Ley 9/2017) parte 1: arts. 1-59 (objeto, tipos de contratos, regulación armonizada, régimen,
# duración, medios propios, perfección, invalidez y recurso especial) · bloque III.
# Sin repetir lote-001 (contratos menores, plazo del recurso especial). Se evitan las partes declaradas
# inconstitucionales o con interpretación del TC (arts. 46.4 y 52.3).
NORMA, LOTE, INICIO = 'LCSP', 'lote-008', 8001
T, P = 'test', 'plazo'
PREGUNTAS = [
# Art. 1
('III', T, 'a1', '¿Cuál de los siguientes NO es uno de los principios a los que, según el artículo 1.1, debe ajustarse la contratación del sector público?', 'Preferencia de las empresas con domicilio en el territorio del órgano de contratación',
 ['Libertad de acceso a las licitaciones', 'Publicidad y transparencia de los procedimientos', 'No discriminación e igualdad de trato entre los licitadores'],
 'a los principios de libertad de acceso a las licitaciones, publicidad y transparencia de los procedimientos, y no discriminación e igualdad de trato entre los licitadores'),
('III', T, 'a1', 'Según el artículo 1.1, la eficiente utilización de los fondos públicos se asegura, entre otros medios, mediante la selección de:', 'La oferta económicamente más ventajosa',
 ['La oferta de precio más bajo en todo caso', 'La oferta presentada en primer lugar', 'La oferta de la empresa con mayor volumen de negocios'], 'la selección de la oferta económicamente más ventajosa'),
('III', T, 'a1', 'Según el artículo 1.3, en toda contratación pública los criterios sociales y medioambientales se incorporarán:', 'De manera transversal y preceptiva, siempre que guarden relación con el objeto del contrato',
 ['Solo en los contratos sujetos a regulación armonizada', 'De forma potestativa, a criterio del órgano de contratación', 'Únicamente en los contratos de obras'],
 'se incorporarán de manera transversal y preceptiva criterios sociales y medioambientales'),
# Arts. 13-17: tipos de contratos
('III', T, 'a1-5', 'Por «obra» se entiende el resultado de un conjunto de trabajos de construcción o de ingeniería civil, destinado a cumplir por sí mismo una función económica o técnica, que tenga por objeto:', 'Un bien inmueble',
 ['Un bien mueble', 'Cualquier bien, mueble o inmueble', 'Un servicio público'], 'que tenga por objeto un bien inmueble'),
('III', T, 'a1-5', 'Con carácter general, los contratos de obras se referirán a:', 'Una obra completa, susceptible de ser entregada al uso general o al servicio correspondiente',
 ['Cada una de las unidades de obra por separado', 'La redacción del proyecto exclusivamente', 'Cualquier parte de una obra, aunque no sea susceptible de utilización independiente'],
 'Los contratos de obras se referirán a una obra completa'),
('III', T, 'a1-6', 'En el contrato de concesión de obras, la contraprestación a favor del concesionario consiste:', 'Únicamente en el derecho a explotar la obra, o en dicho derecho acompañado del de percibir un precio',
 ['Exclusivamente en un precio cierto abonado por la Administración', 'En la adquisición de la propiedad de la obra', 'En una subvención a fondo perdido'],
 're:la contraprestación a favor de aquel consiste, o bien únicamente en el derecho a explotar la obra'),
('III', T, 'a1-6', 'El derecho de explotación de las obras en la concesión de obras deberá implicar la transferencia al concesionario de:', 'Un riesgo operacional',
 ['La propiedad de la obra', 'Un riesgo exclusivamente financiero', 'Ningún riesgo, que asume la Administración'], 'deberá implicar la transferencia al concesionario de un riesgo operacional'),
('III', T, 'a1-6', 'El riesgo operacional transferido al concesionario abarca:', 'El riesgo de demanda o el de suministro, o ambos',
 ['Solo el riesgo de construcción', 'Solo el riesgo de tipo de interés', 'El riesgo derivado de las decisiones de la Administración concedente'], 'abarcando el riesgo de demanda o el de suministro, o ambos'),
('III', T, 'a1-7', 'Mediante el contrato de concesión de servicios, uno o varios poderes adjudicadores encomiendan a título oneroso:', 'La gestión de un servicio cuya prestación sea de su titularidad o competencia',
 ['La ejecución de una obra pública', 'La adquisición de productos o bienes muebles', 'El ejercicio de la autoridad inherente a los poderes públicos'],
 'la gestión de un servicio cuya prestación sea de su titularidad o competencia'),
('III', T, 'a1-8', 'Son contratos de suministro los que tienen por objeto:', 'La adquisición, el arrendamiento financiero o el arrendamiento, con o sin opción de compra, de productos o bienes muebles',
 ['La adquisición o el arrendamiento de bienes inmuebles', 'Prestaciones de hacer consistentes en el desarrollo de una actividad', 'La gestión de un servicio público con riesgo operacional'],
 'Son contratos de suministro los que tienen por objeto la adquisición'),
('III', T, 'a1-8', 'Salvo lo previsto para los programas de ordenador, NO tienen la consideración de contrato de suministro los contratos relativos a:', 'Propiedades incorporales o valores negociables',
 ['La adquisición de energía primaria o transformada', 'La fabricación de bienes con características fijadas por la entidad contratante', 'El arrendamiento de equipos para el tratamiento de la información'],
 'no tendrán la consideración de contrato de suministro los contratos relativos a propiedades incorporales o valores negociables'),
('III', T, 'a1-8', 'Los contratos de adquisición de programas de ordenador desarrollados a medida se consideran contratos:', 'De servicios',
 ['De suministro', 'De obras', 'Mixtos de suministro y servicios'], 'a excepción de los contratos de adquisición de programas de ordenador desarrollados a medida, que se considerarán contratos de servicios'),
('III', T, 'a1-8', 'Los contratos que tengan por objeto la adquisición de energía primaria o energía transformada se consideran:', 'Contratos de suministro',
 ['Contratos de servicios', 'Contratos de concesión de servicios', 'Contratos privados excluidos de la Ley'], 'Los que tengan por objeto la adquisición de energía primaria o energía transformada'),
('III', T, 'a1-9', 'Son contratos de servicios aquellos cuyo objeto son:', 'Prestaciones de hacer consistentes en el desarrollo de una actividad o dirigidas a la obtención de un resultado distinto de una obra o suministro',
 ['Prestaciones de dar consistentes en la entrega de bienes muebles', 'Trabajos de construcción que tengan por objeto un bien inmueble', 'La gestión de un servicio con transferencia del riesgo operacional'],
 'cuyo objeto son prestaciones de hacer consistentes en el desarrollo de una actividad'),
('III', T, 'a1-9', '¿Qué NO puede ser objeto de un contrato de servicios?', 'Los servicios que impliquen ejercicio de la autoridad inherente a los poderes públicos',
 ['Las prestaciones dirigidas a la obtención de un resultado distinto de una obra o suministro', 'Los servicios ejecutados de forma sucesiva y por precio unitario', 'El desarrollo de una actividad'],
 'No podrán ser objeto de estos contratos los servicios que impliquen ejercicio de la autoridad'),
('III', T, 'a1-10', 'Cuando un contrato mixto comprenda prestaciones propias de dos o más contratos de obras, suministros o servicios, para su adjudicación se atenderá:', 'Al carácter de la prestación principal',
 ['A la prestación de mayor duración', 'A la prestación que figure en primer lugar en el pliego', 'A las normas del contrato de servicios en todo caso'],
 're:Cuando un contrato mixto comprenda prestaciones propias de dos o más contratos de obras, suministros o servicios se atenderá al carácter de la prestación principal'),
('III', T, 'a1-10', 'En un contrato mixto compuesto en parte por servicios y en parte por suministros, el objeto principal se determina:', 'En función de cuál sea el mayor de los valores estimados de los respectivos servicios o suministros',
 ['En función de la duración de cada prestación', 'Por decisión discrecional del órgano de contratación', 'Considerándolo siempre contrato de suministro'],
 'el objeto principal se determinará en función de cuál sea el mayor de los valores estimados'),
# Arts. 19-23: regulación armonizada
('III', T, 'a1-11', 'Para que un contrato de obras, concesión, suministro o servicios esté sujeto a regulación armonizada por razón de su valor estimado, la entidad contratante debe tener el carácter de:', 'Poder adjudicador',
 ['Entidad del sector público que no sea poder adjudicador', 'Sociedad concesionaria privada', 'Entidad local exclusivamente'],
 'siempre que la entidad contratante tenga el carácter de poder adjudicador'),
('III', T, 'a1-11', 'Cualquiera que sea su valor estimado, NO se consideran sujetos a regulación armonizada:', 'Los contratos declarados secretos o reservados',
 ['Los contratos de servicios sociales del anexo IV', 'Los contratos subvencionados del artículo 23', 'Los contratos de concesión de servicios'],
 'c) Los declarados secretos o reservados'),
('III', T, 'a2-2', 'Están sujetos a regulación armonizada los contratos de obras, de concesión de obras y de concesión de servicios cuyo valor estimado sea igual o superior a:', '5.404.000 euros',
 ['3.000.000 euros', '1.000.000 euros', '750.000 euros'], 'cuyo valor estimado sea igual o superior a 5.404.000 euros'),
('III', T, 'a2-2', 'En los contratos de obras por lotes sujetos a regulación armonizada, el órgano de contratación puede exceptuar de estas normas los lotes cuyo valor estimado sea inferior a (siempre que no sobrepasen en conjunto el 20 % del total):', '1.000.000 euros',
 ['80.000 euros', '500.000 euros', '140.000 euros'], 'a los lotes cuyo valor estimado sea inferior a un millón de euros'),
('III', T, 'a2-3', 'Umbral de regulación armonizada de los contratos de suministro adjudicados por la Administración General del Estado, sus organismos autónomos o las entidades gestoras y servicios comunes de la Seguridad Social:', '140.000 euros',
 ['216.000 euros', '100.000 euros', '750.000 euros'], r're:a\) 140\.000 euros, cuando se trate de contratos adjudicados por la Administración General del Estado'),
('III', T, 'a2-3', 'En los suministros por lotes sujetos a regulación armonizada pueden exceptuarse de estas normas los lotes cuyo valor estimado sea inferior a (con el límite del 20 % del valor acumulado):', '80.000 euros',
 ['1.000.000 euros', '40.000 euros', '15.000 euros'], 'a los lotes cuyo valor estimado sea inferior a 80.000 euros'),
('III', T, 'a2-4', 'Umbral de regulación armonizada de los contratos de servicios adjudicados por entidades del sector público distintas de la AGE, sus organismos autónomos y las entidades gestoras y servicios comunes de la Seguridad Social:', '216.000 euros',
 ['140.000 euros', '750.000 euros', '5.404.000 euros'], r're:b\) 216\.000 euros, cuando los contratos hayan de adjudicarse por entidades del sector público distintas'),
('III', T, 'a2-4', 'Umbral de regulación armonizada de los contratos de servicios sociales y otros servicios específicos del anexo IV:', '750.000 euros',
 ['216.000 euros', '1.000.000 euros', '140.000 euros'], r're:c\) 750\.000 euros, cuando se trate de contratos que tengan por objeto los servicios sociales'),
('III', T, 'a2-5', 'Son contratos subvencionados sujetos a regulación armonizada los de obras y servicios de las categorías legales subvencionados de forma directa por poderes adjudicadores en:', 'Más de un 50 por 100 de su importe',
 ['Más de un 25 por 100 de su importe', 'Más de un 80 por 100 de su importe', 'Cualquier porcentaje de su importe'], 'de forma directa y en más de un 50 por 100 de su importe'),
# Arts. 25-28
('III', T, 'a2-7', 'Aunque los celebre una Administración Pública, tienen carácter privado los contratos cuyo objeto sea:', 'La suscripción a revistas, publicaciones periódicas y bases de datos',
 ['La adquisición de material de oficina', 'La limpieza de edificios administrativos', 'La construcción de un edificio administrativo'],
 'Aquellos cuyo objeto sea la suscripción a revistas, publicaciones periódicas y bases de datos'),
('III', T, 'a2-7', 'Los contratos administrativos se rigen por la LCSP y sus disposiciones de desarrollo y, supletoriamente:', 'Por las restantes normas de derecho administrativo y, en su defecto, por las normas de derecho privado',
 ['Por las normas de derecho privado y, en su defecto, por las de derecho administrativo', 'Exclusivamente por el Código Civil', 'Por los pliegos de prescripciones técnicas'],
 'supletoriamente se aplicarán las restantes normas de derecho administrativo y, en su defecto, las normas de derecho privado'),
('III', T, 'a2-8', 'Los contratos celebrados por entidades del sector público que, siendo poder adjudicador, no reúnan la condición de Administración Pública tienen la consideración de:', 'Contratos privados',
 ['Contratos administrativos', 'Contratos administrativos especiales', 'Encargos a medios propios'],
 'b) Los celebrados por entidades del sector público que siendo poder adjudicador no reúnan la condición de Administraciones Públicas'),
('III', T, 'a2-8', 'Los contratos privados que celebren las Administraciones Públicas se rigen, en cuanto a sus efectos, modificación y extinción, por:', 'El derecho privado',
 ['El derecho administrativo', 'La LCSP en todo caso', 'Los pliegos de prescripciones técnicas'], 'En lo que respecta a su efectos, modificación y extinción, estos contratos se regirán por el derecho privado'),
('III', T, 'a2-9', '¿Qué orden jurisdiccional es competente para las cuestiones relativas a la preparación y adjudicación de los contratos privados de las Administraciones Públicas?', 'El contencioso-administrativo',
 ['El civil', 'El social', 'El mercantil'], 'b) Las que se susciten en relación con la preparación y adjudicación de los contratos privados de las Administraciones Públicas'),
('III', T, 'a2-9', '¿Qué orden jurisdiccional es competente para las controversias entre las partes sobre los efectos y extinción de los contratos privados de los poderes adjudicadores (salvo las modificaciones impugnables por los artículos 204 y 205)?', 'El civil',
 ['El contencioso-administrativo', 'El social', 'El penal'],
 r're:El orden jurisdiccional civil será el competente para resolver: a\) Las controversias que se susciten entre las partes en relación con los efectos y extinción de los contratos privados'),
('III', T, 'a2-10', 'Las entidades del sector público no podrán celebrar otros contratos que aquellos que sean:', 'Necesarios para el cumplimiento y realización de sus fines institucionales',
 ['Autorizados previamente por el Consejo de Ministros', 'De valor inferior a los umbrales de regulación armonizada', 'Incluidos en el Plan Anual Normativo'],
 'no podrán celebrar otros contratos que aquellos que sean necesarios para el cumplimiento y realización de sus fines institucionales'),
('III', T, 'a2-10', 'Las entidades del sector público darán a conocer anticipadamente su plan de contratación mediante:', 'Un anuncio de información previa',
 ['Una orden ministerial publicada en el BOE', 'Una comunicación a la Junta Consultiva de Contratación Pública del Estado', 'Su inclusión en los Presupuestos Generales del Estado'],
 'darán a conocer su plan de contratación anticipadamente mediante un anuncio de información previa'),
# Art. 29: duración
('III', P, 'a2-11', 'Preaviso mínimo con el que debe comunicarse la prórroga para que sea obligatoria para el empresario (salvo que el pliego establezca uno mayor)', '2 meses',
 ['1 mes', '3 meses', '6 meses'], 'siempre que su preaviso se produzca al menos con dos meses de antelación'),
('III', P, 'a2-11', 'Duración de los contratos por debajo de la cual quedan exceptuados de la obligación de preaviso de la prórroga', '2 meses',
 ['1 mes', '3 meses', '6 meses'], 'Quedan exceptuados de la obligación de preaviso los contratos cuya duración fuera inferior a dos meses'),
('III', T, 'a2-11', '¿Puede producirse la prórroga de un contrato del sector público por el consentimiento tácito de las partes?', 'No, en ningún caso',
 ['Sí, si el pliego lo prevé', 'Sí, en los contratos de servicios de prestación sucesiva', 'Sí, si ninguna de las partes la denuncia con dos meses de antelación'],
 'En ningún caso podrá producirse la prórroga por el consentimiento tácito de las partes'),
('III', P, 'a2-11', 'Demora de la Administración en el abono del precio que, si se supera, hace que la prórroga no sea obligatoria para el contratista', '6 meses',
 ['3 meses', '4 meses', '8 meses'], 'por haberse demorado la Administración en el abono del precio más de seis meses'),
('III', P, 'a2-11', 'Duración máxima, con carácter general, de los contratos de suministros y de servicios de prestación sucesiva, incluidas las prórrogas', '5 años',
 ['4 años', '6 años', '10 años'], 'tendrán un plazo máximo de duración de cinco años, incluyendo las posibles prórrogas'),
('III', P, 'a2-11', 'Prórroga máxima del contrato originario cuando, por acontecimientos imprevisibles, no se ha formalizado el nuevo contrato a su vencimiento', '9 meses',
 ['6 meses', '12 meses', '3 meses'], 'en todo caso por un periodo máximo de nueve meses'),
('III', P, 'a2-11', 'Antelación mínima con la que debe haberse publicado el anuncio de licitación del nuevo contrato, respecto del fin del originario, para poder prorrogar este excepcionalmente hasta el inicio de aquel', '3 meses',
 ['2 meses', '6 meses', '1 mes'], 'se haya publicado con una antelación mínima de tres meses respecto de la fecha de finalización del contrato originario'),
('III', P, 'a2-11', 'Duración máxima de los contratos de arrendamiento de bienes muebles, incluidas las prórrogas', '5 años',
 ['3 años', '4 años', '10 años'], 'La duración de los contratos de arrendamiento de bienes muebles no podrá exceder'),
('III', P, 'a2-11', 'Duración máxima, incluidas las prórrogas, de los contratos de concesión de obras (cuando superan los cinco años)', '40 años',
 ['25 años', '30 años', '50 años'], 'a) Cuarenta años para los contratos de concesión de obras'),
('III', P, 'a2-11', 'Duración máxima, incluidas las prórrogas, de las concesiones de servicios que comprendan la explotación de un servicio no relacionado con la prestación de servicios sanitarios', '25 años',
 ['40 años', '10 años', '20 años'], 'b) Veinticinco años en los contratos de concesión de servicios'),
('III', P, 'a2-11', 'Duración máxima, incluidas las prórrogas, de las concesiones de servicios cuyo objeto consista en la prestación de servicios sanitarios (no comprendidas en la letra a)', '10 años',
 ['25 años', '5 años', '15 años'], 'c) Diez años en los contratos de concesión de servicios'),
('III', T, 'a2-11', 'Para restablecer el equilibrio económico del contrato, los plazos de las concesiones fijados en los pliegos solo podrán ampliarse en:', 'Un 15 por ciento de su duración inicial',
 ['Un 10 por ciento de su duración inicial', 'Un 20 por ciento de su duración inicial', 'Un 25 por ciento de su duración inicial'], 'solo podrán ser ampliados en un 15 por ciento de su duración inicial'),
# Arts. 30-32
('III', T, 'a3-2', 'La ejecución de obras por la propia Administración procede cuando posea elementos auxiliares utilizables cuyo empleo suponga una economía superior al:', '5 por 100 del importe del presupuesto del contrato',
 ['10 por 100 del importe del presupuesto del contrato', '20 por 100 del importe del presupuesto del contrato', '15 por 100 del importe del presupuesto del contrato'],
 'cuyo empleo suponga una economía superior al 5 por 100'),
('III', T, 'a3-2', 'La fabricación de bienes muebles por los servicios de la Administración, en el supuesto de elementos auxiliares, requiere que el ahorro sea superior al:', '20 por 100 del presupuesto del suministro',
 ['5 por 100 del presupuesto del suministro', '10 por 100 del presupuesto del suministro', '50 por 100 del presupuesto del suministro'],
 'el ahorro que pueda obtenerse sea superior al 20 por 100 del presupuesto del suministro'),
('III', T, 'a3-2', 'En la ejecución de obras por la Administración de los supuestos a) y b) del artículo 30.1, la contratación con colaboradores no podrá sobrepasar:', 'El 60 por ciento del importe total del proyecto',
 ['El 50 por ciento del importe total del proyecto', 'El 80 por ciento del importe total del proyecto', 'El 40 por ciento del importe total del proyecto'],
 'la contratación con colaboradores no podrá sobrepasar el 60 por ciento del importe total del proyecto'),
('III', T, 'a3-2', 'Según el artículo 30.3, la prestación de servicios se realizará normalmente:', 'Por la propia Administración por sus propios medios',
 ['Mediante contrato de servicios en todo caso', 'Mediante encargo a un medio propio personificado', 'Mediante contrato de concesión de servicios'],
 'La prestación de servicios se realizará normalmente por la propia Administración por sus propios medios'),
('III', T, 'a3-4', 'El encargo a un medio propio personificado que cumpla los requisitos del artículo 32:', 'No tendrá la consideración de contrato',
 ['Tendrá la consideración de contrato de servicios', 'Tendrá la consideración de contrato administrativo especial', 'Deberá adjudicarse por procedimiento abierto'],
 'El encargo que cumpla dichos requisitos no tendrá la consideración de contrato'),
('III', T, 'a3-4', 'Para ser medio propio personificado, el ente destinatario del encargo debe realizar, en el ejercicio de los cometidos confiados por el poder adjudicador que lo controla o por otras personas jurídicas controladas del mismo modo:', 'Más del 80 por ciento de sus actividades',
 ['Más del 50 por ciento de sus actividades', 'Más del 60 por ciento de sus actividades', 'La totalidad de sus actividades'],
 'b) Que más del 80 por ciento de las actividades del ente destinatario del encargo se lleven a cabo en el ejercicio de los cometidos que le han sido confiados por el poder adjudicador que hace el encargo'),
('III', T, 'a3-4', 'Cuando el medio propio personificado sea un ente de personificación jurídico-privada, su capital o patrimonio:', 'Tendrá que ser en su totalidad de titularidad o aportación pública',
 ['Deberá ser público al menos en un 51 por ciento', 'Deberá ser público al menos en un 80 por ciento', 'Podrá tener cualquier participación privada minoritaria'],
 'la totalidad de su capital o patrimonio tendrá que ser de titularidad o aportación pública'),
# Arts. 34-41
('III', T, 'a3-6', 'En los contratos del sector público podrán incluirse cualesquiera pactos, cláusulas y condiciones siempre que:', 'No sean contrarios al interés público, al ordenamiento jurídico y a los principios de buena administración',
 ['Sean aprobados por la Junta Consultiva de Contratación Pública del Estado', 'Figuren en un modelo normalizado de contrato', 'No incrementen el valor estimado del contrato'],
 'siempre que no sean contrarios al interés público, al ordenamiento jurídico y a los principios de buena administración'),
('III', T, 'a3-7', '¿Cuál de las siguientes NO figura entre las menciones que debe incluir necesariamente el documento de formalización del contrato (salvo que ya estén en los pliegos)?', 'La composición de la mesa de contratación',
 ['El precio cierto, o el modo de determinarlo', 'Las condiciones de pago', 'Los supuestos en que procede la resolución'],
 r're:deberán incluir, necesariamente, las siguientes menciones: a\) La identificación de las partes.*?k\) Los supuestos en que procede la resolución'),
('III', T, 'a3-8', 'Con carácter general (salvo contratos menores y contratos basados en acuerdo marco o sistema dinámico), los contratos de los poderes adjudicadores se perfeccionan con:', 'Su formalización',
 ['Su adjudicación', 'La presentación de la oferta', 'El inicio de su ejecución'], 'se perfeccionan con su formalización'),
('III', T, 'a3-8', 'Los contratos basados en un acuerdo marco y los contratos específicos en el marco de un sistema dinámico de adquisición se perfeccionan con:', 'Su adjudicación',
 ['Su formalización', 'La publicación en el perfil de contratante', 'La celebración del acuerdo marco'], 'en el marco de un sistema dinámico de adquisición, se perfeccionan con su adjudicación'),
('III', T, 'a3-8', 'Salvo que se indique otra cosa en su clausulado, los contratos del sector público se entenderán celebrados en el lugar:', 'Donde se encuentre la sede del órgano de contratación',
 ['Del domicilio social del contratista', 'Donde deba ejecutarse la prestación', 'Donde se presentó la oferta'],
 'se entenderán celebrados en el lugar donde se encuentre la sede del órgano de contratación'),
('III', T, 'a3-9', 'Las entidades del sector público pueden contratar verbalmente:', 'Solo cuando el contrato tenga carácter de emergencia',
 ['En los contratos menores', 'Cuando el valor estimado sea inferior a 5.000 euros', 'Cuando lo autorice el titular del departamento'],
 'Las entidades del sector público no podrán contratar verbalmente'),
('III', T, 'a3-11', 'Según el artículo 39.1, son causas de nulidad de derecho administrativo de los contratos las indicadas en:', 'El artículo 47 de la Ley 39/2015',
 ['El artículo 48 de la Ley 39/2015', 'El artículo 106 de la Ley 39/2015', 'El artículo 35 de la Ley 40/2015'],
 'Son causas de nulidad de derecho administrativo las indicadas en el artículo 47'),
('III', T, 'a3-11', '¿Cuál de las siguientes es causa de nulidad de pleno derecho de los contratos según el artículo 39.2?', 'La carencia o insuficiencia de crédito, salvo los supuestos de emergencia',
 ['El incumplimiento de los requisitos de los artículos 204 y 205 para la modificación del contrato', 'Las cláusulas que otorguen ventajas a empresas que hayan contratado previamente con cualquier Administración', 'Los encargos a medios propios que no cumplan los requisitos del artículo 32'],
 'b) La carencia o insuficiencia de crédito'),
('III', T, 'a3-11', 'Formalizar el contrato sin respetar la suspensión automática del acto recurrido cuando se ha interpuesto recurso especial es causa de:', 'Nulidad de pleno derecho',
 ['Anulabilidad', 'Irregularidad no invalidante', 'Resolución del contrato por incumplimiento del contratista'], 'sin respetar la suspensión automática del acto recurrido'),
('III', T, 'a4-2', '¿Cuál de las siguientes es causa de anulabilidad de derecho administrativo según el artículo 40?', 'El incumplimiento de las circunstancias y requisitos exigidos para la modificación de los contratos en los artículos 204 y 205',
 ['La falta de solvencia económica o técnica del adjudicatario', 'La carencia o insuficiencia de crédito', 'La falta de publicación preceptiva del anuncio de licitación en el perfil de contratante'],
 'a) El incumplimiento de las circunstancias y requisitos exigidos para la modificación'),
('III', T, 'a4-3', 'Cuando se trate de contratos de una Administración Pública, ¿quién es competente para declarar la nulidad o lesividad de sus actos preparatorios y de adjudicación?', 'El órgano de contratación',
 ['El Consejo de Estado', 'El Tribunal Administrativo Central de Recursos Contractuales', 'La Junta Consultiva de Contratación Pública del Estado'],
 'serán competentes para declarar la nulidad o lesividad de los actos a que se refieren los apartados anteriores el órgano de contratación'),
# Arts. 44-60: recurso especial
('III', T, 'a4-6', 'Son susceptibles de recurso especial en materia de contratación los contratos de obras cuyo valor estimado sea superior a:', '3.000.000 euros',
 ['5.404.000 euros', '1.000.000 euros', '500.000 euros'], 'Contratos de obras cuyo valor estimado sea superior a tres millones de euros'),
('III', T, 'a4-6', 'Son susceptibles de recurso especial en materia de contratación los contratos de suministro y servicios cuyo valor estimado sea superior a:', '100.000 euros',
 ['40.000 euros', '15.000 euros', '216.000 euros'], 'de suministro y servicios, que tenga un valor estimado superior a cien mil euros'),
('III', T, 'a4-6', 'Son susceptibles de recurso especial en materia de contratación las concesiones de obras o de servicios cuyo valor estimado supere:', '3.000.000 euros',
 ['5.404.000 euros', '1.000.000 euros', '750.000 euros'], 'c) Concesiones de obras o de servicios cuyo valor estimado supere los tres millones de euros'),
('III', T, 'a4-6', '¿Cuál de las siguientes actuaciones NO figura entre las que pueden ser objeto del recurso especial en materia de contratación?', 'La imposición de penalidades al contratista durante la ejecución del contrato',
 ['Los acuerdos de adjudicación', 'Los acuerdos de rescate de concesiones', 'Los pliegos que establezcan las condiciones que deban regir la contratación'],
 r're:Podrán ser objeto del recurso las siguientes actuaciones: a\).*?f\) Los acuerdos de rescate de concesiones'),
('III', T, 'a4-6', 'No cabe recurso especial en materia de contratación en relación con los procedimientos de adjudicación que se sigan por:', 'El trámite de emergencia',
 ['El procedimiento abierto', 'El procedimiento restringido', 'La tramitación urgente'], 'No se dará este recurso en relación con los procedimientos de adjudicación que se sigan por el trámite de emergencia'),
('III', T, 'a4-6', 'Contra las actuaciones susceptibles de ser impugnadas mediante el recurso especial en materia de contratación:', 'No procede la interposición de recursos administrativos ordinarios',
 ['Procede previamente el recurso de alzada', 'Procede previamente el recurso potestativo de reposición', 'El interesado puede elegir entre el recurso especial y el de alzada'],
 'no procederá la interposición de recursos administrativos ordinarios'),
('III', T, 'a4-7', 'El Tribunal Administrativo Central de Recursos Contractuales está adscrito, según el artículo 45:', 'Al Ministerio de Hacienda y Función Pública',
 ['Al Ministerio de Justicia', 'Al Consejo de Estado', 'A la Presidencia del Gobierno'], 'Dicho órgano estará adscrito al Ministerio de Hacienda y Función Pública'),
('III', T, 'a4-7', 'El Tribunal Administrativo Central de Recursos Contractuales está compuesto por:', 'Un Presidente y un mínimo de cinco vocales',
 ['Un Presidente y un mínimo de tres vocales', 'Un Presidente y un mínimo de siete vocales', 'Un Presidente, un Vicepresidente y tres vocales'], 'compuesto por un Presidente y un mínimo de cinco vocales'),
('III', P, 'a4-7', 'Tiempo de actividad profesional que deben superar los funcionarios de carrera para ser designados vocales del Tribunal Administrativo Central de Recursos Contractuales', '10 años',
 ['5 años', '15 años', '8 años'], 'que hayan desempeñado su actividad profesional por tiempo superior a diez años'),
('III', P, 'a4-7', 'Tiempo de actividad profesional que debe superar el Presidente del Tribunal Administrativo Central de Recursos Contractuales', '15 años',
 ['10 años', '20 años', '12 años'], 'por tiempo superior a quince años'),
('III', P, 'a4-7', 'Duración del nombramiento del Presidente y los vocales del Tribunal Administrativo Central de Recursos Contractuales (no prorrogable)', '6 años',
 ['4 años', '5 años', '8 años'], 'La duración del nombramiento efectuado de conformidad con este apartado será de seis años'),
('III', T, 'a4-7', 'Mientras prestan servicio en el Tribunal Administrativo Central de Recursos Contractuales, el Presidente y los vocales pasan a la situación de:', 'Servicios especiales',
 ['Servicio activo', 'Excedencia voluntaria', 'Servicio en otras Administraciones Públicas'], 'pasarán a la situación de Servicios Especiales'),
('III', T, 'a4-7', 'La designación del Presidente y los vocales del Tribunal Administrativo Central de Recursos Contractuales corresponde:', 'Al Gobierno, a propuesta conjunta de los Ministros de Hacienda y Función Pública y de Justicia',
 ['A las Cortes Generales, por mayoría de tres quintos', 'Al Consejo General del Poder Judicial', 'Al Ministro de Hacienda y Función Pública, previo concurso'],
 'se realizará por el Gobierno a propuesta conjunta'),
('III', T, 'a4-10', 'Según el artículo 48, en todo caso se entenderá legitimada para interponer el recurso especial en materia de contratación:', 'La organización empresarial sectorial representativa de los intereses afectados',
 ['Cualquier ciudadano, aunque no tenga interés afectado', 'El Defensor del Pueblo', 'El Ministerio Fiscal'], 'En todo caso se entenderá legitimada la organización empresarial sectorial'),
('III', P, 'a4-11', 'Plazo del órgano competente para resolver el recurso para decidir sobre las medidas cautelares solicitadas antes de interponerlo, desde la presentación del escrito', '5 días hábiles',
 ['2 días hábiles', '10 días hábiles', '3 días hábiles'], 'dentro de los cinco días hábiles siguientes a la presentación del escrito en que se soliciten'),
('III', P, 'a4-11', 'Plazo del órgano de contratación para presentar alegaciones sobre la solicitud de medidas cautelares', '2 días hábiles',
 ['3 días hábiles', '5 días hábiles', '10 días hábiles'], 'que dispondrá de un plazo de dos días hábiles'),
('III', T, 'a4-11', 'Contra las resoluciones dictadas en el procedimiento de medidas cautelares previas al recurso especial:', 'No cabe recurso alguno, sin perjuicio de los que procedan contra las del procedimiento principal',
 ['Cabe recurso potestativo de reposición', 'Cabe recurso de alzada', 'Cabe recurso especial en materia de contratación'],
 'Contra las resoluciones dictadas en este procedimiento no cabrá recurso alguno'),
('III', T, 'a5-2', 'Cuando el recurso especial se interponga contra el anuncio de licitación, el plazo comienza a contarse:', 'A partir del día siguiente al de su publicación en el perfil de contratante',
 ['Desde su publicación en el Boletín Oficial del Estado', 'Desde el mismo día de su publicación en el perfil de contratante', 'Desde la finalización del plazo de presentación de ofertas'],
 'el plazo comenzará a contarse a partir del día siguiente al de su publicación en el perfil de contratante'),
('III', P, 'a5-2', 'Plazo para interponer el recurso especial fundado en las causas de nulidad del artículo 39.2 c), d), e) o f), desde la publicación de la formalización con las razones de la falta de publicación de la convocatoria', '30 días',
 ['15 días', '20 días', '45 días'], 'a) Treinta días a contar desde la publicación de la formalización del contrato'),
('III', P, 'a5-2', 'Plazo para interponer el recurso especial fundado en dichas causas de nulidad en los restantes casos, desde la formalización del contrato', '6 meses',
 ['3 meses', '2 meses', '12 meses'], 'antes de que transcurran seis meses a contar desde la formalización del contrato'),
('III', P, 'a5-3', 'Plazo para subsanar los defectos del escrito de recurso especial, desde el siguiente a la notificación del requerimiento', '3 días hábiles',
 ['5 días hábiles', '10 días hábiles', '2 días hábiles'], 'en un plazo de tres días hábiles desde el siguiente a su notificación'),
('III', T, 'a5-5', 'Interpuesto el recurso especial, queda en suspenso la tramitación del procedimiento cuando el acto recurrido sea:', 'El de adjudicación (salvo contratos basados en acuerdo marco o sistema dinámico)',
 ['El anuncio de licitación', 'Los pliegos', 'Cualquier acto de trámite'], 'quedará en suspenso la tramitación del procedimiento cuando el acto recurrido sea el de adjudicación'),
('III', T, 'a5-7', '¿Cuál de los siguientes NO es un supuesto de inadmisión del recurso especial previsto en el artículo 55?', 'La falta de motivación del acto recurrido',
 ['La incompetencia del órgano para conocer del recurso', 'La falta de legitimación del recurrente', 'La interposición del recurso una vez finalizado el plazo'],
 r're:podrá declarar su inadmisión cuando constare de modo inequívoco y manifiesto cualquiera de los siguientes supuestos: a\).*?d\) La interposición del recurso, una vez finalizado el plazo establecido para su interposición'),
('III', P, 'a5-8', 'Plazo para remitir el expediente de contratación, con el informe, al órgano competente para resolver el recurso especial una vez reclamado', '2 días hábiles',
 ['5 días hábiles', '3 días hábiles', '10 días hábiles'], 'quien deberá remitirlo dentro de los dos días hábiles siguientes acompañado del correspondiente informe'),
('III', P, 'a5-8', 'Plazo de los restantes interesados para formular alegaciones en el recurso especial', '5 días hábiles',
 ['10 días hábiles', '3 días hábiles', '15 días hábiles'], 'concediéndoles un plazo de cinco días hábiles para formular alegaciones'),
('III', P, 'a5-8', 'Duración del período de prueba en el recurso especial en materia de contratación', '10 días hábiles',
 ['5 días hábiles', '15 días hábiles', '20 días hábiles'], 'la apertura del período de prueba por plazo de diez días hábiles'),
('III', P, 'a5-9', 'Plazo para resolver el recurso especial una vez recibidas las alegaciones (o transcurrido su plazo) y, en su caso, la prueba', '5 días hábiles',
 ['10 días hábiles', '15 días hábiles', '2 días hábiles'], 'deberá resolver el recurso dentro de los cinco días hábiles siguientes'),
('III', P, 'a5-9', 'Tiempo desde el siguiente a la interposición del recurso especial sin notificación de la resolución tras el cual el interesado puede considerarlo desestimado', '2 meses',
 ['1 mes', '3 meses', '6 meses'], 'Transcurridos dos meses contados desde el siguiente a la interposición del recurso'),
('III', T, 'a5-10', 'Si se aprecia temeridad o mala fe en la interposición del recurso especial, la multa al responsable será de:', 'Entre 1.000 y 30.000 euros',
 ['Entre 100 y 3.000 euros', 'Entre 3.000 y 60.000 euros', 'Entre 6.000 y 600.000 euros'], 'El importe de la multa será de entre 1.000 y 30.000 euros'),
('III', T, 'a5-10', 'El importe de la multa impuesta por temeridad o mala fe en el recurso especial se ingresa:', 'En todo caso en el Tesoro Público',
 ['En la cuenta del órgano de contratación', 'A favor de los restantes licitadores perjudicados', 'En el presupuesto del Tribunal que la impone'], 'El importe de la multa impuesta se ingresará en todo caso en el Tesoro Público'),
('III', T, 'a5-11', 'Contra la resolución dictada en el procedimiento del recurso especial en materia de contratación:', 'Solo cabe recurso contencioso-administrativo',
 ['Cabe recurso de alzada', 'Cabe recurso potestativo de reposición', 'Cabe recurso extraordinario de revisión'],
 'Contra la resolución dictada en este procedimiento solo cabrá la interposición de recurso contencioso-administrativo'),
('III', T, 'a5-11', 'La resolución del recurso especial en materia de contratación:', 'Será directamente ejecutiva',
 ['Solo será ejecutiva cuando sea firme en vía judicial', 'Será ejecutiva tras su publicación en el BOE', 'Requiere la conformidad del órgano de contratación para ser ejecutiva'],
 'la resolución será directamente ejecutiva'),
]
