# Lote 17 · Ley 50/1997, del Gobierno · bloque I (tema I.5: el Gobierno, el Presidente, el Consejo de Ministros,
# designación, cese y responsabilidad; funciones) y, en lo relativo a la potestad normativa, tema III.1.
NORMA, LOTE, INICIO = 'LGOB', 'lote-017', 17001
T, P = 'test', 'plazo'
PREGUNTAS = [
('I', T, 'a1', 'Según el artículo 1 de la Ley del Gobierno, el Gobierno se compone de:', 'El Presidente, el Vicepresidente o Vicepresidentes, en su caso, y los Ministros',
 ['El Presidente, los Ministros y los Secretarios de Estado', 'El Presidente y los Ministros con cartera exclusivamente', 'El Presidente, los Ministros y los Subsecretarios'],
 'El Gobierno se compone del Presidente, del Vicepresidente o Vicepresidentes, en su caso, y de los Ministros'),
('I', T, 'a1', 'Los miembros del Gobierno se reúnen en:', 'Consejo de Ministros y en Comisiones Delegadas del Gobierno',
 ['Consejo de Ministros y Comisión General de Secretarios de Estado y Subsecretarios', 'Consejo de Ministros exclusivamente', 'Pleno del Gobierno y Consejo de Estado'],
 'Los miembros del Gobierno se reúnen en Consejo de Ministros y en Comisiones Delegadas del Gobierno'),
('I', T, 'a2', '¿Cuál de las siguientes funciones corresponde al Presidente del Gobierno según el artículo 2?', 'Interponer el recurso de inconstitucionalidad',
 ['Aprobar los Reales Decretos-leyes', 'Aprobar el Proyecto de Ley de Presupuestos Generales del Estado', 'Declarar el estado de alarma'],
 'i) Interponer el recurso de inconstitucionalidad'),
('I', T, 'a2', 'Proponer al Rey la disolución del Congreso, del Senado o de las Cortes Generales corresponde al Presidente del Gobierno:', 'Previa deliberación del Consejo de Ministros',
 ['Previa autorización del Congreso de los Diputados', 'Previo dictamen del Consejo de Estado', 'Sin necesidad de trámite previo alguno'],
 'c) Proponer al Rey, previa deliberación del Consejo de Ministros, la disolución del Congreso, del Senado o de las Cortes Generales'),
('I', T, 'a2', 'Proponer al Rey la convocatoria de un referéndum consultivo corresponde al Presidente del Gobierno:', 'Previa autorización del Congreso de los Diputados',
 ['Previa deliberación del Consejo de Ministros exclusivamente', 'Previa autorización del Senado', 'Previo informe del Tribunal Constitucional'],
 'e) Proponer al Rey la convocatoria de un referéndum consultivo, previa autorización del Congreso de los Diputados'),
('I', T, 'a2', 'Crear, modificar y suprimir los Departamentos Ministeriales y las Secretarías de Estado corresponde:', 'Al Presidente del Gobierno, por Real Decreto',
 ['Al Consejo de Ministros, por Real Decreto', 'A las Cortes Generales, por ley', 'Al Ministro de Hacienda, por orden'],
 'j) Crear, modificar y suprimir, por Real Decreto, los Departamentos Ministeriales'),
('I', T, 'a2', 'Resolver los conflictos de atribuciones que surjan entre los diferentes Ministerios corresponde a:', 'El Presidente del Gobierno',
 ['El Consejo de Ministros', 'La Comisión General de Secretarios de Estado y Subsecretarios', 'El Tribunal Supremo'],
 'l) Resolver los conflictos de atribuciones que puedan surgir entre los diferentes Ministerios'),
('I', T, 'a3', 'El Vicepresidente del Gobierno que asume la titularidad de un Departamento Ministerial:', 'Ostenta además la condición de Ministro',
 ['Pierde la condición de Vicepresidente', 'Pasa a ser Secretario de Estado', 'No puede refrendar actos del Rey'],
 'El Vicepresidente que asuma la titularidad de un Departamento Ministerial, ostentará, además, la condición de Ministro'),
('I', T, 'a4', 'Además de los Ministros titulares de un Departamento, pueden existir:', 'Ministros sin cartera, con la responsabilidad de determinadas funciones gubernamentales',
 ['Ministros interinos nombrados por las Cortes', 'Ministros adjuntos con rango de Secretario de Estado', 'Viceministros'],
 'podrán existir Ministros sin cartera'),
'RETIRADA: duplicada del lote 11',
('I', T, 'a5', '¿Cuál de las siguientes funciones corresponde al Consejo de Ministros según el artículo 5?', 'Aprobar los Reales Decretos-leyes y los Reales Decretos Legislativos',
 ['Plantear la cuestión de confianza', 'Interponer el recurso de inconstitucionalidad', 'Proponer el nombramiento de los Ministros'],
 'c) Aprobar los Reales Decretos-leyes y los Reales Decretos Legislativos'),
('I', T, 'a5', 'Según el artículo 5, el Consejo de Ministros puede declarar:', 'Los estados de alarma y de excepción, y proponer al Congreso la declaración del estado de sitio',
 ['Los estados de alarma, excepción y sitio', 'Solo el estado de alarma', 'El estado de sitio, previa autorización del Senado'],
 'f) Declarar los estados de alarma y de excepción y proponer al Congreso de los Diputados la declaración del estado de sitio'),
('I', T, 'a5', 'El Consejo de Ministros aprueba los reglamentos para el desarrollo y ejecución de las leyes:', 'Previo dictamen del Consejo de Estado',
 ['Previa autorización de las Cortes Generales', 'Previo informe del Tribunal Supremo', 'Sin necesidad de dictamen alguno'],
 'h) Aprobar los reglamentos para el desarrollo y la ejecución de las leyes, previo dictamen del Consejo de Estado'),
('I', T, 'a5', 'A las reuniones del Consejo de Ministros pueden asistir, cuando sean convocados:', 'Los Secretarios de Estado y, excepcionalmente, otros altos cargos',
 ['Los Subsecretarios en todo caso', 'Los Presidentes de las Comunidades Autónomas', 'Los portavoces de los grupos parlamentarios'],
 'A las reuniones del Consejo de Ministros podrán asistir los Secretarios de Estado'),
('I', T, 'a6', 'La creación, modificación y supresión de las Comisiones Delegadas del Gobierno se acuerda:', 'Por el Consejo de Ministros mediante Real Decreto, a propuesta del Presidente del Gobierno',
 ['Por el Presidente del Gobierno mediante orden', 'Por las Cortes Generales mediante ley', 'Por el Ministro de la Presidencia'],
 'será acordada por el Consejo de Ministros mediante Real Decreto, a propuesta del Presidente del Gobierno'),
('I', T, 'a7', 'Según la Ley del Gobierno, los Secretarios de Estado son:', 'Órganos superiores de la AGE, directamente responsables de la ejecución de la acción del Gobierno en un sector de actividad específica',
 ['Miembros del Gobierno', 'Órganos directivos de la AGE', 'Órganos de apoyo político sin competencias propias'],
 'Los Secretarios de Estado son órganos superiores de la Administración General del Estado'),
('I', T, 'a8', 'La Comisión General de Secretarios de Estado y Subsecretarios está presidida por:', 'Un Vicepresidente del Gobierno o, en su defecto, el Ministro de la Presidencia',
 ['El Presidente del Gobierno', 'El Subsecretario de la Presidencia', 'El Secretario de Estado más antiguo'],
 'corresponde a un Vicepresidente del Gobierno o, en su defecto, al Ministro de la Presidencia'),
('I', T, 'a8', 'La Secretaría de la Comisión General de Secretarios de Estado y Subsecretarios la ejerce:', 'El Subsecretario de la Presidencia',
 ['El Director del Secretariado del Gobierno en todo caso', 'El Ministro de la Presidencia', 'El Abogado General del Estado'],
 'será ejercida por el Subsecretario de la Presidencia'),
('I', T, 'a8', 'La Comisión General de Secretarios de Estado y Subsecretarios:', 'No puede en ningún caso adoptar decisiones o acuerdos por delegación del Gobierno',
 ['Adopta acuerdos por delegación del Consejo de Ministros', 'Aprueba los nombramientos de altos cargos', 'Sus deliberaciones son públicas'],
 'En ningún caso la Comisión podrá adoptar decisiones o acuerdos por delegación del Gobierno'),
('I', T, 'a8', 'Las deliberaciones de la Comisión General de Secretarios de Estado y Subsecretarios son:', 'Reservadas',
 ['Públicas', 'Publicadas en el BOE', 'Retransmitidas'], 'Las deliberaciones de la Comisión General de Secretarios de Estado y Subsecretarios serán reservadas'),
('I', T, 'a9', 'El órgano de apoyo del Consejo de Ministros, de las Comisiones Delegadas y de la Comisión General de Secretarios de Estado y Subsecretarios es:', 'El Secretariado del Gobierno',
 ['El Gabinete de la Presidencia', 'La Abogacía General del Estado', 'El Consejo de Estado'],
 'El Secretariado del Gobierno, como órgano de apoyo del Consejo de Ministros'),
('I', T, 'a10', 'Los miembros de los Gabinetes:', 'Realizan tareas de confianza y asesoramiento especial, sin poder adoptar actos o resoluciones de los órganos de la AGE',
 ['Pueden dictar cualquier acto administrativo del Ministerio', 'Son funcionarios de carrera en todo caso', 'Tienen la condición de alto cargo'],
 'Los miembros de los Gabinetes realizan tareas de confianza y asesoramiento especial'),
('I', T, 'a11', '¿Cuál de los siguientes NO es un requisito para ser miembro del Gobierno según el artículo 11?', 'Ser Diputado o Senador',
 ['Ser español', 'Ser mayor de edad', 'Disfrutar de los derechos de sufragio activo y pasivo'],
 'Para ser miembro del Gobierno se requiere ser español, mayor de edad'),
('I', T, 'a12', 'Los Vicepresidentes y Ministros son nombrados y separados por:', 'El Rey, a propuesta del Presidente del Gobierno',
 ['El Presidente del Gobierno', 'El Congreso de los Diputados', 'El Rey, a propuesta del Congreso'], 'Los Vicepresidentes y Ministros serán nombrados y separados por el Rey, a propuesta del Presidente del Gobierno'),
('I', T, 'a12', 'En el nombramiento de las personas titulares de Vicepresidencias y Ministerios, cada uno de los sexos debe suponer en su conjunto como mínimo:', 'El cuarenta por ciento',
 ['El cincuenta por ciento', 'El treinta por ciento', 'El veinticinco por ciento'], 'de forma que cada uno de los sexos suponga como mínimo el cuarenta por ciento en su conjunto'),
('I', T, 'a12', 'La separación de los Ministros sin cartera lleva aparejada:', 'La extinción de dichos órganos',
 ['Su conversión en Secretarías de Estado', 'Su integración en la Presidencia', 'Su mantenimiento hasta nuevo nombramiento'], 'La separación de los Ministros sin cartera llevará aparejada la extinción de dichos órganos'),
('I', T, 'a13', 'En caso de vacante, ausencia o enfermedad, las funciones del Presidente del Gobierno son asumidas:', 'Por los Vicepresidentes según su orden de prelación y, en su defecto, por los Ministros según el orden de precedencia de los Departamentos',
 ['Por el Ministro de la Presidencia en todo caso', 'Por el Presidente del Congreso', 'Por el Ministro de mayor edad'],
 'las funciones del Presidente del Gobierno serán asumidas por los Vicepresidentes'),
('I', T, 'a13', 'La suplencia de los Ministros para el despacho ordinario de los asuntos se determina por:', 'Real Decreto del Presidente del Gobierno, recayendo en otro miembro del Gobierno',
 ['Orden del propio Ministro, recayendo en un Secretario de Estado', 'Acuerdo del Consejo de Ministros, recayendo en el Subsecretario', 'Ley'],
 'será determinada por Real Decreto del Presidente del Gobierno, debiendo recaer, en todo caso, en otro miembro del Gobierno'),
('I', T, 'a14', 'Los miembros del Gobierno NO pueden ejercer:', 'Otras funciones representativas que las propias del mandato parlamentario, ni actividad profesional o mercantil alguna',
 ['El mandato parlamentario', 'La dirección de su Departamento', 'El refrendo de los actos del Rey'],
 'Los miembros del Gobierno no podrán ejercer otras funciones representativas que las propias del mandato parlamentario'),
('I', T, 'a15', 'Los Secretarios de Estado son nombrados y separados por:', 'Real Decreto del Consejo de Ministros, a propuesta del Presidente o del miembro del Gobierno a cuyo Departamento pertenezcan',
 ['El Rey, a propuesta del Presidente', 'Orden del Ministro del Departamento', 'Real Decreto del Presidente del Gobierno'],
 'Los Secretarios de Estado son nombrados y separados por Real Decreto del Consejo de Ministros'),
('I', T, 'a16', 'Los Directores de Gabinete de los Secretarios de Estado son nombrados por:', 'Orden Ministerial, previo conocimiento del Consejo de Ministros',
 ['Real Decreto del Consejo de Ministros', 'Resolución del Subsecretario', 'El propio Secretario de Estado sin trámite alguno'],
 'Los Directores de Gabinete de los Secretarios de Estado serán nombrados por Orden Ministerial'),
('I', T, 'a16', 'Los funcionarios que se incorporan a los Gabinetes pasan, salvo que opten por permanecer en servicio activo, a la situación de:', 'Servicios especiales',
 ['Excedencia voluntaria', 'Servicio en otras Administraciones Públicas', 'Suspensión de funciones'], 'pasarán a la situación de servicios especiales'),
('I', T, 'a18', 'En el Consejo de Ministros actúa como Secretario:', 'El Ministro de la Presidencia',
 ['El Subsecretario de la Presidencia', 'El Vicepresidente primero', 'El Director del Secretariado del Gobierno'], 'actuando como Secretario el Ministro de la Presidencia'),
('I', T, 'a18', 'Las reuniones del Consejo de Ministros pueden tener carácter:', 'Decisorio o deliberante',
 ['Público o reservado', 'Ordinario o urgente exclusivamente', 'Consultivo exclusivamente'], 'Las reuniones del Consejo de Ministros podrán tener carácter decisorio o deliberante'),
('I', T, 'a18', 'En el acta de las sesiones del Consejo de Ministros figuran exclusivamente:', 'Las circunstancias de tiempo y lugar, la relación de asistentes, los acuerdos adoptados y los informes presentados',
 ['El contenido íntegro de las deliberaciones', 'Las opiniones de cada Ministro', 'Los votos particulares'],
 'figurarán, exclusivamente, las circunstancias relativas al tiempo y lugar de su celebración'),
('I', T, 'a20', '¿Cuál de las siguientes competencias NO es en ningún caso delegable según el artículo 20.3?', 'Las atribuidas directamente por la Constitución',
 ['Las del Presidente del Gobierno en favor de los Vicepresidentes', 'Las de los Ministros en favor de los Secretarios de Estado', 'Las funciones administrativas del Consejo de Ministros en las Comisiones Delegadas'],
 'a) Las atribuidas directamente por la Constitución'),
('I', T, 'a20', 'Contra el acuerdo de avocación del Consejo de Ministros:', 'No cabe recurso, aunque puede impugnarse en el que se interponga contra la decisión adoptada',
 ['Cabe recurso de reposición', 'Cabe recurso de alzada ante el Presidente', 'Cabe recurso ante el Tribunal Constitucional'],
 'Contra el acuerdo de avocación no cabrá recurso'),
('I', T, 'a21', 'El Gobierno cesa, entre otros supuestos:', 'Tras la celebración de elecciones generales',
 ['Al aprobarse la Ley de Presupuestos', 'Al cumplirse dos años de mandato', 'Por la dimisión de un Ministro'],
 'El Gobierno cesa tras la celebración de elecciones generales'),
('I', T, 'a21', 'El Gobierno cesante continúa en funciones:', 'Hasta la toma de posesión del nuevo Gobierno',
 ['Durante un máximo de dos meses', 'Hasta la constitución de las nuevas Cortes', 'Hasta la investidura del nuevo Presidente'],
 'El Gobierno cesante continúa en funciones hasta la toma de posesión del nuevo Gobierno'),
('I', T, 'a21', '¿Cuál de las siguientes facultades NO puede ejercer el Presidente del Gobierno en funciones?', 'Plantear la cuestión de confianza',
 ['Convocar y presidir el Consejo de Ministros', 'Representar al Gobierno', 'Impartir instrucciones a los Ministros'], 'b) Plantear la cuestión de confianza'),
('I', T, 'a21', 'El Gobierno en funciones NO puede:', 'Aprobar el Proyecto de Ley de Presupuestos Generales del Estado',
 ['Despachar los asuntos públicos ordinarios', 'Adoptar medidas urgentes debidamente acreditadas', 'Facilitar el traspaso de poderes'],
 'a) Aprobar el Proyecto de Ley de Presupuestos Generales del Estado'),
('I', T, 'a21', 'Mientras el Gobierno esté en funciones como consecuencia de elecciones generales, las delegaciones legislativas otorgadas por las Cortes:', 'Quedan en suspenso',
 ['Se mantienen vigentes', 'Se extinguen definitivamente', 'Se transfieren al Congreso'], 'quedarán en suspenso durante todo el tiempo que el Gobierno esté en funciones'),
('III', T, 'a23', 'Las disposiciones de entrada en vigor de leyes o reglamentos del Gobierno que impongan nuevas obligaciones a quienes desempeñen una actividad económica o profesional preverán su vigencia:', 'El 2 de enero o el 1 de julio siguientes a su aprobación',
 ['A los veinte días de su publicación', 'El 1 de enero o el 1 de julio', 'Al día siguiente de su publicación'],
 'preverán el comienzo de su vigencia el 2 de enero o el 1 de julio siguientes a su aprobación'),
('III', T, 'a24', 'Las disposiciones y resoluciones de los Ministros revisten la forma de:', 'Órdenes Ministeriales',
 ['Reales Decretos', 'Acuerdos', 'Instrucciones'], 'f) Órdenes Ministeriales, las disposiciones y resoluciones de los Ministros'),
('III', T, 'a24', 'Cuando una disposición o resolución afecte a varios Departamentos, reviste la forma de:', 'Orden del Ministro de la Presidencia, dictada a propuesta de los Ministros interesados',
 ['Real Decreto del Presidente del Gobierno', 'Orden conjunta de todos los Ministros firmada por el más antiguo', 'Acuerdo de la Comisión General de Secretarios de Estado y Subsecretarios'],
 'revestirá la forma de Orden del Ministro de la Presidencia, dictada a propuesta de los Ministros interesados'),
('III', T, 'a24', 'Según el artículo 24.2, en la jerarquía de los reglamentos, las disposiciones aprobadas por Orden Ministerial están:', 'Por debajo de las aprobadas por Real Decreto del Presidente o acordado en Consejo de Ministros',
 ['Por encima de los Reales Decretos', 'Al mismo nivel que los Reales Decretos', 'Por encima de las leyes'],
 r're:Los reglamentos se ordenarán según la siguiente jerarquía: 1\.º.*?2\.º Disposiciones aprobadas por Orden Ministerial'),
('III', T, 'a25', 'El Plan Anual Normativo contiene:', 'Las iniciativas legislativas o reglamentarias que vayan a elevarse para su aprobación en el año siguiente',
 ['Las normas aprobadas el año anterior', 'Las sentencias que anulan reglamentos', 'Los proyectos de las Comunidades Autónomas'],
 'que contendrá las iniciativas legislativas o reglamentarias que vayan a ser elevadas para su aprobación en el año siguiente'),
('III', T, 'a25', 'El Ministro de la Presidencia eleva el Plan Anual Normativo al Consejo de Ministros para su aprobación:', 'Antes del 30 de abril',
 ['Antes del 31 de diciembre', 'Antes del 1 de octubre', 'Antes del 31 de marzo'], 'elevará el Plan al Consejo de Ministros para su aprobación antes del 30 de abril'),
('III', P, 'a26', 'Plazo mínimo de la consulta pública previa en la elaboración de anteproyectos de ley y reglamentos', '15 días naturales',
 ['10 días naturales', '20 días naturales', '30 días naturales'], 'que en ningún caso será inferior a quince días naturales'),
('III', T, 'a27', 'La tramitación urgente de una iniciativa normativa en la AGE implica que los plazos del procedimiento de elaboración:', 'Se reducen a la mitad de su duración',
 ['Se reducen a un tercio', 'Se mantienen, pero tiene preferencia', 'Se suprimen'], 'se reducirán a la mitad de su duración'),
('III', P, 'a27', 'Duración del trámite de audiencia o información pública en la tramitación urgente de iniciativas normativas', '7 días',
 ['15 días', '10 días', '5 días'], 'cuyo plazo de realización será de siete días'),
('I', T, 'a29', 'Todos los actos y omisiones del Gobierno están sometidos al control político de:', 'Las Cortes Generales',
 ['El Tribunal Constitucional', 'El Tribunal Supremo', 'El Consejo de Estado'], 'Todos los actos y omisiones del Gobierno están sometidos al control político de las Cortes Generales'),
('I', T, 'a29', 'Los actos, la inactividad y las vías de hecho del Gobierno son impugnables ante:', 'La jurisdicción contencioso-administrativa',
 ['La jurisdicción civil', 'El Consejo de Estado', 'El Defensor del Pueblo'], 'son impugnables ante la jurisdicción contencioso-administrativa'),
]
