# Lote 13 · LOVG (Ley Orgánica 1/2004, de Medidas de Protección Integral contra la Violencia de Género) · bloque I
# (asignación PROVISIONAL hasta confirmar el Anexo III, ver data/programa.md). Títulos preliminar, I, II y III (arts. 1-32).
# Se evitan preguntas sobre adscripciones ministeriales con denominaciones no actualizadas.
NORMA, LOTE, INICIO = 'LOVG', 'lote-013', 13001
T, P = 'test', 'plazo'
PREGUNTAS = [
('I', T, 'a1', 'La LO 1/2004 actúa contra la violencia que se ejerce sobre las mujeres por parte de quienes sean o hayan sido sus cónyuges o estén o hayan estado ligados a ellas por relaciones similares de afectividad:', 'Aun sin convivencia',
 ['Solo si existe convivencia', 'Solo si existe matrimonio', 'Solo si la relación sigue vigente'], 'por relaciones similares de afectividad, aun sin convivencia'),
('I', T, 'a1', 'Según el artículo 1.3, la violencia de género comprende:', 'Todo acto de violencia física y psicológica, incluidas las agresiones a la libertad sexual, las amenazas, las coacciones o la privación arbitraria de libertad',
 ['Solo la violencia física con resultado de lesiones', 'Solo los actos constitutivos de delito grave', 'Solo la violencia ejercida en el domicilio familiar'],
 'comprende todo acto de violencia física y psicológica'),
('I', T, 'a1', 'La violencia de género de la LO 1/2004 comprende también la que, con el objetivo de causar perjuicio o daño a las mujeres, se ejerza sobre:', 'Sus familiares o allegados menores de edad',
 ['Sus compañeros de trabajo', 'Cualquier tercero', 'Sus bienes exclusivamente'], 'se ejerza sobre sus familiares o allegados menores de edad'),
('I', T, 'a2', '¿Cuál de los siguientes es uno de los fines de la LO 1/2004 según su artículo 2?', 'Garantizar derechos económicos para las mujeres víctimas de violencia de género, con el fin de facilitar su integración social',
 ['Suprimir los juzgados especializados', 'Limitar la asistencia jurídica gratuita a los casos de condena firme', 'Excluir a las trabajadoras por cuenta propia de sus derechos'],
 'e) Garantizar derechos económicos para las mujeres víctimas de violencia de género'),
('I', T, 'a2', 'Según el artículo 2.k), las medidas de la LO 1/2004 deben respetar el principio de:', 'Transversalidad',
 ['Subsidiariedad', 'Territorialidad', 'Gradualidad'], 'k) Garantizar el principio de transversalidad de las medidas'),
('I', T, 'a3', 'El Plan Estatal de Sensibilización y Prevención de la Violencia de Género tiene carácter:', 'Permanente',
 ['Anual', 'Cuatrienal', 'Experimental'], 'se pondrá en marcha un Plan Estatal de Sensibilización y Prevención de la Violencia de Género con carácter permanente'),
('I', T, 'a3', 'El Informe anual de evaluación del Plan Estatal de Sensibilización y Prevención de la Violencia de Género se remite a:', 'Las Cortes Generales',
 ['El Consejo General del Poder Judicial', 'El Defensor del Pueblo', 'Las Comunidades Autónomas exclusivamente'],
 'elaborará el Informe anual de evaluación del Plan Estatal de Sensibilización y Prevención de la Violencia de Género y lo remitirá a las Cortes Generales'),
('I', T, 'a3', 'Las campañas de información y sensibilización contra la violencia de género se realizarán garantizando el acceso a ellas de:', 'Las personas con discapacidad',
 ['Solo las mujeres mayores de edad', 'Solo los centros educativos', 'Solo las personas residentes en zonas urbanas'],
 'se realizarán de manera que se garantice el acceso a las mismas de las personas con discapacidad'),
('I', T, 'a4', 'Según el artículo 4, las Universidades incluirán y fomentarán en todos los ámbitos académicos la formación, docencia e investigación en igualdad de género y no discriminación de forma:', 'Transversal',
 ['Optativa', 'Exclusivamente en los estudios de Derecho', 'Solo en los programas de doctorado'], 'en igualdad de género y no discriminación de forma transversal'),
('I', T, 'a5', 'Las Administraciones competentes deberán prever, respecto de los hijos afectados por un cambio de residencia derivado de actos de violencia de género:', 'Su escolarización inmediata',
 ['Su escolarización en el curso siguiente', 'Su escolarización en centros privados', 'Una beca de comedor exclusivamente'],
 'Las Administraciones competentes deberán prever la escolarización inmediata de los hijos'),
('I', T, 'a6', 'Las Administraciones educativas velarán para que en todos los materiales educativos:', 'Se eliminen los estereotipos sexistas o discriminatorios',
 ['Se incluya un capítulo sobre derecho penal', 'Se use exclusivamente el masculino genérico', 'Se supriman las referencias a la familia'],
 'en todos los materiales educativos se eliminen los estereotipos sexistas o discriminatorios'),
('I', T, 'a8', 'En el Consejo Escolar del Estado se asegurará la representación de:', 'El Instituto de la Mujer y las organizaciones que defiendan los intereses de las mujeres con implantación en todo el territorio nacional',
 ['La Delegación del Gobierno contra la Violencia de Género exclusivamente', 'Las asociaciones de víctimas de cualquier delito', 'Las Fuerzas y Cuerpos de Seguridad del Estado'],
 'en el Consejo Escolar del Estado se asegurará la representación del Instituto de la Mujer'),
('I', T, 'a9', 'Velar por el cumplimiento de los principios y valores educativos destinados a fomentar la igualdad real entre mujeres y hombres corresponde a:', 'Los servicios de inspección educativa',
 ['Los Consejos Escolares exclusivamente', 'El Ministerio Fiscal', 'Las asociaciones de padres y madres'],
 'Los servicios de inspección educativa velarán por el cumplimiento y aplicación de los principios y valores'),
('I', T, 'a10', 'Según la LO 1/2004, se considera ilícita la publicidad que:', 'Utilice la imagen de la mujer con carácter vejatorio o discriminatorio',
 ['Se dirija exclusivamente a mujeres', 'Utilice la imagen de cualquier persona sin su consentimiento', 'Se emita en horario infantil'],
 'se considerará ilícita la publicidad que utilice la imagen de la mujer con carácter vejatorio o discriminatorio'),
('I', T, 'a12', '¿Cuál de los siguientes NO está legitimado para ejercitar la acción de cesación de publicidad ilícita por utilizar en forma vejatoria la imagen de la mujer?', 'Cualquier particular, aunque no le afecte',
 ['El Ministerio Fiscal', 'El Instituto de la Mujer u órgano equivalente de cada Comunidad Autónoma', 'Las asociaciones que tengan como objetivo único la defensa de los intereses de la mujer'],
 r're:La Delegación Especial del Gobierno contra la Violencia sobre la Mujer , el Instituto de la Mujer.*?estarán legitimados para ejercitar ante los Tribunales la acción de cesación'),
('I', T, 'a13', 'La Administración pública promoverá, en relación con los medios de comunicación y la publicidad:', 'Acuerdos de autorregulación con mecanismos de control preventivo y de resolución extrajudicial de controversias',
 ['La censura previa de los contenidos', 'La prohibición de informar sobre violencia de género', 'Sanciones penales a los medios de comunicación'],
 'La Administración pública promoverá acuerdos de autorregulación'),
('I', T, 'a14', 'En la difusión de informaciones relativas a la violencia sobre la mujer, los medios de comunicación tendrán especial cuidado en:', 'El tratamiento gráfico de las informaciones',
 ['La hora de emisión', 'La extensión de la noticia', 'La identificación de la víctima'], 'se tendrá especial cuidado en el tratamiento gráfico de las informaciones'),
('I', T, 'a15', 'Las Administraciones sanitarias promoverán actuaciones de los profesionales sanitarios para la detección precoz de la violencia de género en el seno de:', 'El Consejo Interterritorial del Sistema Nacional de Salud',
 ['La Conferencia Sectorial de Igualdad', 'El Observatorio Estatal de Violencia sobre la Mujer', 'Los colegios de médicos'],
 'en el seno del Consejo Interterritorial del Sistema Nacional de Salud, promoverán e impulsarán actuaciones'),
('I', T, 'a16', 'La Comisión contra la Violencia de Género del Consejo Interterritorial del Sistema Nacional de Salud remite su informe anual a:', 'El Observatorio Estatal de la Violencia sobre la Mujer y al Pleno del Consejo Interterritorial',
 ['Las Cortes Generales', 'El Defensor del Pueblo', 'El Ministerio Fiscal'],
 'La Comisión emitirá un informe anual que será remitido al Observatorio Estatal de la Violencia sobre la Mujer y al Pleno del Consejo Interterritorial'),
('I', T, 'a16', 'La Comisión contra la Violencia de Género del Consejo Interterritorial del Sistema Nacional de Salud está compuesta por:', 'Representantes de todas las Comunidades Autónomas con competencia en la materia',
 ['Representantes del Ministerio del Interior', 'Jueces de violencia sobre la mujer', 'Asociaciones de víctimas exclusivamente'],
 'estará compuesta por representantes de todas las Comunidades Autónomas con competencia en la materia'),
# Derechos
('I', T, 'a17', 'Los servicios de información y orientación, atención psicosocial inmediata y asesoramiento jurídico 24 horas a las víctimas de violencias contra las mujeres tienen carácter de:', 'Servicios esenciales',
 ['Servicios complementarios', 'Servicios voluntarios', 'Servicios de pago'], 'tendrán carácter de servicios esenciales'),
('I', T, 'a18', 'La información a las mujeres víctimas de violencia de género que desconozcan el castellano:', 'Deberá ser accesible para ellas, o en su caso en la otra lengua oficial de su territorio de residencia',
 ['Solo se facilitará en castellano', 'Solo se facilitará si aportan intérprete propio', 'Solo se facilitará por escrito'],
 'La información deberá ser accesible para las mujeres que desconozcan el castellano'),
('I', T, 'a19', 'La organización de los servicios sociales de atención a las víctimas responde a los principios de:', 'Atención permanente, actuación urgente, especialización de prestaciones y multidisciplinariedad profesional',
 ['Gratuidad, voluntariedad y confidencialidad exclusivamente', 'Subsidiariedad y territorialidad', 'Centralización y jerarquía'],
 'responderá a los principios de atención permanente, actuación urgente, especialización de prestaciones y multidisciplinariedad profesional'),
('I', T, 'a19', 'Tienen también derecho a la asistencia social integral a través de los servicios sociales:', 'Los menores bajo la patria potestad o guarda y custodia de la persona agredida, o que convivan en contextos de violencia de género',
 ['Solo los menores que hayan sufrido lesiones físicas', 'Los agresores condenados', 'Los ascendientes de la víctima exclusivamente'],
 'También tendrán derecho a la asistencia social integral a través de estos servicios sociales los menores'),
('I', T, 'a1-2', 'El Sistema Público de Salud garantiza a las mujeres víctimas de violencia de género y a sus hijos e hijas el derecho a la atención sanitaria, con especial atención:', 'Psicológica y psiquiátrica',
 ['Odontológica', 'Estética', 'Exclusivamente de urgencias'], 'con especial atención psicológica y psiquiátrica'),
('I', T, 'a20', 'Las víctimas de violencia de género tienen derecho a recibir asesoramiento jurídico gratuito:', 'En el momento inmediatamente previo a la interposición de la denuncia',
 ['Solo tras la interposición de la denuncia', 'Solo si acreditan insuficiencia de recursos', 'Solo una vez dictada sentencia'],
 'tienen derecho a recibir asesoramiento jurídico gratuito en el momento inmediatamente previo a la interposición de la denuncia'),
('I', T, 'a20', 'Las víctimas de violencia de género pueden personarse como acusación particular:', 'En cualquier momento del procedimiento, sin que ello permita retrotraer las actuaciones ya practicadas',
 ['Solo antes de la fase de instrucción', 'Solo en el plazo de diez días desde la denuncia', 'Nunca, solo actúa el Ministerio Fiscal'],
 'Las víctimas de violencia de género podrán personarse como acusación particular en cualquier momento del procedimiento'),
('I', T, 'a20', 'El derecho a la asistencia jurídica gratuita de la víctima asiste también, en caso de fallecimiento de esta, a:', 'Sus causahabientes, siempre que no fueran partícipes en los hechos',
 ['Cualquier familiar hasta el cuarto grado', 'Las asociaciones de víctimas', 'Nadie, se extingue con la víctima'],
 'Este derecho asistirá también a los causahabientes en caso de fallecimiento de la víctima'),
('I', T, 'a21', 'La suspensión y la extinción del contrato de trabajo de la trabajadora víctima de violencia de género:', 'Dan lugar a situación legal de desempleo',
 ['No dan derecho a prestación por desempleo', 'Equivalen a una baja voluntaria', 'Solo dan derecho a una indemnización de la empresa'],
 'darán lugar a situación legal de desempleo'),
('I', T, 'a21', 'Las empresas que formalicen contratos de interinidad para sustituir a trabajadoras víctimas de violencia de género que hayan suspendido su contrato tienen derecho a una bonificación de las cuotas empresariales por contingencias comunes del:', '100 por 100',
 ['50 por 100', '75 por 100', '25 por 100'], 'tendrán derecho a una bonificación del 100 por 100 de las cuotas empresariales'),
('I', P, 'a21', 'Duración de la bonificación de cuotas por el contrato de interinidad en los supuestos de movilidad geográfica o cambio de centro de trabajo de la trabajadora víctima', '6 meses',
 ['3 meses', '12 meses', '18 meses'], 'o durante seis meses en los supuestos de movilidad geográfica o cambio de centro de trabajo'),
('I', T, 'a21', 'Las ausencias o faltas de puntualidad al trabajo motivadas por la situación derivada de la violencia de género:', 'Se consideran justificadas y serán remuneradas cuando así lo determinen los servicios sociales de atención o de salud',
 ['Se consideran injustificadas en todo caso', 'Se justifican pero no se remuneran', 'Solo se justifican con sentencia firme'],
 'se considerarán justificadas y serán remuneradas, cuando así lo determinen los servicios sociales de atención o servicios de salud'),
('I', P, 'a21', 'Período durante el que se suspende la obligación de cotizar a las trabajadoras por cuenta propia víctimas de violencia de género que cesen en su actividad', '6 meses',
 ['3 meses', '12 meses', '24 meses'], 'se les suspenderá la obligación de cotización durante un período de seis meses'),
('I', T, 'a22', 'El programa de acción específico de empleo para las víctimas de violencia de género se dirige a las víctimas:', 'Inscritas como demandantes de empleo',
 ['Con contrato indefinido', 'Mayores de 45 años exclusivamente', 'Que hayan obtenido sentencia firme'],
 'para las víctimas de violencia de género inscritas como demandantes de empleo'),
('I', T, 'a24', 'La funcionaria víctima de violencia de género tiene derecho, en los términos de su legislación específica, a:', 'La reducción o reordenación de su tiempo de trabajo, la movilidad geográfica de centro de trabajo y la excedencia',
 ['La jubilación anticipada', 'El ascenso automático de nivel', 'Una indemnización a cargo de la Administración'],
 'tendrá derecho a la reducción o a la reordenación de su tiempo de trabajo, a la movilidad geográfica de centro de trabajo y a la excedencia'),
('I', T, 'a25', 'Las ausencias totales o parciales al trabajo de una funcionaria motivadas por la situación física o psicológica derivada de la violencia de género:', 'Se consideran justificadas en los términos de su legislación específica',
 ['Se descuentan de sus vacaciones', 'Se consideran falta leve', 'Requieren autorización previa del superior'],
 'se considerarán justificadas en los términos que se determine en su legislación específica'),
('I', T, 'a27', 'La ayuda de pago único del artículo 27 se reconoce a las víctimas que carezcan de rentas superiores, en cómputo mensual, al:', '75 por 100 del salario mínimo interprofesional, excluida la parte proporcional de dos pagas extraordinarias',
 ['100 por 100 del salario mínimo interprofesional', '50 por 100 del salario mínimo interprofesional', '75 por 100 del IPREM'],
 'al 75 por 100 del salario mínimo interprofesional'),
('I', P, 'a27', 'Importe, con carácter general, de la ayuda de pago único a víctimas de violencia de género, expresado en meses de subsidio por desempleo', '6 meses',
 ['12 meses', '3 meses', '18 meses'], 'El importe de esta ayuda será equivalente al de seis meses de subsidio por desempleo'),
('I', P, 'a27', 'Importe de la ayuda de pago único, en meses de subsidio por desempleo, cuando la víctima tenga reconocida una discapacidad igual o superior al 33 por 100', '12 meses',
 ['6 meses', '18 meses', '24 meses'], 'el importe será equivalente a doce meses de subsidio por desempleo'),
('I', T, 'a27', 'Las ayudas de pago único a víctimas de violencia de género se financian con cargo a:', 'Los Presupuestos Generales del Estado',
 ['Los presupuestos de las entidades locales', 'Las cuotas de la Seguridad Social', 'Las multas impuestas a los agresores'],
 'Estas ayudas, financiadas con cargo a los Presupuestos Generales del Estado'),
('I', T, 'a28', 'En el acceso a viviendas protegidas y residencias públicas para mayores, las mujeres víctimas de violencia de género son consideradas:', 'Colectivos prioritarios',
 ['Colectivos excluidos', 'Colectivos con reserva del 50 % de las plazas', 'Colectivos sin preferencia especial'],
 'serán consideradas colectivos prioritarios en el acceso a viviendas protegidas'),
('I', T, 'a2-2', 'El derecho a la reparación de las víctimas de violencia de género comprende, entre otros elementos:', 'Las acciones de reparación simbólica y las garantías de no repetición',
 ['Solo la indemnización económica', 'Solo la asistencia psicológica', 'La condena penal del agresor exclusivamente'],
 'las acciones de reparación simbólica y las garantías de no repetición'),
('I', T, 'a2-3', 'La indemnización por los daños y perjuicios a la víctima de violencia de género será satisfecha por:', 'La persona o personas civil o penalmente responsables',
 ['La Administración General del Estado en todo caso', 'Las Comunidades Autónomas', 'El Consorcio de Compensación de Seguros'],
 'La indemnización será satisfecha por la o las personas civil o penalmente responsables'),
# Tutela institucional
('I', T, 'a29', 'La elaboración de la Macroencuesta de Violencia contra las Mujeres corresponde a:', 'La Delegación del Gobierno contra la Violencia de Género',
 ['El Instituto Nacional de Estadística', 'El Observatorio Estatal de Violencia sobre la Mujer', 'El Consejo General del Poder Judicial'],
 'y elaborará la Macroencuesta de Violencia contra las Mujeres'),
('I', T, 'a29', 'La persona titular de la Delegación del Gobierno contra la Violencia de Género:', 'Está legitimada ante los órganos jurisdiccionales para intervenir en defensa de los derechos e intereses tutelados por la ley',
 ['No puede intervenir ante los órganos jurisdiccionales', 'Solo puede actuar como testigo', 'Solo puede intervenir en procesos penales con condena firme'],
 'estará legitimada ante los órganos jurisdiccionales para intervenir en defensa de los derechos'),
('I', T, 'a30', 'Al Observatorio Estatal de Violencia sobre la Mujer, órgano colegiado, le corresponde:', 'El asesoramiento, evaluación, colaboración institucional, elaboración de informes y estudios, y propuestas de actuación en materia de violencia de género',
 ['La instrucción de las causas penales por violencia de género', 'La concesión de las ayudas de pago único', 'La dirección de las unidades policiales especializadas'],
 'al que corresponderá el asesoramiento, evaluación, colaboración institucional, elaboración de informes y estudios'),
('I', T, 'a30', 'El Observatorio Estatal de Violencia sobre la Mujer remite al Gobierno y a las Comunidades Autónomas un informe sobre la evolución de la violencia sobre la mujer con periodicidad:', 'Anual',
 ['Semestral', 'Trimestral', 'Bienal'], 'con periodicidad anual, un informe sobre la evolución de la violencia ejercida sobre la mujer'),
('I', T, 'a30', 'Los datos contenidos en los informes, estudios y propuestas del Observatorio Estatal de Violencia sobre la Mujer se consignarán:', 'Desagregados por sexo',
 ['De forma anónima y agregada sin distinción de sexo', 'Solo respecto de las víctimas mortales', 'Por provincias exclusivamente'],
 'se consignarán desagregados por sexo'),
('I', T, 'a31', 'El Gobierno establecerá en las Fuerzas y Cuerpos de Seguridad del Estado:', 'Unidades especializadas en la prevención de la violencia de género y en el control de la ejecución de las medidas judiciales',
 ['Juzgados de guardia propios', 'Una fiscalía especializada', 'Centros de acogida para víctimas'],
 'unidades especializadas en la prevención de la violencia de género'),
('I', T, 'a32', 'Los planes de colaboración que elaboren los poderes públicos contra la violencia de género deberán implicar, entre otros, a:', 'Las administraciones sanitarias, la Administración de Justicia, las Fuerzas y Cuerpos de Seguridad y los servicios sociales y organismos de igualdad',
 ['Solo a las Fuerzas y Cuerpos de Seguridad', 'Solo a la Administración de Justicia', 'Solo a las asociaciones de mujeres'],
 'que deberán implicar a las administraciones sanitarias, la Administración de Justicia, las Fuerzas y Cuerpos de Seguridad'),
]
