# Lote 11 · Ley 40/2015, Título I y II (arts. 54-131): Administración General del Estado y sector público
# institucional estatal · bloque I (organización de la Administración pública).
# Se evitan preguntas que dependan de denominaciones de ministerios no actualizadas en el texto
# (p. ej. «Ministerio de Hacienda y Administraciones Públicas») y la adscripción orgánica de las Delegaciones.
NORMA, LOTE, INICIO = 'L40', 'lote-011', 11001
T, P = 'test', 'plazo'
PREGUNTAS = [
# Arts. 54-60: estructura de la AGE
('I', T, 'a54', 'Además de los principios generales del artículo 3, la Administración General del Estado actúa y se organiza de acuerdo con los principios de:', 'Descentralización funcional y desconcentración funcional y territorial',
 ['Centralización y concentración territorial', 'Autonomía y subsidiariedad', 'Jerarquía y tutela'],
 'así como los de descentralización funcional y desconcentración funcional y territorial'),
('I', T, 'a55', 'La organización de la Administración General del Estado responde a los principios de:', 'División funcional en Departamentos ministeriales y gestión territorial integrada en Delegaciones del Gobierno en las Comunidades Autónomas',
 ['División territorial en provincias y gestión funcional en organismos autónomos', 'Centralización en la Presidencia del Gobierno', 'Gestión compartida con las Comunidades Autónomas'],
 'responde a los principios de división funcional en Departamentos ministeriales'),
('I', T, 'a55', '¿Cuál de las siguientes NO es una de las partes que comprende la Administración General del Estado según el artículo 55.2?', 'La Organización Institucional',
 ['La Organización Central', 'La Organización Territorial', 'La Administración General del Estado en el exterior'],
 r're:La Administración General del Estado comprende: a\) La Organización Central, que integra los Ministerios y los servicios comunes\. b\) La Organización Territorial\. c\) La Administración General del Estado en el exterior'),
('I', T, 'a55', 'En la organización central de la AGE, son órganos superiores:', 'Los Ministros y los Secretarios de Estado',
 ['Los Ministros, los Secretarios de Estado y los Subsecretarios', 'Los Ministros exclusivamente', 'Los Subsecretarios y Secretarios generales'],
 r're:a\) Órganos superiores: 1\.º Los Ministros\. 2\.º Los Secretarios de Estado'),
('I', T, 'a55', '¿Cuál de los siguientes es un órgano directivo de la organización central de la AGE?', 'El Secretario general técnico',
 ['El Ministro', 'El Secretario de Estado', 'El Consejo de Ministros'],
 r're:b\) Órganos directivos: 1\.º Los Subsecretarios y Secretarios generales\. 2\.º Los Secretarios generales técnicos y Directores generales\. 3\.º Los Subdirectores generales'),
('I', T, 'a55', 'Los Delegados del Gobierno en las Comunidades Autónomas tienen rango de:', 'Subsecretario',
 ['Secretario de Estado', 'Director general', 'Subdirector general'], 'que tendrán rango de Subsecretario'),
('I', T, 'a55', 'Los Subdelegados del Gobierno en las provincias tienen nivel de:', 'Subdirector general',
 ['Director general', 'Subsecretario', 'Jefe de Servicio'], 'los cuales tendrán nivel de Subdirector general'),
('I', T, 'a55', 'En la Administración General del Estado en el exterior son órganos directivos:', 'Los embajadores y representantes permanentes ante Organizaciones internacionales',
 ['Los cónsules honorarios', 'Los agregados sectoriales', 'Los Delegados del Gobierno'],
 'En la Administración General del Estado en el exterior son órganos directivos los embajadores'),
('I', T, 'a55', 'Los órganos superiores y directivos de la AGE tienen además la condición de alto cargo, excepto:', 'Los Subdirectores generales y asimilados',
 ['Los Directores generales', 'Los Secretarios generales técnicos', 'Los Delegados del Gobierno'],
 'excepto los Subdirectores generales y asimilados'),
('I', T, 'a55', 'Según el artículo 55.9, corresponde a los órganos superiores establecer los planes de actuación de la organización situada bajo su responsabilidad y a los órganos directivos:', 'Su desarrollo y ejecución',
 ['Su aprobación definitiva', 'Su evaluación final', 'Su elevación al Consejo de Ministros'], 'y a los órganos directivos su desarrollo y ejecución'),
('I', T, 'a5-2', 'Los titulares de las Secretarías de Estado y órganos directivos de la AGE se nombrarán de modo que las personas de cada sexo, en el ámbito de cada departamento ministerial:', 'No superen el sesenta por ciento ni sean menos del cuarenta por ciento',
 ['No superen el cincuenta por ciento', 'No superen el setenta por ciento ni sean menos del treinta por ciento', 'Sean exactamente la mitad'],
 'no superen el sesenta por ciento ni sean menos del cuarenta por ciento en el ámbito de cada departamento ministerial'),
('I', T, 'a56', 'Los elementos organizativos básicos de las estructuras orgánicas son:', 'Las unidades administrativas',
 ['Los órganos directivos', 'Los puestos de trabajo aislados', 'Las Subdirecciones Generales'], 'Las unidades administrativas son los elementos organizativos básicos de las estructuras orgánicas'),
('I', T, 'a56', 'Las unidades administrativas se establecen mediante:', 'Las relaciones de puestos de trabajo',
 ['Real Decreto del Consejo de Ministros', 'Orden del Ministro respectivo', 'Ley'], 'Las unidades administrativas se establecen mediante las relaciones de puestos de trabajo'),
('I', T, 'a57', 'El número, la denominación y el ámbito de competencia de los Ministerios y Secretarías de Estado se establecen mediante:', 'Real Decreto del Presidente del Gobierno',
 ['Ley de las Cortes Generales', 'Real Decreto del Consejo de Ministros', 'Orden del Ministro de la Presidencia'],
 'se establecen mediante Real Decreto del Presidente del Gobierno'),
('I', T, 'a58', 'Según el artículo 58.2, los Ministerios contarán en todo caso con:', 'Una Subsecretaría y, dependiendo de ella, una Secretaría General Técnica',
 ['Una Secretaría de Estado y una Secretaría General', 'Una Dirección General de Servicios y una Intervención Delegada', 'Un Gabinete y una Secretaría General'],
 'Los Ministerios contarán, en todo caso, con una Subsecretaría, y dependiendo de ella una Secretaría General Técnica'),
('I', T, 'a58', 'Las Direcciones Generales se organizan para la distribución de sus competencias en:', 'Subdirecciones Generales',
 ['Secretarías Generales', 'Gabinetes técnicos', 'Delegaciones'], 'Las Direcciones Generales se organizan en Subdirecciones Generales'),
('I', T, 'a59', 'Las Direcciones Generales y Subdirecciones Generales se crean, modifican y suprimen por:', 'Real Decreto del Consejo de Ministros',
 ['Orden del Ministro respectivo', 'Real Decreto del Presidente del Gobierno', 'Las relaciones de puestos de trabajo'],
 'y órganos similares a los anteriores se crean, modifican y suprimen por Real Decreto del Consejo de Ministros'),
('I', T, 'a59', 'Los órganos de nivel inferior a Subdirección General se crean, modifican y suprimen por:', 'Orden del Ministro respectivo, previa autorización del ministro competente',
 ['Real Decreto del Consejo de Ministros', 'Resolución del Subsecretario', 'Las relaciones de puestos de trabajo'],
 'Los órganos de nivel inferior a Subdirección General se crean, modifican y suprimen por orden del Ministro respectivo'),
('I', T, 'a59', 'Las unidades que no tengan la consideración de órganos se crean, modifican y suprimen a través de:', 'Las relaciones de puestos de trabajo',
 ['Orden ministerial', 'Real Decreto', 'Resolución del Director general'], 'Las unidades que no tengan la consideración de órganos se crean, modifican y suprimen a través de las relaciones de puestos de trabajo'),
('I', T, 'a60', 'Los Ministros son superiores jerárquicos directos de:', 'Los Secretarios de Estado y Subsecretarios',
 ['Los Directores generales exclusivamente', 'Los Delegados del Gobierno', 'Los Subdirectores generales'], 'superiores jerárquicos directos de los Secretarios de Estado y Subsecretarios'),
('I', T, 'a60', 'Los órganos directivos se ordenan jerárquicamente entre sí del siguiente modo:', 'Subsecretario, Director general y Subdirector general',
 ['Director general, Subsecretario y Subdirector general', 'Secretario general técnico, Subsecretario y Director general', 'Subdirector general, Director general y Subsecretario'],
 'se ordenan jerárquicamente entre sí de la siguiente forma: Subsecretario, Director general y Subdirector general'),
('I', T, 'a60', 'Los Secretarios Generales Técnicos tienen categoría de:', 'Director general',
 ['Subsecretario', 'Secretario de Estado', 'Subdirector general'], 'los Secretarios Generales Técnicos tienen categoría de Director general'),
('I', T, 'a60', 'Los Secretarios generales tienen categoría de:', 'Subsecretario',
 ['Director general', 'Secretario de Estado', 'Ministro'], 'Los Secretarios generales tienen categoría de Subsecretario'),
# Arts. 61-67: titulares de órganos
('I', T, 'a61', '¿Cuál de las siguientes es una función de los Ministros según el artículo 61?', 'Imponer la sanción de separación del servicio por faltas muy graves',
 ['Convocar y resolver los concursos de personal funcionario', 'Desempeñar la jefatura superior de todo el personal del Departamento', 'Nombrar a los Subdelegados del Gobierno'],
 's) Imponer la sanción de separación del servicio por faltas muy graves'),
('I', T, 'a61', 'Ejercer la potestad reglamentaria en las materias propias de su Departamento corresponde a:', 'Los Ministros',
 ['Los Subsecretarios', 'Los Secretarios generales técnicos', 'Los Directores generales'], 'a) Ejercer la potestad reglamentaria en las materias propias de su Departamento'),
('I', T, 'a62', 'Los Secretarios de Estado son directamente responsables de:', 'La ejecución de la acción del Gobierno en un sector de actividad específica',
 ['La representación ordinaria del Ministerio', 'La jefatura superior del personal del Departamento', 'La producción normativa y la asistencia jurídica'],
 'Los Secretarios de Estado son directamente responsables de la ejecución de la acción del Gobierno en un sector de actividad específica'),
('I', T, 'a62', 'Nombrar y separar a los Subdirectores Generales de la Secretaría de Estado corresponde a:', 'El Secretario de Estado',
 ['El Consejo de Ministros', 'El Director general', 'El Secretario general técnico'], 'c) Nombrar y separar a los Subdirectores Generales de la Secretaría de Estado'),
('I', T, 'a63', 'La representación ordinaria del Ministerio corresponde a:', 'Los Subsecretarios',
 ['Los Ministros', 'Los Secretarios de Estado', 'Los Secretarios generales técnicos'], 'Los Subsecretarios ostentan la representación ordinaria del Ministerio'),
('I', T, 'a63', 'Desempeñar la jefatura superior de todo el personal del Departamento corresponde a:', 'El Subsecretario',
 ['El Ministro', 'El Secretario general técnico', 'El Director general de Servicios'], 'f) Desempeñar la jefatura superior de todo el personal del Departamento'),
('I', T, 'a63', 'Ejercer la potestad disciplinaria del personal del Departamento por faltas graves o muy graves, salvo la separación del servicio, corresponde a:', 'El Subsecretario',
 ['El Ministro', 'El Director general', 'El Subdirector general de Recursos Humanos'],
 'ñ) Ejercer la potestad disciplinaria del personal del Departamento por faltas graves o muy graves, salvo la separación del servicio'),
('I', T, 'a63', 'Convocar y resolver pruebas selectivas de personal funcionario y laboral del Departamento corresponde a:', 'El Subsecretario',
 ['El Ministro', 'El Secretario de Estado', 'El Secretario general técnico'], 'm) Convocar y resolver pruebas selectivas de personal funcionario y laboral'),
('I', T, 'a63', 'Los Subsecretarios son nombrados y separados:', 'Por Real Decreto del Consejo de Ministros a propuesta del titular del Ministerio',
 ['Por Orden del Ministro', 'Por Real Decreto del Presidente del Gobierno', 'Por el Secretario de Estado del que dependan'],
 'Los Subsecretarios serán nombrados y separados por Real Decreto del Consejo de Ministros a propuesta del titular del Ministerio'),
('I', T, 'a63', 'Los Subsecretarios deben nombrarse, con carácter general, entre funcionarios de carrera del Estado, de las CCAA o de las Entidades locales pertenecientes al:', 'Subgrupo A1',
 ['Subgrupo A2', 'Grupo B', 'Subgrupo C1'], 'pertenecientes al Subgrupo A1, a que se refiere el artículo 76 del texto refundido'),
('I', T, 'a64', 'Los Secretarios generales se nombran entre:', 'Personas con cualificación y experiencia en el desempeño de puestos de responsabilidad en la gestión pública o privada',
 ['Funcionarios del Subgrupo A1 exclusivamente', 'Altos cargos con al menos cinco años de antigüedad', 'Miembros de las Cortes Generales'],
 'Los nombramientos habrán de efectuarse entre personas con cualificación y experiencia en el desempeño de puestos de responsabilidad en la gestión pública o privada'),
('I', T, 'a65', 'Los Secretarios generales técnicos dependen inmediatamente de:', 'El Subsecretario',
 ['El Ministro', 'El Secretario de Estado', 'El Director general'], 'Los Secretarios generales técnicos, bajo la inmediata dependencia del Subsecretario'),
('I', T, 'a65', 'Los Secretarios generales técnicos tienen, en todo caso, las competencias relativas a:', 'Producción normativa, asistencia jurídica y publicaciones',
 ['Gestión de personal y presupuestos', 'Inspección de servicios y régimen disciplinario', 'Contratación y patrimonio'],
 'las relativas a producción normativa, asistencia jurídica y publicaciones'),
('I', T, 'a66', 'Los Directores generales son los titulares de los órganos directivos encargados de:', 'La gestión de una o varias áreas funcionalmente homogéneas del Ministerio',
 ['La representación ordinaria del Ministerio', 'La ejecución de la acción del Gobierno en un sector', 'La gestión ordinaria de una Subdirección General'],
 'Los Directores generales son los titulares de los órganos directivos encargados de la gestión de una o varias áreas funcionalmente homogéneas'),
('I', T, 'a66', 'Excepcionalmente, el titular de una Dirección General puede no ser funcionario cuando:', 'Lo permita el Real Decreto de estructura, en atención a las características específicas de sus funciones, motivándolo en memoria razonada',
 ['Lo decida libremente el Ministro', 'Lo autoricen las Cortes Generales', 'Nunca, debe ser siempre funcionario del Subgrupo A1'],
 'salvo que el Real Decreto de estructura permita que, en atención a las características específicas de las funciones de la Dirección General'),
('I', T, 'a67', 'Los Subdirectores generales son nombrados y cesados por:', 'El Ministro, Secretario de Estado o Subsecretario del que dependan',
 ['El Consejo de Ministros mediante Real Decreto', 'El Director general del que dependan', 'El Presidente del Gobierno'],
 'y cesados por el Ministro, Secretario de Estado o Subsecretario del que dependan'),
('I', T, 'a67', 'El nombramiento de los Subdirectores generales debe respetar los principios de:', 'Igualdad, mérito y capacidad',
 ['Confianza política', 'Antigüedad', 'Libre designación sin requisitos'], 'Los Subdirectores generales serán nombrados, respetando los principios de igualdad, mérito y capacidad'),
# Arts. 68-80: servicios comunes y Administración periférica
('I', T, 'a68', '¿Cuál de las siguientes funciones corresponde a los servicios comunes de los Ministerios según el artículo 68?', 'Estadística para fines estatales y publicaciones',
 ['Ejecución de la acción del Gobierno en un sector', 'Representación del Gobierno en las Comunidades Autónomas', 'Dirección de las Fuerzas y Cuerpos de Seguridad'],
 'estadística para fines estatales y publicaciones'),
('I', T, 'a69', '¿Cuántas Delegaciones del Gobierno existen según el artículo 69.1?', 'Una en cada Comunidad Autónoma',
 ['Una en cada provincia', 'Una en cada Comunidad Autónoma pluriprovincial', 'Una por cada Ministerio'], 'Existirá una Delegación del Gobierno en cada una de las Comunidades Autónomas'),
('I', T, 'a69', 'Salvo acuerdo distinto del Consejo de Ministros o previsión del Estatuto de Autonomía, las Delegaciones del Gobierno tienen su sede en:', 'La localidad donde radique el Consejo de Gobierno de la Comunidad Autónoma',
 ['La capital de la provincia más poblada', 'La localidad donde radique el Parlamento autonómico', 'Madrid'],
 'tendrán su sede en la localidad donde radique el Consejo de Gobierno de la Comunidad Autónoma'),
('I', T, 'a69', 'En las Comunidades Autónomas uniprovinciales, las Subdelegaciones del Gobierno:', 'Pueden crearse por Real Decreto cuando circunstancias como la población o el volumen de gestión lo justifiquen',
 ['Existen siempre', 'Están prohibidas', 'Se crean por orden del Delegado del Gobierno'],
 'Podrán crearse por Real Decreto Subdelegaciones del Gobierno en las Comunidades Autónomas uniprovinciales'),
('I', T, 'a70', 'Los Directores Insulares de la Administración General del Estado son nombrados por:', 'El Delegado del Gobierno, mediante libre designación entre funcionarios del Subgrupo A1',
 ['El Consejo de Ministros', 'El Subdelegado del Gobierno, por concurso', 'El Presidente del Cabildo o Consejo Insular'],
 'Serán nombrados por el Delegado del Gobierno mediante el procedimiento de libre designación'),
('I', T, 'a71', 'Los servicios territoriales integrados en las Delegaciones del Gobierno dependen:', 'Del Delegado del Gobierno o, en su caso, del Subdelegado, a través de la Secretaría General',
 ['Del órgano central competente sobre el sector de actividad', 'Del Ministro de la Presidencia directamente', 'De la Comunidad Autónoma'],
 'Los servicios territoriales integrados dependerán del Delegado del Gobierno'),
('I', T, 'a71', 'Los servicios territoriales no integrados en las Delegaciones del Gobierno dependen:', 'Del órgano central competente sobre el sector de actividad en el que operen',
 ['Del Delegado del Gobierno', 'Del Subdelegado del Gobierno', 'De la Secretaría General de la Delegación'],
 'Los servicios territoriales no integrados dependerán del órgano central competente sobre el sector de actividad'),
('I', T, 'a72', 'Los Delegados del Gobierno representan al Gobierno de la Nación en el territorio de la Comunidad Autónoma:', 'Sin perjuicio de la representación ordinaria del Estado a través de los Presidentes autonómicos',
 ['Con exclusión de cualquier otra representación del Estado', 'Solo en materia de seguridad ciudadana', 'Por delegación del Presidente autonómico'],
 'Los Delegados del Gobierno representan al Gobierno de la Nación en el territorio de la respectiva Comunidad Autónoma'),
('I', T, 'a72', 'Los Delegados del Gobierno son nombrados y separados por:', 'Real Decreto del Consejo de Ministros, a propuesta del Presidente del Gobierno',
 ['Real Decreto del Presidente del Gobierno, a propuesta del Ministro del Interior', 'El Presidente de la Comunidad Autónoma', 'Orden del Ministro de la Presidencia'],
 'Los Delegados del Gobierno serán nombrados y separados por Real Decreto del Consejo de Ministros, a propuesta del Presidente del Gobierno'),
('I', T, 'a72', 'En caso de ausencia, vacante o enfermedad, el Delegado del Gobierno es suplido:', 'Por el Subdelegado del Gobierno que el Delegado designe y, en su defecto, por el de la provincia en que tenga su sede',
 ['Por el Secretario General de la Delegación en todo caso', 'Por el Subdelegado más antiguo', 'Por el Ministro competente'],
 'será suplido por el Subdelegado del Gobierno que el Delegado designe'),
('I', T, 'a73', 'Nombrar a los Subdelegados del Gobierno en las provincias corresponde a:', 'El Delegado del Gobierno en la Comunidad Autónoma',
 ['El Consejo de Ministros', 'El Ministro del Interior', 'El Presidente del Gobierno'], '2.º Nombrar a los Subdelegados del Gobierno en las provincias de su ámbito de actuación'),
('I', T, 'a73', 'Los Delegados del Gobierno elevan al Gobierno un informe sobre el funcionamiento de los servicios públicos estatales en el ámbito autonómico con carácter:', 'Anual',
 ['Semestral', 'Trimestral', 'Bienal'], '4.º Elevar al Gobierno, con carácter anual'),
('I', T, 'a73', 'La jefatura de las Fuerzas y Cuerpos de Seguridad del Estado en el territorio de la Comunidad Autónoma corresponde a:', 'El Delegado del Gobierno, bajo la dependencia funcional del Ministerio del Interior',
 ['El Presidente de la Comunidad Autónoma', 'El Subdelegado del Gobierno de la capital', 'El Director General de la Policía'],
 'cuya jefatura corresponderá al Delegado del Gobierno, quien ejercerá las competencias del Estado en esta materia bajo la dependencia funcional del Ministerio del Interior'),
('I', T, 'a74', 'Los Subdelegados del Gobierno se nombran:', 'Por el Delegado del Gobierno mediante libre designación entre funcionarios de carrera del Subgrupo A1',
 ['Por Real Decreto del Consejo de Ministros', 'Por concurso de méritos entre funcionarios del Subgrupo A2', 'Por el Ministro del Interior'],
 r're:que será nombrado por aquél mediante el procedimiento de libre designación.*?clasificados como Subgrupo A1'),
('I', T, 'a74', 'En las Comunidades Autónomas uniprovinciales en las que no exista Subdelegado:', 'El Delegado del Gobierno asume las competencias de los Subdelegados',
 ['El Secretario General asume las competencias de los Subdelegados', 'Las competencias pasan al Ministerio del Interior', 'Se nombra un Director Insular'],
 'el Delegado del Gobierno asumirá las competencias que esta Ley atribuye a los Subdelegados del Gobierno en las provincias'),
('I', T, 'a75', 'Dirigir y coordinar la protección civil en el ámbito de la provincia corresponde a:', 'El Subdelegado del Gobierno',
 ['El Delegado del Gobierno', 'El Presidente de la Diputación Provincial', 'El Director Insular'], 'c) Dirigir y coordinar la protección civil en el ámbito de la provincia'),
('I', T, 'a76', 'Las Delegaciones y Subdelegaciones del Gobierno cuentan en todo caso, como órgano de gestión de los servicios comunes, con:', 'Una Secretaría General',
 ['Una Subsecretaría', 'Una Secretaría General Técnica', 'Un Gabinete'], 'contarán, en todo caso, con una Secretaría General'),
('I', T, 'a77', 'La asistencia jurídica y el control económico-financiero de las Delegaciones y Subdelegaciones del Gobierno se ejercen, respectivamente, por:', 'La Abogacía del Estado y la Intervención General de la Administración del Estado',
 ['Los Servicios Jurídicos autonómicos y el Tribunal de Cuentas', 'La Secretaría General Técnica y la Dirección General de Presupuestos', 'El Consejo de Estado y la Intervención General'],
 'se ejercerán por la Abogacía del Estado y la Intervención General de la Administración del Estado respectivamente'),
('I', T, 'a79', 'En las Comunidades Autónomas pluriprovinciales, la Comisión territorial de asistencia al Delegado del Gobierno está presidida por el Delegado e integrada por:', 'Los Subdelegados del Gobierno en las provincias de su territorio',
 ['Los Consejeros autonómicos', 'Los Presidentes de las Diputaciones', 'Los Directores generales de los ministerios'],
 'e integrada por los Subdelegados del Gobierno en las provincias comprendidas en el territorio de ésta'),
('I', T, 'a80', 'El Servicio Exterior del Estado se rige por:', 'La Ley 2/2014, de la Acción y del Servicio Exterior del Estado, y supletoriamente por la Ley 40/2015',
 ['Exclusivamente por la Ley 40/2015', 'Por el Convenio de Viena exclusivamente', 'Por Real Decreto del Ministro de Asuntos Exteriores'],
 'El Servicio Exterior del Estado se rige en todo lo concerniente'),
# Arts. 81-97: sector público institucional y organismos públicos
('I', T, 'a81', 'Las entidades del sector público institucional están sometidas en su actuación a los principios de:', 'Legalidad, eficiencia, estabilidad presupuestaria, sostenibilidad financiera y transparencia en su gestión',
 ['Rentabilidad, competitividad y libre mercado', 'Autonomía plena y no sujeción a control', 'Jerarquía y centralización'],
 'están sometidas en su actuación a los principios de legalidad, eficiencia, estabilidad presupuestaria y sostenibilidad financiera'),
('I', T, 'a82', 'La integración, gestión y publicación del Inventario de Entidades del Sector Público Estatal, Autonómico y Local depende de:', 'La Intervención General de la Administración del Estado',
 ['El Tribunal de Cuentas', 'El Instituto Nacional de Estadística', 'La Dirección General del Patrimonio del Estado'],
 r're:La integración y gestión de dicho Inventario y su publicación dependerá de la Intervención General de la Administración del Estado(?=\. Téngase)'),
('I', P, 'a83', 'Plazo para notificar al Inventario de Entidades del Sector Público los actos de creación, transformación, fusión o extinción de una entidad, desde que ocurra el acto inscribible', '30 días hábiles',
 ['15 días hábiles', '10 días hábiles', '20 días hábiles'], 'en el plazo de treinta días hábiles a contar desde que ocurra el acto inscribible'),
('I', P, 'a83', 'Plazo para practicar la inscripción en el Inventario de Entidades del Sector Público desde la recepción de la solicitud', '15 días hábiles',
 ['30 días hábiles', '10 días hábiles', '5 días hábiles'], 'se practicará dentro del plazo de 15 días hábiles siguientes a la recepción de la solicitud de inscripción'),
('I', T, 'a84', '¿Cuál de las siguientes NO es una clase de organismo público vinculado o dependiente de la AGE según el artículo 84.1.a)?', 'Las sociedades mercantiles estatales',
 ['Los organismos autónomos', 'Las entidades públicas empresariales', 'Las agencias estatales'],
 r're:los cuales se clasifican en: 1\. Organismos autónomos\. 2\. Entidades públicas empresariales\. 3\. Agencias estatales'),
('I', T, 'a84', '¿Cuál de las siguientes entidades NO integra el sector público institucional estatal según el artículo 84.1?', 'Las mutualidades privadas de previsión social',
 ['Las autoridades administrativas independientes', 'Los fondos sin personalidad jurídica', 'Las universidades públicas no transferidas'],
 r're:Integran el sector público institucional estatal las siguientes entidades:.*?g\) Las universidades públicas no transferidas'),
('I', T, 'a8-2', 'En las entidades del sector público institucional estatal, el principio de representación equilibrada exige que las personas de cada sexo, entre sus máximos responsables y personal de alta dirección:', 'No superen el sesenta por ciento ni sean menos del cuarenta por ciento',
 ['No superen el cincuenta por ciento', 'No superen el setenta y cinco por ciento', 'Sean al menos un treinta por ciento'],
 'de tal manera que las personas de cada sexo no superen el sesenta por ciento ni sean menos del cuarenta por ciento en el ámbito de cada entidad'),
('I', T, 'a85', 'El plan de actuación con el que deben contar las entidades del sector público institucional estatal desde su creación se revisa:', 'Cada tres años, completándose con planes anuales',
 ['Cada cinco años', 'Cada año, sin planes anuales', 'Solo cuando lo pida el Ministerio de adscripción'],
 'que se revisarán cada tres años'),
('I', T, 'a85', 'El control de eficacia de las entidades del sector público institucional estatal lo ejerce:', 'El Departamento al que estén adscritas, a través de las inspecciones de servicios',
 ['El Tribunal de Cuentas', 'Las Cortes Generales', 'La propia entidad mediante autoevaluación'],
 'El control de eficacia será ejercido por el Departamento al que estén adscritos, a través de las inspecciones de servicios'),
('I', T, 'a86', 'En la denominación de las entidades del sector público institucional que tengan la condición de medio propio debe figurar:', 'La indicación «Medio Propio» o su abreviatura «M.P.»',
 ['La indicación «Servicio Técnico» o «S.T.»', 'La indicación «Entidad Instrumental»', 'No es necesaria ninguna indicación'],
 'deberá figurar necesariamente la indicación'),
('I', T, 'a87', 'Con carácter general, la transformación de una entidad del sector público institucional estatal se lleva a cabo mediante:', 'Real Decreto, aunque suponga modificación de la ley de creación, salvo la transformación en agencia estatal, que requiere ley',
 ['Ley en todo caso', 'Orden ministerial', 'Acuerdo del órgano de gobierno de la entidad'],
 'La transformación se llevará a cabo mediante Real Decreto, aunque suponga modificación de la Ley de creación'),
('I', T, 'a89', 'Dentro de su esfera de competencia, a los organismos públicos les corresponden las potestades administrativas precisas para sus fines, salvo:', 'La potestad expropiatoria',
 ['La potestad sancionadora', 'La potestad de autoorganización', 'La potestad de ejecución forzosa'], 'salvo la potestad expropiatoria'),
('I', T, 'a90', 'Los máximos órganos de gobierno de los organismos públicos son:', 'El Presidente y el Consejo Rector',
 ['El Director y el Consejo de Administración', 'El Ministro de adscripción y el Subsecretario', 'La Junta General y el Patronato'],
 'Los máximos órganos de gobierno son el Presidente y el Consejo Rector'),
('I', T, 'a91', 'La creación de los organismos públicos estatales se efectúa por:', 'Ley',
 ['Real Decreto del Consejo de Ministros', 'Orden ministerial', 'Acuerdo del Consejo de Ministros'], 'La creación de los organismos públicos se efectuará por Ley'),
('I', T, 'a92', 'El plan anual de actuación de un organismo público debe aprobarse por su departamento de dependencia:', 'En el último trimestre del año natural',
 ['En el primer trimestre del año natural', 'Antes del 30 de junio', 'Dentro del mes siguiente a la aprobación de los Presupuestos'],
 'El plan anual de actuación deberá ser aprobado en el último trimestre del año natural'),
('I', T, 'a93', 'Los estatutos de los organismos públicos se aprueban por:', 'Real Decreto del Consejo de Ministros',
 ['Ley', 'Orden del Ministro de adscripción', 'Acuerdo del Consejo Rector'], 'Los estatutos de los organismos públicos se aprobarán por Real Decreto del Consejo de Ministros'),
('I', T, 'a93', 'Los estatutos de los organismos públicos deben aprobarse y publicarse:', 'Con carácter previo a la entrada en funcionamiento efectivo del organismo',
 ['En el plazo de un año desde su entrada en funcionamiento', 'Junto con su primer presupuesto', 'Solo si lo exige la ley de creación'],
 'Los estatutos deberán ser aprobados y publicados con carácter previo a la entrada en funcionamiento efectivo del organismo público'),
('I', T, 'a94', 'La fusión de organismos públicos estatales de la misma naturaleza jurídica se lleva a cabo mediante:', 'Norma reglamentaria, aunque suponga modificación de la Ley de creación',
 ['Ley en todo caso', 'Acuerdo de los Consejos Rectores', 'Convenio entre los organismos'], 'La fusión se llevará a cabo mediante norma reglamentaria'),
('I', T, 'a95', '¿Cuál de los siguientes NO figura entre los servicios comunes mínimos de los organismos públicos según el artículo 95.2?', 'La gestión de recursos humanos',
 ['La gestión de bienes inmuebles', 'Los sistemas de información y comunicación', 'La contratación pública'],
 r're:Se consideran servicios comunes de los organismos públicos, al menos, los siguientes: a\).*?f\) Contratación pública'),
('I', P, 'a96', 'Plazo para que el titular del máximo órgano de dirección comunique al departamento de adscripción que el organismo público incurre en causa de disolución', '2 meses',
 ['1 mes', '3 meses', '6 meses'], 'lo comunicará al titular del departamento de adscripción en el plazo de dos meses desde que concurra la causa de disolución'),
('I', T, 'a97', 'La liquidación de un organismo público estatal tiene lugar por la cesión e integración global de todo su activo y pasivo en:', 'La Administración General del Estado, que le sucede universalmente',
 ['El organismo público más próximo por razón de materia', 'La Comunidad Autónoma donde tenga su sede', 'Un fondo sin personalidad jurídica en todo caso'],
 'en la Administración General del Estado que le sucederá universalmente en todos sus derechos y obligaciones'),
# Arts. 98-108 sexies: organismos autónomos, EPE y agencias
('I', T, 'a98', 'En la denominación de un organismo público con naturaleza de organismo autónomo debe figurar:', 'La indicación «organismo autónomo» o su abreviatura «O.A.»',
 ['La indicación «entidad pública» o «E.P.»', 'La indicación «agencia» o «A.»', 'No es necesaria ninguna indicación'],
 'deberá figurar en su denominación la indicación «organismo autónomo» o su abreviatura «O.A.»'),
('I', T, 'a100', 'El personal al servicio de los organismos autónomos será:', 'Funcionario o laboral',
 ['Exclusivamente laboral', 'Exclusivamente funcionario', 'Personal eventual en todo caso'], 'El personal al servicio de los organismos autónomos será funcionario o laboral'),
('I', T, 'a100', 'En los organismos autónomos, el órgano de contratación es:', 'El titular del máximo órgano de dirección del organismo',
 ['El Ministro de adscripción', 'El Consejo Rector', 'El Subsecretario del Ministerio de adscripción'],
 'El titular del máximo órgano de dirección del organismo autónomo será el órgano de contratación'),
('I', T, 'a103', 'Las entidades públicas empresariales se financian, con carácter general:', 'Con ingresos de mercado, salvo las que tengan la condición de medio propio personificado',
 ['Exclusivamente con transferencias de los Presupuestos Generales del Estado', 'Con tasas y precios públicos exclusivamente', 'Con endeudamiento ilimitado'],
 'que se financian con ingresos de mercado'),
('I', T, 'a103', 'En la denominación de las entidades públicas empresariales debe figurar:', 'La indicación «entidad pública empresarial» o su abreviatura «E.P.E.»',
 ['La indicación «sociedad mercantil estatal» o «S.M.E.»', 'La indicación «organismo autónomo» o «O.A.»', 'La indicación «empresa pública»'],
 'deberá figurar en su denominación la indicación de «entidad pública empresarial»'),
('I', T, 'a104', 'Las entidades públicas empresariales se rigen, con carácter general, por:', 'El Derecho privado, excepto en la formación de la voluntad de sus órganos y el ejercicio de potestades administrativas, entre otros aspectos',
 ['El Derecho administrativo en todo caso', 'El Derecho laboral exclusivamente', 'El Derecho mercantil sin excepciones'],
 'Las entidades públicas empresariales se rigen por el Derecho privado, excepto en la formación de la voluntad de sus órganos'),
('I', T, 'a106', 'El personal de las entidades públicas empresariales se rige, con carácter general, por:', 'El Derecho laboral, con las excepciones relativas a los funcionarios de la AGE',
 ['El TREBEP en su integridad', 'El Derecho administrativo', 'El Derecho mercantil'], r're:El personal de las entidades públicas empresariales se rige por el Derecho laboral.*?funcionarios públicos de la Administración General del Estado'),
('I', T, 'a1-2', 'Las agencias estatales son creadas por:', 'El Gobierno, para el cumplimiento de los programas correspondientes a las políticas públicas de la AGE',
 ['Las Cortes Generales mediante ley orgánica', 'Los Ministros mediante orden', 'Las Comunidades Autónomas'],
 'que son creadas por el Gobierno para el cumplimiento de los programas correspondientes a las políticas públicas'),
('I', T, 'a1-3', 'La actuación de las agencias estatales se produce con arreglo al plan de acción anual y al pertinente:', 'Contrato plurianual de gestión',
 ['Contrato-programa con el Estado', 'Convenio de colaboración', 'Programa de actuación plurianual'],
 'bajo la vigencia y con arreglo al pertinente contrato plurianual de gestión'),
('I', P, 'a1-3', 'Plazo, desde su constitución, para que el Consejo Rector de una agencia estatal apruebe la propuesta de contrato inicial de gestión', '3 meses',
 ['1 mes', '6 meses', '2 meses'], 'aprueba la propuesta de contrato inicial de gestión, en el plazo de tres meses desde su constitución'),
('I', T, 'a1-4', 'El órgano ejecutivo de la agencia estatal es:', 'El director, nombrado y separado por el Consejo Rector a propuesta del Presidente',
 ['El Presidente, nombrado por el Consejo de Ministros', 'La Comisión de Control', 'El Secretario General'],
 'El órgano ejecutivo de la agencia estatal es el director'),
('I', T, 'a1-5', 'El recurso al endeudamiento por las agencias estatales:', 'Está prohibido salvo que una ley disponga lo contrario, aunque pueden concertar pólizas de crédito para desfases de tesorería',
 ['Está permitido sin límite', 'Requiere autorización del Consejo Rector', 'Está permitido hasta el 50 % de su presupuesto'],
 'El recurso al endeudamiento está prohibido a las agencias estatales, salvo que por Ley se disponga lo contrario'),
('I', T, 'a1-5', 'Para atender desfases temporales de tesorería, las agencias estatales pueden contratar pólizas de crédito o préstamo siempre que el saldo vivo no supere:', 'El 5 % de su presupuesto',
 ['El 10 % de su presupuesto', 'El 1 % de su presupuesto', 'El 20 % de su presupuesto'], 'siempre que el saldo vivo no supere el 5 % de su presupuesto'),
('I', P, 'a1-6', 'Plazo para que la persona titular de la Dirección formule las cuentas anuales de una agencia estatal, desde el cierre del ejercicio', '3 meses',
 ['1 mes', '6 meses', '2 meses'], 'Las cuentas anuales de las agencias estatales se formulan por la persona titular de la Dirección en el plazo de tres meses'),
# Arts. 109-131: AAI, sociedades, consorcios y fundaciones
('I', T, 'a109', 'Las autoridades administrativas independientes tienen atribuidas funciones de:', 'Regulación o supervisión de carácter externo sobre sectores económicos o actividades determinadas',
 ['Prestación directa de servicios públicos', 'Producción de bienes en régimen de mercado', 'Asesoramiento jurídico al Gobierno'],
 'tienen atribuidas funciones de regulación o supervisión de carácter externo sobre sectores económicos o actividades determinadas'),
('I', T, 'a109', 'La necesidad de independencia funcional o especial autonomía de una autoridad administrativa independiente debe determinarse en:', 'Una norma con rango de Ley',
 ['Un Real Decreto', 'Sus estatutos', 'Una orden ministerial'], 'lo que deberá determinarse en una norma con rango de Ley'),
('I', T, 'a111', 'Una sociedad mercantil es estatal, entre otros supuestos, cuando la participación directa en su capital de la AGE o de entidades del sector público institucional estatal sea:', 'Superior al 50 por 100',
 ['Superior al 25 por 100', 'Igual o superior al 40 por 100', 'Del 100 por 100 en todo caso'], 'sea superior al 50 por 100'),
('I', T, 'a111', 'En la denominación de las sociedades mercantiles estatales debe figurar:', 'La indicación «sociedad mercantil estatal» o su abreviatura «S.M.E.»',
 ['La indicación «sociedad anónima pública»', 'La indicación «entidad pública empresarial» o «E.P.E.»', 'No es necesaria ninguna indicación especial'],
 'deberá figurar necesariamente la indicación «sociedad mercantil estatal» o su abreviatura «S.M.E.»'),
('I', T, 'a113', 'Las sociedades mercantiles estatales:', 'En ningún caso pueden disponer de facultades que impliquen el ejercicio de autoridad pública, salvo que excepcionalmente la ley les atribuya potestades administrativas',
 ['Pueden ejercer la potestad expropiatoria', 'Ejercen la potestad sancionadora en todo caso', 'Pueden dictar actos administrativos libremente'],
 'En ningún caso podrán disponer de facultades que impliquen el ejercicio de autoridad pública'),
('I', T, 'a114', 'La creación de una sociedad mercantil estatal se autoriza mediante:', 'Acuerdo del Consejo de Ministros',
 ['Ley de las Cortes Generales', 'Orden del Ministro de Hacienda', 'Escritura pública sin autorización previa'],
 'será autorizada mediante acuerdo del Consejo de Ministros'),
('I', T, 'a117', 'El personal de las sociedades mercantiles estatales, incluido el directivo, se rige por:', 'El Derecho laboral y las normas aplicables por su adscripción al sector público estatal',
 ['El TREBEP como personal funcionario', 'El Derecho administrativo exclusivamente', 'El régimen de altos cargos'],
 'incluido el que tenga condición de directivo, se regirá por el Derecho laboral'),
('I', T, 'a118', 'Los consorcios son entidades de derecho público creadas por varias Administraciones Públicas o entidades del sector público institucional para:', 'El desarrollo de actividades de interés común a todas ellas dentro del ámbito de sus competencias',
 ['La producción de bienes en régimen de mercado con ánimo de lucro', 'La supervisión independiente de sectores económicos', 'La gestión de fondos sin personalidad jurídica'],
 'para el desarrollo de actividades de interés común a todas ellas dentro del ámbito de sus competencias'),
('I', T, 'a118', 'En la denominación de los consorcios debe figurar:', 'La indicación «consorcio» o su abreviatura «C»',
 ['La indicación «mancomunidad»', 'La indicación «C.P.»', 'No es necesaria ninguna indicación'], 'En la denominación de los consorcios deberá figurar necesariamente la indicación «consorcio» o su abreviatura «C»'),
('I', T, 'a120', 'El primer criterio, por orden de prioridad, para determinar la Administración a la que queda adscrito un consorcio es que:', 'Disponga de la mayoría de votos en los órganos de gobierno',
 ['Ostente el mayor porcentaje de participación en el fondo patrimonial', 'Financie en más de un cincuenta por ciento la actividad', 'Tenga mayor número de habitantes'],
 'a) Disponga de la mayoría de votos en los órganos de gobierno'),
('I', T, 'a120', 'El cambio de adscripción de un consorcio a otra Administración conlleva la modificación de sus estatutos en un plazo no superior a:', 'Seis meses desde el inicio del ejercicio presupuestario siguiente',
 ['Tres meses desde el cambio', 'Un año desde el cambio', 'Dos meses desde el inicio del ejercicio siguiente'],
 'en un plazo no superior a seis meses, contados desde el inicio del ejercicio presupuestario siguiente'),
('I', T, 'a121', 'El personal de los consorcios, con carácter general:', 'Puede ser funcionario o laboral y debe proceder de las Administraciones participantes',
 ['Debe ser contratado libremente por el consorcio', 'Es siempre personal eventual', 'Debe ser exclusivamente funcionario de la AGE'],
 'El personal al servicio de los consorcios podrá ser funcionario o laboral y habrá de proceder de las Administraciones participantes'),
('I', T, 'a123', 'Los consorcios se crean mediante:', 'Convenio suscrito por las Administraciones, organismos públicos o entidades participantes',
 ['Ley orgánica', 'Real Decreto del Presidente del Gobierno', 'Escritura pública ante notario'],
 'Los consorcios se crearán mediante convenio suscrito por las Administraciones, organismos públicos o entidades participantes'),
('I', T, 'a123', 'En los consorcios en que participe la AGE, su creación requiere:', 'Autorización por ley y autorización previa del convenio por el Consejo de Ministros',
 ['Solo la firma del convenio por el Ministro', 'Autorización del Tribunal de Cuentas', 'Orden del Ministro de Hacienda'],
 r're:se requerirá: a\) Que su creación se autorice por ley\. b\) El convenio de creación precisará de autorización previa del Consejo de Ministros'),
('I', T, 'a126', 'El ejercicio del derecho de separación de un consorcio produce su disolución, salvo que los restantes miembros acuerden su continuidad y permanezcan en él, al menos:', 'Dos Administraciones, o entidades u organismos públicos vinculados o dependientes de más de una Administración',
 ['Tres Administraciones', 'La mitad de los miembros iniciales', 'Una Administración'],
 'y sigan permaneciendo en el consorcio, al menos, dos Administraciones'),
('I', T, 'a128', 'Las fundaciones del sector público estatal:', 'No podrán ejercer potestades públicas',
 ['Pueden ejercer potestades públicas si lo prevén sus estatutos', 'Ejercen la potestad sancionadora', 'Pueden ejercer la potestad expropiatoria'], 'Las fundaciones no podrán ejercer potestades públicas'),
('I', T, 'a128', 'En la denominación de las fundaciones del sector público estatal debe figurar:', 'La indicación «fundación del sector público» o su abreviatura «F.S.P.»',
 ['La indicación «fundación pública» o «F.P.»', 'La indicación «fundación estatal» o «F.E.»', 'No es necesaria ninguna indicación'],
 'deberá figurar necesariamente la indicación «fundación del sector público» o su abreviatura «F.S.P.»'),
('I', T, 'a128', 'Es fundación del sector público estatal, entre otros supuestos, aquella cuyo patrimonio esté integrado con carácter permanente por bienes o derechos aportados o cedidos por la AGE o el sector público institucional estatal en:', 'Más de un 50 por ciento',
 ['Más de un 25 por ciento', 'Al menos un 33 por ciento', 'La totalidad'], 'esté integrado en más de un 50 por ciento por bienes o derechos aportados'),
('I', T, 'a129', 'El cambio de adscripción de una fundación del sector público a otra Administración conlleva la modificación de sus estatutos en un plazo no superior a:', 'Tres meses desde el inicio del ejercicio presupuestario siguiente',
 ['Seis meses desde el inicio del ejercicio siguiente', 'Un mes desde el cambio', 'Un año desde el cambio'],
 'deberá realizarse en un plazo no superior a tres meses, contados desde el inicio del ejercicio presupuestario siguiente'),
('I', T, 'a131', 'La contratación de las fundaciones del sector público estatal se ajusta a:', 'La legislación sobre contratación del sector público',
 ['El Derecho privado exclusivamente', 'Sus estatutos sin sujeción a la legislación de contratos', 'La Ley de Fundaciones exclusivamente'],
 'La contratación de las fundaciones del sector público estatal se ajustará a lo dispuesto en la legislación sobre contratación del sector público'),
]
