# Lote 7 · TREBEP (RDL 5/2015) · bloque IV (gestión de personal). Sin repetir lote-001 (art. 76).
# Formato: (bloque, tipo, artículo, pregunta, respuesta correcta, [3 distractores], ancla de la cita en el texto del BOE)
NORMA, LOTE, INICIO = 'TREBEP', 'lote-007', 7001
T, P = 'test', 'plazo'
PREGUNTAS = [
('IV', T, 'a1', '¿Cuál de los siguientes NO figura entre los fundamentos de actuación del artículo 1.3 del TREBEP?', 'Libre designación en el acceso al empleo público',
 ['Igualdad, mérito y capacidad en el acceso y en la promoción profesional', 'Transparencia', 'Jerarquía en la atribución, ordenación y desempeño de las funciones y tareas'],
 r're:Este Estatuto refleja, del mismo modo, los siguientes fundamentos de actuación: a\).*?l\) Cooperación entre las Administraciones Públicas en la regulación y gestión del empleo público'),
('IV', T, 'a2', 'Según el artículo 2.5, el TREBEP respecto del personal de las Administraciones Públicas no incluido en su ámbito de aplicación tiene carácter:', 'Supletorio',
 ['Obligatorio', 'Preferente', 'Excluyente'], 'El presente Estatuto tiene carácter supletorio para todo el personal de las Administraciones Públicas no incluido en su ámbito de aplicación'),
('IV', T, 'a4', '¿A cuál de los siguientes colectivos solo se aplica el TREBEP directamente cuando así lo disponga su legislación específica?', 'Personal militar de las Fuerzas Armadas',
 ['Personal funcionario de la Administración General del Estado', 'Personal de las Universidades Públicas', 'Personal funcionario de las entidades locales'], r're:sólo se aplicarán directamente cuando así lo disponga su legislación específica al siguiente personal:.*?d\) Personal militar de las Fuerzas Armadas'),
('IV', T, 'a8', 'Según el artículo 8.2, ¿cuál de los siguientes NO es una clase de empleado público?', 'Personal directivo de libre designación',
 ['Funcionarios interinos', 'Personal laboral', 'Personal eventual'],
 r're:Los empleados públicos se clasifican en: a\) Funcionarios de carrera\. b\) Funcionarios interinos\. c\) Personal laboral, ya sea fijo, por tiempo indefinido o temporal\. d\) Personal eventual'),
('IV', T, 'a9', 'El ejercicio de las funciones que impliquen la participación directa o indirecta en el ejercicio de las potestades públicas corresponde:', 'Exclusivamente a los funcionarios públicos',
 ['A los funcionarios y al personal laboral fijo', 'A cualquier empleado público', 'Al personal eventual de confianza'],
 'corresponden exclusivamente a los funcionarios públicos'),
('IV', T, 'a9', 'Los funcionarios de carrera están vinculados a una Administración Pública por:', 'Una relación estatutaria regulada por el Derecho Administrativo para el desempeño de servicios profesionales retribuidos de carácter permanente',
 ['Un contrato de trabajo por tiempo indefinido', 'Un contrato administrativo de servicios', 'Una relación de confianza o asesoramiento especial'],
 'por una relación estatutaria regulada por el Derecho Administrativo para el desempeño de servicios profesionales retribuidos de carácter permanente'),
('IV', P, 'a10', 'Duración máxima del nombramiento de funcionario interino por exceso o acumulación de tareas', '9 meses dentro de un periodo de 18 meses',
 ['6 meses dentro de un periodo de 12 meses', '12 meses dentro de un periodo de 24 meses', '9 meses dentro de un periodo de 12 meses'],
 'El exceso o acumulación de tareas por plazo máximo de nueve meses, dentro de un periodo de dieciocho meses'),
('IV', P, 'a10', 'Duración máxima de los programas de carácter temporal que justifican el nombramiento de funcionarios interinos (ampliable hasta doce meses más por las leyes de Función Pública)', '3 años',
 ['1 año', '2 años', '4 años'], 'La ejecución de programas de carácter temporal, que no podrán tener una duración superior a tres años'),
('IV', P, 'a10', 'Transcurso desde el nombramiento de un funcionario interino en plaza vacante tras el cual, con carácter general, se produce el fin de la relación de interinidad', '3 años',
 ['2 años', '4 años', '5 años'], 'transcurridos tres años desde el nombramiento del personal funcionario interino se producirá el fin de la relación de interinidad'),
('IV', T, 'a10', 'Los procedimientos de selección del personal funcionario interino se rigen por los principios de:', 'Igualdad, mérito, capacidad, publicidad y celeridad',
 ['Igualdad, mérito y capacidad exclusivamente', 'Confianza y libre designación', 'Antigüedad y experiencia previa'],
 'rigiéndose en todo caso por los principios de igualdad, mérito, capacidad, publicidad y celeridad'),
('IV', T, 'a10', 'La finalización de la relación de interinidad por cobertura reglada del puesto por personal funcionario de carrera se produce:', 'Sin derecho a compensación alguna',
 ['Con una indemnización de veinte días por año trabajado', 'Con una indemnización de doce días por año trabajado', 'Con derecho a ser nombrado funcionario de carrera'],
 'además de por las previstas en el artículo 63, sin derecho a compensación alguna'),
('IV', T, 'a11', 'El contrato de trabajo del personal laboral de las Administraciones Públicas debe formalizarse:', 'Por escrito',
 ['Verbalmente o por escrito, indistintamente', 'Mediante nombramiento publicado en el boletín oficial', 'Mediante acta de toma de posesión'],
 'Es personal laboral el que en virtud de contrato de trabajo formalizado por escrito'),
('IV', T, 'a12', 'El personal eventual realiza exclusivamente funciones:', 'Expresamente calificadas como de confianza o asesoramiento especial',
 ['Propias de los funcionarios de carrera, por razones de urgencia', 'Directivas profesionales', 'De ejecución de programas temporales'],
 'sólo realiza funciones expresamente calificadas como de confianza o asesoramiento especial'),
('IV', T, 'a12', 'El cese del personal eventual tendrá lugar, en todo caso:', 'Cuando se produzca el de la autoridad a la que preste la función de confianza o asesoramiento',
 ['A los cuatro años de su nombramiento', 'Al finalizar cada ejercicio presupuestario', 'Cuando lo acuerde la Mesa General de Negociación'],
 'El cese tendrá lugar, en todo caso, cuando se produzca el de la autoridad a la que se preste la función de confianza o asesoramiento'),
('IV', T, 'a12', 'Según el artículo 12.4, la condición de personal eventual:', 'No podrá constituir mérito para el acceso a la Función Pública o para la promoción interna',
 ['Constituye mérito preferente para el acceso a la Función Pública', 'Da derecho a la condición de funcionario tras cuatro años', 'Computa como servicio para la promoción interna'],
 'La condición de personal eventual no podrá constituir mérito para el acceso a la Función Pública o para la promoción interna'),
('IV', T, 'a13', 'La determinación de las condiciones de empleo del personal directivo:', 'No tiene la consideración de materia objeto de negociación colectiva',
 ['Es materia de negociación obligatoria en la Mesa General', 'Se fija en el convenio colectivo único', 'Se negocia en las Mesas Sectoriales'],
 'no tendrá la consideración de materia objeto de negociación colectiva'),
('IV', T, 'a13', 'Cuando el personal directivo profesional reúna la condición de personal laboral, estará sometido a:', 'La relación laboral de carácter especial de alta dirección',
 ['El convenio colectivo del personal laboral', 'El régimen estatutario de los funcionarios de carrera', 'El régimen del personal eventual'],
 'estará sometido a la relación laboral de carácter especial de alta dirección'),
('IV', T, 'a14', '¿Cuál de los siguientes es un derecho individual de los empleados públicos según el artículo 14?', 'A la inamovilidad en la condición de funcionario de carrera',
 ['A la libertad sindical', 'Al ejercicio de la huelga', 'Al planteamiento de conflictos colectivos de trabajo'], 'A la inamovilidad en la condición de funcionario de carrera'),
('IV', T, 'a15', '¿Cuál de los siguientes es un derecho individual que se ejerce de forma colectiva según el artículo 15?', 'Al ejercicio de la huelga, con la garantía del mantenimiento de los servicios esenciales de la comunidad',
 ['A la inamovilidad en la condición de funcionario de carrera', 'A la formación continua', 'A la libertad de expresión'], r're:derechos individuales que se ejercen de forma colectiva: a\).*?c\) Al ejercicio de la huelga, con la garantía del mantenimiento de los servicios esenciales de la comunidad'),
('IV', T, 'a16', '¿En qué consiste la carrera horizontal?', 'En la progresión de grado, categoría, escalón u otros conceptos análogos, sin necesidad de cambiar de puesto de trabajo',
 ['En el ascenso en la estructura de puestos de trabajo por los procedimientos de provisión', 'En el ascenso a un cuerpo o escala de un Subgrupo superior', 'En el acceso a cuerpos o escalas del mismo Subgrupo'],
 'Carrera horizontal, que consiste en la progresión de grado, categoría, escalón u otros conceptos análogos, sin necesidad de cambiar de puesto de trabajo'),
('IV', T, 'a16', '¿Cómo se denomina el ascenso desde un cuerpo o escala de un Subgrupo a otro superior?', 'Promoción interna vertical',
 ['Carrera vertical', 'Carrera horizontal', 'Promoción interna horizontal'],
 'Promoción interna vertical, que consiste en el ascenso desde un cuerpo o escala de un Subgrupo'),
('IV', T, 'a16', '¿Cómo se denomina el acceso a cuerpos o escalas del mismo Subgrupo profesional?', 'Promoción interna horizontal',
 ['Promoción interna vertical', 'Carrera horizontal', 'Movilidad interadministrativa'], 'Promoción interna horizontal, que consiste en el acceso a cuerpos o escalas del mismo Subgrupo profesional'),
('IV', T, 'a16', 'La carrera vertical consiste en:', 'El ascenso en la estructura de puestos de trabajo por los procedimientos de provisión',
 ['La progresión de grado o escalón sin cambiar de puesto', 'El ascenso a un cuerpo de un Subgrupo superior', 'El cambio de Administración Pública'],
 'Carrera vertical, que consiste en el ascenso en la estructura de puestos de trabajo por los procedimientos de provisión'),
('IV', P, 'a18', 'Antigüedad mínima de servicio activo en el Subgrupo inferior exigida para participar en la promoción interna', '2 años',
 ['1 año', '3 años', '5 años'], 'tener una antigüedad de, al menos, dos años de servicio activo en el inferior Subgrupo'),
('IV', T, 'a19', 'La carrera profesional y la promoción del personal laboral se hará efectiva a través de los procedimientos previstos en:', 'El Estatuto de los Trabajadores o en los convenios colectivos',
 ['Las leyes de Función Pública exclusivamente', 'El propio TREBEP exclusivamente', 'Las relaciones de puestos de trabajo'],
 'a través de los procedimientos previstos en el Estatuto de los Trabajadores o en los convenios colectivos'),
('IV', T, 'a20', 'Según el artículo 20.1, la evaluación del desempeño es el procedimiento mediante el cual se mide y valora:', 'La conducta profesional y el rendimiento o el logro de resultados',
 ['Exclusivamente la antigüedad del empleado', 'Los méritos académicos del empleado', 'La adecuación del puesto a la relación de puestos de trabajo'],
 'La evaluación del desempeño es el procedimiento mediante el cual se mide y valora la conducta profesional y el rendimiento o el logro de resultados'),
('IV', T, 'a20', 'La continuidad en un puesto de trabajo obtenido por concurso quedará vinculada a:', 'La evaluación del desempeño, con audiencia al interesado y resolución motivada',
 ['La antigüedad en el puesto', 'La voluntad del superior jerárquico', 'La negociación en la Mesa Sectorial'], 'La continuidad en un puesto de trabajo obtenido por concurso quedará vinculada a la evaluación del desempeño'),
('IV', T, 'a22', 'Las retribuciones de los funcionarios de carrera se clasifican en:', 'Básicas y complementarias',
 ['Fijas y variables', 'Ordinarias y extraordinarias', 'Básicas, complementarias y diferidas'], 'Las retribuciones de los funcionarios de carrera se clasifican en básicas y complementarias'),
('IV', T, 'a22', '¿Cuántas pagas extraordinarias al año perciben los funcionarios de carrera?', 'Dos',
 ['Una', 'Tres', 'Cuatro'], 'Las pagas extraordinarias serán dos al año'),
('IV', T, 'a22', 'Las retribuciones complementarias retribuyen:', 'Las características de los puestos de trabajo, la carrera profesional o el desempeño, rendimiento o resultados alcanzados',
 ['La adscripción del cuerpo a un Subgrupo y la antigüedad', 'Exclusivamente la antigüedad en el servicio', 'Las aportaciones a planes de pensiones'],
 'Las retribuciones complementarias son las que retribuyen las características de los puestos de trabajo'),
('IV', T, 'a23', 'Las retribuciones básicas de los funcionarios están integradas única y exclusivamente por:', 'El sueldo y los trienios',
 ['El sueldo, los trienios y el complemento de destino', 'El sueldo y el complemento específico', 'Los trienios y la productividad'],
 'estarán integradas única y exclusivamente por: a) El sueldo'),
('IV', T, 'a23', 'Los trienios consisten en una cantidad, igual para cada Subgrupo o Grupo, por cada:', 'Tres años de servicio',
 ['Dos años de servicio', 'Cinco años de servicio', 'Seis años de servicio'], 'por cada tres años de servicio'),
('IV', T, 'a23', '¿Dónde se fijan las retribuciones básicas de los funcionarios?', 'En la Ley de Presupuestos Generales del Estado',
 ['En la relación de puestos de trabajo', 'En los convenios colectivos', 'En la ley de Función Pública de cada Comunidad Autónoma'], 'Las retribuciones básicas, que se fijan en la Ley de Presupuestos Generales del Estado'),
('IV', T, 'a24', 'Según el artículo 24, ¿cuál de los siguientes es un factor para fijar las retribuciones complementarias?', 'Los servicios extraordinarios prestados fuera de la jornada normal de trabajo',
 ['La adscripción del cuerpo o escala a un Subgrupo', 'El número de trienios reconocidos', 'La edad del funcionario'], r're:atendiendo, entre otros, a los siguientes factores:.*?d\) Los servicios extraordinarios prestados fuera de la jornada normal de trabajo'),
('IV', T, 'a26', 'Las retribuciones de los funcionarios en prácticas se corresponderán, como mínimo, con:', 'Las del sueldo del Subgrupo o Grupo en que aspiren a ingresar',
 ['El salario mínimo interprofesional', 'Las retribuciones íntegras del puesto que vayan a ocupar', 'Las del Subgrupo inmediatamente inferior'],
 'como mínimo, se corresponderán a las del sueldo del Subgrupo o Grupo'),
('IV', T, 'a29', 'Las cantidades destinadas a financiar aportaciones a planes de pensiones de empleo o contratos de seguro colectivos tendrán la consideración de:', 'Retribución diferida',
 ['Retribución complementaria', 'Indemnización por razón del servicio', 'Acción social'], 'tendrán a todos los efectos la consideración de retribución diferida'),
('IV', T, 'a30', 'La deducción proporcional de haberes por la parte de jornada no realizada:', 'No tiene carácter sancionador',
 ['Tiene carácter de sanción disciplinaria leve', 'Requiere la previa instrucción de un expediente disciplinario', 'Solo procede en caso de huelga'],
 'la parte de jornada no realizada dará lugar a la deducción proporcional de haberes, que no tendrá carácter sancionador'),
('IV', T, 'a31', '¿Quiénes están legitimados para interponer recursos contra las resoluciones de los órganos de selección según el artículo 31.6?', 'Las organizaciones sindicales más representativas en el ámbito de la Función Pública',
 ['Solo los aspirantes que hayan participado en el proceso', 'Las Juntas de Personal exclusivamente', 'El Defensor del Pueblo exclusivamente'],
 'Las organizaciones sindicales más representativas en el ámbito de la Función Pública están legitimadas para la interposición de recursos'),
('IV', T, 'a33', 'Además de las más representativas, están legitimados para estar presentes en las Mesas de Negociación los sindicatos que hayan obtenido, en las elecciones a Delegados y Juntas de Personal de su ámbito:', 'El 10 por 100 o más de los representantes',
 ['El 5 por 100 o más de los representantes', 'El 15 por 100 o más de los representantes', 'El 20 por 100 o más de los representantes'],
 'así como los sindicatos que hayan obtenido el 10 por 100 o más de los representantes'),
('IV', T, 'a35', 'En la composición numérica de las Mesas de Negociación, ninguna de las partes puede superar:', 'Quince miembros',
 ['Diez miembros', 'Veinte miembros', 'Veinticinco miembros'], 'sin que ninguna de las partes pueda superar el número de quince miembros'),
('IV', T, 'a37', '¿Cuál de las siguientes materias está excluida de la obligatoriedad de la negociación según el artículo 37.2?', 'Los poderes de dirección y control propios de la relación jerárquica',
 ['La determinación y aplicación de las retribuciones complementarias de los funcionarios', 'Los criterios generales de acción social', 'Los criterios generales sobre ofertas de empleo público'],
 r're:Quedan excluidas de la obligatoriedad de la negociación, las materias siguientes:.*?d\) Los poderes de dirección y control propios de la relación jerárquica'),
('IV', T, 'a38', 'Salvo acuerdo en contrario, los Pactos y Acuerdos:', 'Se prorrogarán de año en año si no mediara denuncia expresa de una de las partes',
 ['Se extinguen automáticamente al año de su firma', 'Se prorrogan por períodos de tres años', 'Se prorrogan hasta la firma de un nuevo convenio, sin posibilidad de denuncia'],
 'Salvo acuerdo en contrario, los Pactos y Acuerdos se prorrogarán de año en año si no mediara denuncia expresa de una de las partes'),
('IV', T, 'a38', 'Los Acuerdos ratificados que traten sobre materias sometidas a reserva de ley:', 'Carecen de eficacia directa',
 ['Son directamente aplicables al personal', 'Modifican automáticamente la ley', 'Se elevan a reglamento por la Mesa General'], 'su contenido carecerá de eficacia directa'),
('IV', T, 'a39', '¿Cuáles son los órganos específicos de representación de los funcionarios?', 'Los Delegados de Personal y las Juntas de Personal',
 ['Los Comités de Empresa y los Delegados Sindicales', 'Las Mesas de Negociación', 'Las Comisiones Paritarias'], 'Los órganos específicos de representación de los funcionarios son los Delegados de Personal y las Juntas de Personal'),
('IV', T, 'a39', 'Las Juntas de Personal se constituirán en unidades electorales que cuenten con un censo mínimo de:', '50 funcionarios',
 ['30 funcionarios', '6 funcionarios', '100 funcionarios'], 'Las Juntas de Personal se constituirán en unidades electorales que cuenten con un censo mínimo de 50 funcionarios'),
('IV', T, 'a39', 'En las unidades electorales de 31 a 49 funcionarios, ¿cuántos Delegados de Personal se eligen?', 'Tres',
 ['Uno', 'Dos', 'Cinco'], 'Hasta 30 funcionarios se elegirá un Delegado, y de 31 a 49 se elegirán tres'),
('IV', T, 'a39', '¿Cuántos representantes tiene una Junta de Personal en una unidad electoral de 50 a 100 funcionarios?', '5',
 ['3', '7', '9'], 'De 50 a 100 funcionarios: 5'),
('IV', T, 'a41', 'Crédito de horas mensuales de los representantes en unidades electorales de hasta 100 funcionarios:', '15 horas',
 ['10 horas', '20 horas', '30 horas'], 'Hasta 100 funcionarios: 15'),
('IV', P, 'a42', 'Mandato de los miembros de las Juntas de Personal y de los Delegados de Personal', '4 años',
 ['2 años', '3 años', '5 años'], 'será de cuatro años, pudiendo ser reelegidos'),
('IV', T, 'a44', '¿Mediante qué sistema se eligen las Juntas de Personal?', 'Listas cerradas y sistema proporcional corregido',
 ['Listas abiertas y sistema mayoritario', 'Listas abiertas y sistema proporcional', 'Listas cerradas y sistema mayoritario'],
 'Las Juntas de Personal se elegirán mediante listas cerradas a través de un sistema proporcional corregido'),
('IV', T, 'a44', '¿Mediante qué sistema se eligen los Delegados de Personal?', 'Listas abiertas y sistema mayoritario',
 ['Listas cerradas y sistema proporcional corregido', 'Listas cerradas y sistema mayoritario', 'Designación sindical directa'],
 'y los Delegados de Personal mediante listas abiertas y sistema mayoritario'),
('IV', T, 'a46', 'Los empleados públicos pueden convocar una reunión si su número no es inferior al:', '40 por 100 del colectivo convocado',
 ['10 por 100 del colectivo convocado', '25 por 100 del colectivo convocado', '50 por 100 del colectivo convocado'],
 'en número no inferior al 40 por 100 del colectivo convocado'),
('IV', T, 'a4-2', 'Según el artículo 47 bis, la prestación del servicio mediante teletrabajo:', 'Habrá de ser expresamente autorizada, será compatible con la modalidad presencial y tendrá carácter voluntario y reversible, salvo supuestos excepcionales',
 ['Es obligatoria cuando lo decida la Administración', 'Sustituye en todo caso a la modalidad presencial', 'No requiere autorización expresa'],
 'La prestación del servicio mediante teletrabajo habrá de ser expresamente autorizada y será compatible con la modalidad presencial'),
('IV', T, 'a4-2', 'En el teletrabajo, ¿quién proporciona y mantiene los medios tecnológicos necesarios para la actividad?', 'La Administración',
 ['El propio empleado', 'Las organizaciones sindicales', 'El empleado y la Administración a partes iguales'],
 'La Administración proporcionará y mantendrá a las personas que trabajen en esta modalidad, los medios tecnológicos necesarios'),
('IV', P, 'a48', 'Permiso por accidente o enfermedad graves, hospitalización o intervención quirúrgica con reposo domiciliario del cónyuge o de un pariente de primer grado', '5 días hábiles',
 ['3 días hábiles', '4 días hábiles', '2 días hábiles'], 'que requiera el cuidado efectivo de aquella, cinco días hábiles'),
('IV', P, 'a48', 'Permiso por accidente o enfermedad graves, hospitalización o intervención quirúrgica con reposo domiciliario de un familiar dentro del segundo grado', '4 días hábiles',
 ['2 días hábiles', '3 días hábiles', '5 días hábiles'], 'de un familiar dentro del segundo grado de consanguinidad o afinidad, el permiso será de cuatro días hábiles'),
('IV', P, 'a48', 'Permiso por fallecimiento del cónyuge o familiar de primer grado, cuando el suceso se produzca en la misma localidad', '3 días hábiles',
 ['2 días hábiles', '4 días hábiles', '5 días hábiles'], 'tres días hábiles cuando el suceso se produzca en la misma localidad'),
('IV', P, 'a48', 'Permiso por fallecimiento de familiar dentro del segundo grado, cuando se produzca en distinta localidad', '4 días hábiles',
 ['2 días hábiles', '3 días hábiles', '5 días hábiles'], 'el permiso será de dos días hábiles cuando se produzca en la misma localidad y de cuatro días hábiles cuando sea en distinta localidad'),
('IV', P, 'a48', 'Permiso por traslado de domicilio sin cambio de residencia', '1 día',
 ['2 días', '3 días', '4 días'], 'Por traslado de domicilio sin cambio de residencia, un día'),
('IV', P, 'a48', 'Permiso por asuntos particulares, al año', '6 días',
 ['3 días', '5 días', '8 días'], 'Por asuntos particulares, seis días al año'),
('IV', P, 'a48', 'Permiso por matrimonio o registro o constitución formalizada de pareja de hecho', '15 días',
 ['10 días', '20 días', '22 días'], 'de pareja de hecho, quince días'),
('IV', T, 'a48', 'El permiso por lactancia de un hijo menor de doce meses da derecho a:', 'Una hora de ausencia del trabajo, que podrá dividirse en dos fracciones',
 ['Media hora diaria de ausencia', 'Dos horas diarias de ausencia', 'Una reducción del 50 % de la jornada'],
 'tendrán derecho a una hora de ausencia del trabajo que podrá dividir en dos fracciones'),
('IV', T, 'a48', 'En caso de nacimiento de hijos prematuros que deban permanecer hospitalizados, el funcionario tiene derecho a ausentarse del trabajo, con retribuciones íntegras, durante un máximo de:', 'Dos horas diarias',
 ['Una hora diaria', 'Tres horas diarias', 'Media jornada'], 'tendrá derecho a ausentarse del trabajo durante un máximo de dos horas diarias percibiendo las retribuciones íntegras'),
('IV', T, 'a48', 'Para atender el cuidado de un familiar de primer grado por enfermedad muy grave, el funcionario puede solicitar una reducción retribuida de la jornada de hasta el cincuenta por ciento durante un plazo máximo de:', 'Un mes',
 ['Quince días', 'Dos meses', 'Tres meses'], 'por razones de enfermedad muy grave y por el plazo máximo de un mes'),
('IV', T, 'a48', 'La reducción de jornada por guarda legal del artículo 48.h) procede, entre otros supuestos, cuando el funcionario tenga el cuidado directo de algún menor de:', 'Doce años',
 ['Ocho años', 'Diez años', 'Catorce años'], 'cuando el funcionario tenga el cuidado directo de algún menor de doce años'),
('IV', P, 'a49', 'Duración del permiso por nacimiento para la madre biológica (caso general, sin monoparentalidad)', '19 semanas',
 ['16 semanas', '17 semanas', '20 semanas'], 'Permiso por nacimiento para la madre biológica: tendrá una duración de diecinueve semanas'),
('IV', P, 'a49', 'Duración del permiso por nacimiento para la madre biológica en el supuesto de monoparentalidad', '32 semanas',
 ['26 semanas', '28 semanas', '38 semanas'], 'Permiso por nacimiento para la madre biológica: tendrá una duración de diecinueve semanas. En el supuesto de monoparentalidad, por existir una única persona progenitora, el permiso será de treinta y dos semanas'),
('IV', P, 'a49', 'Semanas obligatorias e ininterrumpidas, inmediatamente posteriores al parto, del permiso por nacimiento para la madre biológica', '6 semanas',
 ['4 semanas', '8 semanas', '10 semanas'], 'Seis semanas ininterrumpidas inmediatamente posteriores al parto, serán obligatorias'),
('IV', P, 'a49', 'Duración máxima del permiso parental (no retribuido) para el cuidado de hijo hasta que cumpla ocho años', '8 semanas',
 ['4 semanas', '6 semanas', '12 semanas'], 'tendrá una duración no superior a ocho semanas'),
('IV', T, 'a49', 'La funcionaria víctima de violencia de género o sexual que reduzca su jornada mantendrá sus retribuciones íntegras cuando la reducción sea de:', 'Un tercio o menos',
 ['La mitad o menos', 'Un cuarto o menos', 'Cualquier duración'], 'mantendrá sus retribuciones íntegras cuando reduzca su jornada en un tercio o menos'),
('IV', T, 'a49', 'En el permiso por cuidado de hijo menor afectado por cáncer u otra enfermedad grave, la reducción de jornada debe ser de, al menos:', 'La mitad de la duración de la jornada',
 ['Un tercio de la jornada', 'Un cuarto de la jornada', 'Dos horas diarias'], 'a una reducción de la jornada de trabajo de al menos la mitad de la duración de aquélla'),
('IV', T, 'a50', 'Los funcionarios tienen derecho a disfrutar, durante cada año natural, de unas vacaciones retribuidas de:', 'Veintidós días hábiles',
 ['Treinta días naturales', 'Veinte días hábiles', 'Veinticinco días hábiles'], 'de unas vacaciones retribuidas de veintidós días hábiles'),
('IV', T, 'a50', 'A efectos del cómputo de las vacaciones de los funcionarios:', 'No se consideran días hábiles los sábados, sin perjuicio de las adaptaciones para horarios especiales',
 ['Los sábados se consideran días hábiles', 'Se computan días naturales', 'Los domingos se consideran días hábiles'], 'no se considerarán como días hábiles los sábados'),
('IV', T, 'a50', 'El período de vacaciones anuales retribuidas de los funcionarios públicos:', 'No puede ser sustituido por una cuantía económica, salvo en los casos de conclusión de la relación de servicios por causas ajenas a su voluntad',
 ['Puede sustituirse por una compensación económica a petición del funcionario', 'Puede acumularse indefinidamente a años posteriores', 'Puede sustituirse por días de asuntos particulares'],
 'El período de vacaciones anuales retribuidas de los funcionarios públicos no puede ser sustituido por una cuantía económica'),
('IV', P, 'a50', 'Límite, desde el final del año en que se originen, para disfrutar las vacaciones que no pudieron disfrutarse por incapacidad temporal, maternidad o riesgo durante el embarazo o la lactancia', '18 meses',
 ['6 meses', '12 meses', '24 meses'], 'siempre que no hayan transcurrido más de dieciocho meses a partir del final del año en que se hayan originado'),
('IV', T, 'a52', 'Los principios y reglas del Código de Conducta de los empleados públicos:', 'Informarán la interpretación y aplicación del régimen disciplinario',
 ['Carecen de efectos jurídicos', 'Sustituyen al régimen disciplinario', 'Solo se aplican al personal directivo'],
 'Los principios y reglas establecidos en este capítulo informarán la interpretación y aplicación del régimen disciplinario'),
('IV', T, 'a54', 'Según los principios de conducta, los empleados públicos obedecerán las instrucciones y órdenes profesionales de los superiores, salvo que:', 'Constituyan una infracción manifiesta del ordenamiento jurídico, en cuyo caso lo pondrán en conocimiento de los órganos de inspección',
 ['No estén de acuerdo con ellas', 'No se den por escrito', 'Afecten a su horario de trabajo'], 'salvo que constituyan una infracción manifiesta del ordenamiento jurídico'),
('IV', T, 'a54', 'Según el artículo 54.6, los empleados públicos rechazarán cualquier regalo, favor o servicio en condiciones ventajosas que:', 'Vaya más allá de los usos habituales, sociales y de cortesía',
 ['Supere los 50 euros', 'Proceda de otra Administración', 'No se haya declarado previamente'], 'que vaya más allá de los usos habituales, sociales y de cortesía'),
('IV', T, 'a55', '¿Cuál de los siguientes NO es un principio de los procedimientos de selección del artículo 55.2?', 'Preferencia de los aspirantes con experiencia en la Administración',
 ['Publicidad de las convocatorias y de sus bases', 'Imparcialidad y profesionalidad de los miembros de los órganos de selección', 'Agilidad, sin perjuicio de la objetividad, en los procesos de selección'],
 r're:así como los establecidos a continuación: a\) Publicidad de las convocatorias y de sus bases.*?f\) Agilidad, sin perjuicio de la objetividad, en los procesos de selección'),
('IV', T, 'a56', 'Edad mínima para participar en los procesos selectivos de acceso al empleo público:', 'Dieciséis años cumplidos',
 ['Dieciocho años cumplidos', 'Diecisiete años cumplidos', 'Veintiún años cumplidos'], 'Tener cumplidos dieciséis años'),
('IV', T, 'a56', 'Una edad máxima de acceso al empleo público distinta de la edad de jubilación forzosa solo puede establecerse:', 'Por ley',
 ['Por la convocatoria de cada proceso selectivo', 'Por real decreto', 'Por orden ministerial'], 'Sólo por ley podrá establecerse otra edad máxima'),
('IV', T, 'a57', 'Los nacionales de los Estados miembros de la Unión Europea pueden acceder como personal funcionario a los empleos públicos en igualdad de condiciones que los españoles, con excepción de:',
 'Aquellos que impliquen una participación en el ejercicio del poder público o en la salvaguardia de los intereses del Estado o de las Administraciones Públicas',
 ['Ninguno', 'Todos los del Grupo A', 'Todos los de la Administración General del Estado'],
 'con excepción de aquellos que directa o indirectamente impliquen una participación en el ejercicio del poder público'),
('IV', T, 'a57', 'Los extranjeros con residencia legal en España pueden acceder a las Administraciones Públicas:', 'Como personal laboral, en igualdad de condiciones que los españoles',
 ['Como personal funcionario, en igualdad de condiciones que los españoles', 'Solo como personal eventual', 'En ningún caso'],
 'así como los extranjeros con residencia legal en España podrán acceder a las Administraciones Públicas, como personal laboral, en igualdad de condiciones que los españoles'),
('IV', T, 'a57', 'La exención del requisito de nacionalidad para el acceso a la condición de funcionario por razones de interés general solo puede establecerse por:', 'Ley de las Cortes Generales o de las asambleas legislativas de las comunidades autónomas',
 ['Real decreto del Consejo de Ministros', 'La convocatoria del proceso selectivo', 'Acuerdo de la Mesa General de Negociación'],
 'Sólo por ley de las Cortes Generales o de las asambleas legislativas de las comunidades autónomas podrá eximirse del requisito de la nacionalidad'),
('IV', T, 'a59', 'En las ofertas de empleo público se reservará para personas con discapacidad un cupo no inferior al:', 'Siete por ciento de las vacantes',
 ['Cinco por ciento de las vacantes', 'Dos por ciento de las vacantes', 'Diez por ciento de las vacantes'], 'se reservará un cupo no inferior al siete por ciento de las vacantes'),
('IV', T, 'a59', 'De la reserva para personas con discapacidad, ¿qué porcentaje mínimo de las plazas ofertadas se destina a personas que acrediten discapacidad intelectual?', 'El dos por ciento',
 ['El uno por ciento', 'El tres por ciento', 'El cinco por ciento'], 'al menos, el dos por ciento de las plazas ofertadas lo sea para ser cubiertas por personas que acrediten discapacidad intelectual'),
('IV', T, 'a60', '¿Quiénes NO pueden formar parte de los órganos de selección?', 'El personal de elección o de designación política, los funcionarios interinos y el personal eventual',
 ['Los funcionarios de carrera de otras Administraciones', 'El personal laboral fijo', 'Los funcionarios de carrera del Subgrupo A1'],
 'El personal de elección o de designación política, los funcionarios interinos y el personal eventual no podrán formar parte de los órganos de selección'),
('IV', T, 'a60', 'La pertenencia a los órganos de selección será siempre:', 'A título individual, sin que pueda ostentarse en representación o por cuenta de nadie',
 ['En representación de las organizaciones sindicales', 'En representación de la Administración convocante', 'A propuesta de las Juntas de Personal'],
 'La pertenencia a los órganos de selección será siempre a título individual'),
('IV', T, 'a61', '¿Cuáles son los sistemas selectivos de los funcionarios de carrera?', 'La oposición y el concurso-oposición; el concurso solo con carácter excepcional y en virtud de ley',
 ['La oposición, el concurso-oposición y el concurso, indistintamente', 'El concurso y la libre designación', 'La oposición exclusivamente'],
 'Los sistemas selectivos de funcionarios de carrera serán los de oposición y concurso-oposición'),
('IV', T, 'a61', 'En los procesos selectivos que incluyan valoración de méritos, dicha valoración:', 'Tendrá una puntuación proporcionada que no determinará, en ningún caso, por sí misma el resultado del proceso selectivo',
 ['Determinará por sí sola el resultado del proceso', 'Tendrá siempre el mismo peso que las pruebas de capacidad', 'Solo podrá computar la antigüedad'],
 'que no determinará, en ningún caso, por sí misma el resultado del proceso selectivo'),
('IV', T, 'a61', '¿Pueden los órganos de selección proponer el acceso a la condición de funcionario de un número de aprobados superior al de plazas convocadas?', 'No, excepto cuando así lo prevea la propia convocatoria',
 ['Sí, en todo caso', 'Sí, hasta un diez por ciento más', 'Sí, si hay empate en la puntuación'],
 'no podrán proponer el acceso a la condición de funcionario de un número superior de aprobados al de plazas convocadas, excepto cuando así lo prevea la propia convocatoria'),
('IV', T, 'a61', '¿Cuáles son los sistemas selectivos del personal laboral fijo?', 'La oposición, el concurso-oposición o el concurso de valoración de méritos',
 ['Solo la oposición', 'Solo el concurso de méritos', 'La libre designación'],
 'Los sistemas selectivos de personal laboral fijo serán los de oposición, concurso-oposición'),
('IV', T, 'a62', '¿Cuál de los siguientes NO es uno de los requisitos sucesivos para adquirir la condición de funcionario de carrera (artículo 62)?', 'La superación de un período de evaluación del desempeño de un año',
 ['La superación del proceso selectivo', 'El acto de acatamiento de la Constitución', 'La toma de posesión dentro del plazo que se establezca'],
 r're:La condición de funcionario de carrera se adquiere por el cumplimiento sucesivo de los siguientes requisitos: a\).*?d\) Toma de posesión dentro del plazo que se establezca'),
('IV', T, 'a63', '¿Cuál de las siguientes NO es causa de pérdida de la condición de funcionario de carrera según el artículo 63?', 'La sanción de suspensión firme de funciones',
 ['La renuncia a la condición de funcionario', 'La jubilación total del funcionario', 'La pena de inhabilitación absoluta o especial para cargo público que tuviere carácter firme'],
 r're:Son causas de pérdida de la condición de funcionario de carrera: a\).*?e\) La pena principal o accesoria de inhabilitación absoluta o especial para cargo público que tuviere carácter firme'),
('IV', T, 'a64', 'No podrá ser aceptada la renuncia a la condición de funcionario cuando:', 'Esté sujeto a expediente disciplinario o se haya dictado contra él auto de procesamiento o de apertura de juicio oral por algún delito',
 ['Tenga menos de cinco años de servicios', 'Esté en situación de excedencia', 'No la haya comunicado con un mes de antelación'],
 'No podrá ser aceptada la renuncia cuando el funcionario esté sujeto a expediente disciplinario'),
('IV', T, 'a64', 'La renuncia a la condición de funcionario:', 'No inhabilita para ingresar de nuevo en la Administración a través del procedimiento de selección establecido',
 ['Inhabilita para volver a ingresar en la Administración', 'Inhabilita durante cinco años', 'Solo permite reingresar como personal laboral'],
 'La renuncia a la condición de funcionario no inhabilita para ingresar de nuevo en la Administración Pública'),
('IV', T, 'a66', 'La pena de inhabilitación especial firme produce la pérdida de la condición de funcionario respecto de:', 'Los empleos o cargos especificados en la sentencia',
 ['Todos los empleos o cargos que tuviere', 'Ningún empleo, solo suspende sus funciones', 'Los empleos de la misma Administración'],
 'produce la pérdida de la condición de funcionario respecto de aquellos empleos o cargos especificados en la sentencia'),
('IV', T, 'a67', 'Con carácter general, la jubilación forzosa se declarará de oficio al cumplir el funcionario:', 'Sesenta y cinco años',
 ['Sesenta y siete años', 'Setenta años', 'Sesenta años'], 'La jubilación forzosa se declarará de oficio al cumplir el funcionario los sesenta y cinco años de edad'),
('IV', T, 'a67', 'La prolongación de la permanencia en el servicio activo puede solicitarse, como máximo, hasta que se cumplan:', 'Setenta años',
 ['Sesenta y siete años', 'Sesenta y ocho años', 'Setenta y dos años'], 'como máximo hasta que se cumpla setenta años de edad'),
('IV', T, 'a68', 'En caso de extinción de la relación de servicios por pérdida de la nacionalidad o jubilación por incapacidad permanente, desaparecida la causa, la rehabilitación solicitada:', 'Le será concedida',
 ['Podrá concederse con carácter excepcional', 'Requiere superar un nuevo proceso selectivo', 'Requiere informe favorable del Consejo de Estado'],
 'podrá solicitar la rehabilitación de su condición de funcionario, que le será concedida'),
('IV', T, 'a70', 'La Oferta de empleo público comporta la obligación de convocar los procesos selectivos para las plazas comprometidas y hasta un:', 'Diez por cien adicional',
 ['Cinco por cien adicional', 'Quince por cien adicional', 'Veinte por cien adicional'], 'para las plazas comprometidas y hasta un diez por cien adicional'),
('IV', P, 'a70', 'Plazo improrrogable para la ejecución de la oferta de empleo público', '3 años',
 ['1 año', '2 años', '4 años'], 'deberá desarrollarse dentro del plazo improrrogable de tres años'),
('IV', T, 'a70', 'La Oferta de empleo público se aprobará:', 'Anualmente por los órganos de Gobierno de las Administraciones Públicas, y se publicará en el Diario oficial correspondiente',
 ['Cada tres años por las Cortes Generales', 'Anualmente por la Mesa General de Negociación', 'Cada dos años por el Ministerio competente, sin publicación'], 'que se aprobará anualmente por los órganos de Gobierno de las Administraciones Públicas'),
('IV', T, 'a74', '¿Qué deben comprender, al menos, las relaciones de puestos de trabajo?', 'La denominación de los puestos, los grupos de clasificación, los cuerpos o escalas, los sistemas de provisión y las retribuciones complementarias',
 ['Únicamente la denominación de los puestos y su titular', 'Las retribuciones básicas y los trienios de cada titular', 'El nombre de los funcionarios que ocupan cada puesto'],
 'comprenderán, al menos, la denominación de los puestos, los grupos de clasificación profesional'),
('IV', T, 'a75', 'Los cuerpos y escalas de funcionarios se crean, modifican y suprimen por:', 'Ley de las Cortes Generales o de las asambleas legislativas de las comunidades autónomas',
 ['Real decreto', 'Orden ministerial', 'Acuerdo de la Mesa General de Negociación'],
 'Los cuerpos y escalas de funcionarios se crean, modifican y suprimen por ley de las Cortes Generales o de las asambleas legislativas de las comunidades autónomas'),
('IV', T, 'a76', '¿Qué titulación se exige para el acceso a los cuerpos o escalas del Subgrupo C1?', 'Título de Bachiller o Técnico',
 ['Título de Graduado en Educación Secundaria Obligatoria', 'Título de Técnico Superior', 'Título universitario de Grado'], 'C1: Título de Bachiller o Técnico'),
('IV', T, 'a76', '¿Qué titulación se exige para el acceso a los cuerpos o escalas del Grupo B?', 'Título de Técnico Superior',
 ['Título de Bachiller o Técnico', 'Título universitario de Grado', 'Título de Graduado en Educación Secundaria Obligatoria'], 'se exigirá estar en posesión del título de Técnico Superior'),
('IV', T, 'a78', 'Según el artículo 78.2, la provisión de puestos de trabajo se llevará a cabo por los procedimientos de:', 'Concurso y libre designación con convocatoria pública',
 ['Oposición y concurso-oposición', 'Concurso y comisión de servicios', 'Libre designación y redistribución de efectivos'],
 'se llevará a cabo por los procedimientos de concurso y de libre designación con convocatoria pública'),
('IV', T, 'a79', '¿Cuál es el procedimiento normal de provisión de puestos de trabajo?', 'El concurso',
 ['La libre designación', 'La comisión de servicios', 'La redistribución de efectivos'], 'El concurso, como procedimiento normal de provisión de puestos de trabajo'),
('IV', T, 'a80', 'La libre designación con convocatoria pública consiste en:', 'La apreciación discrecional por el órgano competente de la idoneidad de los candidatos en relación con los requisitos del puesto',
 ['La valoración de méritos por órganos colegiados de carácter técnico', 'La adjudicación del puesto por antigüedad', 'El sorteo entre los candidatos que reúnan los requisitos'],
 'consiste en la apreciación discrecional por el órgano competente de la idoneidad de los candidatos'),
('IV', T, 'a80', 'Los titulares de puestos provistos por libre designación con convocatoria pública:', 'Podrán ser cesados discrecionalmente, debiendo asignárseles otro puesto conforme al sistema de carrera',
 ['Solo pueden ser cesados previo expediente disciplinario', 'Son inamovibles en el puesto durante dos años', 'Quedan en excedencia forzosa al ser cesados'],
 'podrán ser cesados discrecionalmente'),
('IV', T, 'a82', 'El traslado de la funcionaria víctima de violencia de género o sexual a otro puesto de análogas características:', 'Tendrá la consideración de traslado forzoso, sin necesidad de que sea vacante de necesaria cobertura',
 ['Tendrá la consideración de traslado voluntario', 'Solo procede a vacantes de necesaria cobertura', 'Requiere concurso de méritos'],
 'sin necesidad de que sea vacante de necesaria cobertura'),
('IV', T, 'a85', '¿Cuál de las siguientes NO es una situación administrativa de los funcionarios de carrera del artículo 85.1?', 'Reserva de puesto',
 ['Servicios especiales', 'Servicio en otras Administraciones Públicas', 'Suspensión de funciones'],
 r're:Los funcionarios de carrera se hallarán en alguna de las siguientes situaciones: a\) Servicio activo\. b\) Servicios especiales\. c\) Servicio en otras Administraciones Públicas\. d\) Excedencia\. e\) Suspensión de funciones'),
('IV', T, 'a87', 'Un funcionario de carrera que sea nombrado alto cargo de la Administración será declarado en situación de:', 'Servicios especiales',
 ['Servicio activo', 'Excedencia voluntaria por interés particular', 'Servicio en otras Administraciones Públicas'],
 'Cuando sean designados miembros del Gobierno o de los órganos de gobierno de las comunidades autónomas'),
('IV', T, 'a87', 'Para pasar a servicios especiales por misión en organismos internacionales, gobiernos o entidades públicas extranjeras, la misión debe tener un período determinado superior a:', 'Seis meses',
 ['Tres meses', 'Un año', 'Dos años'], 'Cuando sean autorizados para realizar una misión por periodo determinado superior a seis meses'),
('IV', T, 'a87', 'Los funcionarios en situación de servicios especiales perciben:', 'Las retribuciones del puesto o cargo que desempeñen, sin perjuicio del derecho a percibir los trienios reconocidos',
 ['Las retribuciones de su puesto de funcionario de carrera', 'Ambas retribuciones acumuladas', 'Ninguna retribución'],
 'percibirán las retribuciones del puesto o cargo que desempeñen y no las que les correspondan como funcionarios de carrera'),
('IV', P, 'a89', 'Servicios efectivos mínimos inmediatamente anteriores exigidos, con carácter general, para obtener la excedencia voluntaria por interés particular', '5 años',
 ['1 año', '2 años', '3 años'], 'durante un periodo mínimo de cinco años inmediatamente anteriores'),
('IV', T, 'a89', 'La excedencia voluntaria por interés particular no podrá declararse cuando:', 'Al funcionario se le instruya expediente disciplinario',
 ['El funcionario tenga hijos menores', 'El funcionario esté en su primer año de servicio', 'Lo deniegue la Junta de Personal'], 'No podrá declararse cuando al funcionario público se le instruya expediente disciplinario'),
('IV', T, 'a89', 'Durante la excedencia voluntaria por interés particular, el funcionario:', 'No devenga retribuciones ni se le computa el tiempo a efectos de ascensos, trienios y derechos de Seguridad Social',
 ['Percibe las retribuciones básicas', 'Tiene reserva del puesto durante dos años', 'Computa el tiempo a efectos de trienios'],
 'Quienes se encuentren en situación de excedencia por interés particular no devengarán retribuciones'),
('IV', T, 'a89', 'La excedencia voluntaria por agrupación familiar:', 'Puede concederse sin el requisito de haber prestado un período mínimo de servicios efectivos',
 ['Exige cinco años de servicios previos', 'Da derecho a reserva del puesto durante dos años', 'Computa a efectos de trienios'],
 'Podrá concederse la excedencia voluntaria por agrupación familiar sin el requisito de haber prestado servicios efectivos'),
('IV', P, 'a89', 'Duración máxima de la excedencia para atender al cuidado de cada hijo', '3 años',
 ['1 año', '2 años', '4 años'], 'tendrán derecho a un período de excedencia de duración no superior a tres años para atender al cuidado de cada hijo'),
('IV', P, 'a89', 'Reserva del puesto de trabajo desempeñado durante la excedencia por cuidado de familiares (como mínimo)', '2 años',
 ['6 meses', '1 año', '3 años'], 'El puesto de trabajo desempeñado se reservará, al menos, durante dos años'),
('IV', T, 'a89', 'El tiempo de permanencia en la excedencia por cuidado de familiares:', 'Es computable a efectos de trienios, carrera y derechos en el régimen de Seguridad Social',
 ['No es computable a ningún efecto', 'Solo es computable a efectos de Seguridad Social', 'Solo es computable si dura menos de un año'],
 'El tiempo de permanencia en esta situación será computable a efectos de trienios, carrera y derechos en el régimen de Seguridad Social'),
('IV', P, 'a89', 'Reserva del puesto de trabajo durante la excedencia por razón de violencia de género o sexual (período inicial, prorrogable)', '6 primeros meses',
 ['2 primeros meses', '3 primeros meses', '12 primeros meses'], 'Durante los seis primeros meses tendrán derecho a la reserva del puesto de trabajo'),
('IV', P, 'a89', 'Percepción de retribuciones íntegras al inicio de la excedencia por razón de violencia de género o sexual', '2 primeros meses',
 ['1 primer mes', '3 primeros meses', '6 primeros meses'], 'Durante los dos primeros meses de esta excedencia la funcionaria tendrá derecho a percibir las retribuciones íntegras'),
('IV', T, 'a90', 'La suspensión de funciones determina la pérdida del puesto de trabajo cuando exceda de:', 'Seis meses',
 ['Tres meses', 'Un año', 'Dos años'], 'La suspensión determinará la pérdida del puesto de trabajo cuando exceda de seis meses'),
('IV', P, 'a90', 'Duración máxima de la suspensión firme por sanción disciplinaria', '6 años',
 ['3 años', '4 años', '5 años'], 'La suspensión firme por sanción disciplinaria no podrá exceder de seis años'),
('IV', T, 'a93', 'Los funcionarios o el personal laboral que indujeren a otros a la realización de actos constitutivos de falta disciplinaria:', 'Incurrirán en la misma responsabilidad que éstos',
 ['No incurren en responsabilidad alguna', 'Incurren en una falta leve en todo caso', 'Solo responden si la falta es muy grave'], 'incurrirán en la misma responsabilidad que éstos'),
('IV', T, 'a94', 'Cuando de la instrucción de un procedimiento disciplinario resulten indicios fundados de criminalidad:', 'Se suspenderá su tramitación poniéndolo en conocimiento del Ministerio Fiscal',
 ['Se continuará el procedimiento hasta su resolución', 'Se archivará el procedimiento definitivamente', 'Se impondrá la sanción de separación del servicio'],
 'se suspenderá su tramitación poniéndolo en conocimiento del Ministerio Fiscal'),
('IV', T, 'a95', '¿Cuál de las siguientes es una falta muy grave según el artículo 95.2?', 'El abandono del servicio',
 ['La incorrección con los compañeros', 'El retraso injustificado en el horario', 'El descuido en el ejercicio de las funciones'], r're:Son faltas muy graves: a\).*?c\) El abandono del servicio'),
('IV', T, 'a95', 'Las faltas graves serán establecidas por:', 'Ley de las Cortes Generales o de la asamblea legislativa autonómica, o por los convenios colectivos para el personal laboral',
 ['El propio TREBEP, en una lista cerrada', 'Reglamento de cada Ministerio', 'La Mesa General de Negociación'],
 'Las faltas graves serán establecidas por ley de las Cortes Generales o de la asamblea legislativa de la correspondiente comunidad autónoma'),
('IV', T, 'a96', 'La sanción de separación del servicio de los funcionarios:', 'Sólo podrá sancionar la comisión de faltas muy graves',
 ['Puede imponerse por faltas graves o muy graves', 'Puede imponerse por cualquier falta', 'Solo puede imponerse a funcionarios interinos'], 'y que sólo podrá sancionar la comisión de faltas muy graves'),
('IV', T, 'a96', '¿En qué consiste la sanción de demérito?', 'En la penalización a efectos de carrera, promoción o movilidad voluntaria',
 ['En la pérdida de un trienio', 'En la suspensión de empleo y sueldo', 'En el traslado a otra localidad'], 'Demérito, que consistirá en la penalización a efectos de carrera, promoción o movilidad voluntaria'),
('IV', P, 'a97', 'Prescripción de las faltas muy graves (TREBEP)', '3 años',
 ['2 años', '4 años', '6 años'], 'Las infracciones muy graves prescribirán a los tres años'),
('IV', P, 'a97', 'Prescripción de las faltas leves (TREBEP)', '6 meses',
 ['1 mes', '3 meses', '9 meses'], 'las graves a los dos años y las leves a los seis meses'),
('IV', P, 'a97', 'Prescripción de las sanciones impuestas por faltas leves (TREBEP)', '1 año',
 ['2 años', '3 años', '4 años'], 'las impuestas por faltas leves al año'),
('IV', T, 'a97', 'El plazo de prescripción de las sanciones disciplinarias comenzará a contarse:', 'Desde la firmeza de la resolución sancionadora',
 ['Desde la comisión de la falta', 'Desde la incoación del expediente', 'Desde la notificación de la propuesta de resolución'], 'El de las sanciones, desde la firmeza de la resolución sancionadora'),
('IV', T, 'a98', 'La imposición de sanciones por faltas leves se llevará a cabo:', 'Por procedimiento sumario con audiencia al interesado',
 ['Sin procedimiento alguno', 'Por el procedimiento ordinario con instructor y secretario', 'Por resolución del Ministerio Fiscal'],
 'La imposición de sanciones por faltas leves se llevará a cabo por procedimiento sumario con audiencia al interesado'),
('IV', T, 'a98', 'La suspensión provisional como medida cautelar en un expediente disciplinario no podrá exceder, salvo paralización imputable al interesado, de:', '6 meses',
 ['3 meses', '1 año', '2 años'], 'no podrá exceder de 6 meses, salvo en caso de paralización del procedimiento imputable al interesado'),
('IV', T, 'a98', 'Durante la suspensión provisional, el funcionario suspenso tiene derecho a percibir:', 'Las retribuciones básicas y, en su caso, las prestaciones familiares por hijo a cargo',
 ['Las retribuciones íntegras', 'Ninguna retribución', 'Solo los trienios'], 'tendrá derecho a percibir durante la suspensión las retribuciones básicas'),
]
