# Lote 19 · LO 4/1981, de los estados de alarma, excepción y sitio · bloque I (tema I.1: garantía y suspensión
# de los derechos fundamentales).
NORMA, LOTE, INICIO = 'LOAES', 'lote-019', 19001
T, P = 'test', 'plazo'
PREGUNTAS = [
('I', T, 'aprimero', 'Procede la declaración de los estados de alarma, excepción o sitio cuando:', 'Circunstancias extraordinarias hagan imposible el mantenimiento de la normalidad mediante los poderes ordinarios de las autoridades competentes',
 ['Lo solicite la mayoría absoluta del Congreso', 'Se produzca cualquier alteración del orden público', 'Lo acuerde el Consejo de Seguridad Nacional'],
 'cuando circunstancias extraordinarias hiciesen imposible el mantenimiento de la normalidad mediante los poderes ordinarios'),
('I', T, 'aprimero', 'La declaración de los estados de alarma, excepción y sitio:', 'No interrumpe el normal funcionamiento de los poderes constitucionales del Estado',
 ['Suspende la actividad de las Cortes Generales', 'Suspende la actividad del Tribunal Constitucional', 'Disuelve automáticamente el Congreso'],
 'no interrumpe el normal funcionamiento de los poderes constitucionales del Estado'),
('I', T, 'asegundo', 'La declaración de los estados de alarma, excepción o sitio entra en vigor:', 'Desde el instante mismo de su publicación en el «Boletín Oficial del Estado»',
 ['A los veinte días de su publicación', 'Al día siguiente de su publicación', 'Desde su comunicación al Congreso'],
 'y entrará en vigor desde el instante mismo de su publicación en aquél'),
('I', T, 'atercero', 'Los actos y disposiciones de la Administración adoptados durante la vigencia de los estados de alarma, excepción y sitio:', 'Son impugnables en vía jurisdiccional de conformidad con las leyes',
 ['No son impugnables', 'Solo son impugnables ante el Tribunal Constitucional', 'Solo son impugnables una vez finalizado el estado'],
 'serán impugnables en vía jurisdiccional de conformidad con lo dispuesto en las leyes'),
('I', T, 'acuao', '¿Cuál de las siguientes NO es una de las alteraciones graves de la normalidad que permiten declarar el estado de alarma según el artículo cuarto?', 'Una insurrección contra la integridad territorial de España',
 ['Crisis sanitarias, como epidemias', 'Catástrofes como terremotos o inundaciones', 'Situaciones de desabastecimiento de productos de primera necesidad'],
 r're:cuando se produzca alguna de las siguientes alteraciones graves de la normalidad\. a\).*?d\) Situaciones de desabastecimiento de productos de primera necesidad'),
('I', T, 'aquinto', 'Cuando los supuestos del estado de alarma afecten exclusivamente al territorio de una Comunidad Autónoma, puede solicitar al Gobierno su declaración:', 'El Presidente de la Comunidad Autónoma',
 ['El Parlamento autonómico', 'El Delegado del Gobierno', 'Cualquier alcalde afectado'], 'el Presidente de la misma, podrá solicitar del Gobierno la declaración de estado de alarma'),
('I', T, 'asexto', 'La declaración del estado de alarma se lleva a cabo mediante:', 'Decreto acordado en Consejo de Ministros',
 ['Ley orgánica', 'Resolución del Congreso de los Diputados', 'Real Decreto del Presidente del Gobierno'], 'La declaración del estado de alarma se llevará a cabo mediante decreto acordado en Consejo de Ministros'),
('I', P, 'asexto', 'Duración máxima del estado de alarma fijada en el decreto de declaración (prorrogable solo con autorización expresa del Congreso)', '15 días',
 ['30 días', '60 días', '10 días'], 'que no podrá exceder de quince días'),
('I', T, 'asexto', 'La prórroga del estado de alarma requiere:', 'Autorización expresa del Congreso de los Diputados',
 ['Acuerdo del Consejo de Ministros', 'Autorización del Senado', 'Dictamen del Consejo de Estado'], 'Sólo se podrá prorrogar con autorización expresa del Congreso de los Diputados'),
('I', T, 'aseptimo', 'A los efectos del estado de alarma, la Autoridad competente es:', 'El Gobierno o, por delegación, el Presidente de la Comunidad Autónoma cuando afecte solo a su territorio',
 ['El Ministro del Interior en todo caso', 'El Jefe del Estado Mayor de la Defensa', 'El Congreso de los Diputados'],
 'A los efectos del estado de alarma la Autoridad competente será el Gobierno'),
('I', T, 'aoctavo', 'De la declaración del estado de alarma el Gobierno da cuenta a:', 'El Congreso de los Diputados',
 ['El Senado', 'El Rey', 'El Tribunal Constitucional'], 'El Gobierno dará cuenta al Congreso de los Diputados de la declaración del estado de alarma'),
('I', T, 'aonce', 'Durante el estado de alarma, la intervención y ocupación transitoria de industrias, fábricas o locales puede acordarse:', 'Con excepción de domicilios privados',
 ['Incluidos los domicilios privados', 'Solo con autorización judicial', 'Solo respecto de bienes públicos'], 'con excepción de domicilios privados'),
('I', T, 'aonce', '¿Cuál de las siguientes medidas puede acordar el decreto de declaración del estado de alarma?', 'Limitar la circulación o permanencia de personas o vehículos en horas y lugares determinados',
 ['Suspender el derecho de reunión', 'Suspender la libertad de expresión', 'Detener personas durante diez días'],
 'a) Limitar la circulación o permanencia de personas o vehículos en horas y lugares determinados'),
('I', T, 'atrece', 'Para declarar el estado de excepción, el Gobierno debe:', 'Solicitar previamente autorización del Congreso de los Diputados',
 ['Dar cuenta al Congreso en el plazo de quince días', 'Obtener autorización del Senado', 'Obtener la propuesta del Rey'],
 'podrá solicitar del Congreso de los Diputados autorización para declarar el estado de excepción'),
'RETIRADA: duplicada del lote 3',
('I', T, 'atrece', 'Los derechos cuya suspensión se solicite en el estado de excepción no pueden ser otros que los enumerados en:', 'El artículo 55.1 de la Constitución',
 ['El artículo 53.2 de la Constitución', 'El artículo 116.2 de la Constitución', 'El Título I completo de la Constitución'],
 'que no podrán ser otros que los enumerados en el apartado uno del artículo cincuenta y cinco de la Constitución'),
('I', T, 'atrece', 'Ante la solicitud de autorización del estado de excepción, el Congreso:', 'Puede aprobarla en sus propios términos o introducir modificaciones',
 ['Solo puede aprobarla o rechazarla en bloque', 'Debe remitirla al Senado', 'Solo emite un informe no vinculante'],
 'pudiendo aprobarla en sus propios términos o introducir modificaciones en la misma'),
('I', P, 'aquince', 'Duración máxima de la prórroga del estado de excepción', '30 días',
 ['15 días', '60 días', '10 días'], 'la prórroga de aquél, que no podrá exceder de treinta días'),
('I', T, 'aquince', 'El Gobierno puede poner fin al estado de excepción antes de que finalice su período:', 'Mediante decreto acordado en Consejo de Ministros, dando cuenta inmediatamente al Congreso',
 ['Solo con autorización previa del Congreso', 'Solo con autorización del Senado', 'No puede, debe agotarse el período'],
 'mediante decreto acordado en Consejo de Ministros, podrá poner fin al estado de excepción'),
('I', P, 'adieciseis', 'Duración máxima de la detención acordada por la Autoridad gubernativa durante el estado de excepción', '10 días',
 ['72 horas', '5 días', '15 días'], 'La detención no podrá exceder de diez días'),
('I', P, 'adieciseis', 'Plazo para comunicar al juez competente la detención practicada durante el estado de excepción', '24 horas',
 ['72 horas', '48 horas', '12 horas'], 'La detención habrá de ser comunicada al juez competente en el plazo de veinticuatro horas'),
('I', T, 'aveinte', 'Durante el estado de excepción, la Autoridad gubernativa puede exigir a personas determinadas que comuniquen todo desplazamiento fuera de su localidad de residencia con una antelación de:', 'Dos días',
 ['Un día', 'Tres días', 'Cinco días'], 'con una antelación de dos días'),
('I', T, 'aveintiuno', 'La suspensión de publicaciones y emisiones durante el estado de excepción:', 'No puede llevar aparejado ningún tipo de censura previa',
 ['Permite la censura previa', 'Requiere autorización judicial', 'Solo afecta a publicaciones extranjeras'], 'no podrá llevar aparejado ningún tipo de censura previa'),
('I', T, 'aveintidos', 'Durante el estado de excepción, las reuniones orgánicas de partidos políticos, sindicatos y asociaciones empresariales conforme a sus fines y Estatutos:', 'No pueden ser prohibidas, disueltas ni sometidas a autorización previa',
 ['Pueden prohibirse libremente', 'Requieren autorización previa', 'Solo pueden celebrarse en locales públicos'],
 'no podrán ser prohibidas, disueltas ni sometidas a autorización previa'),
('I', T, 'atreintaydos', 'El estado de sitio procede cuando se produzca o amenace producirse:', 'Una insurrección o acto de fuerza contra la soberanía, independencia, integridad territorial u ordenamiento constitucional de España',
 ['Una epidemia grave', 'Una huelga en servicios esenciales', 'Una catástrofe natural'],
 'Cuando se produzca o amenace producirse una insurrección o acto de fuerza contra la soberanía o independencia de España'),
('I', T, 'atreintaydos', 'La declaración del estado de sitio corresponde, a propuesta del Gobierno, a:', 'El Congreso de los Diputados',
 ['El Consejo de Ministros', 'El Senado', 'Las Cortes Generales en sesión conjunta'], 'podrá proponer al Congreso de los Diputados la declaración de estado de sitio'),
('I', T, 'atreintaydos', 'La declaración del estado de sitio puede autorizar, además de lo previsto para los estados de alarma y excepción:', 'La suspensión temporal de las garantías jurídicas del detenido del artículo 17.3 de la Constitución',
 ['La suspensión del derecho a la vida', 'La disolución del Congreso', 'La suspensión de la tutela judicial efectiva'],
 'la suspensión temporal de las garantías jurídicas del detenido'),
('I', T, 'atreintaytres', 'En el estado de sitio, ejecuta las medidas en el territorio afectado, bajo la dirección del Gobierno:', 'La Autoridad militar designada por el Gobierno',
 ['El Ministro del Interior', 'El Delegado del Gobierno', 'El Presidente de la Comunidad Autónoma'], 'el Gobierno designará la Autoridad militar'),
('I', T, 'atreintaycinco', 'En la declaración del estado de sitio, el Congreso de los Diputados puede determinar:', 'Los delitos que durante su vigencia quedan sometidos a la Jurisdicción Militar',
 ['La suspensión de las elecciones', 'La destitución del Gobierno', 'La disolución de los partidos políticos'],
 'podrá determinar los delitos que durante su vigencia quedan sometidos a la Jurisdicción Militar'),
]
