# Lote 10 · LGP (Ley 47/2003, General Presupuestaria) · bloque V (gestión financiera).
# Arts. 1-80 (sector público estatal, Hacienda Pública, principios, presupuestos, créditos y modificaciones,
# gestión del gasto, anticipos de caja fija y pagos a justificar) y arts. 140-159 (control interno).
# Se evitan preguntas que dependan de denominaciones de ministerios no actualizadas en el texto.
NORMA, LOTE, INICIO = 'LGP', 'lote-010', 10001
T, P = 'test', 'plazo'
PREGUNTAS = [
# Arts. 1-4
('V', T, 'a1', 'La Ley General Presupuestaria tiene por objeto la regulación del régimen presupuestario, económico-financiero, de contabilidad, intervención y control financiero:', 'Del sector público estatal',
 ['De todas las Administraciones Públicas', 'De las comunidades autónomas y entidades locales', 'Exclusivamente de la Administración General del Estado'],
 'Esta ley tiene por objeto la regulación del régimen presupuestario'),
('V', T, 'a2', 'Según el artículo 2.1 de la LGP, forman parte del sector público estatal:', 'La Administración General del Estado y el sector público institucional estatal',
 ['Solo la Administración General del Estado y sus organismos autónomos', 'La Administración General del Estado y las comunidades autónomas', 'Solo las entidades con presupuesto limitativo'],
 r're:A los efectos de esta Ley forman parte del sector público estatal: a\) La Administración General del Estado\. b\) El sector público institucional estatal'),
('V', T, 'a2', '¿A qué institución NO se aplica la Ley General Presupuestaria, por gozar de autonomía presupuestaria según el artículo 72 de la Constitución?', 'A las Cortes Generales',
 ['A los organismos autónomos', 'A las agencias estatales', 'A las universidades públicas no transferidas'],
 'esta Ley no será de aplicación a las Cortes Generales'),
('V', T, 'a3', 'Según el artículo 3 de la LGP, las entidades públicas empresariales y las sociedades mercantiles estatales integran:', 'El sector público empresarial',
 ['El sector público administrativo', 'El sector público fundacional', 'La Hacienda Pública estatal'],
 r're:El sector público empresarial, integrado por: a\) Las entidades públicas empresariales\. b\) Las sociedades mercantiles estatales\. c\) Cualesquiera organismos'),
('V', T, 'a3', 'Las fundaciones del sector público estatal integran:', 'El sector público fundacional',
 ['El sector público administrativo', 'El sector público empresarial', 'El sector público institucional local'],
 r're:no incluidos en el sector público administrativo\. 3\. El sector público fundacional, integrado por las fundaciones del sector público estatal'),
('V', T, 'a3', 'Los organismos autónomos forman parte, según la LGP, del:', 'Sector público administrativo',
 ['Sector público empresarial', 'Sector público fundacional', 'Sector público financiero'],
 r're:El sector público administrativo, integrado por: a\) La Administración General del Estado, los organismos autónomos'),
('V', T, 'a4', 'Según el artículo 4.3 de la LGP, en el régimen económico y financiero del sector público estatal tienen carácter supletorio:', 'Las demás normas de derecho administrativo y, en su defecto, las normas de derecho común',
 ['Las normas de derecho común y, en su defecto, las de derecho administrativo', 'Exclusivamente las normas del Derecho de la Unión Europea', 'La Ley General Tributaria en todo caso'],
 'Tendrán carácter supletorio las demás normas de derecho administrativo y, en su defecto, las normas de derecho común'),
# Arts. 5-25: Hacienda Pública
('V', T, 'a5', 'La Hacienda Pública estatal está constituida por el conjunto de derechos y obligaciones de contenido económico cuya titularidad corresponde:', 'A la Administración General del Estado y a sus organismos autónomos',
 ['A todo el sector público estatal', 'A la Administración General del Estado exclusivamente', 'A las Administraciones Públicas territoriales'],
 'cuya titularidad corresponde a la Administración General del Estado y a sus organismos autónomos'),
('V', T, 'a5', 'Los derechos de la Hacienda Pública estatal se clasifican en:', 'Derechos de naturaleza pública y de naturaleza privada',
 ['Derechos tributarios y no tributarios exclusivamente', 'Derechos ordinarios y extraordinarios', 'Derechos presupuestarios y extrapresupuestarios'],
 'Los derechos de la Hacienda Pública estatal se clasifican en derechos de naturaleza pública y de naturaleza privada'),
('V', T, 'a7', 'Transigir judicial o extrajudicialmente sobre los derechos de la Hacienda Pública estatal, o someterlos a arbitraje, requiere (salvo lo previsto en el art. 10.2):', 'Real decreto acordado en Consejo de Ministros, previa audiencia del Consejo de Estado en pleno',
 ['Orden del Ministro de Hacienda', 'Ley de las Cortes Generales en todo caso', 'Resolución del Interventor General de la Administración del Estado'],
 'sino mediante real decreto acordado en Consejo de Ministros, previa audiencia del de Estado en pleno'),
('V', T, 'a7', 'Las exenciones, condonaciones, rebajas o moratorias en el pago de los derechos de la Hacienda Pública estatal:', 'Solo se concederán en los casos y formas que determinen las leyes',
 ['Pueden concederlas libremente los ministros', 'Pueden concederse por resolución de la Agencia Tributaria en cualquier caso', 'Están prohibidas en todo caso'],
 'Tampoco se concederán exenciones, condonaciones, rebajas ni moratorias en el pago de los derechos a la Hacienda Pública estatal, sino en los casos y formas que determinen las leyes'),
('V', T, 'a9', 'Cuando los organismos autónomos concurran con la Administración General del Estado en el cobro de créditos:', 'Tiene preferencia la Administración General del Estado',
 ['Tienen preferencia los organismos autónomos', 'Se cobran a prorrata', 'Se atiende al crédito más antiguo'],
 'Cuando los organismos autónomos concurran con la Administración General del Estado, tendrá preferencia para el cobro de los créditos esta última'),
('V', T, 'a12', 'Las providencias de apremio acreditativas del descubierto de deudas de derechos de naturaleza pública:', 'Tienen la misma fuerza ejecutiva que la sentencia judicial',
 ['Necesitan homologación judicial para ejecutarse', 'Solo tienen valor informativo', 'Requieren previa conformidad del deudor'],
 'tendrán la misma fuerza ejecutiva que la sentencia judicial'),
('V', T, 'a12', 'El procedimiento de apremio se suspenderá inmediatamente, sin necesidad de garantía, cuando el interesado demuestre, entre otros supuestos:', 'Que la deuda ha prescrito o ha sido ingresada',
 ['Que ha interpuesto una demanda civil', 'Que carece de liquidez', 'Que la deuda es superior a 3.000 euros'],
 r're:sin necesidad de prestar garantía, cuando el interesado demuestre.*?o bien que dicha deuda ha prescrito o ha sido ingresada'),
('V', T, 'a13', 'El aplazamiento o fraccionamiento de las cantidades adeudadas a la Hacienda Pública estatal en virtud de una relación de derecho público:', 'Devenga el correspondiente interés de demora',
 ['No devenga interés alguno', 'Devenga el interés legal del dinero incrementado en un 25 %', 'Está prohibido'],
 'devengando el correspondiente interés de demora'),
('V', P, 'a15', 'Plazo de prescripción, salvo leyes especiales, del derecho de la Hacienda Pública estatal a reconocer o liquidar créditos a su favor', '4 años',
 ['5 años', '3 años', '10 años'], 'prescribirá a los cuatro años el derecho de la Hacienda Pública estatal'),
('V', T, 'a15', 'La prescripción de los derechos de la Hacienda Pública estatal se interrumpe conforme a la Ley General Tributaria y se aplica:', 'De oficio',
 ['Solo a instancia del deudor', 'Solo por declaración judicial', 'A instancia del Tribunal de Cuentas'],
 'se interrumpirá conforme a lo establecido en la Ley General Tributaria y se aplicará de oficio'),
('V', T, 'a17', 'Las cantidades adeudadas a la Hacienda Pública estatal devengan interés de demora:', 'Desde el día siguiente al de su vencimiento',
 ['Desde el mismo día de su vencimiento', 'Desde la notificación de la providencia de apremio', 'A partir del mes siguiente a su vencimiento'],
 'devengarán interés de demora desde el día siguiente al de su vencimiento'),
('V', T, 'a17', 'El interés de demora de las cantidades adeudadas a la Hacienda Pública estatal resulta de aplicar:', 'El interés legal fijado en la Ley de Presupuestos para cada ejercicio',
 ['El tipo de interés del Banco Central Europeo', 'El interés legal incrementado en un 25 % en todo caso', 'El tipo que fije cada órgano gestor'],
 'del interés legal fijado en la Ley de Presupuestos para dichos ejercicios'),
('V', T, 'a20', 'Según el artículo 20 de la LGP, las obligaciones de la Hacienda Pública estatal nacen:', 'De la ley, de los negocios jurídicos y de los actos o hechos que, según derecho, las generen',
 ['Exclusivamente de la Ley de Presupuestos', 'Solo de los contratos', 'De las sentencias judiciales exclusivamente'],
 'Las obligaciones de la Hacienda Pública estatal nacen de la ley, de los negocios jurídicos y de los actos o hechos que, según derecho, las generen'),
('V', T, 'a21', 'Las obligaciones de la Hacienda Pública estatal solo son exigibles cuando resulten:', 'De la ejecución de los presupuestos, de sentencia judicial firme o de operaciones no presupuestarias legalmente autorizadas',
 ['De cualquier acuerdo del órgano gestor', 'De la mera reclamación del acreedor', 'De los convenios, aunque no tengan crédito'],
 'sólo son exigibles cuando resulten de la ejecución de los presupuestos'),
('V', T, 'a21', 'En convenios y encomiendas de gestión, el acreedor de la Administración puede percibir un anticipo por operaciones preparatorias hasta un límite máximo de:', 'El 10 por ciento de la cantidad total a percibir',
 ['El 20 por ciento de la cantidad total a percibir', 'El 50 por ciento de la cantidad total a percibir', 'El 5 por ciento de la cantidad total a percibir'],
 'hasta un límite máximo del 10 por ciento de la cantidad total a percibir'),
('V', T, 'a23', 'Ningún tribunal ni autoridad administrativa podrá dictar providencia de embargo contra los bienes y derechos patrimoniales del Estado cuando:', 'Se encuentren materialmente afectados a un servicio público o a una función pública',
 ['Su valor sea inferior a 600.000 euros', 'Estén inscritos en el Registro de la Propiedad', 'Sean bienes muebles'],
 'cuando se encuentren materialmente afectados a un servicio público o a una función pública'),
('V', P, 'a23', 'Plazo para concluir la modificación presupuestaria necesaria para pagar una obligación impuesta por resolución judicial, desde la notificación de la resolución', '3 meses',
 ['1 mes', '2 meses', '6 meses'], 'deberá concluirse el procedimiento correspondiente dentro de los tres meses siguientes al día de la notificación de la resolución judicial'),
('V', P, 'a24', 'Plazo desde la notificación de la resolución judicial o del reconocimiento de la obligación tras el cual, si la Administración no paga y el acreedor lo reclama por escrito, se devengan intereses de demora', '3 meses',
 ['1 mes', '2 meses', '6 meses'], 'Si la Administración no pagara al acreedor de la Hacienda Pública estatal dentro de los tres meses siguientes'),
('V', P, 'a25', 'Plazo de prescripción, salvo leyes especiales, del derecho a exigir el pago de las obligaciones ya reconocidas o liquidadas', '4 años',
 ['5 años', '3 años', '1 año'], 'b) El derecho a exigir el pago de las obligaciones ya reconocidas o liquidadas'),
('V', T, 'a25', 'La prescripción de las obligaciones de la Hacienda Pública estatal se interrumpe, salvo leyes especiales, conforme a:', 'Las disposiciones del Código Civil',
 ['La Ley General Tributaria', 'La Ley 39/2015', 'La Ley de Enjuiciamiento Civil'], 'la prescripción se interrumpirá conforme a las disposiciones del Código Civil'),
# Arts. 26-31: principios y programación
('V', T, 'a26', '¿Cuál de los siguientes NO figura entre los principios de programación presupuestaria del artículo 26.1 de la LGP?', 'Anualidad estricta sin escenarios plurianuales',
 ['Estabilidad presupuestaria', 'Sostenibilidad financiera', 'Plurianualidad'],
 'La programación presupuestaria se regirá por los principios de estabilidad presupuestaria, sostenibilidad financiera, plurianualidad'),
('V', T, 'a27', 'La gestión del sector público estatal está sometida al régimen de presupuesto anual aprobado por:', 'Las Cortes Generales',
 ['El Consejo de Ministros', 'El Ministro de Hacienda', 'El Tribunal de Cuentas'],
 'La gestión del sector público estatal está sometida al régimen de presupuesto anual aprobado por las Cortes Generales'),
('V', T, 'a28', 'Los escenarios presupuestarios plurianuales determinan los límites que la acción de gobierno debe respetar, referidos a:', 'Los tres ejercicios siguientes',
 ['Los dos ejercicios siguientes', 'Los cinco ejercicios siguientes', 'La legislatura'],
 'determinarán los límites, referidos a los tres ejercicios siguientes'),
('V', T, 'a28', 'Los escenarios presupuestarios plurianuales están integrados por:', 'Un escenario de ingresos y un escenario de gastos',
 ['Un escenario financiero y otro no financiero', 'Un escenario estatal y otro autonómico', 'Un escenario de inversiones exclusivamente'],
 'Los escenarios presupuestarios plurianuales estarán integrados por un escenario de ingresos y un escenario de gastos'),
('V', T, 'a29', 'El programa plurianual de cada ministerio contiene los programas de todos sus centros gestores y se aprueba por:', 'El Ministro',
 ['El Consejo de Ministros', 'Las Cortes Generales', 'El Subsecretario'], 'se aprobará por el Ministro'),
('V', T, 'a31', 'Las asignaciones presupuestarias a los centros gestores de gasto se efectúan tomando en cuenta, entre otras circunstancias:', 'El nivel de cumplimiento de los objetivos en ejercicios anteriores',
 ['El número de empleados de cada centro', 'El gasto realizado en el ejercicio anterior exclusivamente', 'Las peticiones de los ciudadanos'],
 'el nivel de cumplimiento de los objetivos en ejercicios anteriores'),
# Arts. 32-38: los Presupuestos Generales del Estado
('V', T, 'a32', 'Los Presupuestos Generales del Estado constituyen:', 'La expresión cifrada, conjunta y sistemática de los derechos y obligaciones a liquidar durante el ejercicio por los órganos y entidades del sector público estatal',
 ['Una previsión orientativa de ingresos sin carácter vinculante', 'El conjunto de cuentas anuales del ejercicio anterior', 'La programación plurianual del gasto del Gobierno'],
 'Los Presupuestos Generales del Estado constituyen la expresión cifrada, conjunta y sistemática'),
('V', T, 'a33', 'Los presupuestos de las entidades de los sectores empresarial y fundacional que se integran en los PGE tienen carácter:', 'Estimativo',
 ['Limitativo', 'Vinculante a nivel de concepto', 'Ampliable'], 'b) Los presupuestos estimativos de las entidades de los sectores empresarial y fundacional'),
('V', T, 'a33', 'Entre las determinaciones de los Presupuestos Generales del Estado figura:', 'La estimación de los beneficios fiscales que afecten a los tributos del Estado',
 ['La aprobación de las cuentas anuales del ejercicio anterior', 'La fijación de los tipos de interés del Tesoro', 'La relación de puestos de trabajo de cada ministerio'],
 'e) La estimación de los beneficios fiscales que afecten a los tributos del Estado'),
('V', T, 'a34', 'El ejercicio presupuestario coincide con:', 'El año natural',
 ['El período de 1 de julio a 30 de junio', 'La legislatura', 'El período de vigencia de los escenarios plurianuales'],
 'El ejercicio presupuestario coincidirá con el año natural'),
('V', T, 'a34', 'Al ejercicio presupuestario se imputan las obligaciones económicas reconocidas:', 'Hasta el fin del mes de diciembre, siempre que correspondan a gastos realizados dentro del ejercicio',
 ['Hasta el 31 de marzo del año siguiente', 'Durante el ejercicio, aunque correspondan a gastos de otros ejercicios', 'Hasta la aprobación de la Cuenta General'],
 'b) Las obligaciones económicas reconocidas hasta el fin del mes de diciembre'),
('V', T, 'a34', 'La imputación al presupuesto de obligaciones de ejercicios anteriores no comprendidas en los supuestos del artículo 34.2 y 3 requiere:', 'Norma con rango de ley que la autorice',
 ['Acuerdo del Consejo de Ministros', 'Orden del Ministro de Hacienda', 'Informe favorable de la Intervención Delegada'],
 'la imputación requerirá norma con rango de ley que la autorice'),
('V', T, 'a35', 'Son créditos presupuestarios:', 'Cada una de las asignaciones individualizadas de gasto puestas a disposición de los centros gestores',
 ['Los derechos económicos liquidados en el ejercicio', 'Las previsiones de ingresos del Estado', 'Los préstamos concedidos por el Tesoro'],
 'Son créditos presupuestarios cada una de las asignaciones individualizadas de gasto'),
('V', T, 'a36', 'Elevar al acuerdo del Gobierno el anteproyecto de Ley de Presupuestos Generales del Estado corresponde:', 'Al Ministro de Hacienda',
 ['Al Presidente del Gobierno', 'A la Comisión de Políticas de Gasto', 'Al Director General de Presupuestos'],
 'Corresponderá al Ministro de Hacienda elevar al acuerdo del Gobierno el anteproyecto'),
('V', T, 'a36', 'Para fijar las directrices de distribución del gasto en la elaboración de los Presupuestos se constituye:', 'La Comisión de Políticas de Gasto',
 ['La Comisión General de Secretarios de Estado y Subsecretarios', 'La Comisión Delegada para Asuntos Presupuestarios', 'El Consejo de Política Fiscal y Financiera'],
 'se constituirá la Comisión de Políticas de Gasto'),
('V', T, 'a37', 'El proyecto de Ley de Presupuestos Generales del Estado debe remitirse a las Cortes Generales:', 'Antes del día 1 de octubre del año anterior al que se refiera',
 ['Antes del día 1 de noviembre del año anterior', 'Antes del día 1 de septiembre del año anterior', 'Antes del 31 de diciembre del año anterior'],
 'será remitido a las Cortes Generales antes del día 1 de octubre del año anterior al que se refiera'),
('V', T, 'a37', '¿Cuál de los siguientes documentos NO acompaña al proyecto de Ley de PGE según el artículo 37.2?', 'Las cuentas anuales auditadas de cada sociedad mercantil estatal',
 ['El informe de impacto de género', 'La memoria de los beneficios fiscales', 'Un informe económico y financiero'],
 r're:Al proyecto de Ley de Presupuestos Generales del Estado se acompañará la siguiente documentación complementaria: a\).*?k\) Una memoria de los beneficios fiscales'),
('V', T, 'a38', 'Si la Ley de Presupuestos Generales del Estado no se aprueba antes del primer día del ejercicio correspondiente:', 'Se consideran automáticamente prorrogados los presupuestos iniciales del ejercicio anterior',
 ['El Gobierno aprueba un presupuesto provisional por real decreto-ley', 'Solo pueden atenderse gastos de personal', 'Se paraliza toda ejecución de gasto'],
 'se considerarán automáticamente prorrogados los presupuestos iniciales del ejercicio anterior'),
('V', T, 'a38', 'La prórroga de los Presupuestos Generales del Estado NO afecta a los créditos:', 'Para programas o actuaciones que terminen en el ejercicio cuyos presupuestos se prorrogan',
 ['De gastos de personal', 'De la Deuda Pública', 'De transferencias a la Seguridad Social'],
 'La prórroga no afectará a los créditos para gastos correspondientes a programas o actuaciones que terminen'),
# Arts. 39-50: estructura y créditos
('V', T, 'a40', '¿Cuál de las siguientes NO es una de las clasificaciones de los estados de gastos según el artículo 40.1 de la LGP?', 'La clasificación territorial',
 ['La clasificación orgánica', 'La clasificación por programas', 'La clasificación económica'],
 r're:se estructurarán de acuerdo con las siguientes clasificaciones: a\) La clasificación orgánica.*?b\) La clasificación por programas.*?c\) La clasificación económica, que agrupará los créditos por capítulos'),
('V', T, 'a40', 'La clasificación económica agrupa los créditos de gastos por:', 'Capítulos, separando operaciones corrientes, de capital, financieras y el Fondo de Contingencia',
 ['Secciones y servicios', 'Programas y subprogramas', 'Políticas de gasto'],
 'La clasificación económica, que agrupará los créditos por capítulos'),
('V', T, 'a40', 'En la clasificación económica de gastos, dentro de las operaciones de capital se distinguen:', 'Las inversiones reales y las transferencias de capital',
 ['Los gastos de personal y los gastos financieros', 'Los activos y pasivos financieros', 'Los gastos corrientes en bienes y servicios'],
 'En los créditos para operaciones de capital se distinguirán las inversiones reales y las transferencias de capital'),
('V', T, 'a40', 'La clasificación orgánica agrupa los créditos asignados a los distintos centros gestores por:', 'Secciones y servicios',
 ['Capítulos, artículos y conceptos', 'Programas', 'Finalidades'], 'La clasificación orgánica que agrupará por secciones y servicios'),
('V', T, 'a41', 'Los estados de ingresos se estructuran siguiendo las clasificaciones:', 'Orgánica y económica',
 ['Orgánica, por programas y económica', 'Económica y funcional', 'Por programas y territorial'],
 'se estructurarán siguiendo las clasificaciones orgánica y económica'),
('V', T, 'a42', 'Según el principio de especialidad, los créditos para gastos se destinarán:', 'Exclusivamente a la finalidad específica para la que hayan sido autorizados por la Ley de Presupuestos o por las modificaciones aprobadas',
 ['A cualquier gasto del mismo ministerio', 'A cualquier gasto del mismo capítulo', 'A la finalidad que decida el órgano gestor'],
 'Los créditos para gastos se destinarán exclusivamente a la finalidad específica'),
('V', T, 'a43', 'En el presupuesto del Estado, con carácter general, los créditos se especifican a nivel de:', 'Concepto',
 ['Capítulo', 'Artículo', 'Subconcepto'], 'En el presupuesto del Estado los créditos se especificarán a nivel de concepto'),
('V', T, 'a43', 'En el presupuesto del Estado, los créditos para gastos de personal y gastos corrientes en bienes y servicios se especifican a nivel de:', 'Artículo',
 ['Concepto', 'Capítulo', 'Subconcepto'], 'que se especificarán a nivel de artículo y las inversiones reales a nivel de capítulo'),
('V', T, 'a43', 'En el presupuesto del Estado, las inversiones reales se especifican a nivel de:', 'Capítulo',
 ['Artículo', 'Concepto', 'Programa'], 'y las inversiones reales a nivel de capítulo'),
('V', T, 'a46', 'Los actos administrativos y disposiciones generales de rango inferior a ley que adquieran compromisos de gasto por cuantía superior al importe de los créditos autorizados son:', 'Nulos de pleno derecho',
 ['Anulables', 'Válidos, pero el exceso no puede pagarse', 'Válidos si se convalidan por el Consejo de Ministros'],
 'siendo nulos de pleno derecho los actos administrativos y las disposiciones generales con rango inferior a ley'),
('V', T, 'a46', 'Según el artículo 46 de la LGP, los créditos para gastos son:', 'Limitativos',
 ['Estimativos', 'Ampliables', 'Indicativos'], 'Los créditos para gastos son limitativos'),
('V', T, 'a47', 'Con carácter general, el número de ejercicios a que pueden aplicarse los gastos plurianuales no será superior a:', 'Cuatro',
 ['Tres', 'Cinco', 'Seis'], 'El número de ejercicios a que pueden aplicarse los gastos no será superior a cuatro'),
('V', T, 'a47', 'En los compromisos de gasto plurianuales, el gasto imputado al ejercicio inmediato siguiente no puede exceder del siguiente porcentaje del crédito inicial:', 'El 70 por ciento',
 ['El 60 por ciento', 'El 50 por ciento', 'El 80 por ciento'], 'en el ejercicio inmediato siguiente, el 70 por ciento'),
('V', T, 'a47', 'En los compromisos de gasto plurianuales, el gasto imputado a los ejercicios tercero y cuarto no puede exceder del siguiente porcentaje del crédito inicial:', 'El 50 por ciento',
 ['El 60 por ciento', 'El 70 por ciento', 'El 40 por ciento'], 'y en los ejercicios tercero y cuarto, el 50 por ciento'),
('V', T, 'a47', 'En los contratos de obra plurianuales (salvo abono total del precio), al adjudicar se efectúa una retención adicional de crédito del:', '10 por ciento del importe de adjudicación',
 ['5 por ciento del importe de adjudicación', '20 por ciento del importe de adjudicación', '3 por ciento del importe de adjudicación'],
 'se efectuará una retención adicional de crédito del 10 por ciento del importe de adjudicación'),
('V', T, 'a47', 'En casos especialmente justificados, modificar los porcentajes o incrementar el número de anualidades de los gastos plurianuales corresponde a:', 'El Gobierno',
 ['El Ministro de Hacienda sin más trámite', 'Las Cortes Generales', 'El titular del departamento afectado'], 'El Gobierno, en casos especialmente justificados, podrá acordar la modificación de los porcentajes anteriores'),
('V', T, 'a48', 'Puede diferirse el pago del precio de compra de bienes inmuebles adquiridos directamente cuyo importe exceda de seis millones de euros, siempre que el desembolso inicial a la firma de la escritura no sea inferior al:', '25 por ciento del precio',
 ['10 por ciento del precio', '50 por ciento del precio', '20 por ciento del precio'], 'el desembolso inicial a la firma de la escritura pueda ser inferior al 25 por ciento del precio'),
('V', T, 'a49', 'Los créditos para gastos que el último día del ejercicio no estén afectados al cumplimiento de obligaciones ya reconocidas:', 'Quedan anulados de pleno derecho, sin perjuicio de las incorporaciones del artículo 58',
 ['Se incorporan automáticamente al ejercicio siguiente', 'Se transfieren al Fondo de Contingencia', 'Se mantienen vigentes durante tres meses más'],
 'quedarán anulados de pleno derecho'),
('V', T, 'a50', 'El Fondo de Contingencia de ejecución presupuestaria se dota por importe del:', 'Dos por ciento del total de gastos para operaciones no financieras, con las exclusiones legales',
 ['Uno por ciento del total de los créditos del Estado', 'Cinco por ciento del total de gastos', 'Diez por ciento de los gastos de capital'],
 'por importe del dos por ciento del total de gastos para operaciones no financieras'),
('V', T, 'a50', '¿Cuál de las siguientes modificaciones de crédito NO puede financiar el Fondo de Contingencia?', 'Las transferencias de crédito',
 ['Las ampliaciones de crédito', 'Los créditos extraordinarios y suplementos de crédito', 'Las incorporaciones de crédito'],
 r're:El Fondo únicamente financiará, cuando proceda, las siguientes modificaciones de crédito.*?c\) Las incorporaciones de crédito, conforme al artículo 58'),
('V', T, 'a50', 'La aplicación del Fondo de Contingencia se aprueba:', 'Mediante acuerdo del Consejo de Ministros, previamente a la autorización de las modificaciones de crédito',
 ['Por orden del Ministro de Hacienda, después de autorizar las modificaciones', 'Por ley de las Cortes Generales', 'Por resolución de la Dirección General de Presupuestos'],
 'mediante acuerdo del Consejo de Ministros, previamente a la autorización de las respectivas modificaciones de crédito'),
('V', T, 'a50', 'El Gobierno remite a las Cortes Generales un informe sobre la utilización del Fondo de Contingencia con periodicidad:', 'Trimestral',
 ['Mensual', 'Semestral', 'Anual'], 'un informe trimestral acerca de la utilización del Fondo'),
# Arts. 51-63: modificaciones presupuestarias
('V', T, 'a51', '¿Cuál de las siguientes NO es una figura de modificación de los créditos iniciales del artículo 51 de la LGP?', 'Las bajas por anulación',
 ['Las transferencias', 'Las generaciones', 'Las incorporaciones'],
 r're:mediante: a\) Transferencias\. b\) Generaciones\. c\) Ampliaciones\. d\) Créditos extraordinarios y suplementos de crédito\. e\) Incorporaciones'),
('V', T, 'a52', 'Las transferencias de crédito son:', 'Traspasos de dotaciones entre créditos',
 ['Incrementos de crédito por ingresos no previstos', 'Créditos para gastos sin dotación previa', 'Remanentes del ejercicio anterior'], 'Las transferencias son traspasos de dotaciones entre créditos'),
('V', T, 'a52', 'Con carácter general, las transferencias de crédito NO pueden realizarse:', 'Desde créditos para operaciones de capital a créditos para operaciones corrientes',
 ['Entre créditos de un mismo programa', 'Desde créditos para operaciones corrientes a créditos para operaciones de capital', 'Entre créditos de una misma sección presupuestaria'],
 'ni desde créditos para operaciones de capital a créditos para operaciones corrientes'),
('V', T, 'a52', 'Con carácter general, las transferencias de crédito NO pueden realizarse entre créditos:', 'De distintas secciones presupuestarias',
 ['De un mismo servicio', 'De un mismo programa', 'De un mismo capítulo'], 'b) No podrán realizarse entre créditos de distintas secciones presupuestarias'),
('V', T, 'a52', 'Con carácter general, las transferencias de crédito no pueden minorar:', 'Créditos extraordinarios o créditos que se hayan suplementado o ampliado en el ejercicio',
 ['Créditos de gastos corrientes en bienes y servicios', 'Créditos de inversiones reales', 'Créditos del mismo programa'],
 'c) No minorarán créditos extraordinarios o créditos que se hayan suplementado o ampliado en el ejercicio'),
('V', T, 'a53', 'Las generaciones de crédito son modificaciones que incrementan los créditos como consecuencia de:', 'La realización de determinados ingresos no previstos o superiores a los contemplados en el presupuesto inicial',
 ['Traspasos de dotaciones entre créditos', 'La aprobación de una ley de crédito extraordinario', 'La incorporación de remanentes del ejercicio anterior'],
 'Las generaciones son modificaciones que incrementan los créditos como consecuencia de la realización de determinados ingresos'),
('V', T, 'a53', '¿Cuál de los siguientes ingresos NO figura entre los que pueden dar lugar a generaciones de crédito según el artículo 53.2?', 'Los ingresos por impuestos directos',
 ['Ventas de bienes y prestación de servicios', 'Enajenaciones de inmovilizado', 'Reembolsos de préstamos'],
 r're:Podrán dar lugar a generaciones los ingresos realizados en el propio ejercicio como consecuencia de: a\).*?f\) Ingresos por reintegros de pagos indebidos'),
('V', T, 'a53', 'Los ingresos procedentes del reembolso de préstamos solo pueden generar crédito en:', 'Los créditos destinados a la concesión de nuevos préstamos',
 ['Cualquier crédito del mismo ministerio', 'Los créditos de gastos de personal', 'El Fondo de Contingencia'],
 'Los ingresos procedentes de reembolso de préstamos únicamente podrán dar lugar a generaciones en aquellos créditos destinados a la concesión de nuevos préstamos'),
('V', T, 'a53', 'Con carácter excepcional, pueden generar crédito en el presupuesto del ejercicio los ingresos realizados:', 'En el último trimestre del ejercicio anterior',
 ['En cualquier momento de los dos ejercicios anteriores', 'En el primer trimestre del ejercicio siguiente', 'En el último mes del ejercicio anterior'],
 'los ingresos realizados en el último trimestre del ejercicio anterior'),
('V', T, 'a54', 'Tienen la condición de créditos ampliables, entre otros:', 'Los destinados al pago de pensiones de Clases Pasivas del Estado',
 ['Los destinados a atenciones protocolarias y representativas', 'Los de gastos corrientes en bienes y servicios', 'Los de arrendamientos de edificios'],
 'Excepcionalmente tendrán la condición de ampliables los créditos destinados al pago de pensiones de Clases Pasivas del Estado'),
('V', T, 'a54', 'Las ampliaciones de crédito que afecten a operaciones del presupuesto del Estado se financian:', 'Con cargo al Fondo de Contingencia o con baja en otros créditos del presupuesto no financiero',
 ['Con Deuda Pública en todo caso', 'Con el remanente de tesorería del Estado', 'Con mayores ingresos tributarios del ejercicio siguiente'],
 'se financiarán con cargo al Fondo de Contingencia, conforme a lo previsto en el artículo 50 de esta ley, o con baja en otros créditos del presupuesto no financiero'),
('V', T, 'a55', 'Si con cargo al Presupuesto del Estado debe realizarse un gasto que no puede demorarse al ejercicio siguiente, no existe crédito adecuado o el consignado es insuficiente y no ampliable, y no cabe dotarlo con las restantes figuras del artículo 51, procede tramitar:', 'Un crédito extraordinario o suplementario',
 ['Una generación de crédito', 'Una incorporación de remanentes', 'Un anticipo de caja fija'],
 'deberá procederse a la tramitación de un crédito extraordinario o suplementario del inicialmente previsto'),
('V', T, 'a55', 'Si la necesidad de un crédito extraordinario o suplementario surge en operaciones financieras del Presupuesto del Estado, se financiará:', 'Con Deuda Pública o con baja en otros créditos de la misma naturaleza',
 ['Con el Fondo de Contingencia', 'Con anticipos de caja fija', 'Con el remanente de tesorería'],
 'se financiará con Deuda Pública o con baja en otros créditos de la misma naturaleza'),
('V', T, 'a55', 'Los créditos extraordinarios y suplementos de crédito del Estado para obligaciones del ejercicio corriente financiados con cargo al Fondo de Contingencia los autoriza:', 'El Consejo de Ministros',
 ['Las Cortes Generales mediante ley', 'El Ministro de Hacienda', 'El titular del departamento afectado'],
 'El Consejo de Ministros autorizará los créditos extraordinarios y suplementos de crédito'),
('V', T, 'a55', 'Los créditos extraordinarios o suplementarios del Estado para obligaciones del propio ejercicio financiados con baja en otros créditos requieren:', 'Un proyecto de ley remitido a las Cortes Generales, previo informe de la Dirección General de Presupuestos y dictamen del Consejo de Estado',
 ['Un acuerdo del Consejo de Ministros', 'Una orden del Ministro de Hacienda', 'Una resolución del Interventor General'],
 'b) Cuando se trate de créditos extraordinarios o suplementarios para atender obligaciones del propio ejercicio cuando se financien con baja en otros créditos'),
('V', T, 'a56', 'Los créditos extraordinarios o suplementarios de los organismos autónomos solo pueden financiarse con:', 'La parte no aplicada del remanente de tesorería del ejercicio anterior o con mayores ingresos sobre los previstos',
 ['El Fondo de Contingencia exclusivamente', 'Deuda Pública', 'Baja en créditos de otros organismos'],
 'únicamente podrá realizarse con cargo a la parte del remanente de tesorería al fin del ejercicio anterior que no haya sido aplicada en el presupuesto del organismo'),
('V', T, 'a56', 'Los presidentes o directores de los organismos autónomos pueden autorizar créditos extraordinarios o suplementarios hasta el 10 % del capítulo, siempre que no se supere la cuantía de:', '500.000 euros',
 ['1.000.000 de euros', '300.000 euros', '12.000.000 de euros'], 'cuando no supere la cuantía de 500.000 euros, excluidos los que afecten a gastos de personal'),
('V', T, 'a58', 'Pueden incorporarse a los créditos de un ejercicio los remanentes de crédito del ejercicio anterior:', 'Cuando lo disponga una norma de rango legal y los procedentes de determinadas generaciones',
 ['Siempre que lo solicite el órgano gestor', 'En todo caso, de forma automática', 'Solo los de gastos de personal'],
 'se podrán incorporar a los correspondientes créditos de un ejercicio los remanentes de crédito del ejercicio anterior'),
('V', T, 'a60', 'Los anticipos de Tesorería para gastos inaplazables tienen un límite máximo, en cada ejercicio, del:', 'Uno por ciento de los créditos autorizados al Estado por la Ley de Presupuestos',
 ['Dos por ciento de los gastos no financieros', 'Cinco por ciento de los créditos autorizados', 'Siete por ciento de los gastos corrientes'],
 'con el límite máximo en cada ejercicio del uno por ciento de los créditos autorizados al Estado'),
('V', T, 'a60', 'Si las Cortes Generales no aprueban el proyecto de ley del crédito extraordinario o suplemento que motivó un anticipo de Tesorería:', 'El Gobierno dispone la cancelación del anticipo con cargo a los créditos del departamento u organismo cuya minoración ocasione menos trastornos',
 ['El anticipo se convierte en crédito definitivo', 'El anticipo se cancela con cargo al Fondo de Contingencia en todo caso', 'Se exige su reintegro a los acreedores'],
 r're:dispondrá la cancelación del anticipo de Tesorería.*?cuya minoración ocasione menos trastornos para el servicio público'),
('V', T, 'a61', 'Autorizar las transferencias entre distintas secciones presupuestarias como consecuencia de reorganizaciones administrativas corresponde a:', 'El Gobierno',
 ['El Ministro de Hacienda', 'Los ministros afectados', 'La Dirección General de Presupuestos'],
 'a) Autorizar las transferencias entre distintas secciones presupuestarias como consecuencia de reorganizaciones administrativas'),
('V', T, 'a62', 'Autorizar las incorporaciones de remanentes de crédito reguladas en el artículo 58 corresponde a:', 'El Ministro de Hacienda',
 ['El Consejo de Ministros', 'Los titulares de los ministerios', 'Las Cortes Generales'], 'c) Las incorporaciones de remanentes reguladas en el artículo 58'),
('V', T, 'a63', 'Los titulares de los ministerios pueden autorizar transferencias entre créditos de un mismo programa o entre programas de un mismo servicio:', 'Previo informe favorable de la Intervención Delegada competente',
 ['Previo acuerdo del Consejo de Ministros', 'Sin necesidad de informe alguno', 'Previo dictamen del Consejo de Estado'],
 'previo informe favorable de la Intervención Delegada competente'),
('V', T, 'a67', 'En las entidades del sector público empresarial que reciben aportaciones de los PGE, las variaciones de endeudamiento superiores a 12.000.000 de euros sobre su presupuesto de capital son competencia de:', 'El Consejo de Ministros',
 ['El Ministerio del que dependan funcionalmente', 'La persona titular del Ministerio de Hacienda y Función Pública', 'El consejo de administración de la entidad'],
 'Del Consejo de Ministros cuando su importe exceda de la cuantía de 12.000.000 euros'),
('V', T, 'a65', 'El programa de actuación plurianual de las entidades con presupuestos de explotación y capital refleja los datos económico-financieros previstos para el ejercicio del proyecto de PGE y:', 'Los dos ejercicios inmediatamente siguientes',
 ['Los tres ejercicios inmediatamente siguientes', 'Los cuatro ejercicios siguientes', 'El ejercicio siguiente'], 'y a los dos ejercicios inmediatamente siguientes'),
# Arts. 69-80: gestión del gasto
('V', T, 'a69', 'Los sujetos del sector público estatal adecuarán su gestión económico-financiera al cumplimiento de:', 'La eficacia en la consecución de los objetivos y la eficiencia en la asignación y utilización de recursos públicos',
 ['La maximización de los ingresos', 'La rentabilidad económica en todo caso', 'La reducción del gasto de personal'],
 'adecuarán su gestión económico-financiera al cumplimiento de la eficacia en la consecución de los objetivos fijados'),
('V', T, 'a73', '¿Cuál es el orden correcto de las fases del procedimiento de gestión de los gastos según el artículo 73?', 'Aprobación, compromiso, reconocimiento de la obligación, ordenación del pago y pago material',
 ['Compromiso, aprobación, ordenación del pago, reconocimiento de la obligación y pago material', 'Aprobación, reconocimiento de la obligación, compromiso, pago material y ordenación del pago', 'Reconocimiento de la obligación, aprobación, compromiso, ordenación del pago y pago material'],
 r're:a\) Aprobación del gasto\. b\) Compromiso de gasto\. c\) Reconocimiento de la obligación\. d\) Ordenación del pago\. e\) Pago material'),
('V', T, 'a73', 'El acto mediante el cual se autoriza la realización de un gasto determinado por una cuantía cierta o aproximada, reservando crédito, sin relación con terceros, es:', 'La aprobación del gasto',
 ['El compromiso de gasto', 'El reconocimiento de la obligación', 'La ordenación del pago'], 'La aprobación es el acto mediante el cual se autoriza la realización de un gasto determinado'),
('V', T, 'a73', 'La fase del gasto que constituye un acto con relevancia jurídica para con terceros, vinculando a la Hacienda Pública a la realización del gasto, es:', 'El compromiso',
 ['La aprobación', 'La ordenación del pago', 'La retención de crédito'], 'El compromiso es un acto con relevancia jurídica para con terceros'),
('V', T, 'a73', 'El acto mediante el que se declara la existencia de un crédito exigible contra la Hacienda Pública estatal, derivado de un gasto aprobado y comprometido, es:', 'El reconocimiento de la obligación',
 ['El compromiso de gasto', 'La aprobación del gasto', 'El pago material'], 'El reconocimiento de la obligación es el acto mediante el que se declara la existencia de un crédito exigible'),
('V', T, 'a73', 'Cuando la naturaleza de la operación o gasto así lo determine, las fases de ejecución del gasto:', 'Se acumularán en un solo acto',
 ['Deben tramitarse siempre por separado', 'Se sustituyen por la intervención material', 'Se suprimen'],
 'se acumularán en un solo acto las fases de ejecución precisas'),
('V', T, 'a74', 'Corresponde aprobar y comprometer los gastos propios de sus presupuestos, salvo los reservados al Consejo de Ministros, y reconocer las obligaciones:', 'A los Ministros y titulares de los demás órganos del Estado con dotaciones diferenciadas',
 ['Al Ordenador General de Pagos del Estado', 'A la Intervención General de la Administración del Estado', 'A la Dirección General de Presupuestos'],
 'Corresponde a los Ministros y a los titulares de los demás órganos del Estado con dotaciones diferenciadas'),
('V', T, 'a74', 'Los órganos de los departamentos ministeriales necesitan autorización del Consejo de Ministros para suscribir convenios o contratos-programa cuando el gasto sea superior a:', '12 millones de euros',
 ['6 millones de euros', '3 millones de euros', '1 millón de euros'], 'cuando el importe del gasto que de aquellos se derive sea superior a doce millones de euros'),
('V', T, 'a77', 'Se entiende por pago indebido el que se realiza:', 'Por error material, aritmético o de hecho, a favor de quien no tiene derecho de cobro o en cuantía superior a la reconocida',
 ['Fuera del plazo legal de pago', 'Sin fiscalización previa', 'Mediante anticipo de caja fija'],
 'se entiende por pago indebido el que se realiza por error material, aritmético o de hecho'),
('V', T, 'a78', 'Los anticipos de caja fija son provisiones de fondos de carácter:', 'Extrapresupuestario y permanente, para gastos periódicos o repetitivos del capítulo de gastos corrientes en bienes y servicios',
 ['Presupuestario y temporal, para inversiones reales', 'Extrapresupuestario y ocasional, para gastos de personal', 'Presupuestario, para gastos en el extranjero'],
 r're:las provisiones de fondos de carácter extrapresupuestario y permanente.*?de gastos periódicos o repetitivos'),
('V', T, 'a78', 'Con carácter general, la cuantía global de los anticipos de caja fija de cada ministerio u organismo autónomo no puede superar:', 'El siete por ciento del total de créditos del capítulo de gastos corrientes en bienes y servicios',
 ['El diez por ciento del total del presupuesto', 'El tres por ciento de los créditos de personal', 'El catorce por ciento de los gastos de capital'],
 'no podrá superar para cada ministerio u organismo autónomo el siete por ciento del total de créditos'),
('V', T, 'a79', 'Pueden librarse fondos con el carácter de «a justificar» cuando:', 'Excepcionalmente, no pueda aportarse la documentación justificativa de las obligaciones en el momento del reconocimiento',
 ['Lo solicite el acreedor', 'El gasto sea superior a 5.000 euros', 'El gasto sea de personal'],
 'Cuando, excepcionalmente, no pueda aportarse la documentación justificativa de las obligaciones'),
('V', P, 'a79', 'Plazo general de rendición de las cuentas justificativas de los pagos a justificar', '3 meses',
 ['1 mes', '2 meses', '6 meses'], 'El plazo de rendición de las cuentas será de tres meses'),
('V', P, 'a79', 'Plazo de rendición de las cuentas de pagos a justificar correspondientes a expropiaciones y pagos en el extranjero', '6 meses',
 ['3 meses', '12 meses', '4 meses'], 'excepto las correspondientes a pagos de expropiaciones y pagos en el extranjero que podrán ser rendidas en el plazo de seis meses'),
('V', P, 'a79', 'Plazo para la aprobación o reparo de la cuenta justificativa de un pago a justificar, desde la aportación de los documentos justificativos', '2 meses',
 ['1 mes', '3 meses', '6 meses'], 'En el curso de los dos meses siguientes a la fecha de aportación de los documentos justificativos'),
('V', T, 'a80', 'La gestión del presupuesto de ingresos se realiza en las fases de:', 'Reconocimiento del derecho y extinción del derecho',
 ['Aprobación, compromiso y pago', 'Liquidación y recaudación en período ejecutivo', 'Previsión, liquidación y contabilización'],
 'a) Reconocimiento del derecho. b) Extinción del derecho'),
# Arts. 140-159: control
('V', T, 'a140', 'El control interno de la gestión económica y financiera del sector público estatal corresponde a:', 'La Intervención General de la Administración del Estado',
 ['El Tribunal de Cuentas', 'La Dirección General de Presupuestos', 'La Autoridad Independiente de Responsabilidad Fiscal'],
 'La Intervención General de la Administración del Estado ejercerá en los términos previstos en esta ley el control interno'),
('V', T, 'a140', 'El control externo del sector público estatal corresponde a:', 'El Tribunal de Cuentas',
 ['La Intervención General de la Administración del Estado', 'El Consejo de Estado', 'La Comisión Nacional de los Mercados y la Competencia'],
 'corresponde al Tribunal de Cuentas el control externo del sector público estatal'),
('V', T, 'a142', 'El control interno regulado en la LGP se realiza mediante:', 'La función interventora, el control financiero permanente y la auditoría pública',
 ['La fiscalización previa, la auditoría privada y el control parlamentario', 'El control de eficacia y el control de legalidad exclusivamente', 'La inspección de servicios y la auditoría externa'],
 'El control se realizará mediante el ejercicio de la función interventora, el control financiero permanente y la auditoría pública'),
('V', T, 'a144', 'La Intervención General de la Administración del Estado ejerce sus funciones de control conforme a los principios de:', 'Autonomía, ejercicio desconcentrado y jerarquía interna',
 ['Dependencia jerárquica del órgano controlado', 'Oportunidad y discrecionalidad', 'Centralización y coordinación'],
 'conforme a los principios de autonomía, ejercicio desconcentrado y jerarquía interna'),
('V', T, 'a148', 'La función interventora tiene por objeto controlar los actos del sector público estatal que den lugar al reconocimiento de derechos o a la realización de gastos:', 'Antes de que sean aprobados',
 ['Una vez ejecutados', 'Al cierre del ejercicio', 'Solo si lo solicita el órgano gestor'], 'La función interventora tiene por objeto controlar, antes de que sean aprobados'),
('V', T, 'a150', 'La intervención formal consiste en:', 'La verificación del cumplimiento de los requisitos legales mediante el examen de los documentos que deban incorporarse al expediente',
 ['La comprobación de la real y efectiva aplicación de los fondos públicos', 'La auditoría de las cuentas anuales', 'La inspección física de las obras'],
 'La intervención formal consistirá en la verificación del cumplimiento de los requisitos legales'),
('V', T, 'a150', 'En la intervención material se comprueba:', 'La real y efectiva aplicación de los fondos públicos',
 ['El cumplimiento de los requisitos formales del expediente', 'La existencia de crédito adecuado', 'La competencia del órgano'],
 r're:En la intervención material se comprobará la real y efectiva aplicación de los fondos públicos\. 2\. El ejercicio'),
('V', T, 'a151', '¿Cuál de los siguientes NO está sometido a fiscalización previa según el artículo 151?', 'Los contratos menores',
 ['Los contratos de obras de valor estimado superior a 40.000 euros', 'Los convenios de colaboración con gasto', 'Las subvenciones concedidas en régimen de concurrencia competitiva'],
 'a) los contratos menores así como los asimilados a ellos en virtud de la legislación contractual'),
('V', T, 'a151', 'No están sometidos a fiscalización previa los gastos que se paguen mediante anticipo de caja fija cuando sean menores de:', '5.000 euros',
 ['15.000 euros', '3.000 euros', '40.000 euros'], 'c) los gastos menores de 5.000 euros cuyo pago se realice mediante el procedimiento especial de anticipo de caja fija'),
('V', T, 'a151', 'Las subvenciones con asignación nominativa:', 'No están sometidas a fiscalización previa',
 ['Requieren siempre fiscalización previa plena', 'Requieren autorización del Consejo de Ministros', 'Se fiscalizan solo si superan 12 millones de euros'],
 'e) las subvenciones con asignación nominativa'),
('V', T, 'a154', 'Si la Intervención está en desacuerdo con el contenido de los actos examinados, deberá formular sus reparos:', 'Por escrito, con cita de los preceptos legales en los que sustente su criterio',
 ['Verbalmente ante el órgano gestor', 'Mediante comunicación al Tribunal de Cuentas', 'Por escrito, sin necesidad de motivación'],
 'deberá formular sus reparos por escrito, con cita de los preceptos legales en los que sustente su criterio'),
('V', T, 'a154', 'La formulación del reparo por la Intervención:', 'Suspende la tramitación del expediente hasta que sea solventado',
 ['No afecta a la tramitación del expediente', 'Produce la nulidad del expediente', 'Obliga a archivar el expediente'],
 'La formulación del reparo suspenderá la tramitación del expediente hasta que sea solventado'),
('V', T, 'a155', 'Cuando el reparo lo haya formulado la Intervención General de la Administración del Estado y subsista la discrepancia, la resolución definitiva corresponde a:', 'El Consejo de Ministros',
 ['El Ministro de Hacienda', 'El Tribunal de Cuentas', 'El Subsecretario del departamento'],
 'corresponderá al Consejo de Ministros adoptar resolución definitiva'),
('V', T, 'a156', 'Cuando la función interventora era preceptiva y se ha omitido:', 'No se podrá reconocer la obligación ni tramitar el pago hasta que se subsane la omisión',
 ['El acto es válido y puede pagarse sin más', 'El expediente se archiva automáticamente', 'Solo se exige responsabilidad al interventor'],
 'no se podrá reconocer la obligación, ni tramitar el pago, ni intervenir favorablemente estas actuaciones hasta que se subsane dicha omisión'),
('V', T, 'a156', 'El acuerdo favorable del Consejo de Ministros en un supuesto de omisión de fiscalización:', 'No exime de la exigencia de las responsabilidades a que hubiera lugar',
 ['Exime de cualquier responsabilidad', 'Requiere ratificación de las Cortes', 'Solo es posible para gastos inferiores a 12 millones de euros'],
 'El acuerdo favorable del Consejo de Ministros no eximirá de la exigencia de las responsabilidades'),
('V', T, 'a157', 'El control financiero permanente se realiza:', 'De forma continua, a través de la correspondiente intervención delegada',
 ['Antes de la aprobación de cada gasto', 'Una vez al año por el Tribunal de Cuentas', 'Solo a solicitud del órgano controlado'],
 'tendrá por objeto la verificación de una forma continua realizada a través de la correspondiente intervención delegada'),
]
