# Lote 18 · LO 3/1981, del Defensor del Pueblo · bloque I (tema I.1: el Defensor del Pueblo).
NORMA, LOTE, INICIO = 'LODP', 'lote-018', 18001
T, P = 'test', 'plazo'
PREGUNTAS = [
('I', T, 'aprimero', 'Según su ley orgánica, el Defensor del Pueblo es:', 'El alto comisionado de las Cortes Generales designado por éstas para la defensa de los derechos del Título I de la Constitución',
 ['Un órgano del Poder Judicial', 'Un órgano dependiente del Ministerio de Justicia', 'El alto comisionado del Gobierno para la defensa de los ciudadanos'],
 'El Defensor del Pueblo es el alto comisionado de las Cortes Generales'),
('I', P, 'asegundo', 'Duración del mandato del Defensor del Pueblo', '5 años',
 ['4 años', '6 años', '9 años'], 'será elegido por las Cortes Generales para un periodo de cinco años'),
('I', T, 'asegundo', 'La Comisión de las Cortes encargada de relacionarse con el Defensor del Pueblo es:', 'Una Comisión Mixta Congreso-Senado',
 ['La Comisión Constitucional del Congreso', 'La Comisión de Peticiones del Senado', 'La Diputación Permanente'], 'Se designará en las Cortes Generales una Comisión Mixta Congreso-Senado'),
('I', T, 'asegundo', 'Para ser designado Defensor del Pueblo, el candidato debe obtener en el Congreso una votación favorable de:', 'Las tres quintas partes de sus miembros, y ser ratificado después por la misma mayoría del Senado',
 ['La mayoría absoluta del Congreso exclusivamente', 'Las dos terceras partes de cada Cámara', 'La mayoría simple de ambas Cámaras en sesión conjunta'],
 'Será designado quien obtuviese una votación favorable de las tres quintas partes de los miembros del Congreso'),
('I', P, 'asegundo', 'Plazo máximo para que el Senado ratifique al Defensor del Pueblo elegido por el Congreso', '20 días',
 ['10 días', '15 días', '30 días'], 'en un plazo máximo de veinte días, fuese ratificado por esta misma mayoría del Senado'),
('I', T, 'asegundo', 'Si no se alcanzan las mayorías iniciales y se formulan nuevas propuestas, la designación queda realizada cuando, tras obtener tres quintos en el Congreso, se alcance en el Senado:', 'La mayoría absoluta',
 ['La mayoría simple', 'Las tres quintas partes', 'Las dos terceras partes'], 'la designación quedará realizada al alcanzarse la mayoría absoluta del Senado'),
('I', T, 'atercero', 'Puede ser elegido Defensor del Pueblo:', 'Cualquier español mayor de edad en pleno disfrute de sus derechos civiles y políticos',
 ['Solo un licenciado en Derecho con diez años de ejercicio', 'Solo un Diputado o Senador', 'Cualquier ciudadano de la Unión Europea residente en España'],
 'Podrá ser elegido Defensor del Pueblo cualquier español mayor de edad'),
('I', T, 'acuao', 'El Defensor del Pueblo toma posesión de su cargo:', 'Ante las Mesas de ambas Cámaras reunidas conjuntamente',
 ['Ante el Rey', 'Ante el Pleno del Congreso', 'Ante el Tribunal Constitucional'], 'tomará posesión de su cargo ante las Mesas de ambas Cámaras reunidas conjuntamente'),
('I', T, 'aquinto', '¿Cuál de las siguientes NO es causa de cese del Defensor del Pueblo según el artículo quinto?', 'La disolución de las Cortes Generales',
 ['La renuncia', 'La expiración del plazo de su nombramiento', 'La condena por sentencia firme por delito doloso'],
 r're:El Defensor del Pueblo cesará por alguna de las siguientes causas: Uno\) Por renuncia\..*?Cinco\) Por haber sido condenado, mediante sentencia firme, por delito doloso'),
('I', T, 'aquinto', 'En los casos de muerte, renuncia y expiración del plazo del mandato, la vacante del Defensor del Pueblo la declara:', 'El Presidente del Congreso',
 ['El Presidente del Senado', 'La Comisión Mixta Congreso-Senado', 'El Rey'], 'La vacante en el cargo se declarará por el Presidente del Congreso en los casos de muerte, renuncia y expiración del plazo del mandato'),
('I', T, 'aquinto', 'En caso de cese por actuar con notoria negligencia, la decisión se adopta:', 'Por mayoría de las tres quintas partes de los componentes de cada Cámara, mediante debate y previa audiencia del interesado',
 ['Por el Presidente del Congreso', 'Por mayoría absoluta del Congreso', 'Por el Tribunal Supremo'],
 'se decidirá, por mayoría de las tres quintas partes de los componentes de cada Cámara'),
('I', T, 'aquinto', 'Mientras las Cortes no designen nuevo Defensor del Pueblo tras su muerte, cese o incapacidad, desempeñan sus funciones interinamente:', 'Los Adjuntos al Defensor del Pueblo, en su propio orden',
 ['El Presidente del Congreso', 'La Comisión Mixta Congreso-Senado', 'El asesor más antiguo'], 'desempeñarán sus funciones, interinamente, en su propio orden, los Adjuntos al Defensor del Pueblo'),
('I', T, 'asexto', 'El Defensor del Pueblo:', 'No está sujeto a mandato imperativo alguno ni recibe instrucciones de ninguna autoridad',
 ['Recibe instrucciones de la Comisión Mixta Congreso-Senado', 'Está sujeto a las instrucciones del Presidente del Congreso', 'Actúa bajo la dirección del Ministerio Fiscal'],
 'El Defensor del Pueblo no estará sujeto a mandato imperativo alguno'),
('I', T, 'asexto', 'La decisión sobre la inculpación, prisión, procesamiento y juicio del Defensor del Pueblo corresponde exclusivamente a:', 'La Sala de lo Penal del Tribunal Supremo',
 ['El Tribunal Constitucional', 'La Audiencia Nacional', 'El Tribunal Superior de Justicia de Madrid'], 'exclusivamente a la Sala de lo Penal del Tribunal Supremo'),
('I', P, 'aseptimo', 'Plazo, desde su nombramiento y antes de tomar posesión, para que el Defensor del Pueblo cese en toda situación de incompatibilidad (si no, se entiende que no acepta)', '10 días',
 ['15 días', '1 mes', '5 días'], 'dentro de los diez días siguientes a su nombramiento'),
('I', T, 'aseptimo', 'La condición de Defensor del Pueblo es incompatible, entre otros, con:', 'La afiliación a un partido político',
 ['La condición de español', 'El disfrute de los derechos civiles', 'La residencia fuera de Madrid'], 'con la afiliación a un partido político'),
('I', T, 'aoctavo', 'El Defensor del Pueblo está auxiliado por:', 'Un Adjunto Primero y un Adjunto Segundo',
 ['Tres Adjuntos', 'Un único Adjunto', 'Un Vicedefensor y un Secretario General'], 'El Defensor del Pueblo estará auxiliado por un Adjunto Primero y un Adjunto Segundo'),
('I', T, 'aoctavo', 'Los Adjuntos del Defensor del Pueblo son nombrados y separados por:', 'El Defensor del Pueblo, previa conformidad de las Cámaras',
 ['Las Cortes Generales por mayoría de tres quintos', 'El Presidente del Congreso', 'El Gobierno'], 'El Defensor del Pueblo nombrará y separará a sus Adjuntos previa conformidad de las Cámaras'),
('I', T, 'anoveno', 'Las investigaciones del Defensor del Pueblo pueden iniciarse:', 'De oficio o a petición de parte',
 ['Solo a petición de parte', 'Solo a petición de las Cortes', 'Solo de oficio'], 'podrá iniciar y proseguir de oficio o a petición de parte'),
('I', T, 'adiez', 'Pueden dirigirse al Defensor del Pueblo:', 'Toda persona natural o jurídica que invoque un interés legítimo, sin restricción alguna',
 ['Solo los ciudadanos españoles mayores de edad', 'Solo las personas residentes en España', 'Solo quienes hayan agotado la vía administrativa'],
 'Podrá dirigirse al Defensor del Pueblo toda persona natural o jurídica que invoque un interés legítimo'),
('I', T, 'adiez', '¿Quién NO puede presentar quejas ante el Defensor del Pueblo?', 'Una autoridad administrativa en asuntos de su competencia',
 ['Un menor de edad', 'Una persona internada en un centro penitenciario', 'Un extranjero no residente'],
 'No podrá presentar quejas ante el Defensor del Pueblo ninguna autoridad administrativa en asuntos de su competencia'),
('I', T, 'aonce', 'Cuando las Cortes Generales no estén reunidas, hayan sido disueltas o haya expirado su mandato, el Defensor del Pueblo se dirige a:', 'Las Diputaciones Permanentes de las Cámaras',
 ['El Gobierno', 'El Rey', 'Las Mesas de las Cámaras'], 'el Defensor del Pueblo se dirigirá a las Diputaciones Permanentes de las Cámaras'),
('I', T, 'aonce', 'La declaración de los estados de excepción o de sitio:', 'No interrumpe la actividad del Defensor del Pueblo ni el derecho de los ciudadanos a acceder a él',
 ['Suspende la actividad del Defensor del Pueblo', 'Suspende el derecho a presentar quejas', 'Traslada sus funciones al Ministerio Fiscal'],
 'La declaración de los estados de excepción o de sitio no interrumpirán la actividad del Defensor del Pueblo'),
('I', T, 'atrece', 'Cuando el Defensor del Pueblo reciba quejas sobre el funcionamiento de la Administración de Justicia, deberá dirigirlas:', 'Al Ministerio Fiscal o al Consejo General del Poder Judicial, según el tipo de reclamación',
 ['Al Ministerio de Justicia', 'Al Tribunal Supremo', 'Al Tribunal Constitucional'],
 r're:deberá dirigirlas al Ministerio Fiscal para que éste investigue su realidad.*?al Consejo General del Poder Judicial'),
('I', P, 'aquince', 'Plazo máximo para presentar una queja ante el Defensor del Pueblo, desde que se tuvo conocimiento de los hechos', '1 año',
 ['6 meses', '2 años', '3 meses'], 'y en el plazo máximo de un año, contado a partir del momento en que tuviera conocimiento de los hechos'),
('I', T, 'aquince', 'Las actuaciones del Defensor del Pueblo son para el interesado:', 'Gratuitas, sin que sea preceptiva la asistencia de Letrado ni de Procurador',
 ['Sujetas a tasa', 'Gratuitas, pero con asistencia letrada obligatoria', 'De pago si la queja es desestimada'],
 'Todas las actuaciones del Defensor del Pueblo son gratuitas para el interesado'),
('I', T, 'adieciseis', 'La correspondencia dirigida al Defensor del Pueblo desde centros de detención, internamiento o custodia:', 'No puede ser objeto de censura de ningún tipo',
 ['Puede ser revisada por el director del centro', 'Requiere autorización judicial', 'Debe remitirse a través del Ministerio Fiscal'],
 'no podrá ser objeto de censura de ningún tipo'),
('I', T, 'adiecisiete', 'El Defensor del Pueblo rechazará en todo caso:', 'Las quejas anónimas',
 ['Las quejas de extranjeros', 'Las quejas de menores', 'Las quejas sobre la Administración local'], 'El Defensor del Pueblo rechazará las quejas anónimas'),
('I', T, 'adiecisiete', 'El Defensor del Pueblo no entrará en el examen individual de las quejas:', 'Sobre las que esté pendiente resolución judicial',
 ['Que afecten a la Administración militar', 'Presentadas por personas jurídicas', 'Referidas a Comunidades Autónomas'],
 'no entrará en el examen individual de aquellas quejas sobre las que esté pendiente resolución judicial'),
('I', T, 'adiecisiete', 'Las decisiones del Defensor del Pueblo de rechazar quejas:', 'No son susceptibles de recurso',
 ['Son recurribles en alzada ante la Comisión Mixta', 'Son recurribles ante el Tribunal Constitucional', 'Son recurribles en reposición'], 'Sus decisiones no serán susceptibles de recurso'),
('I', P, 'adieciocho', 'Plazo máximo, ampliable, para que el organismo afectado remita informe escrito al Defensor del Pueblo tras admitirse una queja', '15 días',
 ['10 días', '1 mes', '20 días'], 'en el plazo máximo de quince días, se remita informe escrito'),
('I', T, 'adiecinueve', 'Todos los poderes públicos están obligados a auxiliar al Defensor del Pueblo en sus investigaciones con carácter:', 'Preferente y urgente',
 ['Subsidiario', 'Voluntario', 'Ordinario'], 'están obligados a auxiliar, con carácter preferente y urgente, al Defensor del Pueblo'),
('I', T, 'aveintidos', 'La no remisión al Defensor del Pueblo de documentos clasificados como secretos debe acordarla:', 'El Consejo de Ministros',
 ['El Ministro competente', 'La Comisión Mixta Congreso-Senado', 'El Centro Nacional de Inteligencia'], 'la no remisión de dichos documentos deberá ser acordada por el Consejo de Ministros'),
('I', T, 'aveinticinco', 'Cuando el Defensor del Pueblo tenga conocimiento de hechos presumiblemente delictivos, lo pondrá de inmediato en conocimiento de:', 'El Fiscal General del Estado',
 ['El juzgado de guardia', 'El Ministro de Justicia', 'La Policía Judicial'], 'lo pondrá de inmediato en conocimiento del Fiscal General del Estado'),
('I', T, 'aveintiocho', 'Respecto de los actos y resoluciones de la Administración, el Defensor del Pueblo:', 'No es competente para modificarlos o anularlos, aunque puede sugerir la modificación de los criterios utilizados',
 ['Puede anularlos si son ilegales', 'Puede suspender su ejecución', 'Puede modificarlos con autorización de las Cortes'],
 'aun no siendo competente para modificar o anular los actos y resoluciones de la Administración Pública'),
('I', T, 'aveintinueve', 'El Defensor del Pueblo está legitimado para interponer:', 'Los recursos de inconstitucionalidad y de amparo',
 ['Solo el recurso de amparo', 'Los recursos contencioso-administrativos en nombre de los ciudadanos', 'La cuestión de inconstitucionalidad'],
 'está legitimado para interponer los recursos de inconstitucionalidad y de amparo'),
('I', P, 'atreinta', 'Plazo máximo para que las autoridades y funcionarios respondan por escrito a las advertencias, recomendaciones o sugerencias del Defensor del Pueblo', '1 mes',
 ['15 días', '2 meses', '10 días'], 'vendrán obligados a responder por escrito en término no superior al de un mes'),
('I', T, 'atreintaydos', 'El Defensor del Pueblo da cuenta de su gestión a las Cortes Generales mediante un informe con periodicidad:', 'Anual',
 ['Semestral', 'Trimestral', 'Bienal'], 'El Defensor del Pueblo dará cuenta anualmente a las Cortes Generales de la gestión realizada'),
('I', T, 'atreintaytres', 'En el informe anual del Defensor del Pueblo:', 'No constarán datos personales que permitan la pública identificación de los interesados',
 ['Figuran los nombres de todos los reclamantes', 'Se incluyen las quejas anónimas', 'No se da cuenta de las quejas rechazadas'],
 'En el informe no constarán datos personales que permitan la pública identificación de los interesados'),
('I', T, 'atreintaysiete', 'La dotación económica para el funcionamiento del Defensor del Pueblo constituye una partida dentro de:', 'Los Presupuestos de las Cortes Generales',
 ['El presupuesto del Ministerio de Justicia', 'El presupuesto de la Presidencia del Gobierno', 'El presupuesto del Tribunal Constitucional'],
 'constituirá una partida dentro de los Presupuestos de las Cortes Generales'),
]
