# Lote 2 · Constitución Española (CE), 1.ª parte: Título preliminar a Título III (arts. 1-96) · bloque I
# Formato: (bloque, tipo, artículo, pregunta, respuesta correcta, [3 distractores], ancla de la cita en el texto del BOE)
NORMA, LOTE, INICIO = 'CE', 'lote-002', 2001
PREGUNTAS = [
# ---- Título preliminar ----
('I', 'test', 'a1', 'Según el artículo 1.1, ¿qué valores superiores de su ordenamiento jurídico propugna España?',
 'La libertad, la justicia, la igualdad y el pluralismo político',
 ['La libertad, la seguridad, la igualdad y la solidaridad', 'La dignidad, la justicia, la igualdad y la legalidad', 'La libertad, la justicia, la solidaridad y la seguridad jurídica'],
 'la libertad, la justicia, la igualdad y el pluralismo político'),
('I', 'test', 'a1', '¿En quién reside la soberanía nacional?', 'En el pueblo español',
 ['En las Cortes Generales', 'En el Rey', 'En el Gobierno'], 'La soberanía nacional reside en el pueblo español'),
('I', 'test', 'a1', '¿Cuál es la forma política del Estado español?', 'La Monarquía parlamentaria',
 ['La Monarquía constitucional', 'La Monarquía hereditaria', 'La Monarquía democrática'], 'La forma política del Estado español es la Monarquía parlamentaria'),
('I', 'test', 'a2', 'Según el artículo 2, ¿en qué se fundamenta la Constitución?', 'En la indisoluble unidad de la Nación española',
 ['En el derecho a la autonomía de las nacionalidades y regiones', 'En la solidaridad entre las Comunidades Autónomas', 'En el pluralismo político'],
 'La Constitución se fundamenta en la indisoluble unidad de la Nación española'),
('I', 'test', 'a3', 'Respecto del castellano, lengua española oficial del Estado, todos los españoles tienen:', 'El deber de conocerla y el derecho a usarla',
 ['El derecho a conocerla y el deber de usarla', 'El deber de conocerla y de usarla', 'El derecho a conocerla y a usarla, sin deber alguno'],
 'Todos los españoles tienen el deber de conocerla y el derecho a usarla'),
('I', 'test', 'a3', 'Según el artículo 3.2, las demás lenguas españolas serán también oficiales:', 'En las respectivas Comunidades Autónomas de acuerdo con sus Estatutos',
 ['En todo el territorio nacional, junto al castellano', 'En las Comunidades Autónomas que lo acuerden por ley orgánica', 'Solo en el ámbito de la Administración local'],
 'Las demás lenguas españolas serán también oficiales en las respectivas Comunidades Autónomas de acuerdo con sus Estatutos'),
('I', 'test', 'a4', '¿Qué anchura tiene la franja amarilla de la bandera de España respecto de cada una de las rojas?', 'Doble anchura',
 ['La misma anchura', 'Triple anchura', 'La mitad de anchura'], 'siendo la amarilla de doble anchura que cada una de las rojas'),
('I', 'test', 'a6', 'Según el artículo 6, los partidos políticos expresan:', 'El pluralismo político',
 ['La soberanía nacional', 'La voluntad general de la Nación', 'Los intereses económicos y sociales que les son propios'], 'Los partidos políticos expresan el pluralismo político'),
('I', 'test', 'a7', 'Según el artículo 7, los sindicatos de trabajadores y las asociaciones empresariales contribuyen a la defensa y promoción de:',
 'Los intereses económicos y sociales que les son propios',
 ['El pluralismo político', 'La participación política de los ciudadanos', 'La formación y manifestación de la voluntad popular'],
 'contribuyen a la defensa y promoción de los intereses económicos y sociales que les son propios'),
('I', 'test', 'a8', 'Según el artículo 8.1, las Fuerzas Armadas están constituidas por:', 'El Ejército de Tierra, la Armada y el Ejército del Aire',
 ['El Ejército de Tierra, la Armada, el Ejército del Aire y la Guardia Civil', 'El Ejército de Tierra y la Armada', 'El Ejército de Tierra, la Armada y la Guardia Real'],
 'constituidas por el Ejército de Tierra, la Armada y el Ejército del Aire'),
('I', 'test', 'a8', '¿Qué tipo de norma regulará las bases de la organización militar?', 'Una ley orgánica',
 ['Una ley ordinaria', 'Un real decreto', 'Un decreto legislativo'], 'Una ley orgánica regulará las bases de la organización militar'),
('I', 'test', 'a9', 'Según el artículo 9.2, ¿a quién corresponde promover las condiciones para que la libertad y la igualdad del individuo y de los grupos sean reales y efectivas?',
 'A los poderes públicos', ['Al Gobierno', 'A las Cortes Generales', 'Al Defensor del Pueblo'],
 'Corresponde a los poderes públicos promover las condiciones para que la libertad y la igualdad del individuo y de los grupos en que se integra sean reales y efectivas'),
('I', 'test', 'a9', 'El artículo 9.3 garantiza la irretroactividad de:', 'Las disposiciones sancionadoras no favorables o restrictivas de derechos individuales',
 ['Todas las disposiciones normativas', 'Las leyes y los reglamentos, sin excepción', 'Las disposiciones favorables a los derechos individuales'],
 'la irretroactividad de las disposiciones sancionadoras no favorables o restrictivas de derechos individuales'),
# ---- Título I ----
('I', 'test', 'a10', 'Según el artículo 10.2, las normas relativas a los derechos fundamentales y a las libertades que la Constitución reconoce se interpretarán de conformidad con:',
 'La Declaración Universal de Derechos Humanos y los tratados y acuerdos internacionales sobre las mismas materias ratificados por España',
 ['La jurisprudencia del Tribunal Supremo y del Tribunal Constitucional', 'La Carta de las Naciones Unidas exclusivamente', 'Las leyes orgánicas que los desarrollen exclusivamente'],
 'se interpretarán de conformidad con la Declaración Universal de Derechos Humanos'),
('I', 'test', 'a10', 'Según el artículo 10.1, la dignidad de la persona, los derechos inviolables que le son inherentes, el libre desarrollo de la personalidad y el respeto a la ley y a los derechos de los demás son:',
 'Fundamento del orden político y de la paz social',
 ['Valores superiores del ordenamiento jurídico', 'Principios rectores de la política social y económica', 'Límites al ejercicio de los derechos fundamentales'],
 'son fundamento del orden político y de la paz social'),
('I', 'test', 'a11', 'Según el artículo 11.2, ¿quién no podrá ser privado de su nacionalidad?', 'Ningún español de origen',
 ['Ningún español residente en España', 'Ningún español mayor de edad', 'Ningún español, cualquiera que sea el modo en que adquirió la nacionalidad'],
 'Ningún español de origen podrá ser privado de su nacionalidad'),
('I', 'test', 'a11', '¿Con qué países podrá el Estado concertar tratados de doble nacionalidad?',
 'Con los países iberoamericanos o con aquellos que hayan tenido o tengan una particular vinculación con España',
 ['Solo con los Estados miembros de la Unión Europea', 'Solo con los países iberoamericanos', 'Con cualquier país, siempre que exista reciprocidad'],
 'concertar tratados de doble nacionalidad con los países iberoamericanos'),
('I', 'test', 'a12', '¿A qué edad son mayores de edad los españoles?', 'A los dieciocho años',
 ['A los dieciséis años', 'A los veintiún años', 'A los diecisiete años'], 'Los españoles son mayores de edad a los dieciocho años'),
('I', 'test', 'a13', '¿Qué derechos del artículo 23 podrán establecerse para los extranjeros por tratado o ley, atendiendo a criterios de reciprocidad?',
 'El derecho de sufragio activo y pasivo en las elecciones municipales',
 ['El derecho de sufragio activo y pasivo en las elecciones generales', 'Solo el derecho de sufragio activo en las elecciones municipales', 'El derecho de sufragio activo en las elecciones autonómicas y municipales'],
 'sufragio activo y pasivo en las elecciones municipales'),
('I', 'test', 'a13', 'En materia de extradición, el artículo 13.3 establece que:', 'Quedan excluidos los delitos políticos, no considerándose como tales los actos de terrorismo',
 ['Quedan excluidos los delitos políticos, incluidos los actos de terrorismo', 'Solo se concederá respecto de nacionales de la Unión Europea', 'Se concederá aunque no exista tratado ni ley que la prevea'],
 'Quedan excluidos de la extradición los delitos políticos, no considerándose como tales los actos de terrorismo'),
('I', 'test', 'a14', '¿Cuál de las siguientes circunstancias NO se menciona expresamente en el artículo 14 como causa de discriminación?', 'La edad',
 ['El nacimiento', 'La raza', 'La opinión'],
 'por razón de nacimiento, raza, sexo, religión, opinión o cualquier otra condición o circunstancia personal o social'),
('I', 'test', 'a15', 'Según el artículo 15, queda abolida la pena de muerte, salvo:', 'Lo que puedan disponer las leyes penales militares para tiempos de guerra',
 ['Para los delitos de terrorismo', 'Lo que dispongan los tratados internacionales ratificados por España', 'Durante la vigencia del estado de sitio'],
 'Queda abolida la pena de muerte, salvo lo que puedan disponer las leyes penales militares para tiempos de guerra'),
('I', 'test', 'a16', '¿Qué establece el artículo 16.3 sobre las confesiones religiosas?', 'Ninguna confesión tendrá carácter estatal',
 ['La religión católica es la oficial del Estado', 'Las confesiones deberán inscribirse para ser reconocidas por el Estado', 'Los poderes públicos no mantendrán relaciones con ninguna confesión'],
 'Ninguna confesión tendrá carácter estatal'),
('I', 'plazo', 'a17', 'Duración máxima de la detención preventiva, tras la cual el detenido debe ser puesto en libertad o a disposición de la autoridad judicial',
 '72 horas', ['24 horas', '48 horas', '96 horas'], 'en el plazo máximo de setenta y dos horas'),
('I', 'test', 'a17', 'El procedimiento de «habeas corpus» que regulará la ley tiene por objeto:', 'Producir la inmediata puesta a disposición judicial de toda persona detenida ilegalmente',
 ['Fijar el plazo máximo de duración de la prisión provisional', 'Garantizar la asistencia de abogado en las diligencias policiales', 'Recurrir en amparo ante el Tribunal Constitucional'],
 'para producir la inmediata puesta a disposición judicial de toda persona detenida ilegalmente'),
('I', 'test', 'a18', 'Según el artículo 18.2, ¿en qué caso puede hacerse una entrada o registro en un domicilio sin consentimiento del titular ni resolución judicial?',
 'En caso de flagrante delito', ['Por orden de la autoridad gubernativa', 'En caso de alteración grave del orden público', 'Por orden del Ministerio Fiscal'],
 'sin consentimiento del titular o resolución judicial, salvo en caso de flagrante delito'),
('I', 'test', 'a18', 'Se garantiza el secreto de las comunicaciones y, en especial, de las postales, telegráficas y telefónicas, salvo:', 'Resolución judicial',
 ['Autorización del Ministerio del Interior', 'Orden del Ministerio Fiscal', 'Acuerdo del Consejo de Ministros'],
 'en especial, de las postales, telegráficas y telefónicas, salvo resolución judicial'),
('I', 'test', 'a20', 'Según el artículo 20.5, el secuestro de publicaciones, grabaciones y otros medios de información sólo podrá acordarse:', 'En virtud de resolución judicial',
 ['Por acuerdo del Consejo de Ministros', 'Por resolución administrativa motivada', 'Por decreto del Ministerio Fiscal'],
 'Sólo podrá acordarse el secuestro de publicaciones, grabaciones y otros medios de información en virtud de resolución judicial'),
('I', 'test', 'a21', 'El ejercicio del derecho de reunión pacífica y sin armas:', 'No necesitará autorización previa',
 ['Requerirá autorización previa de la autoridad gubernativa', 'Requerirá autorización judicial previa', 'Requerirá inscripción previa en un registro'],
 'El ejercicio de este derecho no necesitará autorización previa'),
('I', 'test', 'a21', 'En los casos de reuniones en lugares de tránsito público y manifestaciones, se dará a la autoridad:', 'Comunicación previa',
 ['Solicitud de autorización previa', 'Comunicación posterior a su celebración', 'Solicitud de licencia municipal'],
 'en lugares de tránsito público y manifestaciones se dará comunicación previa a la autoridad'),
('I', 'test', 'a22', 'Las asociaciones constituidas al amparo del artículo 22 deberán inscribirse en un registro:', 'A los solos efectos de publicidad',
 ['Para adquirir personalidad jurídica', 'Como requisito de validez de su constitución', 'Para poder recibir subvenciones públicas'],
 'deberán inscribirse en un registro a los solos efectos de publicidad'),
('I', 'test', 'a22', 'Las asociaciones sólo podrán ser disueltas o suspendidas en sus actividades:', 'En virtud de resolución judicial motivada',
 ['Por resolución motivada del Ministerio del Interior', 'Por acuerdo del Consejo de Ministros', 'Por resolución administrativa, previa audiencia'],
 'sólo podrán ser disueltas o suspendidas en sus actividades en virtud de resolución judicial motivada'),
('I', 'test', 'a22', '¿Qué asociaciones prohíbe expresamente el artículo 22.5?', 'Las secretas y las de carácter paramilitar',
 ['Las secretas y las de carácter político', 'Las de carácter religioso y las paramilitares', 'Las que no se inscriban en el registro'],
 'Se prohíben las asociaciones secretas y las de carácter paramilitar'),
('I', 'test', 'a23', 'Según el artículo 23.2, los ciudadanos tienen derecho a acceder en condiciones de igualdad a:',
 'Las funciones y cargos públicos, con los requisitos que señalen las leyes',
 ['Los archivos y registros administrativos', 'Los medios de comunicación social dependientes del Estado', 'La enseñanza universitaria'],
 'tienen derecho a acceder en condiciones de igualdad a las funciones y cargos públicos'),
('I', 'test', 'a24', 'Según el artículo 24.2, la ley regulará los casos en que no se estará obligado a declarar sobre hechos presuntamente delictivos por razón de:',
 'Parentesco o secreto profesional', ['Parentesco o amistad íntima', 'Secreto profesional o interés legítimo', 'Edad o enfermedad'],
 'por razón de parentesco o de secreto profesional, no se estará obligado a declarar'),
('I', 'test', 'a25', 'Según el artículo 25.3, la Administración civil no podrá imponer sanciones que:', 'Directa o subsidiariamente, impliquen privación de libertad',
 ['Tengan carácter pecuniario', 'Superen la cuantía máxima fijada por el Gobierno', 'Impliquen la inhabilitación para el ejercicio de actividades'],
 'La Administración civil no podrá imponer sanciones que, directa o subsidiariamente, impliquen privación de libertad'),
('I', 'test', 'a25', 'Según el artículo 25.2, las penas privativas de libertad y las medidas de seguridad estarán orientadas hacia:', 'La reeducación y reinserción social',
 ['La prevención general y especial', 'El castigo y la retribución', 'La reparación del daño a la víctima'],
 'estarán orientadas hacia la reeducación y reinserción social'),
('I', 'test', 'a26', '¿Qué prohíbe el artículo 26 en el ámbito de la Administración civil y de las organizaciones profesionales?', 'Los Tribunales de Honor',
 ['Los colegios profesionales de adscripción obligatoria', 'Los jurados populares', 'Las comisiones de investigación'],
 'Se prohíben los Tribunales de Honor en el ámbito de la Administración civil'),
('I', 'test', 'a27', 'Según el artículo 27.4, la enseñanza básica es:', 'Obligatoria y gratuita',
 ['Obligatoria, pero no necesariamente gratuita', 'Gratuita, pero no obligatoria', 'Obligatoria y gratuita solo en los centros públicos'],
 'La enseñanza básica es obligatoria y gratuita'),
('I', 'test', 'a28', 'Según el artículo 28.1, ¿a quiénes podrá la ley limitar o exceptuar el ejercicio del derecho a sindicarse?',
 'A las Fuerzas o Institutos armados o a los demás Cuerpos sometidos a disciplina militar',
 ['A los funcionarios públicos', 'A los trabajadores de los servicios esenciales de la comunidad', 'A los trabajadores extranjeros'],
 'La ley podrá limitar o exceptuar el ejercicio de este derecho a las Fuerzas o Institutos armados'),
('I', 'test', 'a28', 'La ley que regule el ejercicio del derecho de huelga establecerá las garantías precisas para asegurar:', 'El mantenimiento de los servicios esenciales de la comunidad',
 ['El funcionamiento ordinario de las Administraciones públicas', 'La libertad de empresa y la productividad', 'La paz social durante la vigencia de los convenios'],
 'para asegurar el mantenimiento de los servicios esenciales de la comunidad'),
('I', 'test', 'a29', 'Los miembros de las Fuerzas o Institutos armados o de los Cuerpos sometidos a disciplina militar podrán ejercer el derecho de petición:',
 'Sólo individualmente y con arreglo a lo dispuesto en su legislación específica',
 ['Sólo colectivamente, a través de sus mandos', 'Individual y colectivamente, sin limitación alguna', 'En ningún caso'],
 'podrán ejercer este derecho sólo individualmente'),
('I', 'test', 'a30', 'Según el artículo 30.2, al regular la objeción de conciencia, la ley podrá imponer, en su caso:', 'Una prestación social sustitutoria',
 ['Una sanción administrativa', 'Una contribución económica sustitutoria', 'La pérdida de los derechos políticos'],
 'pudiendo imponer, en su caso, una prestación social sustitutoria'),
('I', 'test', 'a31', 'Según el artículo 31.1, el sistema tributario justo se inspira en los principios de:', 'Igualdad y progresividad',
 ['Generalidad y proporcionalidad', 'Eficiencia y economía', 'Suficiencia y neutralidad'],
 'sistema tributario justo inspirado en los principios de igualdad y progresividad'),
('I', 'test', 'a31', 'Según el artículo 31.2, la programación y ejecución del gasto público responderán a los criterios de:', 'Eficiencia y economía',
 ['Igualdad y progresividad', 'Eficacia y jerarquía', 'Estabilidad y sostenibilidad'],
 'su programación y ejecución responderán a los criterios de eficiencia y economía'),
('I', 'test', 'a33', 'Según el artículo 33.3, nadie podrá ser privado de sus bienes y derechos sino por causa justificada de utilidad pública o interés social y:',
 'Mediante la correspondiente indemnización y de conformidad con lo dispuesto por las leyes',
 ['Mediante resolución judicial firme', 'Previa autorización de las Cortes Generales', 'Por acuerdo del Consejo de Ministros, sin indemnización'],
 'mediante la correspondiente indemnización y de conformidad con lo dispuesto por las leyes'),
('I', 'test', 'a35', 'Según el artículo 35.1, el trabajo es para todos los españoles:', 'Un deber y un derecho',
 ['Solo un derecho', 'Solo un deber', 'Un principio rector de la política social y económica'],
 'Todos los españoles tienen el deber de trabajar y el derecho al trabajo'),
('I', 'test', 'a38', 'El artículo 38 reconoce la libertad de empresa en el marco de:', 'La economía de mercado',
 ['La planificación económica general', 'La economía social', 'La iniciativa pública en la actividad económica'],
 'Se reconoce la libertad de empresa en el marco de la economía de mercado'),
('I', 'test', 'a41', 'Según el artículo 41, el régimen público de Seguridad Social garantizará la asistencia y prestaciones sociales suficientes ante situaciones de necesidad, especialmente en caso de:',
 'Desempleo', ['Jubilación', 'Enfermedad', 'Incapacidad permanente'], 'especialmente en caso de desempleo'),
('I', 'test', 'a47', 'Según el artículo 47, la comunidad participará en:', 'Las plusvalías que genere la acción urbanística de los entes públicos',
 ['Los beneficios de las empresas públicas', 'La adjudicación de las viviendas de protección oficial', 'La aprobación de los planes urbanísticos municipales'],
 'La comunidad participará en las plusvalías que genere la acción urbanística de los entes públicos'),
('I', 'test', 'a49', 'Según el artículo 49.2 (en su redacción de 2024), ¿qué necesidades se atenderán particularmente?',
 'Las necesidades específicas de las mujeres y los menores con discapacidad',
 ['Las necesidades específicas de las personas mayores con discapacidad', 'Las necesidades específicas de las personas con discapacidad intelectual', 'Las necesidades específicas de las personas con discapacidad en el medio rural'],
 'Se atenderán particularmente las necesidades específicas de las mujeres y los menores con discapacidad'),
('I', 'test', 'a50', 'Según el artículo 50, ¿cómo garantizarán los poderes públicos la suficiencia económica a los ciudadanos durante la tercera edad?',
 'Mediante pensiones adecuadas y periódicamente actualizadas',
 ['Mediante un sistema de servicios sociales', 'Mediante prestaciones complementarias libres', 'Mediante la obligación de alimentos de sus familiares'],
 'mediante pensiones adecuadas y periódicamente actualizadas, la suficiencia económica'),
('I', 'test', 'a53', 'Según el artículo 53.2, ¿qué derechos pueden tutelarse ante los Tribunales ordinarios por un procedimiento basado en los principios de preferencia y sumariedad?',
 'Los del artículo 14 y la Sección primera del Capítulo segundo del Título I',
 ['Todos los del Título I', 'Todos los del Capítulo segundo del Título I', 'Los del Capítulo tercero del Título I'],
 'reconocidos en el artículo 14 y la Sección primera del Capítulo segundo ante los Tribunales ordinarios por un procedimiento basado en los principios de preferencia y sumariedad'),
('I', 'test', 'a53', 'Según el artículo 53.1, el ejercicio de los derechos y libertades del Capítulo segundo del Título I sólo podrá regularse:',
 'Por ley, que en todo caso deberá respetar su contenido esencial',
 ['Por decreto-ley, en caso de extraordinaria y urgente necesidad', 'Por real decreto, previo dictamen del Consejo de Estado', 'Por ley o por reglamento, indistintamente'],
 'Sólo por ley, que en todo caso deberá respetar su contenido esencial'),
('I', 'test', 'a53', 'Según el artículo 53.3, los principios reconocidos en el Capítulo tercero del Título I:',
 'Sólo podrán ser alegados ante la Jurisdicción ordinaria de acuerdo con lo que dispongan las leyes que los desarrollen',
 ['Pueden ser objeto de recurso de amparo ante el Tribunal Constitucional', 'Se tutelan por un procedimiento basado en los principios de preferencia y sumariedad', 'No pueden ser alegados en ningún caso ante los tribunales'],
 'Sólo podrán ser alegados ante la Jurisdicción ordinaria de acuerdo con lo que dispongan las leyes que los desarrollen'),
('I', 'test', 'a53', 'Además de a los derechos del artículo 14 y de la Sección primera del Capítulo segundo, ¿a qué es aplicable el recurso de amparo según el artículo 53.2?',
 'A la objeción de conciencia reconocida en el artículo 30',
 ['Al derecho de propiedad reconocido en el artículo 33', 'Al derecho al trabajo reconocido en el artículo 35', 'Al derecho a la vivienda reconocido en el artículo 47'],
 'Este último recurso será aplicable a la objeción de conciencia reconocida en el artículo 30'),
('I', 'test', 'a54', 'Según el artículo 54, el Defensor del Pueblo es:', 'Un alto comisionado de las Cortes Generales',
 ['Un órgano consultivo del Gobierno', 'Un alto comisionado del Gobierno', 'Un órgano dependiente del Ministerio de Justicia'],
 'como alto comisionado de las Cortes Generales'),
('I', 'test', 'a55', 'Los derechos enumerados en el artículo 55.1 podrán ser suspendidos cuando se acuerde la declaración del:', 'Estado de excepción o de sitio',
 ['Estado de alarma, de excepción o de sitio', 'Estado de alarma o de excepción', 'Estado de alarma únicamente'],
 'podrán ser suspendidos cuando se acuerde la declaración del estado de excepción o de sitio'),
('I', 'test', 'a55', '¿Qué apartado del artículo 17 se exceptúa de la suspensión en el supuesto de declaración del estado de excepción?', 'El apartado 3',
 ['El apartado 1', 'El apartado 2', 'El apartado 4'],
 'Se exceptúa de lo establecido anteriormente el apartado 3 del artículo 17 para el supuesto de declaración de estado de excepción'),
('I', 'test', 'a55', 'Según el artículo 55.2, ¿qué derechos pueden ser suspendidos para personas determinadas en relación con las investigaciones sobre bandas armadas o elementos terroristas?',
 'Los de los artículos 17.2 y 18.2 y 3', ['Los de los artículos 17.3 y 24.2', 'Los de los artículos 18.1 y 20.1', 'Los de los artículos 19 y 21'],
 'los derechos reconocidos en los artículos 17, apartado 2, y 18, apartados 2 y 3, pueden ser suspendidos para personas determinadas'),
# ---- Título II ----
('I', 'test', 'a56', 'Según el artículo 56.3, los actos del Rey carecen de validez sin refrendo, salvo lo dispuesto en:', 'El artículo 65.2',
 ['El artículo 62', 'El artículo 63', 'El artículo 99'], 'careciendo de validez sin dicho refrendo, salvo lo dispuesto en el artículo 65, 2'),
('I', 'test', 'a56', 'Según el artículo 56.3, la persona del Rey:', 'Es inviolable y no está sujeta a responsabilidad',
 ['Es inviolable, pero responde ante las Cortes Generales', 'Responde de sus actos ante el Tribunal Supremo', 'Es inviolable solo en el ejercicio de sus funciones'],
 'La persona del Rey es inviolable y no está sujeta a responsabilidad'),
('I', 'test', 'a57', 'En el orden de sucesión a la Corona, en la misma línea y en el mismo grado, se prefiere:', 'El varón a la mujer',
 ['La mujer al varón', 'La persona de menos edad a la de más', 'La persona que designe el Rey'],
 'en el mismo grado, el varón a la mujer, y en el mismo sexo, la persona de más edad a la de menos'),
('I', 'test', 'a57', 'Según el artículo 57.2, el Príncipe heredero tendrá la dignidad de:', 'Príncipe de Asturias',
 ['Príncipe de España', 'Infante de España', 'Príncipe de Castilla'], 'tendrá la dignidad de Príncipe de Asturias'),
('I', 'test', 'a57', '¿Cómo se resolverán las abdicaciones y renuncias y cualquier duda de hecho o de derecho que ocurra en el orden de sucesión a la Corona?', 'Por una ley orgánica',
 ['Por una ley ordinaria', 'Por acuerdo de las Cortes Generales en sesión conjunta', 'Por sentencia del Tribunal Constitucional'], 'se resolverán por una ley orgánica'),
('I', 'test', 'a57', 'Quienes, teniendo derecho a la sucesión en el trono, contrajeren matrimonio contra la expresa prohibición del Rey y de las Cortes Generales:',
 'Quedarán excluidos de la sucesión a la Corona por sí y sus descendientes',
 ['Quedarán excluidos de la sucesión, pero no sus descendientes', 'Perderán la dignidad de Príncipe de Asturias, pero conservarán su derecho', 'Solo quedarán excluidos si así lo declara una ley orgánica'],
 'quedarán excluidas en la sucesión a la Corona por sí y sus descendientes'),
('I', 'test', 'a58', 'Según el artículo 58, la Reina consorte o el consorte de la Reina:', 'No podrán asumir funciones constitucionales, salvo lo dispuesto para la Regencia',
 ['Podrán asumir las funciones constitucionales que el Rey les delegue', 'Ejercerán siempre la Regencia durante la minoría de edad del Rey', 'Podrán presidir el Consejo de Ministros en ausencia del Rey'],
 'no podrán asumir funciones constitucionales, salvo lo dispuesto para la Regencia'),
('I', 'test', 'a59', 'Si no hubiere ninguna persona a quien corresponda la Regencia, ésta será nombrada por las Cortes Generales y se compondrá de:', 'Una, tres o cinco personas',
 ['Una o tres personas', 'Tres personas', 'Dos o cuatro personas'], 'se compondrá de una, tres o cinco personas'),
('I', 'test', 'a59', 'Según el artículo 59.4, para ejercer la Regencia es preciso:', 'Ser español y mayor de edad',
 ['Ser español de origen y mayor de treinta años', 'Ser mayor de edad y miembro de la Familia Real', 'Ser español y haber sido designado en el testamento del Rey difunto'],
 'Para ejercer la Regencia es preciso ser español y mayor de edad'),
('I', 'test', 'a60', 'Según el artículo 60.1, ¿quién será, en primer lugar, tutor del Rey menor?',
 'La persona que en su testamento hubiese nombrado el Rey difunto, siempre que sea mayor de edad y español de nacimiento',
 ['El Presidente del Gobierno', 'La persona que designen las Cortes Generales', 'El Regente, en todo caso'],
 'Será tutor del Rey menor la persona que en su testamento hubiese nombrado el Rey difunto, siempre que sea mayor de edad y español de nacimiento'),
('I', 'test', 'a61', '¿Ante quién presta juramento el Rey al ser proclamado?', 'Ante las Cortes Generales',
 ['Ante el Congreso de los Diputados', 'Ante el Tribunal Constitucional', 'Ante el Consejo de Ministros'], 'El Rey, al ser proclamado ante las Cortes Generales, prestará juramento'),
('I', 'test', 'a62', 'Corresponde al Rey ejercer el derecho de gracia con arreglo a la ley, que no podrá autorizar:', 'Indultos generales',
 ['Indultos particulares', 'Conmutaciones de pena', 'Indultos parciales'], 'Ejercer el derecho de gracia con arreglo a la ley, que no podrá autorizar indultos generales'),
('I', 'test', 'a62', 'Según el artículo 62.g), el Rey preside las sesiones del Consejo de Ministros:', 'Cuando lo estime oportuno, a petición del Presidente del Gobierno',
 ['Siempre que lo estime oportuno, sin necesidad de petición', 'Solo en la primera sesión de cada legislatura', 'Únicamente en tiempo de guerra'],
 'presidir, a estos efectos, las sesiones del Consejo de Ministros, cuando lo estime oportuno, a petición del Presidente del Gobierno'),
('I', 'test', 'a63', 'Al Rey corresponde declarar la guerra y hacer la paz:', 'Previa autorización de las Cortes Generales',
 ['Previa autorización del Congreso de los Diputados', 'A propuesta del Consejo de Seguridad Nacional', 'Previo dictamen del Consejo de Estado'],
 'previa autorización de las Cortes Generales, declarar la guerra y hacer la paz'),
('I', 'test', 'a64', '¿Quién refrenda la propuesta y el nombramiento del Presidente del Gobierno?', 'El Presidente del Congreso',
 ['El Presidente del Gobierno saliente', 'El Presidente del Senado', 'El Ministro de la Presidencia'],
 'La propuesta y el nombramiento del Presidente del Gobierno, y la disolución prevista en el artículo 99, serán refrendados por el Presidente del Congreso'),
('I', 'test', 'a64', 'De los actos del Rey serán responsables:', 'Las personas que los refrenden',
 ['El propio Rey', 'El Gobierno en su conjunto', 'Las Cortes Generales'], 'De los actos del Rey serán responsables las personas que los refrenden'),
# ---- Título III ----
('I', 'test', 'a66', '¿Cuál de las siguientes funciones NO atribuye el artículo 66.2 a las Cortes Generales?', 'Dirigir la política interior y exterior',
 ['Ejercer la potestad legislativa del Estado', 'Aprobar los Presupuestos del Estado', 'Controlar la acción del Gobierno'],
 'Las Cortes Generales ejercen la potestad legislativa del Estado, aprueban sus Presupuestos, controlan la acción del Gobierno'),
('I', 'test', 'a67', 'Según el artículo 67.1, nadie podrá acumular el acta de una Asamblea de Comunidad Autónoma con la de:', 'Diputado al Congreso',
 ['Senador', 'Concejal', 'Diputado provincial'], 'ni acumular el acta de una Asamblea de Comunidad Autónoma con la de Diputado al Congreso'),
('I', 'test', 'a68', 'Según el artículo 68.2, la circunscripción electoral para el Congreso es:', 'La provincia',
 ['La Comunidad Autónoma', 'El municipio', 'La isla'], 'La circunscripción electoral es la provincia'),
('I', 'test', 'a68', '¿Por cuántos Diputados estará representada cada una de las poblaciones de Ceuta y Melilla?', 'Uno',
 ['Dos', 'Tres', 'Cuatro'], 'Las poblaciones de Ceuta y Melilla estarán representadas cada una de ellas por un Diputado'),
('I', 'test', 'a68', 'Según el artículo 68.3, ¿con qué criterios se verificará la elección del Congreso en cada circunscripción?', 'De representación proporcional',
 ['Mayoritarios', 'De representación territorial igualitaria', 'Mixtos, mayoritarios y proporcionales'], 'atendiendo a criterios de representación proporcional'),
('I', 'test', 'a69', '¿Cuántos Senadores se elegirán en cada provincia según el artículo 69.2?', 'Cuatro',
 ['Tres', 'Dos', 'Cinco'], 'En cada provincia se elegirán cuatro Senadores'),
('I', 'test', 'a69', '¿Cuántos Senadores elegirá cada una de las poblaciones de Ceuta y Melilla?', 'Dos',
 ['Uno', 'Tres', 'Cuatro'], 'Las poblaciones de Ceuta y Melilla elegirán cada una de ellas dos Senadores'),
('I', 'test', 'a69', 'Según el artículo 69.3, ¿cuántos Senadores corresponden a cada una de las islas mayores (Gran Canaria, Mallorca y Tenerife)?', 'Tres',
 ['Cuatro', 'Dos', 'Uno'], 'correspondiendo tres a cada una de las islas mayores'),
('I', 'test', 'a69', 'Además de los Senadores elegidos en las provincias, las islas, Ceuta y Melilla, las Comunidades Autónomas designarán:',
 'Un Senador y otro más por cada millón de habitantes de su respectivo territorio',
 ['Dos Senadores y otro más por cada millón de habitantes', 'Un Senador por cada quinientos mil habitantes', 'Un Senador por cada provincia de su territorio'],
 'Las Comunidades Autónomas designarán además un Senador y otro más por cada millón de habitantes'),
('I', 'plazo', 'a69', 'Duración del mandato del Senado', '4 años', ['3 años', '5 años', '6 años'], 'El Senado es elegido por cuatro años'),
('I', 'test', 'a70', '¿Cuál de los siguientes NO está comprendido expresamente en el artículo 70.1 entre las causas de inelegibilidad e incompatibilidad de Diputados y Senadores?',
 'Los miembros del Gobierno', ['Los componentes del Tribunal Constitucional', 'El Defensor del Pueblo', 'Los miembros de las Juntas Electorales'],
 'con la excepción de los miembros del Gobierno'),
('I', 'test', 'a71', '¿Qué órgano es competente en las causas contra Diputados y Senadores?', 'La Sala de lo Penal del Tribunal Supremo',
 ['La Sala de lo Penal de la Audiencia Nacional', 'El Tribunal Constitucional', 'El Tribunal Superior de Justicia de su circunscripción'],
 'En las causas contra Diputados y Senadores será competente la Sala de lo Penal del Tribunal Supremo'),
('I', 'test', 'a71', 'Durante el período de su mandato, los Diputados y Senadores sólo podrán ser detenidos:', 'En caso de flagrante delito',
 ['Previa autorización del Tribunal Supremo', 'Previa autorización del Presidente de su Cámara', 'Fuera del período de sesiones'],
 'sólo podrán ser detenidos en caso de flagrante delito'),
('I', 'test', 'a71', 'Los Diputados y Senadores no podrán ser inculpados ni procesados sin:', 'La previa autorización de la Cámara respectiva',
 ['La previa autorización del Consejo General del Poder Judicial', 'La previa autorización de ambas Cámaras en sesión conjunta', 'La previa autorización de la Mesa del Congreso'],
 'No podrán ser inculpados ni procesados sin la previa autorización de la Cámara respectiva'),
('I', 'test', 'a72', 'Los Reglamentos de las Cámaras y su reforma serán sometidos a una votación final sobre su totalidad, que requerirá:', 'La mayoría absoluta',
 ['La mayoría simple', 'La mayoría de tres quintos', 'La mayoría de dos tercios'],
 'Los Reglamentos y su reforma serán sometidos a una votación final sobre su totalidad, que requerirá la mayoría absoluta'),
('I', 'test', 'a72', '¿Quién preside las sesiones conjuntas de las Cámaras?', 'El Presidente del Congreso',
 ['El Presidente del Senado', 'El Rey', 'El Presidente del Congreso y el del Senado, alternativamente'], 'Las sesiones conjuntas serán presididas por el Presidente del Congreso'),
('I', 'test', 'a73', '¿Cuáles son los períodos ordinarios de sesiones de las Cámaras?', 'De septiembre a diciembre y de febrero a junio',
 ['De septiembre a diciembre y de enero a junio', 'De octubre a diciembre y de febrero a junio', 'De septiembre a enero y de marzo a julio'],
 'el primero, de septiembre a diciembre, y el segundo, de febrero a junio'),
('I', 'test', 'a73', '¿Quién puede pedir que las Cámaras se reúnan en sesiones extraordinarias?',
 'El Gobierno, la Diputación Permanente o la mayoría absoluta de los miembros de cualquiera de las Cámaras',
 ['Solo el Gobierno', 'El Rey, el Gobierno o la quinta parte de los miembros de cualquiera de las Cámaras', 'El Gobierno o la décima parte de los Diputados'],
 'a petición del Gobierno, de la Diputación Permanente o de la mayoría absoluta de los miembros de cualquiera de las Cámaras'),
('I', 'test', 'a74', 'En las decisiones de las Cortes Generales previstas en los artículos 94.1, 145.2 y 158.2, si el texto de la Comisión Mixta no se aprueba en la forma establecida:',
 'Decidirá el Congreso por mayoría absoluta',
 ['Decidirá el Senado por mayoría absoluta', 'Se someterá a referéndum consultivo', 'Decidirán ambas Cámaras en sesión conjunta por mayoría simple'],
 'Si no se aprueba en la forma establecida, decidirá el Congreso por mayoría absoluta'),
('I', 'test', 'a75', 'Según el artículo 75.3, ¿cuál de las siguientes materias queda exceptuada de la delegación en las Comisiones Legislativas Permanentes?', 'Las leyes de bases',
 ['Las proposiciones de ley de iniciativa popular', 'Las proposiciones de ley tomadas en consideración por el Senado', 'Los proyectos de ley declarados urgentes'],
 'la reforma constitucional, las cuestiones internacionales, las leyes orgánicas y de bases y los Presupuestos Generales del Estado'),
('I', 'test', 'a76', 'Las conclusiones de las Comisiones de investigación:', 'No serán vinculantes para los Tribunales, ni afectarán a las resoluciones judiciales',
 ['Serán vinculantes para los Tribunales', 'Tendrán valor de prueba plena en el proceso penal', 'Serán vinculantes una vez aprobadas por el Pleno'],
 'Sus conclusiones no serán vinculantes para los Tribunales, ni afectarán a las resoluciones judiciales'),
('I', 'test', 'a77', 'Las Cámaras pueden recibir peticiones individuales y colectivas, siempre por escrito, quedando prohibida:', 'La presentación directa por manifestaciones ciudadanas',
 ['La presentación por medios electrónicos', 'La presentación por asociaciones', 'La presentación de peticiones colectivas'],
 'quedando prohibida la presentación directa por manifestaciones ciudadanas'),
('I', 'test', 'a78', '¿De cuántos miembros, como mínimo, se compone la Diputación Permanente de cada Cámara?', 'Veintiuno',
 ['Quince', 'Veinticinco', 'Treinta'], 'una Diputación Permanente compuesta por un mínimo de veintiún miembros'),
('I', 'test', 'a78', '¿Quién preside las Diputaciones Permanentes?', 'El Presidente de la Cámara respectiva',
 ['El Vicepresidente primero de la Cámara respectiva', 'El Presidente del Congreso, en ambas Cámaras', 'El miembro de mayor edad de la Diputación'],
 'Las Diputaciones Permanentes estarán presididas por el Presidente de la Cámara respectiva'),
('I', 'test', 'a79', 'Para adoptar acuerdos, las Cámaras deben estar reunidas reglamentariamente y con asistencia de:', 'La mayoría de sus miembros',
 ['Dos tercios de sus miembros', 'Un tercio de sus miembros', 'Tres quintos de sus miembros'], 'con asistencia de la mayoría de sus miembros'),
('I', 'test', 'a79', 'Según el artículo 79.3, el voto de Senadores y Diputados es:', 'Personal e indelegable',
 ['Personal, pero delegable en otro miembro de su grupo', 'Delegable en el portavoz de su grupo parlamentario', 'Secreto en todo caso'],
 'El voto de Senadores y Diputados es personal e indelegable'),
('I', 'test', 'a80', 'Las sesiones plenarias de las Cámaras serán públicas, salvo acuerdo en contrario de cada Cámara, adoptado por:', 'Mayoría absoluta o con arreglo al Reglamento',
 ['Mayoría simple', 'Mayoría de tres quintos', 'Mayoría de dos tercios'],
 'salvo acuerdo en contrario de cada Cámara, adoptado por mayoría absoluta o con arreglo al Reglamento'),
('I', 'test', 'a81', '¿Cuál de las siguientes materias es propia de ley orgánica según el artículo 81.1?', 'El régimen electoral general',
 ['Los Presupuestos Generales del Estado', 'El estatuto de los trabajadores', 'El régimen jurídico de los Colegios Profesionales'],
 'las que aprueben los Estatutos de Autonomía y el régimen electoral general'),
('I', 'test', 'a82', 'La delegación legislativa deberá otorgarse mediante una ley de bases cuando su objeto sea:', 'La formación de textos articulados',
 ['Refundir varios textos legales en uno solo', 'Aprobar una ley orgánica', 'Regular los Presupuestos Generales del Estado'],
 'mediante una ley de bases cuando su objeto sea la formación de textos articulados'),
('I', 'test', 'a82', 'La delegación legislativa para refundir varios textos legales en uno solo deberá otorgarse mediante:', 'Una ley ordinaria',
 ['Una ley de bases', 'Una ley orgánica', 'Un decreto legislativo'], 'por una ley ordinaria cuando se trate de refundir varios textos legales en uno solo'),
('I', 'test', 'a82', 'Según el artículo 82.3, la delegación legislativa se agota:', 'Por el uso que de ella haga el Gobierno mediante la publicación de la norma correspondiente',
 ['Por la convalidación del Congreso de los Diputados', 'Por el transcurso de un año desde su otorgamiento', 'Por el dictamen favorable del Consejo de Estado'],
 'La delegación se agota por el uso que de ella haga el Gobierno mediante la publicación de la norma correspondiente'),
('I', 'test', 'a83', 'Según el artículo 83, las leyes de bases no podrán en ningún caso:', 'Facultar para dictar normas con carácter retroactivo',
 ['Fijar el plazo para el ejercicio de la delegación', 'Delimitar el objeto y alcance de la delegación legislativa', 'Establecer los principios y criterios que han de seguirse en su ejercicio'],
 'Facultar para dictar normas con carácter retroactivo'),
('I', 'test', 'a85', 'Las disposiciones del Gobierno que contengan legislación delegada recibirán el título de:', 'Decretos Legislativos',
 ['Decretos-leyes', 'Reales Decretos', 'Leyes de bases'], 'recibirán el título de Decretos Legislativos'),
('I', 'test', 'a86', 'Según el artículo 86.1, el Gobierno podrá dictar Decretos-leyes:', 'En caso de extraordinaria y urgente necesidad',
 ['Previa autorización del Congreso de los Diputados', 'En caso de grave riesgo, catástrofe o calamidad pública', 'Solo cuando las Cortes Generales estén disueltas'],
 'En caso de extraordinaria y urgente necesidad, el Gobierno podrá dictar disposiciones legislativas provisionales que tomarán la forma de Decretos-leyes'),
('I', 'test', 'a86', '¿Cuál de las siguientes materias figura en el artículo 86.1 entre las que no pueden ser afectadas por los Decretos-leyes?', 'El Derecho electoral general',
 ['Las ayudas a los afectados por catástrofes naturales', 'Las medidas urgentes de apoyo a la actividad empresarial', 'La concesión de créditos extraordinarios'],
 'al régimen de las Comunidades Autónomas ni al Derecho electoral general'),
('I', 'test', 'a87', 'Según el artículo 87.3, la iniciativa popular para la presentación de proposiciones de ley exige no menos de:', '500.000 firmas acreditadas',
 ['250.000 firmas acreditadas', '750.000 firmas acreditadas', '1.000.000 de firmas acreditadas'], 'En todo caso se exigirán no menos de 500.000 firmas acreditadas'),
('I', 'test', 'a87', '¿Cuál de las siguientes materias está excluida de la iniciativa legislativa popular según el artículo 87.3?', 'La prerrogativa de gracia',
 ['La defensa de los consumidores y usuarios', 'La protección del medio ambiente', 'El acceso a la vivienda'],
 'No procederá dicha iniciativa en materias propias de ley orgánica, tributarias o de carácter internacional, ni en lo relativo a la prerrogativa de gracia'),
('I', 'test', 'a87', 'Al remitir a la Mesa del Congreso una proposición de ley, las Asambleas de las Comunidades Autónomas delegan ante dicha Cámara:',
 'Un máximo de tres miembros de la Asamblea encargados de su defensa',
 ['Un máximo de cinco miembros de la Asamblea', 'Un único miembro de la Asamblea', 'Un máximo de dos miembros de la Asamblea'],
 'delegando ante dicha Cámara un máximo de tres miembros de la Asamblea encargados de su defensa'),
('I', 'plazo', 'a90', 'Veto o enmiendas del Senado a los proyectos declarados urgentes por el Gobierno o por el Congreso de los Diputados', '20 días naturales',
 ['10 días naturales', '15 días naturales', '30 días naturales'], 'se reducirá al de veinte días naturales en los proyectos declarados urgentes'),
('I', 'test', 'a90', 'El veto del Senado a un proyecto de ley deberá ser aprobado por:', 'Mayoría absoluta',
 ['Mayoría simple', 'Mayoría de tres quintos', 'Mayoría de dos tercios'], 'El veto deberá ser aprobado por mayoría absoluta'),
('I', 'plazo', 'a90', 'Ratificación por mayoría simple, por el Congreso, del texto inicial vetado por el Senado (desde la interposición del veto)', '2 meses',
 ['1 mes', '3 meses', '6 meses'], 'o por mayoría simple, una vez transcurridos dos meses desde la interposición del mismo'),
('I', 'test', 'a92', 'El referéndum consultivo será convocado por el Rey, mediante propuesta del Presidente del Gobierno, previamente autorizada por:', 'El Congreso de los Diputados',
 ['Las Cortes Generales', 'El Senado', 'El Consejo de Ministros'], 'previamente autorizada por el Congreso de los Diputados'),
('I', 'test', 'a93', '¿Mediante qué norma se podrá autorizar la celebración de tratados por los que se atribuya a una organización o institución internacional el ejercicio de competencias derivadas de la Constitución?',
 'Ley orgánica', ['Ley ordinaria', 'Acuerdo del Consejo de Ministros', 'Real decreto'], 'Mediante ley orgánica se podrá autorizar la celebración de tratados'),
('I', 'test', 'a94', 'Según el artículo 94.2, de la conclusión de los tratados o convenios no incluidos en el apartado 1:', 'El Congreso y el Senado serán inmediatamente informados',
 ['Se requiere la previa autorización del Congreso por mayoría simple', 'Se requiere dictamen previo del Tribunal Constitucional', 'Se informará únicamente al Consejo de Estado'],
 'El Congreso y el Senado serán inmediatamente informados de la conclusión de los restantes tratados o convenios'),
('I', 'test', 'a95', 'La celebración de un tratado internacional que contenga estipulaciones contrarias a la Constitución exigirá:', 'La previa revisión constitucional',
 ['La autorización de las Cortes Generales por mayoría absoluta', 'Su aprobación mediante ley orgánica', 'El dictamen favorable del Consejo de Estado'],
 'exigirá la previa revisión constitucional'),
('I', 'test', 'a95', '¿Quién puede requerir al Tribunal Constitucional para que declare si existe contradicción entre un tratado internacional y la Constitución?', 'El Gobierno o cualquiera de las Cámaras',
 ['El Defensor del Pueblo o 50 Diputados', 'Solo el Gobierno', 'El Consejo de Estado'], 'El Gobierno o cualquiera de las Cámaras puede requerir al Tribunal Constitucional'),
('I', 'test', 'a96', 'Los tratados internacionales válidamente celebrados formarán parte del ordenamiento interno:', 'Una vez publicados oficialmente en España',
 ['Desde su firma por el Rey', 'Desde su autorización por las Cortes Generales', 'Desde que se apruebe la ley orgánica que los desarrolle'],
 'una vez publicados oficialmente en España, formarán parte del ordenamiento interno'),
]
