# Lote 30 · RDLeg 8/2015, texto refundido de la Ley General de la Seguridad Social · bloque IV (tema IV.9:
# régimen de la Seguridad Social del personal laboral; afiliación, cotización y acción protectora). Se evita
# la edad de jubilación del art. 205.1.a), que aún se aplica de forma gradual (disposición transitoria).
NORMA, LOTE, INICIO = 'LGSS', 'lote-030', 30001
T, P = 'test', 'plazo'
PREGUNTAS = [
('IV', T, 'a2', 'Según la LGSS, el sistema de la Seguridad Social se fundamenta en los principios de:', 'Universalidad, unidad, solidaridad e igualdad',
 ['Contributividad, capitalización y libertad', 'Descentralización, desconcentración y coordinación', 'Mérito, capacidad y publicidad'],
 'se fundamenta en los principios de universalidad, unidad, solidaridad e igualdad'),
('IV', T, 'a3', 'Todo pacto, individual o colectivo, por el cual el trabajador renuncie a los derechos que le confiere la LGSS es:', 'Nulo',
 ['Válido si es colectivo', 'Anulable a instancia del trabajador', 'Válido si lo autoriza la Inspección de Trabajo'],
 'Será nulo todo pacto, individual o colectivo, por el cual el trabajador renuncie a los derechos que le confiere la presente ley'),
('IV', T, 'a9', 'Según la LGSS, el sistema de la Seguridad Social está integrado por:', 'El Régimen General y los regímenes especiales',
 ['Solo el Régimen General', 'El Régimen General y los seguros privados', 'Los regímenes autonómicos y el estatal'],
 r're:El sistema de la Seguridad Social viene integrado por los siguientes regímenes: a\) El Régimen General.*?b\) Los regímenes especiales'),
('IV', T, 'a10', '¿Cuál de los siguientes grupos encuadra la LGSS en un régimen especial?', 'Funcionarios públicos, civiles y militares',
 ['Trabajadores por cuenta ajena de la industria', 'Personal laboral de la Administración General del Estado', 'Trabajadores de comercio'],
 'c) Funcionarios públicos, civiles y militares'),
('IV', T, 'a15', 'La afiliación a la Seguridad Social es:', 'Obligatoria y única para toda la vida de la persona y para todo el sistema',
 ['Voluntaria y renovable cada año', 'Obligatoria y distinta para cada régimen', 'Obligatoria solo para trabajadores por cuenta ajena y renovable en cada empleo'],
 'es obligatoria para las personas a que se refiere el artículo 7.1 y única para toda su vida y para todo el sistema'),
('IV', T, 'a16', 'Si las personas o entidades obligadas no solicitan la afiliación o el alta del trabajador:', 'El interesado puede instarlas directamente, sin perjuicio de las responsabilidades de aquellas',
 ['El trabajador pierde todo derecho a prestaciones', 'Solo puede actuar la Inspección de Trabajo', 'El contrato de trabajo es nulo'],
 'podrán los interesados instar directamente su afiliación, alta, baja o variación de datos'),
('IV', T, 'a18', 'La obligación de cotizar a la Seguridad Social nace:', 'Desde el momento de iniciación de la actividad correspondiente',
 ['Al mes de iniciar la actividad', 'Al superar el periodo de prueba', 'Al cobrar la primera nómina'],
 'La obligación de cotizar nacerá desde el momento de iniciación de la actividad correspondiente'),
('IV', P, 'a24', 'Plazo de prescripción del derecho de la Administración de la Seguridad Social a determinar las deudas por cuotas mediante liquidaciones', '4 años',
 ['5 años', '3 años', '1 año'], 'Prescribirán a los cuatro años los siguientes derechos y acciones'),
('IV', T, 'a44', 'Las prestaciones de la Seguridad Social pueden ser objeto de retención, cesión, compensación o descuento:', 'Solo para cumplir obligaciones alimenticias a favor del cónyuge e hijos o por obligaciones contraídas por el beneficiario dentro de la Seguridad Social',
 ['En cualquier caso a petición de un acreedor', 'Nunca, sin excepción alguna', 'Solo para pagar impuestos municipales'],
 'salvo en los dos casos siguientes: a) En orden al cumplimiento de las obligaciones alimenticias a favor del cónyuge e hijos'),
('IV', P, 'a53', 'Plazo de prescripción del derecho al reconocimiento de las prestaciones de la Seguridad Social, con carácter general, desde el día siguiente al hecho causante', '5 años',
 ['4 años', '1 año', '3 años'], 'El derecho al reconocimiento de las prestaciones prescribirá a los cinco años'),
('IV', P, 'a53', 'Retroactividad máxima de los efectos del reconocimiento de una prestación respecto de la fecha de la solicitud', '3 meses',
 ['1 año', '6 meses', '1 mes'], 'se produzcan a partir de los tres meses anteriores a la fecha en que se presente la correspondiente solicitud'),
('IV', P, 'a54', 'Plazo de caducidad del derecho al percibo de las prestaciones a tanto alzado y por una sola vez, desde la notificación de su reconocimiento', '1 año',
 ['5 años', '6 meses', '3 meses'], 'El derecho al percibo de las prestaciones a tanto alzado y por una sola vez caducará al año'),
('IV', T, 'a156', 'Según la LGSS, el accidente que sufre el trabajador al ir o al volver del lugar de trabajo:', 'Tiene la consideración de accidente de trabajo',
 ['Es siempre accidente no laboral', 'Solo es accidente de trabajo si ocurre en vehículo de la empresa', 'No está protegido por la Seguridad Social'],
 'a) Los que sufra el trabajador al ir o al volver del lugar de trabajo'),
('IV', T, 'a156', 'Se entiende por accidente de trabajo toda lesión corporal que el trabajador sufra:', 'Con ocasión o por consecuencia del trabajo que ejecute por cuenta ajena',
 ['Durante su tiempo libre', 'En cualquier lugar, siempre que esté afiliado', 'Solo dentro del centro de trabajo'],
 'Se entiende por accidente de trabajo toda lesión corporal que el trabajador sufra con ocasión o por consecuencia del trabajo que ejecute por cuenta ajena'),
('IV', T, 'a157', 'La enfermedad profesional es la contraída a consecuencia del trabajo por cuenta ajena en las actividades:', 'Que se especifiquen en el cuadro aprobado reglamentariamente y provocada por los elementos o sustancias que en él se indiquen',
 ['Que determine el médico de familia en cada caso', 'Que figuren en el convenio colectivo', 'Que el trabajador declare como peligrosas'],
 'en las actividades que se especifiquen en el cuadro que se apruebe por las disposiciones de aplicación y desarrollo de esta ley'),
('IV', P, 'a169', 'Duración máxima ordinaria de la incapacidad temporal por enfermedad o accidente (prorrogable por otros 180 días)', '365 días',
 ['180 días', '545 días', '730 días'], 'con una duración máxima de trescientos sesenta y cinco días, prorrogables por otros ciento ochenta días'),
('IV', T, 'a172', 'Para el subsidio por incapacidad temporal derivada de enfermedad común se exige un período mínimo de cotización de:', 'Ciento ochenta días dentro de los cinco años inmediatamente anteriores al hecho causante',
 ['Un año dentro de los dos últimos años', 'Quince años', 'Ninguno'],
 'a) En caso de enfermedad común, ciento ochenta días dentro de los cinco años inmediatamente anteriores al hecho causante'),
('IV', T, 'a172', 'Para el subsidio por incapacidad temporal derivada de accidente, sea o no de trabajo, o de enfermedad profesional:', 'No se exige ningún período previo de cotización',
 ['Se exigen ciento ochenta días cotizados', 'Se exige un año cotizado', 'Se exigen treinta días cotizados en el último mes'],
 'b) En caso de accidente, sea o no de trabajo, y de enfermedad profesional, no se exigirá ningún período previo de cotización'),
('IV', T, 'a173', 'En caso de enfermedad común o accidente no laboral, el subsidio por incapacidad temporal se abona:', 'A partir del cuarto día de baja, a cargo del empresario del día cuarto al decimoquinto',
 ['Desde el día siguiente a la baja, a cargo de la entidad gestora', 'Desde el primer día, a cargo del trabajador', 'A partir del decimosexto día, sin cargo al empresario'],
 'el subsidio se abonará a partir del cuarto día de baja en el trabajo, si bien desde el día cuarto al decimoquinto de baja, ambos inclusive, el subsidio estará a cargo del empresario'),
('IV', T, 'a173', 'En caso de accidente de trabajo o enfermedad profesional, el subsidio por incapacidad temporal se abona:', 'Desde el día siguiente al de la baja, siendo a cargo del empresario el salario íntegro del día de la baja',
 ['A partir del cuarto día de baja', 'A partir del decimosexto día de baja', 'Desde el mismo día de la baja, a cargo de la entidad gestora'],
 'el subsidio se abonará desde el día siguiente al de la baja en el trabajo, estando a cargo del empresario el salario íntegro correspondiente al día de la baja'),
('IV', P, 'a174', 'Plazo máximo del subsidio por incapacidad temporal, desde la baja médica, cuyo transcurso extingue el derecho', '545 días naturales',
 ['365 días naturales', '730 días naturales', '180 días naturales'], 'por el transcurso del plazo máximo de quinientos cuarenta y cinco días naturales desde la baja médica'),
('IV', T, 'a194', '¿Cuál de los siguientes NO es un grado de incapacidad permanente según la LGSS?', 'Incapacidad permanente temporal',
 ['Incapacidad permanente parcial', 'Incapacidad permanente absoluta', 'Gran incapacidad'],
 'a) Incapacidad permanente parcial. b) Incapacidad permanente total. c) Incapacidad permanente absoluta. d) Gran incapacidad'),
('IV', T, 'a205', 'Para la pensión de jubilación contributiva se exige un período mínimo de cotización de:', 'Quince años, de los cuales al menos dos dentro de los quince años inmediatamente anteriores al momento de causar el derecho',
 ['Diez años en cualquier momento', 'Veinte años, cinco de ellos en los últimos diez', 'Treinta y cinco años en todo caso'],
 'Tener cubierto un período mínimo de cotización de quince años, de los cuales al menos dos deberán estar comprendidos dentro de los quince años inmediatamente anteriores'),
('IV', T, 'a212', 'El derecho al reconocimiento de la pensión de jubilación:', 'Es imprescriptible',
 ['Prescribe a los cinco años', 'Prescribe a los cuatro años', 'Caduca al año'], 'El derecho al reconocimiento de la pensión de jubilación es imprescriptible'),
('IV', T, 'a216', 'En caso de muerte causada por accidente de trabajo o enfermedad profesional se reconoce, además de las demás prestaciones por muerte y supervivencia:', 'Una indemnización a tanto alzado',
 ['Una pensión de jubilación anticipada', 'Un subsidio de incapacidad temporal', 'Una prestación por desempleo'],
 'En caso de muerte causada por accidente de trabajo o enfermedad profesional se reconocerá, además, una indemnización a tanto alzado'),
('IV', T, 'a218', 'El auxilio por defunción tiene por finalidad:', 'Hacer frente a los gastos de sepelio de quien los haya soportado',
 ['Sustituir el salario del fallecido', 'Pagar las deudas del fallecido con la Seguridad Social', 'Financiar la formación de los huérfanos'],
 'un auxilio por defunción para hacer frente a los gastos de sepelio a quien los haya soportado'),
]
