# Lote 9 · LCSP (Ley 9/2017) parte 2: arts. 61-114 (órgano de contratación, perfil de contratante, aptitud,
# prohibiciones, solvencia, clasificación, objeto, precio, valor estimado, revisión de precios y garantías) y
# arts. 115 y siguientes (preparación, adjudicación, ejecución) · bloque III.
# Sin repetir lote-001 (arts. 118, 150, 153, 198). Se evitan las partes declaradas inconstitucionales o con
# interpretación del TC (arts. 72.4, 80.2, 82.2).
NORMA, LOTE, INICIO = 'LCSP', 'lote-009', 9001
T, P = 'test', 'plazo'
PREGUNTAS = [
# Arts. 61-70
('III', T, 'a6-3', 'En materia contractual, los órganos de contratación:', 'Pueden delegar o desconcentrar sus competencias, con cumplimiento de las normas aplicables',
 ['No pueden delegar sus competencias en ningún caso', 'Solo pueden delegar en el Tribunal Administrativo Central de Recursos Contractuales', 'Solo pueden delegar con autorización de las Cortes Generales'],
 'Los órganos de contratación podrán delegar o desconcentrar sus competencias'),
('III', T, 'a6-4', 'El responsable del contrato que deben designar los órganos de contratación:', 'Podrá ser una persona física o jurídica, vinculada a la entidad contratante o ajena a ella',
 ['Debe ser necesariamente un funcionario de carrera', 'Solo puede ser una persona física vinculada a la entidad contratante', 'Es designado por el contratista'],
 'El responsable del contrato podrá ser una persona física o jurídica'),
('III', T, 'a6-4', 'En los contratos de obras, las facultades del responsable del contrato son ejercidas por:', 'El Director Facultativo',
 ['La mesa de contratación', 'El coordinador de seguridad y salud', 'El interventor delegado'], 'serán ejercidas por el Director Facultativo'),
('III', T, 'a6-5', 'Los órganos de contratación difundirán su perfil de contratante:', 'Exclusivamente a través de Internet',
 ['Exclusivamente a través del Boletín Oficial del Estado', 'En el tablón de anuncios de su sede', 'A través del diario oficial de la provincia'], 'difundirán exclusivamente a través de Internet su perfil de contratante'),
('III', T, 'a6-5', 'El acceso a la información del perfil de contratante:', 'Será libre, sin requerir identificación previa',
 ['Requiere identificación previa con certificado electrónico', 'Está reservado a los licitadores', 'Requiere solicitud previa al órgano de contratación'],
 'El acceso a la información del perfil de contratante será libre, no requiriendo identificación previa'),
('III', P, 'a6-5', 'Período mínimo durante el cual la información de los perfiles de contratante permanecerá accesible al público', '5 años',
 ['3 años', '4 años', '10 años'], 'durante un periodo de tiempo no inferior a 5 años'),
('III', T, 'a6-5', 'La información relativa a los contratos menores debe publicarse en el perfil de contratante al menos con periodicidad:', 'Trimestral',
 ['Mensual', 'Semestral', 'Anual'], 'La publicación de la información relativa a los contratos menores deberá realizarse al menos trimestralmente'),
('III', T, 'a6-5', 'Quedan exceptuados de la publicación periódica de contratos menores los de valor estimado inferior a cierta cuantía, si se pagan por anticipo de caja fija u otro sistema similar. Esa cuantía es:', '5.000 euros',
 ['15.000 euros', '3.000 euros', '1.000 euros'], 'aquellos contratos cuyo valor estimado fuera inferior a cinco mil euros'),
('III', T, 'a6-5', 'La formalización de los encargos a medios propios se publica en el perfil de contratante cuando su importe sea superior a:', '50.000 euros, IVA excluido',
 ['5.000 euros, IVA excluido', '15.000 euros, IVA excluido', '100.000 euros, IVA excluido'], 'cuyo importe fuera superior a 50.000 euros, IVA excluido'),
('III', T, 'a6-6', 'Quienes tengan conocimiento de un posible conflicto de intereses en un procedimiento de licitación deberán:', 'Ponerlo inmediatamente en conocimiento del órgano de contratación',
 ['Comunicarlo al Tribunal de Cuentas en el plazo de diez días', 'Denunciarlo ante el Tribunal Administrativo Central de Recursos Contractuales', 'Ponerlo en conocimiento del Ministerio Fiscal'],
 'deberán ponerlo inmediatamente en conocimiento del órgano de contratación'),
('III', T, 'a6-7', '¿Cuál de los siguientes NO es un requisito general de aptitud para contratar con el sector público según el artículo 65.1?', 'Tener la nacionalidad española',
 ['Tener plena capacidad de obrar', 'No estar incurso en prohibición de contratar', 'Acreditar la solvencia económica y financiera y técnica o profesional, o estar clasificado cuando se exija'],
 'Solo podrán contratar con el sector público las personas naturales o jurídicas'),
('III', T, 'a6-8', 'Las personas jurídicas solo podrán ser adjudicatarias de contratos cuyas prestaciones estén comprendidas:', 'Dentro de los fines, objeto o ámbito de actividad que les sean propios según sus estatutos o reglas fundacionales',
 ['En el epígrafe del Impuesto de Actividades Económicas en que figuren de alta', 'En cualquier actividad lícita, sin limitación', 'Dentro de su ámbito territorial de actuación'],
 'Las personas jurídicas solo podrán ser adjudicatarias de contratos cuyas prestaciones estén comprendidas dentro de los fines'),
('III', T, 'a6-10', 'El informe de reciprocidad que deben aportar las empresas de Estados no comunitarios es elaborado por:', 'La Oficina Económica y Comercial de España en el exterior correspondiente',
 ['La Junta Consultiva de Contratación Pública del Estado', 'El Registro Mercantil', 'El órgano de contratación'],
 'Dicho informe será elaborado por la correspondiente Oficina Económica y Comercial de España en el exterior'),
('III', T, 'a6-11', 'Las uniones temporales de empresarios no necesitan formalizarse en escritura pública:', 'Hasta que se haya efectuado la adjudicación del contrato a su favor',
 ['Hasta la finalización del plazo de presentación de ofertas', 'Hasta la recepción del contrato', 'En ningún momento'],
 'sin que sea necesaria la formalización de las mismas en escritura pública hasta que se haya efectuado la adjudicación'),
('III', T, 'a6-11', 'Los empresarios que concurran agrupados en uniones temporales quedan obligados:', 'Solidariamente',
 ['Mancomunadamente, en proporción a su participación', 'Subsidiariamente', 'Solo el representante de la unión'], 'quedarán obligados solidariamente'),
('III', T, 'a6-11', 'Formalizado el contrato con una UTE, para modificar su composición aumentando, disminuyendo o sustituyendo empresas, se requiere autorización del órgano de contratación y que el contrato se haya ejecutado al menos en:', 'Un 20 por ciento de su importe',
 ['Un 10 por ciento de su importe', 'Un 50 por ciento de su importe', 'Un 30 por ciento de su importe'], 'debiendo haberse ejecutado el contrato al menos en un 20 por ciento de su importe'),
('III', T, 'a7-2', 'Los contratos que tengan por objeto la vigilancia, supervisión, control y dirección de la ejecución de otros contratos:', 'No podrán adjudicarse a las mismas empresas adjudicatarias de los correspondientes contratos ni a empresas vinculadas a estas',
 ['Deberán adjudicarse preferentemente a las empresas adjudicatarias de los contratos controlados', 'Podrán adjudicarse a las mismas empresas con autorización del órgano de contratación', 'Solo pueden ejecutarse mediante medios propios'],
 'no podrán adjudicarse a las mismas empresas adjudicatarias de los correspondientes contratos'),
# Arts. 71-73: prohibiciones de contratar
('III', T, 'a7-3', 'Es causa de prohibición de contratar, en empresas de 50 o más trabajadores, no cumplir el requisito de que sean trabajadores con discapacidad al menos:', 'El 2 por ciento de sus empleados',
 ['El 5 por ciento de sus empleados', 'El 3 por ciento de sus empleados', 'El 7 por ciento de sus empleados'], 'no cumplir el requisito de que al menos el 2 por ciento de sus empleados sean trabajadores con discapacidad'),
('III', T, 'a7-3', 'A efectos de prohibición de contratar, ¿cuándo se considera que una empresa se encuentra al corriente en sus obligaciones tributarias o con la Seguridad Social pese a tener deudas?', 'Cuando las deudas estén aplazadas, fraccionadas o suspendidas con ocasión de su impugnación',
 ['Cuando las deudas sean inferiores a 3.000 euros', 'Cuando las deudas tengan menos de un año de antigüedad', 'Nunca: cualquier deuda impide contratar'],
 'cuando las deudas estén aplazadas, fraccionadas o se hubiera acordado su suspensión'),
('III', P, 'a7-3', 'Límite máximo de la prohibición de contratar por haber contratado a un ex alto cargo incumpliendo la Ley 3/2015, contado desde su cese como alto cargo', '2 años',
 ['1 año', '3 años', '5 años'], 'con el límite máximo de dos años a contar desde el cese como alto cargo'),
('III', T, 'a7-3', 'Según el artículo 71.2, es circunstancia que impide contratar con las entidades del sector público:', 'Haber dejado de formalizar en plazo, por causa imputable al adjudicatario, el contrato adjudicado a su favor',
 ['Haber presentado una oferta incursa en presunción de anormalidad', 'Haber interpuesto un recurso especial que fue desestimado', 'No haber resultado adjudicatario en una licitación anterior'],
 'b) Haber dejado de formalizar el contrato, que ha sido adjudicado a su favor'),
('III', P, 'a7-4', 'Duración máxima de la prohibición de contratar derivada de condena penal firme cuando la sentencia no haya establecido plazo, desde la fecha de la condena', '5 años',
 ['3 años', '10 años', '2 años'], 'esa duración no podrá exceder de cinco años desde la fecha de la condena'),
('III', P, 'a7-4', 'Duración máxima de la prohibición de contratar en los supuestos distintos de la condena penal', '3 años',
 ['5 años', '2 años', '1 año'], 'el plazo de duración no podrá exceder de tres años'),
('III', P, 'a7-5', 'Tiempo tras el fin de la duración de la prohibición de contratar en el que caduca su inscripción en el Registro de Licitadores', '3 meses',
 ['6 meses', '1 mes', '12 meses'], 'caducará pasados 3 meses desde que termine su duración'),
# Arts. 74-82: solvencia y clasificación
('III', T, 'a7-6', 'El requisito de acreditar las condiciones mínimas de solvencia será sustituido, cuando sea exigible conforme a la Ley, por el de:', 'La clasificación',
 ['La declaración responsable', 'La garantía definitiva', 'La inscripción en el Registro Mercantil'], 'Este requisito será sustituido por el de la clasificación'),
('III', T, 'a7-9', 'La clasificación del empresario como contratista de obras es requisito indispensable en los contratos de obras de valor estimado igual o superior a:', '500.000 euros',
 ['1.000.000 euros', '40.000 euros', '5.404.000 euros'], r're:a\) Para los contratos de obras cuyo valor estimado sea igual o superior a 500\.000 euros será requisito indispensable'),
('III', T, 'a7-9', 'En los contratos de servicios, la clasificación del empresario:', 'No es exigible',
 ['Es exigible a partir de 500.000 euros', 'Es exigible a partir de 140.000 euros', 'Es exigible siempre'], 'b) Para los contratos de servicios no será exigible la clasificación del empresario'),
('III', T, 'a7-10', 'A los empresarios no españoles de Estados miembros de la Unión Europea:', 'No les es exigible la clasificación, sin perjuicio de la obligación de acreditar su solvencia',
 ['Les es exigible siempre la clasificación', 'Están exentos de acreditar su solvencia', 'Necesitan autorización del Consejo de Ministros para contratar'],
 'No será exigible la clasificación a los empresarios no españoles de Estados miembros'),
('III', T, 'a7-10', 'Excepcionalmente, la contratación de la AGE con personas no clasificadas cuando la clasificación sea exigible podrá ser autorizada por:', 'El Consejo de Ministros, previo informe de la Junta Consultiva de Contratación Pública del Estado',
 ['El órgano de contratación, motivadamente', 'El Ministro de Hacienda, sin necesidad de informe', 'El Tribunal Administrativo Central de Recursos Contractuales'],
 'podrá ser autorizada por el Consejo de Ministros'),
('III', T, 'a7-11', 'Salvo casos excepcionales, el número de subgrupos de clasificación exigibles en una obra no podrá ser superior a:', 'Cuatro',
 ['Dos', 'Tres', 'Seis'], 'El número de subgrupos exigibles, salvo casos excepcionales, no podrá ser superior a cuatro'),
('III', T, 'a8-4', 'La clasificación de las empresas tiene una vigencia:', 'Indefinida, en tanto se mantengan las condiciones y circunstancias en que se basó su concesión',
 ['De cinco años, renovable', 'De tres años', 'De un año'], 'La clasificación de las empresas tendrá una vigencia indefinida'),
# Arts. 99-105: objeto, presupuesto, valor estimado, precio
('III', T, 'a9-11', 'No podrá fraccionarse un contrato con la finalidad de:', 'Disminuir su cuantía y eludir así los requisitos de publicidad o de procedimiento de adjudicación',
 ['Permitir la realización independiente de cada una de sus partes', 'Facilitar el acceso de las pequeñas y medianas empresas', 'Reservar lotes a Centros Especiales de Empleo'],
 'No podrá fraccionarse un contrato con la finalidad de disminuir la cuantía'),
('III', T, 'a9-11', 'Siempre que la naturaleza o el objeto del contrato lo permitan, deberá preverse:', 'La realización independiente de cada una de sus partes mediante su división en lotes',
 ['La adjudicación del contrato a un único empresario', 'La tramitación por procedimiento negociado', 'La exigencia de garantía provisional'],
 'deberá preverse la realización independiente de cada una de sus partes mediante su división en lotes'),
('III', T, 'a9-11', 'En los contratos adjudicados por lotes, salvo otra previsión en el pliego y salvo ofertas integradoras:', 'Cada lote constituirá un contrato',
 ['Todos los lotes constituyen un único contrato', 'Los lotes se agrupan en un contrato por cada licitador', 'Cada lote constituye un acuerdo marco'], 'cada lote constituirá un contrato'),
('III', T, 'a1-12', 'Por presupuesto base de licitación se entiende, salvo disposición en contrario:', 'El límite máximo de gasto que en virtud del contrato puede comprometer el órgano de contratación, incluido el IVA',
 ['El límite máximo de gasto, excluido el IVA', 'El importe de adjudicación del contrato', 'El importe total del contrato incluidas sus prórrogas, sin IVA'],
 'por presupuesto base de licitación se entenderá el límite máximo de gasto'),
('III', T, 'a1-13', 'En los contratos de obras, suministros y servicios, el valor estimado se determina tomando:', 'El importe total, sin incluir el IVA, pagadero según las estimaciones del órgano de contratación',
 ['El importe total, incluido el IVA', 'El presupuesto base de licitación', 'El precio de adjudicación'],
 'el órgano de contratación tomará el importe total, sin incluir el Impuesto sobre el Valor Añadido'),
('III', T, 'a1-13', 'En el cálculo del valor estimado deben tenerse en cuenta, entre otros conceptos:', 'Cualquier forma de opción eventual y las eventuales prórrogas del contrato',
 ['Solo la duración inicial, sin las prórrogas', 'El Impuesto sobre el Valor Añadido', 'Solo la prestación principal'], 'a) Cualquier forma de opción eventual y las eventuales prórrogas del contrato'),
('III', T, 'a1-13', 'En los contratos de servicios sin precio total cuya duración sea superior a cuarenta y ocho meses o no esté fijada, el valor estimado es el valor mensual multiplicado por:', '48',
 ['12', '36', '60'], 'Si la duración es superior a cuarenta y ocho meses o no se encuentra fijada'),
('III', T, 'a1-13', 'El método de cálculo del valor estimado aplicado por el órgano de contratación deberá figurar en todo caso en:', 'Los pliegos de cláusulas administrativas particulares',
 ['El anuncio de información previa', 'El informe de la Intervención', 'La resolución de adjudicación'],
 'El método de cálculo aplicado por el órgano de contratación para calcular el valor estimado en todo caso deberá figurar'),
('III', T, 'a1-14', 'Los contratos del sector público tendrán siempre:', 'Un precio cierto',
 ['Un precio provisional', 'Un precio revisable', 'Un precio aplazado'], 'Los contratos del sector público tendrán siempre un precio cierto'),
('III', T, 'a1-14', 'En el precio del contrato se entenderá incluido el IVA, que:', 'En todo caso se indicará como partida independiente',
 ['Se indicará solo en los contratos sujetos a regulación armonizada', 'No se indicará nunca por separado', 'Se abonará al finalizar el contrato'], 'que en todo caso se indicará como partida independiente'),
('III', T, 'a1-14', 'El pago aplazado del precio en los contratos de las Administraciones Públicas:', 'Está prohibido, salvo arrendamiento financiero o con opción de compra, o cuando una Ley lo autorice',
 ['Está permitido con un máximo de dos años', 'Está permitido en los contratos menores', 'Está permitido siempre que lo prevea el pliego'],
 'Se prohíbe el pago aplazado del precio en los contratos de las Administraciones Públicas'),
('III', T, 'a1-14', 'En los contratos celebrados con precios provisionales:', 'No cabe la revisión de precios',
 ['La revisión de precios es obligatoria', 'La revisión de precios procede tras el primer año', 'La revisión de precios procede cuando se haya ejecutado el 20 %'],
 'En los contratos celebrados con precios provisionales no cabrá la revisión de precios'),
('III', P, 'a1-15', 'Período de recuperación de la inversión igual o superior al cual cabe la revisión periódica y predeterminada de precios en contratos distintos de obras, armamento y energía', '5 años',
 ['3 años', '2 años', '10 años'], 'en aquellos otros contratos en los que el período de recuperación de la inversión sea igual o superior a cinco años'),
('III', T, 'a1-15', '¿Cuál de los siguientes NO se considerará revisable en ningún caso?', 'El beneficio industrial',
 ['Los costes de las materias primas', 'Los costes de la energía', 'Los costes de los materiales básicos'], 'No se considerarán revisables en ningún caso los costes asociados a las amortizaciones'),
('III', T, 'a1-15', 'Salvo en los suministros de energía, la revisión periódica y predeterminada de precios exige, entre otros requisitos, que el contrato se haya ejecutado al menos en:', 'El 20 por ciento de su importe',
 ['El 10 por ciento de su importe', 'El 25 por ciento de su importe', 'El 50 por ciento de su importe'], 'cuando el contrato se hubiese ejecutado, al menos, en el 20 por ciento de su importe'),
('III', P, 'a1-15', 'Tiempo que debe haber transcurrido desde la formalización del contrato (además del porcentaje de ejecución) para que tenga lugar la revisión periódica y predeterminada de precios', '1 año',
 ['2 años', '3 años', '5 años'], 'hubiese transcurrido un año desde su formalización'),
# Arts. 106-114: garantías
('III', T, 'a1-18', 'Con carácter general, en el procedimiento de contratación la garantía provisional:', 'No procede, salvo que excepcionalmente el órgano de contratación lo justifique por motivos de interés público',
 ['Es obligatoria en todo caso', 'Es obligatoria en los contratos sujetos a regulación armonizada', 'Es obligatoria en los contratos de obras'],
 'En el procedimiento de contratación no procederá la exigencia de garantía provisional'),
('III', T, 'a1-18', 'Cuando se exija, el importe de la garantía provisional no podrá ser superior a:', 'Un 3 por 100 del presupuesto base de licitación, excluido el IVA',
 ['Un 5 por 100 del precio final ofertado, excluido el IVA', 'Un 10 por 100 del presupuesto base de licitación, IVA incluido', 'Un 2 por 100 del valor estimado'],
 'que no podrá ser superior a un 3 por 100 del presupuesto base de licitación'),
('III', T, 'a1-18', 'La garantía provisional se extingue automáticamente y se devuelve a los licitadores:', 'Inmediatamente después de la perfección del contrato',
 ['Al finalizar el plazo de garantía del contrato', 'A los tres meses de la adjudicación', 'Al finalizar el plazo de presentación de ofertas'],
 'será devuelta a los licitadores inmediatamente después de la perfección del contrato'),
('III', T, 'a1-19', 'La garantía definitiva que deben constituir los licitadores que presenten las mejores ofertas en los contratos de las Administraciones Públicas es, con carácter general, de:', 'Un 5 por 100 del precio final ofertado, excluido el IVA',
 ['Un 3 por 100 del presupuesto base de licitación, excluido el IVA', 'Un 10 por 100 del precio final ofertado, IVA incluido', 'Un 5 por 100 del valor estimado, IVA incluido'],
 'una garantía de un 5 por 100 del precio final ofertado'),
('III', T, 'a1-19', 'Con la garantía complementaria en casos especiales, la garantía definitiva total puede alcanzar:', 'Un 10 por 100 del precio final ofertado',
 ['Un 15 por 100 del precio final ofertado', 'Un 8 por 100 del precio final ofertado', 'Un 20 por 100 del precio final ofertado'], 'pudiendo alcanzar la garantía total un 10 por 100 del citado precio'),
('III', T, 'a1-19', 'La exención de constituir garantía definitiva NO es posible en:', 'Los contratos de obras y de concesión de obras',
 ['Los suministros de bienes consumibles cuya entrega y recepción deba efectuarse antes del pago', 'Los contratos de prestación de servicios sociales', 'Los contratos privados de la Administración del artículo 25.1.a) 1.º y 2.º'],
 'Esta exención no será posible en el caso de contratos de obras, ni de concesión de obras'),
('III', T, 'a1-19', 'Cuando el precio del contrato se formule en función de precios unitarios, el importe de la garantía definitiva se fija atendiendo:', 'Al presupuesto base de licitación, IVA excluido',
 ['Al precio final ofertado, IVA incluido', 'Al valor estimado, IVA incluido', 'Al importe de la primera anualidad'], 'el importe de la garantía a constituir se fijará atendiendo al presupuesto base de licitación'),
('III', T, 'a1-20', '¿Cuál de las siguientes NO es una forma admisible de prestar la garantía definitiva según el artículo 108.1?', 'Mediante pagaré o cheque emitido por el propio licitador',
 ['En efectivo o en valores de Deuda Pública', 'Mediante aval de entidad autorizada', 'Mediante contrato de seguro de caución'],
 r're:podrán prestarse en alguna o algunas de las siguientes formas: a\) En efectivo o en valores, que en todo caso serán de Deuda Pública'),
('III', T, 'a1-20', 'Cuando así se prevea en los pliegos, la garantía definitiva en los contratos de obras, suministros y servicios podrá constituirse:', 'Mediante retención en el precio',
 ['Mediante prenda sobre bienes del contratista', 'Mediante hipoteca', 'Mediante declaración responsable'], 'podrá constituirse mediante retención en el precio'),
('III', P, 'a1-21', 'Plazo del contratista para reponer o ampliar la garantía definitiva cuando se hayan hecho efectivas sobre ella penalidades o indemnizaciones, desde la ejecución', '15 días',
 ['10 días', '30 días', '5 días'], 'en el plazo de quince días desde la ejecución'),
('III', P, 'a1-21', 'Plazo para reajustar la garantía cuando varíe el precio por una modificación del contrato, desde la notificación del acuerdo de modificación', '15 días',
 ['10 días', '30 días', '20 días'], 'en el plazo de quince días contados desde la fecha en que se notifique'),
('III', P, 'a1-21', 'Antelación mínima al vencimiento del seguro de caución (en contratos de más de cinco años) para prestar nueva garantía o prorrogar el seguro', '2 meses',
 ['1 mes', '3 meses', '6 meses'], 'con una antelación mínima de dos meses al vencimiento del contrato de seguro de caución'),
('III', T, 'a1-22', '¿De cuál de los siguientes conceptos NO responde la garantía definitiva según el artículo 110?', 'De las deudas tributarias del contratista con la Hacienda Pública',
 ['De las penalidades impuestas al contratista', 'De la obligación de formalizar el contrato en plazo', 'De la incautación que puede decretarse en los casos de resolución del contrato'],
 r're:La garantía definitiva únicamente responderá de los siguientes conceptos: a\).*?d\) De la incautación que puede decretarse en los casos de resolución del contrato'),
('III', P, 'a1-23', 'Plazo para adoptar y notificar el acuerdo de devolución de la garantía definitiva, desde la finalización del plazo de garantía', '2 meses',
 ['1 mes', '3 meses', '6 meses'], 'en el plazo de dos meses desde la finalización del plazo de garantía'),
('III', P, 'a1-23', 'Tiempo desde la terminación del contrato tras el cual, vencido el plazo de garantía y sin recepción formal ni liquidación por causas no imputables al contratista, se devuelve la garantía (regla general)', '1 año',
 ['2 años', '3 años', '5 años'], 'Transcurrido un año desde la fecha de terminación del contrato'),
('III', P, 'a1-23', 'Plazo reducido para esa devolución en contratos de obras de valor estimado inferior a 1.000.000 de euros, otros contratos inferiores a 100.000 euros o licitadores pyme', '6 meses',
 ['3 meses', '4 meses', '9 meses'], 'el plazo se reducirá a seis meses'),
('III', T, 'a1-24', 'Las personas o entidades distintas del contratista que presten garantías a favor de este:', 'No podrán utilizar el beneficio de excusión',
 ['Podrán utilizar el beneficio de excusión', 'Solo responderán una vez agotado el patrimonio del contratista', 'No tendrán la consideración de parte interesada en ningún caso'],
 'no podrán utilizar el beneficio de excusión'),
('III', T, 'a1-24', 'En el contrato de seguro de caución que garantiza un contrato público:', 'El contratista es el tomador del seguro y la Administración contratante, la asegurada',
 ['La Administración es la tomadora y el contratista, el asegurado', 'El asegurador es el tomador y el contratista, el asegurado', 'El contratista es a la vez tomador y asegurado'],
 'Tendrá la condición de tomador del seguro el contratista y la de asegurado la Administración contratante'),
('III', T, 'a1-25', 'Cuando la garantía no sea bastante para cubrir las responsabilidades a las que está afecta, la Administración cobrará la diferencia:', 'Mediante el procedimiento administrativo de apremio',
 ['Mediante demanda ante la jurisdicción civil', 'Mediante la incautación de la garantía de otros contratos', 'Mediante reclamación al Tribunal de Cuentas'],
 'mediante el procedimiento administrativo de apremio'),
('III', T, 'a1-25', 'Para hacer efectivas las garantías, la Administración contratante:', 'Tiene preferencia sobre cualquier otro acreedor, sea cual fuere la naturaleza de su crédito',
 ['Concurre a prorrata con los demás acreedores', 'Tiene preferencia solo sobre los acreedores comunes', 'Queda pospuesta a los créditos laborales y tributarios'],
 'tendrá preferencia sobre cualquier otro acreedor'),
('III', T, 'a1-26', 'En los contratos de entidades del sector público que no tengan la consideración de Administraciones Públicas, las garantías:', 'Pueden exigirse, sin que sea necesaria su constitución en la Caja General de Depósitos',
 ['Son obligatorias en todo caso', 'Deben constituirse siempre en la Caja General de Depósitos', 'Están prohibidas'],
 'sin que resulte necesaria su constitución en la Caja General de Depósitos'),
# Arts. 115-120: preparación y expediente
('III', T, 'a1-27', 'La participación de un operador económico en las consultas preliminares del mercado:', 'No impide su posterior intervención en el procedimiento de contratación',
 ['Le impide participar en la licitación posterior', 'Le otorga preferencia en caso de empate', 'Le exime de acreditar la solvencia'],
 'La participación en la consulta no impide la posterior intervención en el procedimiento de contratación'),
('III', T, 'a1-27', 'Durante las consultas preliminares del mercado, el órgano de contratación:', 'No podrá en ningún caso revelar a los participantes las soluciones propuestas por los otros participantes',
 ['Debe publicar las soluciones propuestas por cada participante', 'Puede revelar las soluciones a los participantes con su consentimiento tácito', 'Debe comunicar las soluciones al Tribunal Administrativo Central de Recursos Contractuales'],
 'el órgano de contratación podrá revelar a los participantes en el mismo las soluciones propuestas por los otros participantes'),
('III', T, 'a1-28', 'En el expediente de contratación de un contrato de servicios debe justificarse, entre otros extremos:', 'El informe de insuficiencia de medios',
 ['El informe del Consejo de Estado', 'La autorización del Consejo de Ministros', 'El informe de la Junta Consultiva de Contratación Pública del Estado'],
 'f) En los contratos de servicios, el informe de insuficiencia de medios'),
('III', T, 'a1-28', 'En el procedimiento de diálogo competitivo, los pliegos de cláusulas administrativas y de prescripciones técnicas se sustituyen por:', 'El documento descriptivo',
 ['La memoria justificativa', 'El anuncio de información previa', 'El documento europeo único de contratación'],
 'serán sustituidos por el documento descriptivo a que hace referencia el apartado 1 del artículo 174'),
('III', T, 'a1-29', 'La resolución motivada del órgano de contratación que aprueba el expediente y dispone la apertura del procedimiento de adjudicación implica también, como regla general:', 'La aprobación del gasto',
 ['La adjudicación del contrato', 'La formalización del contrato', 'La fiscalización previa de la intervención'], 'Dicha resolución implicará también la aprobación del gasto'),
('III', T, 'a1-30', 'En los contratos menores, la tramitación del expediente exige un informe del órgano de contratación que justifique motivadamente:', 'La necesidad del contrato y que no se altera su objeto para evitar los umbrales del contrato menor',
 ['La solvencia del empresario y su clasificación', 'La imposibilidad de utilizar el procedimiento abierto', 'La conformidad de la Intervención General'],
 'En los contratos menores la tramitación del expediente exigirá la emisión de un informe del órgano de contratación'),
('III', T, 'a1-30', 'El informe justificativo del contrato menor no es exigible cuando el pago se verifique mediante anticipos de caja fija u otro sistema similar y el valor estimado no exceda de:', '5.000 euros',
 ['15.000 euros', '3.000 euros', '40.000 euros'], 'siempre y cuando el valor estimado del contrato no exceda de 5.000 euros'),
('III', T, 'a1-30', 'En el contrato menor de obras, además del informe, la aprobación del gasto y la factura, debe añadirse:', 'El presupuesto de las obras',
 ['El acta de replanteo', 'La garantía definitiva', 'El informe del Consejo de Estado'], 'En el contrato menor de obras, deberá añadirse, además, el presupuesto de las obras'),
('III', P, 'a1-31', 'Plazo de los órganos que intervienen en la tramitación de un expediente urgente para emitir sus informes (salvo prórroga justificada)', '5 días',
 ['3 días', '10 días', '15 días'], 'que dispondrán de un plazo de cinco días para emitir los respectivos informes'),
('III', P, 'a1-31', 'Prórroga máxima del plazo para emitir informes en la tramitación urgente cuando la complejidad del expediente impida cumplir el plazo ordinario', '10 días',
 ['5 días', '15 días', '20 días'], 'En tal caso el plazo quedará prorrogado hasta diez días'),
('III', T, 'a1-31', 'En la tramitación urgente, los plazos de licitación, adjudicación y formalización, salvo las excepciones legales:', 'Se reducen a la mitad',
 ['Se reducen a un tercio', 'Se mantienen, pero el expediente tiene preferencia', 'Se reducen en cinco días'], 'los plazos establecidos en esta Ley para la licitación, adjudicación y formalización del contrato se reducirán a la mitad'),
('III', P, 'a1-31', 'Plazo máximo de inicio de la ejecución de un contrato tramitado por urgencia, desde la formalización', '1 mes',
 ['15 días', '2 meses', '3 meses'], 'c) El plazo de inicio de la ejecución del contrato no podrá exceder de un mes, contado desde la formalización'),
('III', T, 'a1-32', 'En la tramitación de emergencia, el órgano de contratación puede ordenar la ejecución de lo necesario o contratar libremente su objeto:', 'Sin obligación de tramitar expediente de contratación e incluso sin crédito suficiente',
 ['Previa tramitación de un expediente abreviado', 'Solo si existe crédito adecuado y suficiente', 'Previa autorización del Consejo de Ministros'],
 r're:sin obligación de tramitar expediente de contratación, podrá ordenar.*?incluso el de la existencia de crédito suficiente'),
('III', P, 'a1-32', 'Plazo máximo para dar cuenta al Consejo de Ministros de los acuerdos de emergencia adoptados en el ámbito de la AGE', '30 días',
 ['10 días', '15 días', '60 días'], 'se dará cuenta de dichos acuerdos al Consejo de Ministros en el plazo máximo de treinta días'),
('III', P, 'a1-32', 'Plazo máximo de inicio de la ejecución de las prestaciones en la tramitación de emergencia, desde la adopción del acuerdo (si se excede, procede el procedimiento ordinario)', '1 mes',
 ['15 días', '2 meses', '3 meses'], 'El plazo de inicio de la ejecución de las prestaciones no podrá ser superior a un mes'),
# Arts. 121-126: pliegos
('III', T, 'a1-33', 'Los pliegos de cláusulas administrativas generales de la AGE los aprueba:', 'El Consejo de Ministros, a propuesta del Ministro de Hacienda y Función Pública y previo dictamen del Consejo de Estado',
 ['El órgano de contratación de cada departamento', 'La Junta Consultiva de Contratación Pública del Estado', 'Las Cortes Generales mediante ley'],
 'previo dictamen del Consejo de Estado, podrá aprobar pliegos de cláusulas administrativas generales'),
('III', T, 'a1-34', 'Una vez aprobados, los pliegos de cláusulas administrativas particulares solo podrán modificarse con posterioridad:', 'Por error material, de hecho o aritmético; en otro caso, la modificación conllevará la retroacción de actuaciones',
 ['Libremente hasta la adjudicación', 'Por acuerdo de la mesa de contratación', 'Con el consentimiento de los licitadores'],
 r're:y solo podrán ser modificados con posterioridad por error material, de hecho o aritmético\. En otro caso, la modificación del pliego conllevará la retroacción de actuaciones\. 2\. En los pliegos'),
('III', T, 'a1-34', 'La aprobación de los pliegos de cláusulas administrativas particulares corresponde:', 'Al órgano de contratación',
 ['A la mesa de contratación', 'Al Servicio Jurídico', 'A la Intervención'], 'La aprobación de los pliegos de cláusulas administrativas particulares corresponderá al órgano de contratación'),
('III', T, 'a1-34', '¿Quién debe informar previamente los pliegos de cláusulas administrativas particulares que propongan estipulaciones contrarias a los pliegos generales?', 'La Junta Consultiva de Contratación Pública del Estado',
 ['El Consejo de Estado', 'El Tribunal de Cuentas', 'El Tribunal Administrativo Central de Recursos Contractuales'],
 'La Junta Consultiva de Contratación Pública del Estado deberá informar con carácter previo todos los pliegos'),
('III', T, 'a1-34', 'En la AGE y sus organismos, la aprobación de los pliegos de cláusulas administrativas particulares requiere informe previo de:', 'El Servicio Jurídico respectivo, salvo que el pliego se ajuste a un modelo ya informado',
 ['La Junta Consultiva de Contratación Pública del Estado en todo caso', 'El Consejo de Estado', 'La Intervención General de la Administración del Estado'],
 'la aprobación de los pliegos y de los modelos requerirá el informe previo del Servicio Jurídico respectivo'),
('III', T, 'a1-38', 'Salvo que lo justifique el objeto del contrato, cuando excepcionalmente las prescripciones técnicas hagan referencia a marcas, patentes o tipos, la referencia irá acompañada de la mención:', '«o equivalente»',
 ['«o similar»', '«preferentemente»', '«sin perjuicio de otras»'], 'en cuyo caso irá acompañada de la mención «o equivalente»'),
# Arts. 131-139: adjudicación
('III', T, 'a1-43', 'Ordinariamente, la adjudicación de los contratos de las Administraciones Públicas se realiza utilizando:', 'Una pluralidad de criterios basados en la mejor relación calidad-precio y el procedimiento abierto o el restringido',
 ['El precio como único criterio y el procedimiento negociado', 'El procedimiento negociado sin publicidad', 'El diálogo competitivo'],
 'La adjudicación se realizará, ordinariamente utilizando una pluralidad de criterios de adjudicación'),
('III', T, 'a1-43', 'Los contratos menores pueden adjudicarse directamente a cualquier empresario:', 'Con capacidad de obrar y que cuente con la habilitación profesional necesaria',
 ['Inscrito en el Registro Oficial de Licitadores y clasificado', 'Que haya presentado garantía provisional', 'Que haya sido seleccionado por la mesa de contratación'],
 'Los contratos menores podrán adjudicarse directamente a cualquier empresario con capacidad de obrar'),
('III', T, 'a1-43', 'No se aplican las normas de preparación y adjudicación de la LCSP a los contratos de asistencia sanitaria en supuestos de urgencia con valor estimado inferior a:', '30.000 euros',
 ['15.000 euros', '40.000 euros', '50.000 euros'], 'con un valor estimado inferior a 30.000 euros'),
('III', T, 'a1-47', 'En los contratos de la Administración General del Estado, el anuncio de licitación se publica en el perfil de contratante y, además:', 'En el «Boletín Oficial del Estado»',
 ['En el boletín oficial de la provincia', 'En un diario de difusión nacional', 'En el tablón de edictos del ministerio'],
 'el anuncio de licitación se publicará además en el «Boletín Oficial del Estado»'),
('III', T, 'a1-47', 'Cuando los contratos estén sujetos a regulación armonizada, la licitación debe publicarse, además, en:', 'El «Diario Oficial de la Unión Europea»',
 ['El «Boletín Oficial de las Cortes Generales»', 'La sede electrónica de la Comisión Nacional de los Mercados y la Competencia', 'El Registro Público de Contratos exclusivamente'],
 'Cuando los contratos estén sujetos a regulación armonizada la licitación deberá publicarse, además, en el «Diario Oficial de la Unión Europea»'),
('III', T, 'a1-48', 'La presentación de proposiciones o la recepción de la documentación en formato electrónico necesaria para presentarlas:', 'No podrá suponer la exigencia de cantidad alguna a los licitadores',
 ['Exige el pago de una tasa por derechos de examen', 'Se cobra según el valor estimado del contrato', 'Es gratuita solo para las pymes'],
 'no podrá suponer la exigencia de cantidad alguna a los licitadores'),
# Arts. 145-152: criterios, desempate, anormales, adjudicación
('III', T, 'a1-57', 'La adjudicación de los contratos se realizará utilizando una pluralidad de criterios de adjudicación en base a:', 'La mejor relación calidad-precio',
 ['El precio más bajo', 'La mayor solvencia del licitador', 'El menor plazo de ejecución'], 'La adjudicación de los contratos se realizará utilizando una pluralidad de criterios de adjudicación en base a la mejor relación calidad-precio'),
('III', T, 'a1-59', 'En defecto de previsión en los pliegos, el primer criterio legal para resolver el empate entre ofertas es:', 'El mayor porcentaje de trabajadores con discapacidad o en situación de exclusión social en la plantilla',
 ['El sorteo', 'El menor porcentaje de contratos temporales en la plantilla', 'El mayor porcentaje de mujeres empleadas en la plantilla'],
 'a) Mayor porcentaje de trabajadores con discapacidad o en situación de exclusión social en la plantilla'),
('III', T, 'a1-59', 'En defecto de previsión en los pliegos, si los criterios sociales legales no deshacen el empate entre ofertas, se acude a:', 'El sorteo',
 ['La oferta presentada en primer lugar', 'La oferta de menor precio', 'La decisión discrecional del órgano de contratación'],
 'd) El sorteo, en caso de que la aplicación de los anteriores criterios no hubiera dado lugar a desempate'),
('III', T, 'a1-59', 'La documentación acreditativa de los criterios de desempate previstos en los pliegos se aporta por los licitadores:', 'En el momento en que se produzca el empate, y no con carácter previo',
 ['Junto con la oferta, en todo caso', 'Tras la formalización del contrato', 'Con la solicitud de participación'],
 'será aportada por los licitadores en el momento en que se produzca el empate, y no con carácter previo'),
('III', T, 'a1-61', 'Cuando el órgano de contratación presuma que una oferta es anormalmente baja:', 'Solo podrá excluirla previa tramitación del procedimiento del artículo 149',
 ['Debe excluirla automáticamente', 'Debe adjudicarle el contrato con garantía complementaria en todo caso', 'Debe remitirla a la Comisión Nacional de los Mercados y la Competencia'],
 'solo podrá excluirla del procedimiento de licitación previa tramitación del procedimiento que establece este artículo'),
('III', T, 'a1-61', 'Si presentan ofertas varias empresas del mismo grupo, para identificar las ofertas incursas en presunción de anormalidad se toma:', 'Únicamente la oferta más baja',
 ['La media de sus ofertas', 'Todas ellas por separado', 'La oferta más alta'], 'se tomará únicamente, para aplicar el régimen de identificación de las ofertas incursas en presunción de anormalidad, aquella que fuere más baja'),
('III', P, 'a1-63', 'Plazo para publicar en el perfil de contratante la resolución de adjudicación', '15 días',
 ['10 días', '20 días', '30 días'], 'debiendo ser publicada en el perfil de contratante en el plazo de 15 días'),
('III', T, 'a1-63', 'La notificación de la adjudicación a candidatos y licitadores se realiza:', 'Por medios electrónicos',
 ['Por correo postal certificado', 'Mediante publicación en el BOE exclusivamente', 'Por el medio que elija cada licitador'], 'La notificación se realizará por medios electrónicos'),
('III', T, 'a1-64', 'La decisión de no adjudicar o celebrar el contrato solo podrá adoptarse:', 'Por razones de interés público debidamente justificadas en el expediente',
 ['Por una infracción no subsanable de las normas de preparación del contrato', 'Cuando lo soliciten la mayoría de los licitadores', 'Cuando la mejor oferta supere el valor estimado'],
 'Solo podrá adoptarse la decisión de no adjudicar o celebrar el contrato por razones de interés público'),
('III', T, 'a1-64', 'El desistimiento del procedimiento de adjudicación debe fundarse en:', 'Una infracción no subsanable de las normas de preparación del contrato o de las reguladoras del procedimiento de adjudicación',
 ['Razones de interés público sobrevenidas', 'La falta de crédito presupuestario', 'La presentación de una sola oferta'],
 'El desistimiento del procedimiento deberá estar fundado en una infracción no subsanable'),
('III', T, 'a1-64', 'El desistimiento del procedimiento de adjudicación:', 'No impide la iniciación inmediata de un procedimiento de licitación',
 ['Impide licitar de nuevo el mismo objeto durante un año', 'Impide licitar de nuevo mientras subsistan sus causas', 'Exige autorización del Consejo de Ministros para volver a licitar'],
 'El desistimiento no impedirá la iniciación inmediata de un procedimiento de licitación'),
('III', T, 'a1-64', 'La decisión de no adjudicar o celebrar el contrato o el desistimiento del procedimiento pueden acordarse por el órgano de contratación:', 'Antes de la formalización',
 ['Antes de la apertura de las ofertas únicamente', 'En cualquier momento de la ejecución', 'Solo antes de la publicación del anuncio de licitación'],
 'podrán acordarse por el órgano de contratación antes de la formalización'),
# Arts. 156-168: procedimientos
('III', T, 'a1-68', 'En el procedimiento abierto:', 'Todo empresario interesado puede presentar una proposición, quedando excluida toda negociación',
 ['Solo pueden presentar proposiciones los empresarios seleccionados', 'Se negocian los términos del contrato con los licitadores', 'Se invita a un mínimo de tres empresas'],
 'En el procedimiento abierto todo empresario interesado podrá presentar una proposición'),
('III', P, 'a1-68', 'Plazo mínimo de presentación de proposiciones en el procedimiento abierto de contratos de obras, suministros y servicios sujetos a regulación armonizada, desde el envío del anuncio a la Oficina de Publicaciones de la UE', '35 días',
 ['30 días', '26 días', '52 días'], 'el plazo de presentación de proposiciones no será inferior a treinta y cinco días'),
('III', P, 'a1-68', 'Plazo mínimo de presentación de proposiciones en el procedimiento abierto de contratos de las Administraciones Públicas no sujetos a regulación armonizada (salvo obras y concesiones)', '15 días',
 ['10 días', '26 días', '20 días'], 'el plazo de presentación de proposiciones no será inferior a quince días, contados desde el día siguiente'),
('III', P, 'a1-68', 'Plazo mínimo de presentación de proposiciones en el procedimiento abierto de contratos de obras y de concesión no sujetos a regulación armonizada', '26 días',
 ['15 días', '20 días', '35 días'], 'el plazo será, como mínimo, de veintiséis días'),
('III', T, 'a1-71', 'El procedimiento abierto simplificado puede utilizarse en contratos de obras de valor estimado igual o inferior a:', '2.000.000 de euros',
 ['5.404.000 euros', '1.000.000 de euros', '500.000 euros'], 'Que su valor estimado sea igual o inferior a 2.000.000 de euros en el caso de contratos de obras'),
('III', T, 'a1-71', 'Para usar el procedimiento abierto simplificado, la ponderación de los criterios evaluables mediante juicio de valor (salvo prestaciones intelectuales) no puede superar:', 'El veinticinco por ciento del total',
 ['El cuarenta y cinco por ciento del total', 'El cincuenta por ciento del total', 'El diez por ciento del total'], 'su ponderación no supere el veinticinco por ciento del total'),
('III', P, 'a1-71', 'Plazo mínimo de presentación de proposiciones en el procedimiento abierto simplificado para contratos de obras', '20 días',
 ['15 días', '10 días', '26 días'], 'En los contratos de obras el plazo será como mínimo de veinte días'),
('III', T, 'a1-71', 'En el procedimiento abierto simplificado, los licitadores deben estar inscritos (o haberlo solicitado) en:', 'El Registro Oficial de Licitadores y Empresas Clasificadas del Sector Público o el registro autonómico correspondiente',
 ['El Registro Mercantil', 'El Registro de Contratos del Sector Público', 'El Registro de Entidades Locales'],
 'deberán estar inscritos en el Registro Oficial de Licitadores y Empresas Clasificadas del Sector Público'),
('III', T, 'a1-71', 'En el procedimiento abierto simplificado, la garantía provisional:', 'No procede',
 ['Es obligatoria del 3 %', 'Es obligatoria del 5 %', 'Procede solo en obras'], 'b) No procederá la constitución de garantía provisional por parte de los licitadores'),
('III', T, 'a1-72', 'En el procedimiento restringido solo pueden presentar proposiciones:', 'Los empresarios que, a su solicitud y en atención a su solvencia, sean seleccionados por el órgano de contratación',
 ['Todos los empresarios interesados', 'Los empresarios invitados sin solicitud previa', 'Los empresarios que hayan participado en las consultas preliminares'],
 'Solo podrán presentar proposiciones aquellos empresarios que, a su solicitud y en atención a su solvencia, sean seleccionados'),
('III', T, 'a1-72', 'Según el artículo 160.4, el procedimiento restringido es especialmente adecuado para:', 'Servicios intelectuales de especial complejidad, como algunos de consultoría, arquitectura o ingeniería',
 ['Suministros de bienes consumibles', 'Contratos de obras de mera conservación', 'Contratos menores'],
 'Este procedimiento es especialmente adecuado cuando se trata de servicios intelectuales de especial complejidad'),
('III', P, 'a1-73', 'Plazo mínimo para presentar solicitudes de participación en el procedimiento restringido de contratos no sujetos a regulación armonizada', '15 días',
 ['10 días', '30 días', '20 días'], 'el plazo para la presentación de solicitudes de participación será, como mínimo, de quince días'),
('III', T, 'a1-74', 'En el procedimiento restringido, el número mínimo de empresarios a los que se invitará a participar no podrá ser inferior a:', 'Cinco',
 ['Tres', 'Seis', 'Diez'], 'que no podrá ser inferior a cinco'),
('III', T, 'a1-80', '¿En cuál de estos casos puede utilizarse el procedimiento negociado sin publicidad en contratos de obras, suministros y servicios?', 'Cuando una imperiosa urgencia por acontecimientos imprevisibles no imputables al órgano de contratación no pueda atenderse con la tramitación urgente',
 ['Siempre que el valor estimado sea inferior a 100.000 euros', 'Cuando así lo prefiera el órgano de contratación por razones de eficacia', 'Cuando el contrato sea de servicios de limpieza'],
 '1.º Una imperiosa urgencia resultante de acontecimientos imprevisibles para el órgano de contratación y no imputables al mismo'),
# Arts. 192-217: ejecución, modificación y extinción
('III', T, 'a1-104', 'La cuantía de cada penalidad por cumplimiento defectuoso no podrá ser superior al:', '10 por ciento del precio del contrato, IVA excluido',
 ['5 por ciento del precio del contrato, IVA excluido', '20 por ciento del precio del contrato, IVA incluido', '50 por ciento del precio del contrato'],
 'las cuantías de cada una de ellas no podrán ser superiores al 10 por ciento del precio del contrato'),
('III', T, 'a1-104', 'El total de las penalidades por cumplimiento defectuoso no podrá superar:', 'El 50 por cien del precio del contrato',
 ['El 10 por cien del precio del contrato', 'El 20 por cien del precio del contrato', 'El importe de la garantía definitiva'], 'ni el total de las mismas superar el 50 por cien del precio del contrato'),
('III', T, 'a1-105', 'La constitución en mora del contratista:', 'No precisa intimación previa por parte de la Administración',
 ['Requiere intimación previa por escrito', 'Requiere declaración judicial', 'Requiere un preaviso de quince días'], 'La constitución en mora del contratista no precisará intimación previa'),
('III', T, 'a1-105', 'Si el contratista incurre en demora en el plazo total por causas imputables a él, la Administración puede imponer penalidades diarias, salvo previsión distinta en el pliego, de:', '0,60 euros por cada 1.000 euros del precio del contrato, IVA excluido',
 ['1 euro por cada 1.000 euros del precio del contrato', '0,20 euros por cada 1.000 euros del precio del contrato', '6 euros por cada 1.000 euros del precio del contrato'],
 'penalidades diarias en la proporción de 0,60 euros por cada 1.000 euros del precio del contrato'),
('III', T, 'a1-105', 'Cada vez que las penalidades por demora alcancen un múltiplo de cierto porcentaje del precio del contrato, el órgano de contratación puede resolverlo o acordar su continuidad con nuevas penalidades. Ese porcentaje es:', 'El 5 por 100',
 ['El 10 por 100', 'El 20 por 100', 'El 3 por 100'], 'Cada vez que las penalidades por demora alcancen un múltiplo del 5 por 100 del precio del contrato'),
('III', T, 'a1-107', 'Si el retraso no es imputable al contratista y este ofrece cumplir si se le amplía el plazo, se le concederá un plazo:', 'Por lo menos igual al tiempo perdido, salvo que pida otro menor',
 ['Igual a la mitad del tiempo perdido', 'De un mes como máximo', 'Igual al doble del tiempo perdido'], 'dándosele un plazo que será, por lo menos, igual al tiempo perdido'),
('III', T, 'a1-109', 'Con carácter general, la ejecución del contrato se realiza:', 'A riesgo y ventura del contratista',
 ['A riesgo y ventura de la Administración', 'Con riesgo compartido por mitades', 'Con garantía de beneficio para el contratista'],
 'La ejecución del contrato se realizará a riesgo y ventura del contratista'),
('III', T, 'a2-15', 'Los contratos administrativos solo podrán ser modificados:', 'Por razones de interés público, en los casos y en la forma previstos en la Ley',
 ['Por acuerdo libre de las partes', 'A solicitud del contratista cuando aumenten sus costes', 'Por decisión de la mesa de contratación'],
 'los contratos administrativos solo podrán ser modificados por razones de interés público'),
('III', T, 'a2-16', 'Modificación máxima (porcentaje del precio inicial) de los contratos de las AAPP cuando esté prevista expresamente en el pliego de cláusulas administrativas particulares:', '20 %',
 ['10 %', '15 %', '50 %'], 'hasta un máximo del veinte por ciento del precio inicial'),
('III', T, 'a2-16', 'Las modificaciones previstas en el pliego de cláusulas administrativas particulares en ningún caso podrán:', 'Alterar la naturaleza global del contrato inicial',
 ['Superar el 10 por ciento del precio inicial', 'Referirse a unidades de obra puntuales', 'Formalizarse por escrito'],
 'modificaciones que puedan alterar la naturaleza global del contrato inicial'),
('III', T, 'a2-18', 'Las modificaciones no previstas del artículo 205 son obligatorias para el contratista cuando la alteración de la cuantía no exceda del:', '20 por ciento del precio inicial, IVA excluido',
 ['10 por ciento del precio inicial, IVA excluido', '50 por ciento del precio inicial, IVA incluido', '15 por ciento del precio inicial, IVA excluido'],
 'una alteración en su cuantía que no exceda del 20 por ciento del precio inicial del contrato'),
('III', P, 'a2-20', 'Plazo de prescripción del derecho del contratista a reclamar los daños y perjuicios por suspensión del contrato, desde que recibe la orden de reanudar la ejecución', '1 año',
 ['2 años', '4 años', '5 años'], 'El derecho a reclamar prescribe en un año'),
('III', T, 'a2-20', 'En la suspensión del contrato, solo se indemnizan los períodos de suspensión:', 'Que estén documentados en la correspondiente acta',
 ['Superiores a un mes', 'Que reconozca la mesa de contratación', 'Declarados por el contratista en su factura'],
 'b) Solo se indemnizarán los períodos de suspensión que estuvieran documentados en la correspondiente acta'),
('III', P, 'a2-22', 'Plazo para el acto formal y positivo de recepción o conformidad, desde la entrega o realización del objeto (salvo otro plazo en el pliego)', '1 mes',
 ['15 días', '2 meses', '3 meses'], 'dentro del mes siguiente a la entrega o realización del objeto del contrato'),
('III', P, 'a2-22', 'Plazo, en contratos distintos de obras, para acordar y notificar la liquidación del contrato y abonar el saldo, desde el acta de recepción o conformidad', '30 días',
 ['15 días', '60 días', '45 días'], 'dentro del plazo de treinta días a contar desde la fecha del acta de recepción o conformidad'),
('III', T, 'a2-23', '¿Cuál de las siguientes NO es causa de resolución del contrato según el artículo 211.1?', 'La revisión de precios conforme a la fórmula del pliego',
 ['El mutuo acuerdo entre la Administración y el contratista', 'La declaración de concurso del contratista', 'El incumplimiento de la obligación principal del contrato'],
 r're:Son causas de resolución del contrato: a\).*?f\) El incumplimiento de la obligación principal del contrato'),
('III', T, 'a2-23', 'Es causa de resolución el retraso injustificado sobre el plan de trabajos, en cualquier actividad, por un plazo superior a:', 'Un tercio del plazo de duración inicial del contrato, incluidas las prórrogas',
 ['La mitad del plazo de duración inicial del contrato', 'Un mes', 'Una cuarta parte del plazo de duración inicial del contrato'],
 'por un plazo superior a un tercio del plazo de duración inicial del contrato'),
('III', T, 'a2-23', 'Cuando concurran diversas causas de resolución con diferentes efectos económicos, se atenderá:', 'A la que haya aparecido con prioridad en el tiempo',
 ['A la más favorable para el contratista', 'A la más favorable para la Administración', 'A la que elija el órgano de contratación'], 'deberá atenderse a la que haya aparecido con prioridad en el tiempo'),
('III', T, 'a2-26', 'Para ceder el contrato, el cedente debe tener ejecutado (salvo concurso y supuestos legales) al menos:', 'Un 20 por 100 del importe del contrato',
 ['Un 10 por 100 del importe del contrato', 'Un 50 por 100 del importe del contrato', 'Un 30 por 100 del importe del contrato'],
 'b) Que el cedente tenga ejecutado al menos un 20 por 100 del importe del contrato'),
('III', P, 'a2-26', 'Plazo para notificar la resolución sobre la solicitud de autorización de cesión del contrato, transcurrido el cual se entiende otorgada', '2 meses',
 ['1 mes', '3 meses', '6 meses'], 'El plazo para la notificación de la resolución sobre la solicitud de autorización será de dos meses'),
('III', T, 'a2-27', 'El contratista que vaya a subcontratar debe comunicar por escrito al órgano de contratación la intención de celebrar los subcontratos:', 'Tras la adjudicación y, a más tardar, cuando inicie la ejecución del contrato',
 ['Antes de presentar su oferta, en todo caso', 'Al finalizar la ejecución del contrato', 'Solo si el subcontrato supera el 50 % del precio'],
 'tras la adjudicación del contrato y, a más tardar, cuando inicie la ejecución de este'),
]
