# Lote 3 · Constitución Española (CE), 2.ª parte: Títulos IV a X (arts. 97-169) · bloque I (art. 134: bloque V, como en lote-001)
# Formato: (bloque, tipo, artículo, pregunta, respuesta correcta, [3 distractores], ancla de la cita en el texto del BOE)
NORMA, LOTE, INICIO = 'CE', 'lote-003', 3001
PREGUNTAS = [
# ---- Título IV ----
('I', 'test', 'a97', 'Según el artículo 97, ¿quién dirige la política interior y exterior, la Administración civil y militar y la defensa del Estado?', 'El Gobierno',
 ['El Rey', 'Las Cortes Generales', 'El Consejo de Estado'],
 'El Gobierno dirige la política interior y exterior, la Administración civil y militar y la defensa del Estado'),
('I', 'test', 'a98', 'Según el artículo 98.1, el Gobierno se compone de:', 'El Presidente, los Vicepresidentes, en su caso, los Ministros y los demás miembros que establezca la ley',
 ['El Presidente y los Ministros, exclusivamente', 'El Presidente, los Vicepresidentes en todo caso y los Ministros', 'El Presidente, los Ministros y los Delegados del Gobierno en las Comunidades Autónomas'],
 'El Gobierno se compone del Presidente, de los Vicepresidentes, en su caso, de los Ministros y de los demás miembros que establezca la ley'),
('I', 'test', 'a99', 'En la primera votación de investidura, el candidato a la Presidencia del Gobierno necesita obtener:', 'La mayoría absoluta del Congreso',
 ['La mayoría simple del Congreso', 'La mayoría absoluta de ambas Cámaras', 'La mayoría de tres quintos del Congreso'],
 'por el voto de la mayoría absoluta de sus miembros, otorgare su confianza a dicho candidato'),
('I', 'plazo', 'a99', 'Nueva votación de investidura, en la que basta la mayoría simple, tras no alcanzarse la mayoría absoluta en la anterior', '48 horas',
 ['24 horas', '72 horas', '12 horas'], 'se someterá la misma propuesta a nueva votación cuarenta y ocho horas después de la anterior'),
('I', 'test', 'a99', 'El Rey propone un candidato a la Presidencia del Gobierno, previa consulta con los representantes designados por los Grupos políticos con representación parlamentaria, y a través de:',
 'El Presidente del Congreso', ['El Presidente del Senado', 'El Presidente del Gobierno en funciones', 'La Junta de Portavoces del Congreso'],
 'y a través del Presidente del Congreso, propondrá un candidato a la Presidencia del Gobierno'),
('I', 'test', 'a101', 'Según el artículo 101.1, el Gobierno cesa:', 'Tras la celebración de elecciones generales, en los casos de pérdida de la confianza parlamentaria, o por dimisión o fallecimiento de su Presidente',
 ['Al finalizar cada período ordinario de sesiones', 'Por decisión del Rey, oído el Consejo de Estado', 'Por la dimisión de la mitad de sus Ministros'],
 'El Gobierno cesa tras la celebración de elecciones generales'),
('I', 'test', 'a101', 'Según el artículo 101.2, el Gobierno cesante:', 'Continuará en funciones hasta la toma de posesión del nuevo Gobierno',
 ['Será sustituido de inmediato por la Diputación Permanente', 'Continuará en funciones durante un plazo máximo de dos meses', 'Cesará en todas sus funciones el mismo día de las elecciones'],
 'El Gobierno cesante continuará en funciones hasta la toma de posesión del nuevo Gobierno'),
('I', 'test', 'a102', 'La acusación contra el Presidente o los miembros del Gobierno por traición o por cualquier delito contra la seguridad del Estado en el ejercicio de sus funciones sólo podrá plantearse:',
 'Por iniciativa de la cuarta parte de los miembros del Congreso, y con la aprobación de la mayoría absoluta del mismo',
 ['Por iniciativa de la décima parte de los Diputados, con la aprobación de la mayoría simple', 'Por el Fiscal General del Estado, previa autorización del Congreso', 'Por iniciativa de la cuarta parte de los Senadores, con la aprobación de la mayoría absoluta del Senado'],
 'sólo podrá ser planteada por iniciativa de la cuarta parte de los miembros del Congreso, y con la aprobación de la mayoría absoluta del mismo'),
('I', 'test', 'a102', '¿Ante qué órgano será exigible la responsabilidad criminal del Presidente y los demás miembros del Gobierno?', 'La Sala de lo Penal del Tribunal Supremo',
 ['El Tribunal Constitucional', 'La Sala de lo Penal de la Audiencia Nacional', 'El Congreso de los Diputados'],
 'será exigible, en su caso, ante la Sala de lo Penal del Tribunal Supremo'),
('I', 'test', 'a103', '¿Cuál de los siguientes NO figura entre los principios de actuación de la Administración Pública enumerados en el artículo 103.1?', 'Transparencia',
 ['Eficacia', 'Jerarquía', 'Desconcentración'],
 'actúa de acuerdo con los principios de eficacia, jerarquía, descentralización, desconcentración y coordinación'),
('I', 'test', 'a103', 'Según el artículo 103.3, la ley regulará el acceso a la función pública de acuerdo con los principios de:', 'Mérito y capacidad',
 ['Antigüedad y experiencia', 'Objetividad y eficacia', 'Jerarquía y coordinación'], 'el acceso a la función pública de acuerdo con los principios de mérito y capacidad'),
('I', 'test', 'a104', 'Según el artículo 104.1, las Fuerzas y Cuerpos de seguridad, bajo la dependencia del Gobierno, tienen como misión:',
 'Proteger el libre ejercicio de los derechos y libertades y garantizar la seguridad ciudadana',
 ['Garantizar la soberanía e independencia de España', 'Velar por la independencia de los Tribunales', 'Supervisar la actividad de la Administración'],
 'tendrán como misión proteger el libre ejercicio de los derechos y libertades y garantizar la seguridad ciudadana'),
('I', 'test', 'a105', 'Según el artículo 105.b), la ley regulará el acceso de los ciudadanos a los archivos y registros administrativos, salvo en lo que afecte a:',
 'La seguridad y defensa del Estado, la averiguación de los delitos y la intimidad de las personas',
 ['Los intereses económicos y comerciales de la Administración', 'La política económica y monetaria del Estado', 'Los procedimientos administrativos en tramitación'],
 'salvo en lo que afecte a la seguridad y defensa del Estado, la averiguación de los delitos y la intimidad de las personas'),
('I', 'test', 'a106', 'Según el artículo 106.2, los particulares tienen derecho a ser indemnizados por toda lesión que sufran en sus bienes y derechos como consecuencia del funcionamiento de los servicios públicos, salvo en los casos de:',
 'Fuerza mayor', ['Caso fortuito', 'Funcionamiento normal de los servicios públicos', 'Culpa leve de la Administración'],
 'salvo en los casos de fuerza mayor, siempre que la lesión sea consecuencia del funcionamiento de los servicios públicos'),
('I', 'test', 'a107', 'Según el artículo 107, el Consejo de Estado es:', 'El supremo órgano consultivo del Gobierno',
 ['El supremo órgano fiscalizador de las cuentas del Estado', 'El órgano de gobierno del Poder Judicial', 'Un alto comisionado de las Cortes Generales'],
 'El Consejo de Estado es el supremo órgano consultivo del Gobierno'),
# ---- Título V ----
('I', 'test', 'a108', 'El Gobierno responde solidariamente en su gestión política ante:', 'El Congreso de los Diputados',
 ['Las Cortes Generales', 'El Senado', 'El Rey'], 'El Gobierno responde solidariamente en su gestión política ante el Congreso de los Diputados'),
('I', 'test', 'a111', 'Para el debate de las interpelaciones y preguntas al Gobierno, los Reglamentos de las Cámaras establecerán:', 'Un tiempo mínimo semanal',
 ['Un tiempo máximo mensual', 'Un tiempo mínimo mensual', 'Un tiempo máximo semanal'], 'Para esta clase de debate los Reglamentos establecerán un tiempo mínimo semanal'),
('I', 'test', 'a112', '¿Quién puede plantear ante el Congreso de los Diputados la cuestión de confianza?', 'El Presidente del Gobierno, previa deliberación del Consejo de Ministros',
 ['El Consejo de Ministros, a propuesta de cualquiera de sus miembros', 'El Presidente del Gobierno, previa autorización del Rey', 'La décima parte de los Diputados'],
 'El Presidente del Gobierno, previa deliberación del Consejo de Ministros, puede plantear ante el Congreso de los Diputados la cuestión de confianza'),
('I', 'test', 'a112', 'En la cuestión de confianza, la confianza se entenderá otorgada cuando vote a favor de la misma:', 'La mayoría simple de los Diputados',
 ['La mayoría absoluta de los Diputados', 'Tres quintos de los Diputados', 'La mayoría simple de ambas Cámaras'],
 'La confianza se entenderá otorgada cuando vote a favor de la misma la mayoría simple de los Diputados'),
('I', 'test', 'a113', '¿Por qué mayoría adopta el Congreso de los Diputados la moción de censura?', 'Mayoría absoluta',
 ['Mayoría simple', 'Mayoría de tres quintos', 'Mayoría de dos tercios'], 'mediante la adopción por mayoría absoluta de la moción de censura'),
('I', 'test', 'a113', 'La moción de censura deberá ser propuesta, al menos, por:', 'La décima parte de los Diputados',
 ['La quinta parte de los Diputados', 'La cuarta parte de los Diputados', 'La mayoría absoluta de los Diputados'],
 'La moción de censura deberá ser propuesta al menos por la décima parte de los Diputados'),
('I', 'plazo', 'a113', 'Votación de la moción de censura: tiempo que debe transcurrir desde su presentación', '5 días',
 ['2 días', '7 días', '10 días'], 'no podrá ser votada hasta que transcurran cinco días desde su presentación'),
('I', 'plazo', 'a113', 'Presentación de mociones de censura alternativas, dentro del período anterior a la votación', 'Los 2 primeros días',
 ['El primer día', 'Los 3 primeros días', 'Los 4 primeros días'], 'En los dos primeros días de dicho plazo podrán presentarse mociones alternativas'),
('I', 'test', 'a113', 'Si la moción de censura no fuere aprobada por el Congreso, sus signatarios:', 'No podrán presentar otra durante el mismo período de sesiones',
 ['No podrán presentar otra durante la misma legislatura', 'No podrán presentar otra hasta transcurrido un año', 'Podrán presentar otra transcurridos dos meses'],
 'sus signatarios no podrán presentar otra durante el mismo período de sesiones'),
('I', 'test', 'a114', 'Si el Congreso adopta una moción de censura:', 'El Gobierno presenta su dimisión al Rey y el candidato incluido en la moción se entiende investido de la confianza de la Cámara',
 ['El Rey abre una nueva ronda de consultas para proponer un candidato', 'El Rey disuelve las Cortes y convoca elecciones', 'El Gobierno continúa en funciones hasta las siguientes elecciones generales'],
 'el candidato incluido en aquélla se entenderá investido de la confianza de la Cámara'),
('I', 'test', 'a115', 'La propuesta de disolución del Congreso, del Senado o de las Cortes Generales no podrá presentarse cuando:', 'Esté en trámite una moción de censura',
 ['Esté en trámite el proyecto de Ley de Presupuestos', 'Las Cámaras estén fuera del período ordinario de sesiones', 'Esté en trámite una proposición de ley de iniciativa popular'],
 'La propuesta de disolución no podrá presentarse cuando esté en trámite una moción de censura'),
('I', 'plazo', 'a115', 'Nueva disolución de las Cámaras desde la anterior (salvo el supuesto del artículo 99.5)', '1 año',
 ['2 años', '3 años', '4 años'], 'No procederá nueva disolución antes de que transcurra un año desde la anterior'),
('I', 'plazo', 'a116', 'Duración máxima del estado de alarma declarado por el Gobierno, sin autorización de prórroga del Congreso', '15 días',
 ['10 días', '30 días', '60 días'], 'por un plazo máximo de quince días'),
('I', 'plazo', 'a116', 'Duración máxima del estado de excepción', '30 días, prorrogables por otro plazo igual',
 ['15 días, prorrogables por otro plazo igual', '60 días, prorrogables por otro plazo igual', '30 días, sin posibilidad de prórroga'],
 'su duración, que no podrá exceder de treinta días, prorrogables por otro plazo igual'),
('I', 'test', 'a116', '¿Cómo se declara el estado de sitio?', 'Por la mayoría absoluta del Congreso de los Diputados, a propuesta exclusiva del Gobierno',
 ['Por el Gobierno mediante decreto acordado en Consejo de Ministros, previa autorización del Congreso', 'Por el Gobierno mediante decreto acordado en Consejo de Ministros, dando cuenta al Congreso', 'Por el Rey, previa autorización de las Cortes Generales'],
 'El estado de sitio será declarado por la mayoría absoluta del Congreso de los Diputados, a propuesta exclusiva del Gobierno'),
('I', 'test', 'a116', '¿Cómo se declara el estado de excepción?', 'Por el Gobierno mediante decreto acordado en Consejo de Ministros, previa autorización del Congreso de los Diputados',
 ['Por el Gobierno mediante decreto, dando cuenta posterior al Congreso', 'Por la mayoría absoluta del Congreso, a propuesta exclusiva del Gobierno', 'Por el Rey, a propuesta del Presidente del Gobierno'],
 'El estado de excepción será declarado por el Gobierno mediante decreto acordado en Consejo de Ministros, previa autorización del Congreso de los Diputados'),
('I', 'test', 'a116', 'Disuelto el Congreso o expirado su mandato, si se produjere alguna de las situaciones que dan lugar a los estados del artículo 116, las competencias del Congreso serán asumidas por:',
 'Su Diputación Permanente', ['El Senado', 'El Gobierno en funciones', 'La Mesa del Congreso'], 'las competencias del Congreso serán asumidas por su Diputación Permanente'),
# ---- Título VI ----
('I', 'test', 'a117', 'Según el artículo 117.1, los Jueces y Magistrados integrantes del poder judicial son:', 'Independientes, inamovibles, responsables y sometidos únicamente al imperio de la ley',
 ['Independientes, inviolables, no sujetos a responsabilidad y sometidos al imperio de la ley', 'Independientes, amovibles, responsables y sometidos al Consejo General del Poder Judicial', 'Imparciales, inamovibles, no sujetos a responsabilidad y sometidos únicamente a la ley'],
 'independientes, inamovibles, responsables y sometidos únicamente al imperio de la ley'),
('I', 'test', 'a117', 'Según el artículo 117.5, ¿qué principio es la base de la organización y funcionamiento de los Tribunales?', 'El principio de unidad jurisdiccional',
 ['El principio de jerarquía', 'El principio de dependencia jerárquica', 'El principio de descentralización'],
 'El principio de unidad jurisdiccional es la base de la organización y funcionamiento de los Tribunales'),
('I', 'test', 'a119', 'Según el artículo 119, la justicia será gratuita cuando así lo disponga la ley y, en todo caso:', 'Respecto de quienes acrediten insuficiencia de recursos para litigar',
 ['En los procesos penales', 'Respecto de los menores de edad', 'En los recursos de amparo'], 'en todo caso, respecto de quienes acrediten insuficiencia de recursos para litigar'),
('I', 'test', 'a120', 'Según el artículo 120.2, el procedimiento judicial será predominantemente oral, sobre todo en materia:', 'Criminal',
 ['Civil', 'Laboral', 'Contencioso-administrativa'], 'El procedimiento será predominantemente oral, sobre todo en materia criminal'),
('I', 'test', 'a121', 'Los daños causados por error judicial darán derecho a una indemnización a cargo de:', 'El Estado',
 ['El Juez o Magistrado que cometió el error', 'El Consejo General del Poder Judicial', 'La parte que se benefició del error'], 'darán derecho a una indemnización a cargo del Estado'),
('I', 'test', 'a122', 'Además del Presidente del Tribunal Supremo, que lo preside, ¿por cuántos miembros nombrados por el Rey está integrado el Consejo General del Poder Judicial?', 'Veinte',
 ['Doce', 'Quince', 'Veintiuno'], 'por veinte miembros nombrados por el Rey por un período de cinco años'),
('I', 'plazo', 'a122', 'Mandato de los miembros del Consejo General del Poder Judicial', '5 años',
 ['4 años', '6 años', '9 años'], 'nombrados por el Rey por un período de cinco años'),
('I', 'test', 'a122', '¿Por qué mayoría eligen el Congreso y el Senado a los miembros del Consejo General del Poder Judicial que les corresponde proponer?', 'Tres quintos de sus miembros',
 ['Mayoría absoluta', 'Dos tercios de sus miembros', 'Mayoría simple'], 'elegidos en ambos casos por mayoría de tres quintos de sus miembros'),
('I', 'test', 'a122', 'De los veinte miembros del Consejo General del Poder Judicial nombrados por el Rey, ¿cuántos lo son entre Jueces y Magistrados de todas las categorías judiciales?', 'Doce',
 ['Ocho', 'Diez', 'Cuatro'], 'De éstos, doce entre Jueces y Magistrados de todas las categorías judiciales'),
('I', 'test', 'a123', 'El Presidente del Tribunal Supremo será nombrado por el Rey, a propuesta de:', 'El Consejo General del Poder Judicial',
 ['El Gobierno', 'El Congreso de los Diputados', 'La Sala de Gobierno del Tribunal Supremo'],
 'El Presidente del Tribunal Supremo será nombrado por el Rey, a propuesta del Consejo General del Poder Judicial'),
('I', 'test', 'a124', 'El Fiscal General del Estado será nombrado por el Rey:', 'A propuesta del Gobierno, oído el Consejo General del Poder Judicial',
 ['A propuesta del Consejo General del Poder Judicial, oído el Gobierno', 'A propuesta del Congreso de los Diputados por mayoría de tres quintos', 'A propuesta del Ministro de Justicia, sin otro trámite'],
 'El Fiscal General del Estado será nombrado por el Rey, a propuesta del Gobierno, oído el Consejo General del Poder Judicial'),
('I', 'test', 'a124', 'Según el artículo 124.2, el Ministerio Fiscal ejerce sus funciones conforme a los principios de:',
 'Unidad de actuación y dependencia jerárquica, con sujeción en todo caso a los de legalidad e imparcialidad',
 ['Independencia e inamovilidad', 'Unidad jurisdiccional y exclusividad', 'Jerarquía, descentralización y coordinación'],
 'conforme a los principios de unidad de actuación y dependencia jerárquica y con sujeción, en todo caso, a los de legalidad e imparcialidad'),
('I', 'test', 'a125', 'Según el artículo 125, ¿mediante qué institución pueden los ciudadanos participar en la Administración de Justicia en los procesos penales que la ley determine?', 'El Jurado',
 ['El Consejo General del Poder Judicial', 'El Ministerio Fiscal', 'La policía judicial'], 'participar en la Administración de Justicia mediante la institución del Jurado'),
('I', 'test', 'a127', 'Los Jueces y Magistrados, así como los Fiscales, mientras se hallen en activo:', 'No podrán desempeñar otros cargos públicos, ni pertenecer a partidos políticos o sindicatos',
 ['Podrán pertenecer a partidos políticos, pero no desempeñar cargos en ellos', 'Podrán afiliarse a sindicatos, pero no a partidos políticos', 'No podrán pertenecer a asociaciones profesionales'],
 'no podrán desempeñar otros cargos públicos, ni pertenecer a partidos políticos o sindicatos'),
# ---- Título VII ----
('V', 'test', 'a134', 'Si la Ley de Presupuestos no se aprobara antes del primer día del ejercicio económico correspondiente:',
 'Se considerarán automáticamente prorrogados los Presupuestos del ejercicio anterior hasta la aprobación de los nuevos',
 ['El Gobierno aprobará los Presupuestos mediante Decreto-ley', 'Se considerarán prorrogados por un máximo de seis meses', 'Se disolverán las Cortes y se convocarán elecciones'],
 'se considerarán automáticamente prorrogados los Presupuestos del ejercicio anterior hasta la aprobación de los nuevos'),
('V', 'test', 'a134', 'Según el artículo 134.7, la Ley de Presupuestos:', 'No puede crear tributos, aunque podrá modificarlos cuando una ley tributaria sustantiva así lo prevea',
 ['Puede crear y modificar tributos libremente', 'Puede crear tributos cuando una ley tributaria sustantiva así lo prevea', 'No puede crear ni modificar tributos en ningún caso'],
 'La Ley de Presupuestos no puede crear tributos. Podrá modificarlos cuando una ley tributaria sustantiva así lo prevea'),
('V', 'test', 'a134', 'Toda proposición o enmienda que suponga aumento de los créditos o disminución de los ingresos presupuestarios requerirá para su tramitación:', 'La conformidad del Gobierno',
 ['La conformidad del Tribunal de Cuentas', 'La mayoría absoluta del Congreso', 'El informe previo del Consejo de Estado'], 'requerirá la conformidad del Gobierno para su tramitación'),
('I', 'test', 'a136', 'Según el artículo 136.1, el Tribunal de Cuentas depende directamente de:', 'Las Cortes Generales',
 ['El Gobierno', 'El Congreso de los Diputados', 'El Ministerio de Hacienda'], 'Dependerá directamente de las Cortes Generales'),
('I', 'test', 'a136', 'Los miembros del Tribunal de Cuentas gozarán de la misma independencia e inamovilidad y estarán sometidos a las mismas incompatibilidades que:', 'Los Jueces',
 ['Los miembros del Tribunal Constitucional', 'Los Diputados y Senadores', 'Los miembros del Gobierno'], 'estarán sometidos a las mismas incompatibilidades que los Jueces'),
('I', 'test', 'a136', 'Según el artículo 136.2, ¿qué remite el Tribunal de Cuentas a las Cortes Generales?', 'Un informe anual',
 ['Un informe semestral', 'Un informe trimestral', 'Un informe al final de cada legislatura'], 'remitirá a las Cortes Generales un informe anual'),
# ---- Título VIII ----
('I', 'test', 'a137', 'Según el artículo 137, el Estado se organiza territorialmente en:', 'Municipios, provincias y las Comunidades Autónomas que se constituyan',
 ['Municipios, comarcas, provincias y Comunidades Autónomas', 'Provincias y Comunidades Autónomas', 'Municipios, provincias, islas y Comunidades Autónomas'],
 'El Estado se organiza territorialmente en municipios, en provincias y en las Comunidades Autónomas que se constituyan'),
('I', 'test', 'a140', 'Según el artículo 140, los Alcaldes serán elegidos:', 'Por los Concejales o por los vecinos',
 ['Siempre por los vecinos mediante sufragio directo', 'Por el Pleno de la Diputación provincial', 'Por la Asamblea de la Comunidad Autónoma'],
 'Los Alcaldes serán elegidos por los Concejales o por los vecinos'),
('I', 'test', 'a141', 'Cualquier alteración de los límites provinciales habrá de ser aprobada por las Cortes Generales mediante:', 'Ley orgánica',
 ['Ley ordinaria', 'Ley de bases', 'Acuerdo de ambas Cámaras por mayoría simple'],
 'Cualquier alteración de los límites provinciales habrá de ser aprobada por las Cortes Generales mediante ley orgánica'),
('I', 'test', 'a141', 'En los archipiélagos, las islas tendrán además su administración propia en forma de:', 'Cabildos o Consejos',
 ['Diputaciones insulares o Mancomunidades', 'Comarcas o Veguerías', 'Juntas o Delegaciones insulares'],
 'las islas tendrán además su administración propia en forma de Cabildos o Consejos'),
('I', 'test', 'a143', 'Según el artículo 143.2, la iniciativa del proceso autonómico corresponde a todas las Diputaciones interesadas o al órgano interinsular correspondiente y a:',
 'Las dos terceras partes de los municipios cuya población represente, al menos, la mayoría del censo electoral de cada provincia o isla',
 ['Las tres cuartas partes de los municipios de cada provincia que representen la mayoría del censo electoral', 'La mayoría absoluta de los municipios de cada provincia', 'La mitad de los municipios que representen dos tercios del censo electoral'],
 'a las dos terceras partes de los municipios cuya población represente, al menos, la mayoría del censo electoral de cada provincia o isla'),
('I', 'plazo', 'a143', 'Cumplimiento de los requisitos de la iniciativa autonómica del artículo 143.2, desde el primer acuerdo adoptado por alguna de las Corporaciones locales interesadas', '6 meses',
 ['3 meses', '9 meses', '12 meses'], 'Estos requisitos deberán ser cumplidos en el plazo de seis meses desde el primer acuerdo'),
('I', 'plazo', 'a143', 'Reiteración de la iniciativa autonómica que no hubiera prosperado', '5 años',
 ['2 años', '3 años', '4 años'], 'La iniciativa, en caso de no prosperar, solamente podrá reiterarse pasados cinco años'),
('I', 'test', 'a145', 'Según el artículo 145.1, en ningún caso se admitirá:', 'La federación de Comunidades Autónomas',
 ['Los convenios entre Comunidades Autónomas para la gestión de servicios propios', 'Los acuerdos de cooperación entre Comunidades Autónomas', 'La agrupación de municipios diferentes de la provincia'],
 'En ningún caso se admitirá la federación de Comunidades Autónomas'),
('I', 'test', 'a145', 'Fuera de los convenios previstos en los Estatutos, los acuerdos de cooperación entre las Comunidades Autónomas necesitarán:', 'La autorización de las Cortes Generales',
 ['La autorización del Gobierno', 'El dictamen del Consejo de Estado', 'La aprobación del Tribunal Constitucional'],
 'los acuerdos de cooperación entre las Comunidades Autónomas necesitarán la autorización de las Cortes Generales'),
('I', 'test', 'a147', 'Según el artículo 147.1, los Estatutos de Autonomía son:', 'La norma institucional básica de cada Comunidad Autónoma',
 ['Leyes ordinarias aprobadas por las Asambleas autonómicas', 'Reglamentos orgánicos del Gobierno autonómico', 'Tratados entre el Estado y cada Comunidad Autónoma'],
 'los Estatutos serán la norma institucional básica de cada Comunidad Autónoma'),
('I', 'test', 'a147', 'La reforma de los Estatutos de Autonomía requerirá, en todo caso:', 'La aprobación por las Cortes Generales, mediante ley orgánica',
 ['La aprobación por mayoría absoluta del Senado', 'El dictamen favorable del Consejo de Estado', 'La autorización del Tribunal Constitucional'],
 'requerirá, en todo caso, la aprobación por las Cortes Generales, mediante ley orgánica'),
('I', 'test', 'a147', '¿Cuál de los siguientes contenidos NO figura entre los que deben contener los Estatutos de autonomía según el artículo 147.2?', 'El régimen electoral de los municipios de la Comunidad',
 ['La delimitación de su territorio', 'La denominación, organización y sede de las instituciones autónomas propias', 'Las competencias asumidas dentro del marco establecido en la Constitución'],
 r're:Los Estatutos de autonomía deberán contener: a\).*?d\) Las competencias asumidas dentro del marco establecido en la Constitución'),
('I', 'plazo', 'a148', 'Ampliación sucesiva de las competencias de las Comunidades Autónomas mediante la reforma de sus Estatutos (artículo 148.2)', '5 años',
 ['3 años', '4 años', '10 años'], 'Transcurridos cinco años, y mediante la reforma de sus Estatutos'),
('I', 'test', 'a148', '¿Cuál de las siguientes materias figura en el artículo 148.1 entre las competencias que pueden asumir las Comunidades Autónomas?', 'Promoción y ordenación del turismo en su ámbito territorial',
 ['Sanidad exterior', 'Estadística para fines estatales', 'Hacienda general y Deuda del Estado'], 'Promoción y ordenación del turismo en su ámbito territorial'),
('I', 'test', 'a149', '¿Cuál de las siguientes materias es competencia exclusiva del Estado según el artículo 149.1?', 'Relaciones internacionales',
 ['Asistencia social', 'Ferias interiores', 'Artesanía'], '3.ª Relaciones internacionales'),
('I', 'test', 'a149', 'Según el artículo 149.3, el derecho estatal será, en todo caso:', 'Supletorio del derecho de las Comunidades Autónomas',
 ['Prevalente sobre el derecho de las Comunidades Autónomas en todas las materias', 'Subordinado al derecho de las Comunidades Autónomas', 'Inaplicable en el territorio de las Comunidades Autónomas'],
 'El derecho estatal será, en todo caso, supletorio del derecho de las Comunidades Autónomas'),
('I', 'test', 'a150', 'Según el artículo 150.3, ¿a quién corresponde apreciar la necesidad de dictar leyes de armonización?', 'A las Cortes Generales, por mayoría absoluta de cada Cámara',
 ['Al Gobierno, previo dictamen del Consejo de Estado', 'Al Tribunal Constitucional', 'Al Congreso de los Diputados, por mayoría de tres quintos'],
 'Corresponde a las Cortes Generales, por mayoría absoluta de cada Cámara, la apreciación de esta necesidad'),
('I', 'test', 'a150', 'Según el artículo 150.2, el Estado podrá transferir o delegar en las Comunidades Autónomas facultades correspondientes a materia de titularidad estatal mediante:', 'Ley orgánica',
 ['Ley marco', 'Ley de armonización', 'Real decreto de traspasos'], 'El Estado podrá transferir o delegar en las Comunidades Autónomas, mediante ley orgánica'),
('I', 'test', 'a152', 'Según el artículo 152.1, ¿qué órgano culminará la organización judicial en el ámbito territorial de la Comunidad Autónoma?', 'Un Tribunal Superior de Justicia',
 ['Una Audiencia Territorial', 'Una Sala del Tribunal Supremo', 'Una Audiencia Provincial'],
 'Un Tribunal Superior de Justicia, sin perjuicio de la jurisdicción que corresponde al Tribunal Supremo, culminará la organización judicial'),
('I', 'test', 'a153', 'El control económico y presupuestario de la actividad de los órganos de las Comunidades Autónomas corresponde a:', 'El Tribunal de Cuentas',
 ['El Tribunal Constitucional', 'El Gobierno, previo dictamen del Consejo de Estado', 'La jurisdicción contencioso-administrativa'],
 'Por el Tribunal de Cuentas, el económico y presupuestario'),
('I', 'test', 'a154', 'Según el artículo 154, ¿quién dirigirá la Administración del Estado en el territorio de la Comunidad Autónoma?', 'Un Delegado nombrado por el Gobierno',
 ['El Presidente de la Comunidad Autónoma', 'Un Delegado elegido por la Asamblea legislativa de la Comunidad', 'Un Subdelegado nombrado por el Ministro del Interior'],
 'Un Delegado nombrado por el Gobierno dirigirá la Administración del Estado en el territorio de la Comunidad Autónoma'),
('I', 'test', 'a155', 'Para adoptar las medidas del artículo 155, el Gobierno necesita, previo requerimiento no atendido al Presidente de la Comunidad Autónoma:', 'La aprobación por mayoría absoluta del Senado',
 ['La aprobación por mayoría absoluta del Congreso', 'La autorización del Tribunal Constitucional', 'La aprobación por mayoría de dos tercios de las Cortes Generales'],
 'con la aprobación por mayoría absoluta del Senado'),
('I', 'test', 'a157', '¿Cuál de los siguientes NO figura entre los recursos de las Comunidades Autónomas enumerados en el artículo 157.1?', 'Los derechos arancelarios de aduanas',
 ['Sus propios impuestos, tasas y contribuciones especiales', 'El producto de las operaciones de crédito', 'Los rendimientos procedentes de su patrimonio'],
 r're:Los recursos de las Comunidades Autónomas estarán constituidos por: a\).*?e\) El producto de las operaciones de crédito'),
('I', 'test', 'a158', 'Según el artículo 158.2, el Fondo de Compensación tiene como destino:', 'Gastos de inversión',
 ['Gastos corrientes', 'Gastos de personal', 'Gastos financieros'], 'se constituirá un Fondo de Compensación con destino a gastos de inversión'),
# ---- Título IX ----
('I', 'test', 'a159', '¿Cuántos miembros del Tribunal Constitucional son nombrados a propuesta del Gobierno?', 'Dos',
 ['Cuatro', 'Tres', 'Uno'], 'dos a propuesta del Gobierno, y dos a propuesta del Consejo General del Poder Judicial'),
('I', 'test', 'a159', '¿Cuántos miembros del Tribunal Constitucional se nombran a propuesta del Senado, y con qué mayoría?', 'Cuatro, por mayoría de tres quintos de sus miembros',
 ['Cuatro, por mayoría absoluta', 'Dos, por mayoría de tres quintos', 'Seis, por mayoría de dos tercios'],
 'cuatro a propuesta del Congreso por mayoría de tres quintos de sus miembros; cuatro a propuesta del Senado, con idéntica mayoría'),
('I', 'test', 'a159', 'Según el artículo 159.2, los miembros del Tribunal Constitucional deberán ser juristas de reconocida competencia con más de:', 'Quince años de ejercicio profesional',
 ['Diez años de ejercicio profesional', 'Veinte años de ejercicio profesional', 'Doce años de ejercicio profesional'],
 'juristas de reconocida competencia con más de quince años de ejercicio profesional'),
('I', 'plazo', 'a159', 'Renovación por terceras partes del Tribunal Constitucional', 'Cada 3 años',
 ['Cada 2 años', 'Cada 4 años', 'Cada 5 años'], 'se renovarán por terceras partes cada tres'),
('I', 'plazo', 'a160', 'Mandato del Presidente del Tribunal Constitucional', '3 años',
 ['2 años', '4 años', '9 años'], 'a propuesta del mismo Tribunal en pleno y por un período de tres años'),
('I', 'test', 'a160', 'El Presidente del Tribunal Constitucional es nombrado por el Rey, entre sus miembros, a propuesta de:', 'El mismo Tribunal en pleno',
 ['El Gobierno', 'El Consejo General del Poder Judicial', 'El Congreso de los Diputados'], 'El Presidente del Tribunal Constitucional será nombrado entre sus miembros por el Rey, a propuesta del mismo Tribunal en pleno'),
('I', 'plazo', 'a161', 'Ratificación o levantamiento, por el Tribunal Constitucional, de la suspensión de una disposición autonómica impugnada por el Gobierno', 'No superior a 5 meses',
 ['No superior a 2 meses', 'No superior a 3 meses', 'No superior a 6 meses'], 'deberá ratificarla o levantarla en un plazo no superior a cinco meses'),
('I', 'test', 'a162', '¿Cuál de los siguientes NO está legitimado para interponer el recurso de inconstitucionalidad según el artículo 162.1.a)?', 'El Ministerio Fiscal',
 ['El Defensor del Pueblo', '50 Senadores', 'El Presidente del Gobierno'],
 'Para interponer el recurso de inconstitucionalidad, el Presidente del Gobierno, el Defensor del Pueblo, 50 Diputados, 50 Senadores'),
('I', 'test', 'a162', 'Según el artículo 162.1.b), están legitimados para interponer el recurso de amparo:',
 'Toda persona natural o jurídica que invoque un interés legítimo, así como el Defensor del Pueblo y el Ministerio Fiscal',
 ['Solo las personas físicas directamente afectadas', 'El Presidente del Gobierno, 50 Diputados o 50 Senadores', 'Solo el Defensor del Pueblo y el Ministerio Fiscal'],
 'toda persona natural o jurídica que invoque un interés legítimo, así como el Defensor del Pueblo y el Ministerio Fiscal'),
('I', 'test', 'a163', 'Según el artículo 163, los efectos del planteamiento de una cuestión de inconstitucionalidad por un órgano judicial:', 'En ningún caso serán suspensivos',
 ['Siempre serán suspensivos', 'Serán suspensivos durante un máximo de cinco meses', 'Serán suspensivos solo en los procesos penales'], 'que en ningún caso serán suspensivos'),
('I', 'test', 'a164', 'Las sentencias del Tribunal Constitucional tienen el valor de cosa juzgada:', 'A partir del día siguiente de su publicación',
 ['Desde la fecha en que se dictan', 'A los veinte días de su publicación', 'Desde su notificación a las partes'],
 'Tienen el valor de cosa juzgada a partir del día siguiente de su publicación y no cabe recurso alguno contra ellas'),
# ---- Título X ----
('I', 'test', 'a166', 'La iniciativa de reforma constitucional se ejercerá en los términos previstos en:', 'Los apartados 1 y 2 del artículo 87',
 ['Los apartados 1, 2 y 3 del artículo 87', 'El apartado 3 del artículo 87', 'El artículo 92'],
 'La iniciativa de reforma constitucional se ejercerá en los términos previstos en los apartados 1 y 2 del artículo 87'),
('I', 'test', 'a167', 'De no lograrse la aprobación por el procedimiento del artículo 167.1, el Congreso podrá aprobar la reforma:',
 'Por mayoría de dos tercios, siempre que el texto hubiere obtenido el voto favorable de la mayoría absoluta del Senado',
 ['Por mayoría de tres quintos, siempre que el texto hubiere obtenido la mayoría simple del Senado', 'Por mayoría absoluta, siempre que el texto hubiere obtenido dos tercios del Senado', 'Por mayoría de dos tercios, sin necesidad de votación favorable en el Senado'],
 'siempre que el texto hubiere obtenido el voto favorable de la mayoría absoluta del Senado, el Congreso, por mayoría de dos tercios, podrá aprobar la reforma'),
('I', 'plazo', 'a167', 'Solicitud de referéndum de ratificación de la reforma constitucional del artículo 167, desde su aprobación por las Cortes Generales', '15 días',
 ['10 días', '20 días', '30 días'], 'dentro de los quince días siguientes a su aprobación'),
('I', 'test', 'a167', 'En el procedimiento del artículo 167, la reforma aprobada se somete a referéndum para su ratificación cuando así lo solicite:', 'Una décima parte de los miembros de cualquiera de las Cámaras',
 ['Una quinta parte de los miembros de cualquiera de las Cámaras', 'La mayoría absoluta del Congreso', 'Una décima parte de los miembros de ambas Cámaras conjuntamente'],
 'una décima parte de los miembros de cualquiera de las Cámaras'),
('I', 'test', 'a168', '¿Cuál de las siguientes reformas exige el procedimiento agravado del artículo 168?', 'Una reforma parcial que afecte al Título II (De la Corona)',
 ['Una reforma del Título VIII (organización territorial)', 'Una reforma del Capítulo tercero del Título I', 'Una reforma del Título III (Cortes Generales)'],
 'o una parcial que afecte al Título preliminar, al Capítulo segundo, Sección primera del Título I, o al Título II'),
('I', 'test', 'a168', 'En el procedimiento del artículo 168, una vez aprobado el principio de la reforma por mayoría de dos tercios de cada Cámara:', 'Se procede a la disolución inmediata de las Cortes',
 ['Se somete directamente a referéndum', 'Se crea una Comisión de composición paritaria', 'Se remite al Tribunal Constitucional para su control previo'],
 'se procederá a la aprobación del principio por mayoría de dos tercios de cada Cámara, y a la disolución inmediata de las Cortes'),
('I', 'test', 'a169', 'Según el artículo 169, no podrá iniciarse la reforma constitucional:', 'En tiempo de guerra o de vigencia de alguno de los estados previstos en el artículo 116',
 ['Durante el último año de la legislatura', 'Sin dictamen previo del Consejo de Estado', 'Mientras esté en trámite una moción de censura'],
 'No podrá iniciarse la reforma constitucional en tiempo de guerra o de vigencia de alguno de los estados previstos en el artículo 116'),
]
