# Lote 25 · Ley 4/2023, para la igualdad real y efectiva de las personas trans y para la garantía de los
# derechos de las personas LGTBI · bloque III (tema III.7: igualdad de trato y no discriminación de las
# personas LGTBI).
NORMA, LOTE, INICIO = 'LTRANS', 'lote-025', 25001
T, P = 'test', 'plazo'
PREGUNTAS = [
('III', T, 'a1', 'La Ley 4/2023 tiene por finalidad garantizar y promover el derecho a la igualdad real y efectiva de:', 'Las personas lesbianas, gais, trans, bisexuales e intersexuales (LGTBI) y de sus familias',
 ['Solo las personas trans mayores de edad', 'Las personas con discapacidad', 'Las víctimas de violencia de género'],
 'garantizar y promover el derecho a la igualdad real y efectiva de las personas lesbianas, gais, trans, bisexuales e intersexuales'),
('III', T, 'a2', 'La Ley 4/2023 se aplica a toda persona física o jurídica, pública o privada, que resida, se encuentre o actúe en territorio español:', 'Cualquiera que fuera su nacionalidad o situación administrativa',
 ['Solo si tiene nacionalidad española', 'Solo si reside legalmente en España', 'Solo si es una Administración pública'],
 'cualquiera que fuera su nacionalidad, origen racial o étnico, religión, domicilio, residencia, edad, estado civil o situación administrativa'),
('III', T, 'a3', 'Según la Ley 4/2023, la situación en que una disposición, criterio o práctica aparentemente neutros ocasiona una desventaja particular por razón de orientación sexual o identidad sexual es:', 'Discriminación indirecta',
 ['Discriminación directa', 'Acoso discriminatorio', 'Discriminación por error'],
 'Discriminación indirecta: Se produce cuando una disposición, criterio o práctica aparentemente neutros ocasiona o puede ocasionar'),
('III', T, 'a3', 'La discriminación que se funda en una apreciación incorrecta acerca de las características de la persona discriminada se denomina:', 'Discriminación por error',
 ['Discriminación por asociación', 'Discriminación indirecta', 'Discriminación múltiple'],
 'La discriminación por error es aquella que se funda en una apreciación incorrecta acerca de las características'),
('III', T, 'a3', 'Según la Ley 4/2023, la denegación de ajustes razonables a las personas con discapacidad se considera:', 'Discriminación directa',
 ['Discriminación indirecta', 'Una infracción leve en todo caso', 'Un trato diferenciado lícito'],
 'Se considerará discriminación directa la denegación de ajustes razonables a las personas con discapacidad'),
('III', T, 'a9', 'El Consejo de Participación de las Personas LGTBI depende:', 'Del Ministerio de Igualdad, a través de la Secretaría de Estado de Igualdad y contra la Violencia de Género',
 ['Del Ministerio de Trabajo', 'De las Cortes Generales', 'Del Defensor del Pueblo'],
 'El Consejo dependerá del Ministerio de Igualdad a través de la Secretaría de Estado de Igualdad y contra la Violencia de Género'),
('III', T, 'a9', 'El Consejo de Participación de las Personas LGTBI presenta una memoria de su actividad con carácter:', 'Semestral',
 ['Anual', 'Trimestral', 'Bienal'], 'El Consejo presentará una memoria con carácter semestral'),
('III', T, 'a1-7', 'Deben contar con un conjunto planificado de medidas para la igualdad de las personas LGTBI, con un protocolo frente al acoso, las empresas de más de:', 'Cincuenta personas trabajadoras',
 ['Diez personas trabajadoras', 'Doscientas cincuenta personas trabajadoras', 'Cien personas trabajadoras'],
 'Las empresas de más de cincuenta personas trabajadoras deberán contar'),
('III', T, 'a1-9', 'La Ley 4/2023 prohíbe las terapias de conversión destinadas a modificar la orientación o identidad sexual o la expresión de género:', 'Incluso si cuentan con el consentimiento de la persona interesada o de su representante legal',
 ['Salvo que cuenten con el consentimiento de la persona interesada', 'Solo cuando se apliquen a menores de edad', 'Solo cuando se presten en centros públicos'],
 'incluso si cuentan con el consentimiento de la persona interesada o de su representante legal'),
('III', T, 'a4-5', 'Puede solicitar por sí misma ante el Registro Civil la rectificación de la mención registral relativa al sexo toda persona de nacionalidad española mayor de:', 'Dieciséis años',
 ['Dieciocho años', 'Catorce años', 'Doce años'], 'Toda persona de nacionalidad española mayor de dieciséis años podrá solicitar por sí misma'),
('III', T, 'a4-5', 'Las personas menores de dieciséis años y mayores de catorce pueden solicitar la rectificación registral del sexo:', 'Por sí mismas, asistidas en el procedimiento por sus representantes legales',
 ['Solo mediante autorización judicial', 'No pueden solicitarla', 'Solo a través del Ministerio Fiscal'],
 'podrán presentar la solicitud por sí mismas, asistidas en el procedimiento por sus representantes legales'),
('III', T, 'a4-5', 'Las personas menores de catorce años y mayores de doce, para modificar la mención registral del sexo, pueden:', 'Solicitar la autorización judicial conforme a la Ley de Jurisdicción Voluntaria',
 ['Presentar la solicitud por sí solas ante el Registro Civil', 'Solicitarlo solo a través de sus progenitores, sin intervención judicial', 'Solicitarlo al Ministerio de Igualdad'],
 'Las personas menores de catorce años y mayores de doce podrán solicitar la autorización judicial'),
('III', T, 'a4-6', 'El ejercicio del derecho a la rectificación registral de la mención relativa al sexo:', 'En ningún caso puede condicionarse a la previa exhibición de informe médico o psicológico',
 ['Requiere informe psicológico favorable', 'Requiere dos años de tratamiento hormonal', 'Requiere informe médico de un centro público'],
 'en ningún caso podrá estar condicionado a la previa exhibición de informe médico o psicológico'),
('III', T, 'a4-6', 'La solicitud de rectificación registral de la mención relativa al sexo puede presentarse ante la persona encargada de:', 'Cualquier Oficina del Registro Civil',
 ['La Oficina del Registro Civil del lugar de nacimiento exclusivamente', 'La Comisaría de Policía que expida el DNI', 'El Juzgado de Primera Instancia'],
 'ante la persona encargada de cualquier Oficina del Registro Civil'),
('III', T, 'a4-8', 'La resolución que acuerda la rectificación de la mención registral del sexo tiene efectos constitutivos a partir de:', 'Su inscripción en el Registro Civil',
 ['La presentación de la solicitud', 'La expedición del nuevo DNI', 'Su publicación en el BOE'],
 'tendrá efectos constitutivos a partir de su inscripción en el Registro Civil'),
('III', T, 'a4-8', 'La rectificación registral del sexo, respecto del régimen jurídico aplicable a efectos de la Ley Orgánica 1/2004 de violencia de género anterior a la inscripción:', 'No lo altera',
 ['Lo deja sin efecto', 'Lo sustituye por el régimen del nuevo sexo con efectos retroactivos', 'Lo suspende durante seis meses'],
 'no alterarán el régimen jurídico que, con anterioridad a la inscripción del cambio registral, fuera aplicable a la persona'),
('III', P, 'a4-9', 'Tiempo desde la inscripción de la rectificación registral del sexo tras el cual puede recuperarse la mención registral anterior', '6 meses',
 ['1 año', '3 meses', '2 años'], 'Transcurridos seis meses desde la inscripción en el Registro Civil de la rectificación'),
('III', T, 'a4-10', 'Las personas trans menores de edad, hayan iniciado o no el procedimiento de rectificación registral del sexo:', 'Tienen derecho a obtener la inscripción registral del cambio de nombre por razones de identidad sexual',
 ['No pueden cambiar de nombre hasta la mayoría de edad', 'Solo pueden cambiar de nombre con autorización judicial', 'Solo pueden usar un nombre social sin inscripción'],
 'tienen derecho a obtener la inscripción registral del cambio de nombre por razones de identidad sexual'),
('III', T, 'a4-11', 'Tras la rectificación registral del sexo, en el nuevo documento nacional de identidad:', 'Se conserva el mismo número',
 ['Se asigna un número nuevo', 'Se añade una letra al número anterior', 'Se suprime el número'],
 'En todo caso, se conservará el mismo número del documento nacional de identidad'),
('III', T, 'a6-6', 'Las cláusulas de los contratos que vulneren el derecho a la no discriminación por razón de orientación sexual o identidad sexual:', 'Son nulas y se tienen por no puestas',
 ['Son anulables a instancia de parte', 'Son válidas si las firmaron ambas partes', 'Solo dan lugar a indemnización'],
 'serán nulas y se tendrán por no puestas'),
('III', T, 'a6-8', 'Cuando quien alega discriminación por razón de orientación o identidad sexual aporta indicios fundados de su existencia:', 'Corresponde a la parte demandada aportar una justificación objetiva y razonable, suficientemente probada',
 ['Debe probar plenamente la discriminación', 'El procedimiento se archiva', 'Debe aportar informe del Ministerio Fiscal'],
 'corresponderá a la parte demandada o a quien se impute la situación discriminatoria la aportación de una justificación objetiva y razonable'),
('III', T, 'a6-5', 'Con el consentimiento expreso de las partes, puede actuar como órgano de mediación o conciliación en casos de discriminación LGTBI:', 'La Autoridad Independiente para la Igualdad de Trato y la No Discriminación',
 ['El Consejo de Participación de las Personas LGTBI', 'El Defensor del Pueblo', 'La Inspección de Trabajo'],
 'la Autoridad Independiente para la Igualdad de Trato y la No Discriminación, podrá actuar como órgano de mediación o conciliación'),
('III', T, 'a7-9', 'En la Administración General del Estado, el procedimiento sancionador de la Ley 4/2023 se inicia:', 'Siempre de oficio',
 ['Siempre a instancia de la persona afectada', 'Solo por denuncia del Ministerio Fiscal', 'De oficio o a instancia de parte, indistintamente'],
 'En el ámbito de la Administración General del Estado, el procedimiento se iniciará siempre de oficio'),
('III', T, 'a7-9', 'En la Administración General del Estado, cuando se trate de infracciones muy graves y la sanción propuesta exceda de 100.000 euros, es competente para resolver:', 'El Consejo de Ministros',
 ['La persona titular del Ministerio de Igualdad', 'La Dirección General de Diversidad Sexual y Derechos LGTBI', 'El Presidente del Gobierno'],
 'cuando se trate de infracciones muy graves y el importe de la sanción propuesta exceda los 100.000 euros, será competente el Consejo de Ministros'),
('III', P, 'a7-10', 'Plazo máximo para notificar la resolución del procedimiento sancionador de la Ley 4/2023', '6 meses',
 ['3 meses', '1 año', '18 meses'], 'El plazo máximo en que deberá notificarse la resolución del procedimiento sancionador será de seis meses'),
('III', T, 'a7-11', 'Según la Ley 4/2023, el acoso discriminatorio por razón de orientación e identidad sexual, cuando no constituya infracción penal, es infracción:', 'Muy grave',
 ['Leve', 'Grave', 'No constituye infracción administrativa'],
 'Son infracciones administrativas muy graves: a) El acoso discriminatorio'),
('III', T, 'a7-11', 'Utilizar o emitir expresiones vejatorias por razón de orientación e identidad sexual en la prestación de servicios públicos o privados es, según la Ley 4/2023, infracción:', 'Leve',
 ['Grave', 'Muy grave', 'No constituye infracción'],
 'Son infracciones administrativas leves: a) Utilizar o emitir expresiones vejatorias'),
('III', T, 'a8-2', 'Las infracciones leves de la Ley 4/2023 se sancionan con:', 'Apercibimiento o multa de 200 a 2.000 euros',
 ['Multa de 2.001 a 10.000 euros', 'Multa de 10.001 a 150.000 euros', 'Cierre del establecimiento'],
 'Las infracciones leves serán sancionadas con apercibimiento o con multa de 200 a 2.000 euros'),
('III', T, 'a8-2', 'Las infracciones muy graves de la Ley 4/2023 se sancionan con multa de:', '10.001 a 150.000 euros',
 ['2.001 a 10.000 euros', '200 a 2.000 euros', '150.001 a 600.000 euros'], 'Las infracciones muy graves serán sancionadas con multa de 10.001 a 150.000 euros'),
('III', P, 'a8-3', 'Plazo de prescripción de las infracciones muy graves de la Ley 4/2023', '3 años',
 ['2 años', '4 años', '5 años'], 'Las infracciones muy graves prescribirán a los tres años'),
('III', P, 'a8-3', 'Plazo de prescripción de las infracciones leves de la Ley 4/2023', '9 meses',
 ['6 meses', '1 año', '3 meses'], 'y las leves a los nueve meses'),
]
