# Lote 23 · Ley 53/1984, de Incompatibilidades del personal al servicio de las Administraciones Públicas ·
# bloque IV (tema IV.6: régimen de incompatibilidades).
NORMA, LOTE, INICIO = 'LINC', 'lote-023', 23001
T, P = 'test', 'plazo'
PREGUNTAS = [
('IV', T, 'aprimero', 'Como regla general, el personal incluido en la Ley 53/1984:', 'No puede compatibilizar sus actividades con el desempeño de un segundo puesto de trabajo, cargo o actividad en el sector público, salvo en los supuestos previstos en ella',
 ['Puede desempeñar libremente un segundo puesto en el sector público', 'Puede desempeñar hasta dos puestos públicos sin autorización', 'Solo necesita comunicar el segundo puesto a su superior'],
 'no podrá compatibilizar sus actividades con el desempeño, por sí o mediante sustitución, de un segundo puesto de trabajo, cargo o actividad en el sector público'),
('IV', T, 'aprimero', 'A efectos de la Ley 53/1984, se entiende por remuneración:', 'Cualquier derecho de contenido económico derivado, directa o indirectamente, de una prestación o servicio personal',
 ['Solo el sueldo base', 'Solo las retribuciones periódicas fijas', 'Solo las cantidades superiores al salario mínimo'],
 'se entenderá por remuneración cualquier derecho de contenido económico derivado, directa o indirectamente, de una prestación o servicio personal'),
('IV', T, 'aprimero', 'El desempeño de un puesto por el personal incluido en la Ley 53/1984 es incompatible, en cualquier caso, con el ejercicio de cualquier cargo, profesión o actividad que:', 'Pueda impedir o menoscabar el estricto cumplimiento de sus deberes o comprometer su imparcialidad o independencia',
 ['Esté retribuido con más de 600 euros mensuales', 'Se realice fuera del horario de trabajo', 'Se desarrolle en otra provincia'],
 'que pueda impedir o menoscabar el estricto cumplimiento de sus deberes o comprometer su imparcialidad o independencia'),
('IV', T, 'asegundo', 'La Ley 53/1984 se aplica al personal de las empresas en que la participación del capital de las Administraciones Públicas sea:', 'Superior al 50 por 100',
 ['Superior al 25 por 100', 'Igual o superior al 10 por 100', 'Del 100 por 100 exclusivamente'],
 'h) El personal que preste servicios en Empresas en que la participación del capital, directa o indirectamente, de las Administraciones Públicas sea superior al 50 por 100'),
('IV', T, 'asegundo', 'Dentro del ámbito de la Ley 53/1984 se incluye todo el personal:', 'Cualquiera que sea la naturaleza jurídica de la relación de empleo',
 ['Solo funcionario de carrera', 'Solo funcionario y eventual', 'Excepto el personal laboral'],
 'se entenderá incluido todo el personal, cualquiera que sea la naturaleza jurídica de la relación de empleo'),
('IV', T, 'atercero', 'Para ejercer una segunda actividad en el sector público es indispensable:', 'La previa y expresa autorización de compatibilidad',
 ['La simple comunicación posterior', 'El silencio de la Administración durante un mes', 'La conformidad del jefe inmediato'],
 'Para el ejercicio de la segunda actividad será indispensable la previa y expresa autorización de compatibilidad'),
('IV', T, 'atercero', 'La autorización de compatibilidad para un segundo puesto público:', 'No supone modificación de la jornada de trabajo y horario de los dos puestos',
 ['Permite reducir la jornada del puesto principal', 'Permite acumular las jornadas en el segundo puesto', 'Exime del control horario en ambos puestos'],
 'que no supondrá modificación de la jornada de trabajo y horario de los dos puestos'),
('IV', T, 'atercero', 'El desempeño de un puesto de trabajo en el sector público es, con carácter general:', 'Incompatible con la percepción de pensión de jubilación o retiro por Derechos Pasivos o por un régimen público y obligatorio de Seguridad Social',
 ['Compatible con cualquier pensión de jubilación', 'Compatible con la pensión si no supera el salario mínimo', 'Compatible con la pensión durante los dos primeros años'],
 'es incompatible con la percepción de pensión de jubilación o retiro por Derechos Pasivos o por cualquier régimen de Seguridad Social público y obligatorio'),
('IV', T, 'atercero', 'Mientras dura el desempeño de un puesto en el sector público, la percepción de la pensión de jubilación:', 'Queda en suspenso, sin que ello afecte a sus actualizaciones',
 ['Se extingue definitivamente', 'Se reduce a la mitad', 'Se mantiene íntegra'],
 'La percepción de las pensiones indicadas quedará en suspenso por el tiempo que dure el desempeño de dicho puesto'),
('IV', T, 'acuarto', 'Puede autorizarse la compatibilidad para un puesto en la esfera docente como Profesor universitario asociado en régimen de dedicación:', 'No superior a la de tiempo parcial',
 ['A tiempo completo', 'Exclusiva', 'De al menos treinta horas semanales'],
 'como Profesor universitario asociado en régimen de dedicación no superior a la de tiempo parcial'),
('IV', T, 'aquinto', 'El personal incluido en la Ley 53/1984 puede compatibilizar sus actividades con el cargo de miembro de una Corporación local:', 'Salvo que desempeñe en ella cargos retribuidos en régimen de dedicación exclusiva',
 ['En ningún caso', 'Solo si renuncia a toda retribución en la Administración', 'Solo en municipios de menos de 5.000 habitantes'],
 'b) Miembros de las Corporaciones locales, salvo que desempeñen en las mismas cargos retribuidos en régimen de dedicación exclusiva'),
('IV', T, 'aquinto', 'En los supuestos de compatibilidad con cargos electivos del artículo 5, como regla general:', 'Sólo puede percibirse la retribución de una de las dos actividades, sin perjuicio de las dietas, indemnizaciones o asistencias de la otra',
 ['Se perciben íntegras ambas retribuciones', 'No puede percibirse ninguna retribución por el cargo electivo ni dietas', 'Se percibe la suma de ambas reducida en un 30 por 100'],
 'sólo podrá percibirse la retribución correspondiente a una de las dos actividades, sin perjuicio de las dietas, indemnizaciones o asistencias que correspondan por la otra'),
('IV', T, 'aseptimo', 'Para autorizar la compatibilidad de actividades públicas, la cantidad total percibida por ambos puestos no puede superar la remuneración prevista en los Presupuestos Generales del Estado para el cargo de:', 'Director General',
 ['Ministro', 'Secretario de Estado', 'Subdirector General'], 'no supere la remuneración prevista en los Presupuestos Generales del Estado para el cargo de Director General'),
('IV', T, 'aseptimo', 'Para los funcionarios del grupo A, la cantidad total percibida por ambos puestos compatibles no puede superar la del principal incrementada en:', 'Un 30 por 100',
 ['Un 50 por 100', 'Un 40 por 100', 'Un 20 por 100'], 'Un 30 por 100, para los funcionarios del grupo A'),
('IV', T, 'aseptimo', 'Para los funcionarios del grupo C, la cantidad total percibida por ambos puestos compatibles no puede superar la del principal incrementada en:', 'Un 40 por 100',
 ['Un 30 por 100', 'Un 35 por 100', 'Un 50 por 100'], 'Un 40 por 100, para los funcionarios del grupo C'),
('IV', T, 'aseptimo', 'Los servicios prestados en el segundo puesto o actividad compatible:', 'No se computan a efectos de trienios ni de derechos pasivos',
 ['Se computan a efectos de trienios', 'Se computan doble a efectos de derechos pasivos', 'Dan derecho a pagas extraordinarias en ambos puestos'],
 'no se computarán a efectos de trienios ni de derechos pasivos'),
('IV', T, 'aseptimo', 'En caso de compatibilidad, las pagas extraordinarias y las prestaciones de carácter familiar:', 'Sólo pueden percibirse por uno de los puestos',
 ['Se perciben por ambos puestos', 'No se perciben por ninguno', 'Se perciben por el puesto mejor retribuido y la mitad por el otro'],
 'Las pagas extraordinarias, así como las prestaciones de carácter familiar, sólo podrán percibirse por uno de los puestos'),
('IV', T, 'aoctavo', 'El personal que, en representación del sector público, pertenezca a Consejos de Administración de entidades o empresas:', 'Sólo puede percibir las dietas o indemnizaciones que correspondan por su asistencia',
 ['Percibe íntegra la retribución de consejero', 'No puede percibir ninguna cantidad', 'Percibe la retribución de consejero si no supera la del puesto principal'],
 'sólo podrá percibir las dietas o indemnizaciones que correspondan por su asistencia a los mismos'),
('IV', T, 'aoctavo', 'Salvo autorización excepcional, no se puede pertenecer a más de:', 'Dos Consejos de Administración u órganos de gobierno',
 ['Un Consejo de Administración', 'Tres Consejos de Administración', 'Cinco Consejos de Administración'],
 'No se podrá pertenecer a más de dos Consejos de Administración u órganos de gobierno'),
('IV', T, 'adiez', 'Si quien accede a un nuevo puesto público incompatible con el que venía desempeñando no ejerce la opción en el plazo de toma de posesión:', 'Se entiende que opta por el nuevo puesto, pasando a excedencia voluntaria en el que venía desempeñando',
 ['Se entiende que opta por el puesto anterior', 'Pierde ambos puestos', 'Se le declara en suspensión de funciones'],
 'A falta de opción en el plazo señalado se entenderá que optan por el nuevo puesto, pasando a la situación de excedencia voluntaria'),
('IV', P, 'adiez', 'Plazo, dentro del plazo de toma de posesión, para instar la autorización de compatibilidad cuando se accede a un puesto susceptible de ella', 'Los 10 primeros días',
 ['Los 5 primeros días', 'Los 15 primeros días', 'El mes siguiente a la toma de posesión'], 'deberán instarla en los diez primeros días del aludido plazo de toma de posesión'),
('IV', T, 'adoce', 'El personal incluido en la Ley 53/1984 no puede ejercer actividades privadas en los asuntos en que haya intervenido por razón del puesto público en:', 'Los dos últimos años',
 ['El último año', 'Los cinco últimos años', 'Los seis últimos meses'], 'haya intervenido en los dos últimos años'),
('IV', T, 'adoce', 'Está prohibida la participación en el capital de empresas concesionarias o contratistas del sector público cuando sea superior al:', '10 por 100',
 ['5 por 100', '25 por 100', '50 por 100'], 'd) La participación superior al 10 por 100 en el capital de las Empresas o Sociedades'),
('IV', T, 'atrece', 'No puede reconocerse compatibilidad para actividades privadas a quien tenga autorizado un segundo puesto público cuando:', 'La suma de jornadas de ambos sea igual o superior a la máxima en las Administraciones Públicas',
 ['Ambos puestos sean de la misma Administración', 'El segundo puesto sea docente', 'Lo solicite fuera del horario de trabajo'],
 'siempre que la suma de jornadas de ambos sea igual o superior a la máxima en las Administraciones Públicas'),
('IV', P, 'acatorce', 'Plazo para dictar la resolución motivada sobre el reconocimiento de compatibilidad para actividades privadas', '2 meses',
 ['1 mes', '3 meses', '15 días'], 'que se dictará en el plazo de dos meses'),
('IV', T, 'acatorce', 'Los reconocimientos de compatibilidad para actividades privadas, en caso de cambio de puesto en el sector público:', 'Quedan automáticamente sin efecto',
 ['Se mantienen en todo caso', 'Se prorrogan durante seis meses', 'Se convierten en autorización para el nuevo puesto'],
 'quedarán automáticamente sin efecto en caso de cambio de puesto en el sector público'),
('IV', T, 'aquince', 'Según la Ley 53/1984, el personal a su servicio:', 'No puede invocar o hacer uso de su condición pública para el ejercicio de actividad mercantil, industrial o profesional',
 ['Puede usar su condición pública como mérito profesional', 'Puede invocarla si tiene autorización de compatibilidad', 'Puede usarla en actividades mercantiles fuera de su provincia'],
 'no podrá invocar o hacer uso de su condición pública para el ejercicio de actividad mercantil, industrial o profesional'),
('IV', T, 'adieciocho', 'Las resoluciones de compatibilidad se inscriben en:', 'Los Registros de Personal correspondientes',
 ['El Registro Mercantil', 'El Boletín Oficial del Estado', 'El Registro de Intereses del Congreso'], 'se inscribirán en los Registros de Personal correspondientes'),
('IV', T, 'adiecinueve', '¿Cuál de las siguientes actividades está exceptuada del régimen de incompatibilidades?', 'La participación en Tribunales calificadores de pruebas selectivas para ingreso en las Administraciones Públicas',
 ['El ejercicio de la abogacía en asuntos del propio Departamento', 'El desempeño de cargos en empresas contratistas del sector público', 'La pertenencia a Consejos de Administración de empresas privadas relacionadas con el Departamento'],
 'c) La participación en Tribunales calificadores de pruebas selectivas para ingreso en las Administraciones Públicas'),
('IV', T, 'adiecinueve', 'Está exceptuado del régimen de incompatibilidades el dictado de cursos o conferencias en centros oficiales de formación de funcionarios cuando no tenga carácter permanente o habitual ni suponga más de:', 'Setenta y cinco horas al año',
 ['Cien horas al año', 'Cincuenta horas al año', 'Ciento cincuenta horas al año'], 'ni supongan más de setenta y cinco horas al año'),
('IV', T, 'adiecinueve', 'La producción y creación literaria, artística, científica y técnica está exceptuada del régimen de incompatibilidades:', 'Siempre que no se origine como consecuencia de una relación de empleo o de prestación de servicios',
 ['Solo si no está retribuida', 'Solo con autorización previa', 'Nunca'],
 'siempre que no se originen como consecuencia de una relación de empleo o de prestación de servicios'),
('IV', T, 'aveinte', 'La autorización o reconocimiento de compatibilidad queda automáticamente revocada si, por incumplir el deber de residencia, asistencia o diligencia, la falta se califica como:', 'Grave o muy grave',
 ['Leve', 'Muy grave únicamente', 'Cualquier falta, incluida la leve'],
 'quedando automáticamente revocada la autorización o reconocimiento de compatibilidad si en la resolución correspondiente se califica de falta grave o muy grave'),
]
