# Lote 27 · Ley 39/2006, de Promoción de la Autonomía Personal y Atención a las personas en situación de
# dependencia · bloque III (tema III.7: dependencia). Ojo: la Ley 4/2026 reforma muchos artículos con
# efectos de 23-10-2026; solo se pregunta lo que no cambia con esa reforma (no el plazo de 3 meses del
# art. 28.1 ni el catálogo de servicios del art. 15, que sí cambian).
NORMA, LOTE, INICIO = 'LDEP', 'lote-027', 27001
T, P = 'test', 'plazo'
PREGUNTAS = [
('III', T, 'a1', 'La Ley 39/2006 crea, para garantizar la promoción de la autonomía personal y la atención a las personas en situación de dependencia:', 'El Sistema para la Autonomía y Atención a la Dependencia',
 ['El Instituto de Mayores y Servicios Sociales', 'La Agencia Estatal de Dependencia', 'El Fondo Nacional de Asistencia Social'],
 'mediante la creación de un Sistema para la Autonomía y Atención a la Dependencia'),
('III', T, 'a6', 'El Sistema para la Autonomía y Atención a la Dependencia se configura como:', 'Una red de utilización pública que integra, de forma coordinada, centros y servicios, públicos y privados',
 ['Una red exclusivamente pública de centros estatales', 'Un organismo autónomo de la Seguridad Social', 'Un fondo de financiación sin centros propios'],
 'El Sistema se configura como una red de utilización pública que integra, de forma coordinada, centros y servicios, públicos y privados'),
('III', T, 'a6', 'La integración de un centro o servicio en el Sistema para la Autonomía y Atención a la Dependencia:', 'No supone alteración alguna en el régimen jurídico de su titularidad, administración, gestión y dependencia orgánica',
 ['Supone su transferencia a la Comunidad Autónoma', 'Implica su conversión en centro público', 'Obliga a su gestión directa por la Administración General del Estado'],
 'no supondrá alteración alguna en el régimen jurídico de su titularidad, administración, gestión y dependencia orgánica'),
('III', T, 'a7', 'El nivel de protección mínimo del Sistema para la Autonomía y Atención a la Dependencia lo establece:', 'La Administración General del Estado',
 ['Cada Ayuntamiento', 'Cada Diputación provincial', 'El Consejo de Estado'],
 'El nivel de protección mínimo establecido por la Administración General del Estado'),
('III', T, 'a8', 'En la composición del Consejo Territorial de Servicios Sociales y del Sistema para la Autonomía y Atención a la Dependencia tienen mayoría:', 'Los representantes de las comunidades autónomas',
 ['Los representantes de la Administración General del Estado', 'Los representantes de las entidades locales', 'Las organizaciones de personas usuarias'],
 'En la composición del Consejo Territorial tendrán mayoría los representantes de las comunidades autónomas'),
('III', T, 'a5', 'Para ser titular de los derechos de la Ley 39/2006 es requisito, con carácter general, residir en territorio español y haberlo hecho durante:', 'Cinco años, de los cuales dos deberán ser inmediatamente anteriores a la solicitud',
 ['Dos años inmediatamente anteriores a la solicitud', 'Diez años, cinco de ellos inmediatamente anteriores', 'Un año inmediatamente anterior a la solicitud'],
 'Residir en territorio español y haberlo hecho durante cinco años, de los cuales dos deberán ser inmediatamente anteriores a la fecha de presentación de la solicitud'),
('III', T, 'a17', 'La prestación económica vinculada al servicio se reconoce:', 'Únicamente cuando no sea posible el acceso a un servicio público o concertado de atención y cuidado',
 ['En todo caso, a elección del beneficiario', 'Solo a las personas con Grado I', 'Como complemento de cualquier servicio público'],
 'únicamente cuando no sea posible el acceso a un servicio público o concertado de atención y cuidado'),
('III', T, 'a17', 'La prestación económica vinculada al servicio está, en todo caso:', 'Vinculada a la adquisición de un servicio',
 ['Libre de cualquier justificación', 'Destinada a retribuir al cuidador familiar', 'Limitada a un pago único'],
 'Esta prestación económica de carácter personal estará, en todo caso, vinculada a la adquisición de un servicio'),
('III', T, 'a26', 'Según la Ley 39/2006, la dependencia moderada corresponde al:', 'Grado I',
 ['Grado II', 'Grado III', 'Grado 0'], 'a) Grado I. Dependencia moderada'),
('III', T, 'a26', 'Según la Ley 39/2006, la gran dependencia corresponde al:', 'Grado III',
 ['Grado I', 'Grado II', 'Grado IV'], 'c) Grado III. Gran dependencia'),
('III', T, 'a26', 'La dependencia severa (Grado II) se da cuando la persona necesita ayuda para realizar varias actividades de la vida diaria:', 'Dos o tres veces al día, sin requerir el apoyo permanente de una persona cuidadora',
 ['Al menos una vez al día', 'Varias veces al día con apoyo indispensable y continuo de otra persona', 'Una vez a la semana'],
 'b) Grado II. Dependencia severa: cuando la persona necesita ayuda para realizar varias actividades de la vida diaria dos o tres veces al día'),
('III', T, 'a27', 'Los órganos de valoración de la situación de dependencia los determinan:', 'Las comunidades autónomas',
 ['El Ministerio de Sanidad', 'Los Ayuntamientos', 'El Instituto Nacional de la Seguridad Social'],
 'Las comunidades autónomas determinarán los órganos de valoración de la situación de dependencia'),
('III', T, 'a27', 'El baremo para valorar los grados de dependencia se acuerda en el Consejo Territorial y se aprueba por:', 'El Gobierno mediante real decreto',
 ['Cada comunidad autónoma mediante decreto', 'Las Cortes Generales mediante ley', 'Orden del Ministerio de Hacienda'],
 'para su posterior aprobación por el Gobierno mediante real decreto. Dicho baremo tendrá entre sus referentes'),
('III', T, 'a28', 'El reconocimiento de la situación de dependencia se efectúa mediante resolución de:', 'La Administración Autonómica correspondiente a la residencia del solicitante, con validez en todo el territorio del Estado',
 ['La Administración General del Estado', 'El Ayuntamiento del domicilio, con validez solo municipal', 'El Juzgado de Primera Instancia'],
 'mediante resolución expedida por la Administración Autonómica correspondiente a la residencia del solicitante y tendrá validez en todo el territorio del Estado'),
('III', T, 'a28', 'Los servicios de valoración de la situación de dependencia y la gestión de sus prestaciones económicas:', 'Se efectúan directamente por las Administraciones Públicas, sin poder ser objeto de delegación, contratación o concierto con entidades privadas',
 ['Pueden contratarse con entidades privadas', 'Corresponden a las mutuas colaboradoras', 'Se conciertan con entidades del tercer sector'],
 'no pudiendo ser objeto de delegación, contratación o concierto con entidades privadas'),
('III', T, 'a30', 'El grado de dependencia es revisable, entre otras causas, por:', 'Mejoría o empeoramiento de la situación de dependencia, o error de diagnóstico o en la aplicación del baremo',
 ['El cambio de domicilio dentro del mismo municipio', 'El transcurso de un año en todo caso', 'La jubilación de la persona cuidadora'],
 r're:a\) Mejoría o empeoramiento de la situación de dependencia\. b\) Error de diagnóstico o en la aplicación del correspondiente baremo'),
('III', P, 'a46', 'Plazo de prescripción de las infracciones muy graves de la Ley 39/2006', '4 años',
 ['3 años', '5 años', '1 año'], 'c) A los cuatro años, las muy graves'),
]
