# Lote 5 · Ley 39/2015 (L39): interesados, silencio, plazos, actos, nulidad, procedimiento, ejecución,
# revisión de oficio y recursos · bloque III. Amplía lote-001 sin repetir sus preguntas.
# Formato: (bloque, tipo, artículo, pregunta, respuesta correcta, [3 distractores], ancla de la cita en el texto del BOE)
NORMA, LOTE, INICIO = 'L39', 'lote-005', 5001
T, P = 'test', 'plazo'
PREGUNTAS = [
('III', T, 'a3', 'Según el artículo 3, los grupos de afectados, las uniones y entidades sin personalidad jurídica y los patrimonios independientes o autónomos tienen capacidad de obrar ante las Administraciones Públicas:', 'Cuando la Ley así lo declare expresamente',
 ['En todo caso', 'En ningún caso', 'Cuando lo autorice el órgano competente para resolver'], 'Cuando la Ley así lo declare expresamente, los grupos de afectados'),
('III', T, 'a4', 'Según el artículo 4.1.c), quienes tengan intereses legítimos que puedan resultar afectados por la resolución son interesados si:', 'Se personan en el procedimiento en tanto no haya recaído resolución definitiva',
 ['Lo solicitan dentro de los diez días siguientes al inicio del procedimiento', 'Han presentado una denuncia', 'Son mayores de edad'], 'y se personen en el procedimiento en tanto no haya recaído resolución definitiva'),
('III', T, 'a4', 'Cuando la condición de interesado derive de alguna relación jurídica transmisible, el derecho-habiente:', 'Sucederá en tal condición cualquiera que sea el estado del procedimiento',
 ['Deberá iniciar un nuevo procedimiento', 'Solo sucederá si aún no se ha abierto el trámite de audiencia', 'No sucederá en la condición de interesado'], 'el derecho-habiente sucederá en tal condición cualquiera que sea el estado del procedimiento'),
('III', T, 'a5', 'Según el artículo 5.3, ¿para cuál de las siguientes actuaciones se presume la representación?', 'Los actos y gestiones de mero trámite',
 ['Interponer recursos', 'Desistir de acciones', 'Renunciar a derechos'], 'Para los actos y gestiones de mero trámite se presumirá aquella representación'),
('III', P, 'a5', 'Aportación de la acreditación de la representación o subsanación de su defecto (plazo que debe conceder el órgano, salvo que las circunstancias requieran uno superior)', '10 días',
 ['5 días', '15 días', '20 días'], 'dentro del plazo de diez días que deberá conceder al efecto el órgano administrativo'),
('III', P, 'a6', 'Validez máxima de los poderes inscritos en los registros electrónicos de apoderamientos, desde la fecha de inscripción', '5 años',
 ['2 años', '3 años', '10 años'], 'Los poderes inscritos en el registro tendrán una validez determinada máxima de cinco años'),
('III', T, 'a7', 'Cuando en una solicitud figuren varios interesados y no se haya señalado expresamente con quién entenderse, las actuaciones se efectuarán con:', 'El que figure en primer término',
 ['Todos ellos por separado', 'El de mayor edad', 'El que resida más cerca del órgano competente'], 'y, en su defecto, con el que figure en primer término'),
('III', P, 'a22', 'Suspensión máxima del plazo para resolver por la petición de informes preceptivos a un órgano de la misma o distinta Administración', '3 meses',
 ['1 mes', '2 meses', '6 meses'], 'Este plazo de suspensión no podrá exceder en ningún caso de tres meses'),
('III', T, 'a22', '¿En cuál de los siguientes casos el artículo 22.2 establece que el plazo máximo para resolver se suspenderá (y no solo que se podrá suspender)?', 'Cuando los interesados promuevan la recusación, desde que se plantee hasta que sea resuelta',
 ['Cuando se soliciten informes preceptivos', 'Cuando deba requerirse al interesado para que subsane deficiencias', 'Cuando se inicien negociaciones para concluir un pacto o convenio'],
 r're:se suspenderá en los siguientes casos: a\).*?c\) Cuando los interesados promuevan la recusación'),
('III', T, 'a23', 'Contra el acuerdo que resuelva sobre la ampliación del plazo máximo de resolución y notificación:', 'No cabrá recurso alguno',
 ['Cabe recurso de alzada', 'Cabe recurso potestativo de reposición', 'Cabe recurso contencioso-administrativo directo'],
 'Contra el acuerdo que resuelva sobre la ampliación de plazos, que deberá ser notificado a los interesados, no cabrá recurso alguno'),
('III', T, 'a23', 'La ampliación excepcional del plazo máximo de resolución y notificación (artículo 23) no puede ser superior:', 'Al plazo establecido para la tramitación del procedimiento',
 ['A la mitad del plazo establecido', 'A tres meses', 'A seis meses'], 'no pudiendo ser éste superior al establecido para la tramitación del procedimiento'),
('III', T, 'a24', 'Con carácter general, en los procedimientos iniciados a solicitud del interesado, el vencimiento del plazo máximo sin notificarse resolución expresa permite entender la solicitud:',
 'Estimada, salvo que una norma con rango de ley, de Derecho de la Unión Europea o de Derecho internacional aplicable en España establezca lo contrario',
 ['Desestimada en todo caso', 'Estimada, salvo que un reglamento establezca lo contrario', 'Desestimada, salvo que una ley establezca lo contrario'],
 'legitima al interesado o interesados para entenderla estimada por silencio administrativo'),
('III', T, 'a24', '¿Cuál de los siguientes procedimientos figura en el artículo 24.1 entre aquellos en que el silencio tiene efecto desestimatorio?', 'Los relativos al ejercicio del derecho de petición del artículo 29 de la Constitución',
 ['Los iniciados por personas jurídicas', 'Los de cuantía inferior a 6.000 euros', 'Los tramitados de forma simplificada'],
 'El silencio tendrá efecto desestimatorio en los procedimientos relativos al ejercicio del derecho de petición'),
('III', T, 'a24', 'Si se interpone recurso de alzada contra la desestimación por silencio de una solicitud y, llegado el plazo, el órgano no resuelve (fuera de las materias excluidas), el recurso:', 'Se entenderá estimado',
 ['Se entenderá desestimado', 'Se entenderá caducado', 'Se tendrá por desistido'], 'se entenderá estimado el mismo si, llegado el plazo de resolución'),
('III', T, 'a24', 'La desestimación por silencio administrativo tiene:', 'Los solos efectos de permitir a los interesados la interposición del recurso administrativo o contencioso-administrativo que proceda',
 ['La consideración de acto administrativo finalizador del procedimiento a todos los efectos', 'Los efectos de una resolución firme', 'Los efectos de la caducidad del procedimiento'],
 'La desestimación por silencio administrativo tiene los solos efectos de permitir'),
('III', T, 'a24', 'En los casos de estimación por silencio administrativo, la resolución expresa posterior a la producción del acto:', 'Sólo podrá dictarse de ser confirmatoria del mismo',
 ['Se adoptará sin vinculación alguna al sentido del silencio', 'Podrá revocar libremente el acto presunto', 'No podrá dictarse en ningún caso'],
 'la resolución expresa posterior a la producción del acto sólo podrá dictarse de ser confirmatoria del mismo'),
('III', P, 'a24', 'Expedición de oficio del certificado acreditativo del silencio, desde que expire el plazo máximo para resolver', '15 días',
 ['5 días', '10 días', '20 días'], 'Este certificado se expedirá de oficio por el órgano competente para resolver en el plazo de quince días'),
('III', T, 'a25', 'En los procedimientos iniciados de oficio en que la Administración ejercite potestades sancionadoras, el vencimiento del plazo máximo sin resolución expresa produce:', 'La caducidad',
 ['La estimación por silencio administrativo', 'La desestimación por silencio administrativo', 'La prescripción de la infracción'],
 'susceptibles de producir efectos desfavorables o de gravamen, se producirá la caducidad'),
('III', T, 'a25', 'En los procedimientos iniciados de oficio de los que pudiera derivarse el reconocimiento de derechos, si vence el plazo sin resolución expresa, los interesados que hubieren comparecido:',
 'Podrán entender desestimadas sus pretensiones por silencio administrativo',
 ['Podrán entender estimadas sus pretensiones', 'Verán caducado el procedimiento', 'Deberán reiterar su solicitud'],
 'los interesados que hubieren comparecido podrán entender desestimadas sus pretensiones por silencio administrativo'),
('III', T, 'a30', 'Los plazos expresados por horas no podrán tener una duración superior a (en tal caso se expresarán en días):', '24 horas',
 ['12 horas', '48 horas', '72 horas'], 'no podrán tener una duración superior a veinticuatro horas'),
('III', T, 'a30', 'Cuando el último día del plazo sea inhábil:', 'Se entenderá prorrogado al primer día hábil siguiente',
 ['Se entenderá vencido el día hábil anterior', 'Se entenderá vencido ese mismo día', 'Se prorrogará tres días hábiles'], 'Cuando el último día del plazo sea inhábil, se entenderá prorrogado al primer día hábil siguiente'),
('III', T, 'a30', 'Si un día es hábil en el municipio o Comunidad Autónoma de residencia del interesado e inhábil en la sede del órgano administrativo, o a la inversa:', 'Se considerará inhábil en todo caso',
 ['Se considerará hábil en todo caso', 'Se estará a lo que resulte en la sede del órgano', 'Se estará a lo que resulte en el domicilio del interesado'], 'se considerará inhábil en todo caso'),
('III', T, 'a30', 'En un plazo fijado en meses, si en el mes de vencimiento no hubiera día equivalente a aquel en que comienza el cómputo:', 'El plazo expira el último día del mes',
 ['El plazo expira el primer día del mes siguiente', 'El plazo se amplía tres días', 'El plazo expira el día hábil anterior'], 'se entenderá que el plazo expira el último día del mes'),
('III', T, 'a30', 'Los plazos expresados en días se contarán:', 'A partir del día siguiente a aquel en que tenga lugar la notificación o publicación del acto',
 ['Desde el mismo día de la notificación o publicación', 'Desde el día en que se dictó el acto', 'Desde el segundo día hábil tras la notificación'], 'Los plazos expresados en días se contarán a partir del día siguiente'),
('III', T, 'a31', 'En el registro electrónico, a efectos del cómputo de plazos fijados en días hábiles para los interesados, la presentación en un día inhábil se entenderá realizada:',
 'En la primera hora del primer día hábil siguiente, salvo que una norma permita expresamente la recepción en día inhábil',
 ['En el mismo día inhábil', 'En la última hora del día hábil anterior', 'A las doce horas del primer día hábil siguiente'],
 'la presentación en un día inhábil se entenderá realizada en la primera hora del primer día hábil siguiente'),
('III', T, 'a32', 'La ampliación de los plazos establecidos que puede conceder la Administración (artículo 32.1) no podrá exceder de:', 'La mitad de los mismos',
 ['Un tercio de los mismos', 'El doble de los mismos', 'Diez días'], 'una ampliación de los plazos establecidos, que no exceda de la mitad de los mismos'),
('III', T, 'a32', '¿Puede ser objeto de ampliación un plazo ya vencido?', 'No, en ningún caso',
 ['Sí, si lo solicita el interesado', 'Sí, si concurre causa justificada', 'Sí, si no se perjudican derechos de tercero'], 'En ningún caso podrá ser objeto de ampliación un plazo ya vencido'),
('III', T, 'a33', 'En la tramitación de urgencia, los plazos establecidos para el procedimiento ordinario:', 'Se reducen a la mitad, salvo los relativos a la presentación de solicitudes y recursos',
 ['Se reducen a la mitad, incluidos los de presentación de solicitudes y recursos', 'Se reducen a un tercio', 'Se reducen en diez días'],
 'se reducirán a la mitad los plazos establecidos para el procedimiento ordinario, salvo los relativos a la presentación de solicitudes y recursos'),
('III', T, 'a35', 'Los actos que deben ser motivados según el artículo 35.1 lo serán:', 'Con sucinta referencia de hechos y fundamentos de derecho',
 ['Con exposición exhaustiva de todos los hechos y fundamentos', 'Con referencia solo a los fundamentos de derecho', 'Con transcripción íntegra del expediente'], 'Serán motivados, con sucinta referencia de hechos y fundamentos de derecho'),
('III', T, 'a35', 'Según el artículo 35.1.f), deben motivarse los actos que:', 'Rechacen pruebas propuestas por los interesados',
 ['Admitan las pruebas propuestas por los interesados', 'Ordenen la notificación a los interesados', 'Incorporen documentos al expediente'], r're:Serán motivados, con sucinta referencia de hechos y fundamentos de derecho:.*?f\) Los actos que rechacen pruebas propuestas por los interesados'),
('III', T, 'a36', 'Según el artículo 36.1, los actos administrativos se producirán:', 'Por escrito a través de medios electrónicos, a menos que su naturaleza exija otra forma más adecuada',
 ['Por escrito en papel, salvo que el interesado elija medios electrónicos', 'De forma verbal, salvo que una ley exija la forma escrita', 'En papel y en formato electrónico simultáneamente'],
 'Los actos administrativos se producirán por escrito a través de medios electrónicos'),
('III', T, 'a37', 'Las resoluciones administrativas que vulneren lo establecido en una disposición reglamentaria son:', 'Nulas',
 ['Anulables', 'Válidas si proceden de un órgano de superior jerarquía', 'Válidas hasta que sean recurridas'], 'Son nulas las resoluciones administrativas que vulneren lo establecido en una disposición reglamentaria'),
('III', T, 'a37', '¿Qué principio impide que las resoluciones administrativas de carácter particular vulneren una disposición de carácter general, aunque procedan de un órgano de igual o superior jerarquía?', 'La inderogabilidad singular',
 ['La jerarquía normativa', 'La irretroactividad', 'La reserva de ley'],
 r're:Inderogabilidad singular\. 1\. Las resoluciones administrativas de carácter particular no podrán vulnerar lo establecido en una disposición de carácter general'),
('III', T, 'a39', 'Los actos de las Administraciones Públicas sujetos al Derecho Administrativo se presumirán válidos y producirán efectos:', 'Desde la fecha en que se dicten, salvo que en ellos se disponga otra cosa',
 ['Desde su notificación, en todo caso', 'Desde su publicación en el boletín oficial', 'Desde que sean firmes'], 'se presumirán válidos y producirán efectos desde la fecha en que se dicten'),
('III', T, 'a39', 'Excepcionalmente, podrá otorgarse eficacia retroactiva a los actos administrativos:', 'Cuando se dicten en sustitución de actos anulados o produzcan efectos favorables al interesado, con los requisitos legales',
 ['Cuando produzcan efectos desfavorables al interesado', 'Siempre que lo acuerde el órgano superior', 'Cuando sean actos sancionadores'],
 'podrá otorgarse eficacia retroactiva a los actos cuando se dicten en sustitución de actos anulados'),
('III', T, 'a40', 'Las notificaciones que, conteniendo el texto íntegro del acto, omitiesen alguno de los demás requisitos exigidos:',
 'Surtirán efecto desde que el interesado realice actuaciones que supongan el conocimiento del contenido y alcance del acto, o interponga el recurso procedente',
 ['Son nulas de pleno derecho', 'Surtirán efecto desde la fecha del acto', 'No surtirán efecto en ningún caso'], 'surtirán efecto a partir de la fecha en que el interesado realice actuaciones'),
('III', T, 'a41', '¿Cuál de las siguientes notificaciones no se efectuará en ningún caso por medios electrónicos?', 'Las que contengan medios de pago a favor de los obligados, tales como cheques',
 ['Las dirigidas a personas jurídicas', 'Las de resoluciones sancionadoras', 'Las dirigidas a empleados públicos'], r're:En ningún caso se efectuarán por medios electrónicos las siguientes notificaciones:.*?b\) Las que contengan medios de pago a favor de los obligados, tales como cheques'),
('III', T, 'a41', 'Cuando el interesado fuera notificado por distintos cauces, se tomará como fecha de notificación:', 'La de la que se hubiera producido en primer lugar',
 ['La de la que se hubiera producido en último lugar', 'La de la notificación electrónica, en todo caso', 'La de la notificación en papel, en todo caso'],
 'se tomará como fecha de notificación la de aquélla que se hubiera producido en primer lugar'),
('III', T, 'a41', 'La falta de práctica del aviso al dispositivo electrónico o a la dirección de correo electrónico del interesado:', 'No impedirá que la notificación sea considerada plenamente válida',
 ['Determina la nulidad de la notificación', 'Obliga a repetir la notificación', 'Suspende los efectos de la notificación'], 'La falta de práctica de este aviso no impedirá que la notificación sea considerada plenamente válida'),
('III', T, 'a41', 'Cuando el interesado o su representante rechace la notificación de una actuación administrativa:', 'Se hará constar en el expediente, dando por efectuado el trámite y siguiéndose el procedimiento',
 ['Se repetirá la notificación dentro de los tres días siguientes', 'Se publicará un anuncio en el «Boletín Oficial del Estado»', 'Se suspenderá el procedimiento'], 'dando por efectuado el trámite y siguiéndose el procedimiento'),
('III', T, 'a42', 'En la notificación en papel en el domicilio, si el interesado no está presente, puede hacerse cargo de ella cualquier persona que se encuentre en el domicilio, haga constar su identidad y sea mayor de:', '14 años',
 ['12 años', '16 años', '18 años'], 'cualquier persona mayor de catorce años'),
('III', P, 'a42', 'Repetición, por una sola vez y en hora distinta, del intento de notificación en papel cuando nadie se hizo cargo de ella', 'Dentro de los 3 días siguientes',
 ['Dentro de los 2 días siguientes', 'Dentro de los 5 días siguientes', 'Dentro de los 10 días siguientes'], 'intento que se repetirá por una sola vez y en una hora distinta dentro de los tres días siguientes'),
('III', T, 'a42', '¿Qué margen mínimo de diferencia debe haber entre los dos intentos de notificación en papel en el domicilio?', 'Tres horas',
 ['Una hora', 'Dos horas', 'Cuatro horas'], 'al menos un margen de diferencia de tres horas entre ambos intentos'),
('III', T, 'a43', 'Las notificaciones por medios electrónicos se entenderán practicadas:', 'En el momento en que se produzca el acceso a su contenido',
 ['En el momento de su puesta a disposición', 'Al día siguiente de su puesta a disposición', 'Cuando se envíe el aviso al correo electrónico'],
 'Las notificaciones por medios electrónicos se entenderán practicadas en el momento en que se produzca el acceso a su contenido'),
('III', T, 'a44', 'Cuando los interesados sean desconocidos, se ignore el lugar de la notificación o, intentada, no se hubiese podido practicar, la notificación se hará por anuncio publicado en:', 'El «Boletín Oficial del Estado»',
 ['El tablón de edictos del Ayuntamiento, exclusivamente', 'El boletín oficial de la provincia, exclusivamente', 'La sede electrónica del órgano, exclusivamente'],
 'la notificación se hará por medio de un anuncio publicado en el «Boletín Oficial del Estado»'),
('III', T, 'a45', 'Los actos integrantes de un procedimiento selectivo o de concurrencia competitiva:', 'Serán objeto de publicación, que surtirá los efectos de la notificación',
 ['Se notificarán individualmente en todo caso', 'No requieren publicación ni notificación', 'Solo se publicarán si lo solicitan los interesados'],
 r're:surtiendo ésta los efectos de la notificación, en los siguientes casos:.*?b\) Cuando se trate de actos integrantes de un procedimiento selectivo o de concurrencia competitiva de cualquier tipo'),
('III', T, 'a47', '¿Cuál de los siguientes vicios determina la nulidad de pleno derecho de un acto según el artículo 47.1?', 'Haber sido dictado por órgano manifiestamente incompetente por razón de la materia o del territorio',
 ['Incurrir en desviación de poder', 'Haberse dictado fuera del tiempo establecido', 'Un defecto de forma que produzca indefensión'],
 r're:son nulos de pleno derecho en los casos siguientes: a\).*?b\) Los dictados por órgano manifiestamente incompetente por razón de la materia o del territorio'),
('III', T, 'a47', 'Los actos que lesionen los derechos y libertades susceptibles de amparo constitucional son:', 'Nulos de pleno derecho',
 ['Anulables', 'Válidos hasta que lo declare el Tribunal Constitucional', 'Convalidables'], 'Los que lesionen los derechos y libertades susceptibles de amparo constitucional'),
('III', T, 'a47', 'Los actos dictados prescindiendo total y absolutamente del procedimiento legalmente establecido son:', 'Nulos de pleno derecho',
 ['Anulables', 'Convalidables en todo caso', 'Válidos si el interesado no los recurre'], r're:son nulos de pleno derecho en los casos siguientes: a\).*?e\) Los dictados prescindiendo total y absolutamente del procedimiento legalmente establecido'),
('III', T, 'a47', 'Las disposiciones administrativas que establezcan la retroactividad de disposiciones sancionadoras no favorables o restrictivas de derechos individuales son:', 'Nulas de pleno derecho',
 ['Anulables', 'Válidas si lo prevé una ley', 'Inaplicables solo al caso concreto'], r're:También serán nulas de pleno derecho las disposiciones administrativas.*?las que establezcan la retroactividad de disposiciones sancionadoras no favorables'),
('III', T, 'a48', 'Según el artículo 48.1, la desviación de poder determina:', 'La anulabilidad del acto',
 ['La nulidad de pleno derecho del acto', 'La inexistencia del acto', 'Una mera irregularidad no invalidante'], 'incurran en cualquier infracción del ordenamiento jurídico, incluso la desviación de poder'),
('III', T, 'a48', 'El defecto de forma sólo determinará la anulabilidad del acto cuando:', 'Carezca de los requisitos formales indispensables para alcanzar su fin o dé lugar a la indefensión de los interesados',
 ['Lo alegue el interesado en el plazo de diez días', 'Se trate de un acto de gravamen', 'Afecte a la notificación del acto'], 'el defecto de forma sólo determinará la anulabilidad'),
('III', T, 'a48', 'La realización de actuaciones administrativas fuera del tiempo establecido para ellas:', 'Sólo implicará la anulabilidad del acto cuando así lo imponga la naturaleza del término o plazo',
 ['Determina siempre la nulidad de pleno derecho', 'Determina siempre la anulabilidad', 'Determina la inexistencia del acto'], 'sólo implicará la anulabilidad del acto cuando así lo imponga la naturaleza del término o plazo'),
('III', T, 'a49', 'La nulidad o anulabilidad de un acto:', 'No implicará la de los sucesivos en el procedimiento que sean independientes del primero',
 ['Implicará la de todos los actos sucesivos del procedimiento', 'Implicará la nulidad de todo el procedimiento', 'Implicará la de los actos anteriores del procedimiento'],
 'no implicará la de los sucesivos en el procedimiento que sean independientes del primero'),
('III', T, 'a50', '¿Cómo se denomina la figura por la que los actos nulos o anulables que contengan los elementos constitutivos de otro distinto producen los efectos de éste?', 'Conversión de actos viciados',
 ['Convalidación', 'Conservación de actos y trámites', 'Revocación'],
 r're:Conversión de actos viciados\. Los actos nulos o anulables que, sin embargo, contengan los elementos constitutivos de otro distinto producirán los efectos de éste'),
('III', T, 'a51', 'El órgano que declare la nulidad o anule las actuaciones dispondrá siempre la conservación de:', 'Aquellos actos y trámites cuyo contenido se hubiera mantenido igual de no haberse cometido la infracción',
 ['Todos los actos anteriores a la infracción', 'Los actos favorables al interesado', 'Únicamente los informes preceptivos'],
 'dispondrá siempre la conservación de aquellos actos y trámites cuyo contenido se hubiera mantenido igual'),
('III', T, 'a52', '¿Qué actos puede convalidar la Administración, subsanando los vicios de que adolezcan?', 'Los actos anulables',
 ['Los actos nulos de pleno derecho', 'Cualquier acto, sea nulo o anulable', 'Únicamente los actos de trámite'], 'La Administración podrá convalidar los actos anulables'),
('III', T, 'a52', 'Si el vicio consistiera en incompetencia no determinante de nulidad, la convalidación podrá realizarse por:', 'El órgano competente cuando sea superior jerárquico del que dictó el acto viciado',
 ['El mismo órgano que dictó el acto', 'Cualquier órgano de la misma Administración', 'El Consejo de Estado'], 'la convalidación podrá realizarse por el órgano competente cuando sea superior jerárquico'),
('III', T, 'a52', 'El acto de convalidación producirá efecto:', 'Desde su fecha, salvo lo dispuesto para la retroactividad de los actos administrativos',
 ['Desde la fecha del acto convalidado, en todo caso', 'Desde su publicación en el boletín oficial', 'Desde su notificación al interesado, en todo caso'], 'El acto de convalidación producirá efecto desde su fecha'),
('III', T, 'a53', 'En los procedimientos de naturaleza sancionadora, los presuntos responsables tienen derecho, entre otros, a:', 'La presunción de no existencia de responsabilidad administrativa mientras no se demuestre lo contrario',
 ['No ser objeto de medidas provisionales', 'La suspensión automática del procedimiento si lo solicitan', 'Que el procedimiento se tramite siempre de forma simplificada'],
 r're:los presuntos responsables tendrán los siguientes derechos:.*?b\) A la presunción de no existencia de responsabilidad administrativa mientras no se demuestre lo contrario'),
('III', T, 'a53', 'Según el artículo 53.1.e), los interesados pueden formular alegaciones y aportar documentos:', 'En cualquier fase del procedimiento anterior al trámite de audiencia',
 ['Solo en el trámite de audiencia', 'Solo en los diez días siguientes al inicio', 'En cualquier momento, incluso después de la resolución'], 'a aportar documentos en cualquier fase del procedimiento anterior al trámite de audiencia'),
('III', T, 'a55', 'Con anterioridad al inicio del procedimiento, el órgano competente podrá abrir:', 'Un período de información o actuaciones previas',
 ['Un trámite de audiencia', 'Un período de prueba', 'Un trámite de información pública obligatorio'], 'podrá abrir un período de información o actuaciones previas'),
('III', P, 'a56', 'Confirmación, modificación o levantamiento, en el acuerdo de iniciación, de las medidas provisionales adoptadas antes de iniciarse el procedimiento (desde su adopción)', '15 días',
 ['5 días', '10 días', '20 días'], 'que deberá efectuarse dentro de los quince días siguientes a su adopción'),
('III', T, 'a56', 'No se podrán adoptar medidas provisionales que:', 'Puedan causar perjuicio de difícil o imposible reparación a los interesados o impliquen violación de derechos amparados por las leyes',
 ['Consistan en la prestación de fianzas', 'Supongan la suspensión temporal de actividades', 'Consistan en el embargo preventivo de bienes'],
 'No se podrán adoptar medidas provisionales que puedan causar perjuicio de difícil o imposible reparación'),
('III', T, 'a56', 'Las medidas provisionales se extinguirán, en todo caso:', 'Cuando surta efectos la resolución administrativa que ponga fin al procedimiento',
 ['A los tres meses de su adopción', 'Al abrirse el trámite de audiencia', 'Al dictarse la propuesta de resolución'],
 'se extinguirán cuando surta efectos la resolución administrativa que ponga fin al procedimiento'),
('III', T, 'a57', 'Contra el acuerdo de acumulación de procedimientos:', 'No procederá recurso alguno',
 ['Cabe recurso de alzada', 'Cabe recurso potestativo de reposición', 'Cabe recurso contencioso-administrativo directo'], 'Contra el acuerdo de acumulación no procederá recurso alguno'),
('III', T, 'a58', '¿Cuál de las siguientes NO es una de las vías de iniciación de oficio previstas en el artículo 58?', 'La solicitud del interesado',
 ['La orden superior', 'La petición razonada de otros órganos', 'La denuncia'],
 'bien por propia iniciativa o como consecuencia de orden superior, a petición razonada de otros órganos o por denuncia'),
('III', T, 'a61', 'La petición razonada de otros órganos para que se inicie un procedimiento:', 'No vincula al órgano competente, que deberá comunicar los motivos por los que, en su caso, no procede la iniciación',
 ['Vincula al órgano competente para iniciar', 'Obliga a iniciar el procedimiento en diez días', 'Equivale a la iniciación del procedimiento'], 'La petición no vincula al órgano competente para iniciar el procedimiento'),
('III', T, 'a62', 'La presentación de una denuncia:', 'No confiere, por sí sola, la condición de interesado en el procedimiento',
 ['Confiere siempre la condición de interesado', 'Obliga a iniciar el procedimiento', 'Debe hacerse de forma anónima'], 'La presentación de una denuncia no confiere, por sí sola, la condición de interesado'),
('III', T, 'a63', 'Según el artículo 63.1, los procedimientos de naturaleza sancionadora:', 'Se iniciarán siempre de oficio y separarán la fase instructora y la sancionadora, encomendadas a órganos distintos',
 ['Pueden iniciarse a solicitud del denunciante', 'Se instruyen y resuelven por el mismo órgano', 'Se inician por orden del Ministerio Fiscal'], 'Los procedimientos de naturaleza sancionadora se iniciarán siempre de oficio'),
('III', T, 'a64', 'Si al dictar el acuerdo de iniciación de un procedimiento sancionador no existen elementos suficientes para la calificación inicial de los hechos, la calificación podrá realizarse después mediante:', 'Un Pliego de cargos',
 ['Una propuesta de resolución', 'Un acta de inspección', 'Una petición razonada'], 'mediante la elaboración de un Pliego de cargos'),
('III', P, 'a65', 'Aportación de alegaciones, documentos e información por los presuntos lesionados, tras notificárseles el inicio de oficio de un procedimiento de responsabilidad patrimonial', '10 días',
 ['5 días', '15 días', '20 días'], 'concediéndoles un plazo de diez días para que aporten'),
('III', T, 'a66', 'Cuando la Administración establezca expresamente modelos específicos de presentación de solicitudes en un procedimiento concreto, estos:', 'Serán de uso obligatorio por los interesados',
 ['Serán de uso voluntario', 'Solo serán obligatorios para las personas jurídicas', 'Solo serán obligatorios en la presentación electrónica'], 'éstos serán de uso obligatorio por los interesados'),
('III', P, 'a67', 'Prescripción del derecho a reclamar responsabilidad patrimonial, desde el hecho o acto que motive la indemnización o la manifestación de su efecto lesivo', '1 año',
 ['2 años', '3 años', '4 años'], 'El derecho a reclamar prescribirá al año de producido el hecho'),
('III', T, 'a67', 'En caso de daños de carácter físico o psíquico a las personas, el plazo para reclamar responsabilidad patrimonial empezará a computarse:', 'Desde la curación o la determinación del alcance de las secuelas',
 ['Desde el día en que se produjo el daño', 'Desde la primera asistencia médica', 'Desde la notificación del alta laboral'],
 'el plazo empezará a computarse desde la curación o la determinación del alcance de las secuelas'),
('III', T, 'a68', 'Salvo en procedimientos selectivos o de concurrencia competitiva, el plazo de subsanación de la solicitud podrá ampliarse prudencialmente hasta:', 'Cinco días',
 ['Tres días', 'Diez días', 'Quince días'], 'este plazo podrá ser ampliado prudencialmente, hasta cinco días'),
('III', T, 'a69', 'Las declaraciones responsables y las comunicaciones permiten el reconocimiento o ejercicio de un derecho o el inicio de una actividad:', 'Desde el día de su presentación, sin perjuicio de las facultades de comprobación, control e inspección',
 ['Desde que la Administración las compruebe', 'Al mes de su presentación', 'Desde su publicación en el boletín oficial'], 'desde el día de su presentación, sin perjuicio de las facultades de comprobación'),
('III', T, 'a69', '¿Puede exigirse a la vez una declaración responsable y una comunicación para iniciar una misma actividad?', 'No, únicamente será exigible una de ellas',
 ['Sí, siempre', 'Sí, cuando lo prevea una ordenanza', 'Sí, para las actividades sujetas a inspección'], 'sin que sea posible la exigencia de ambas acumulativamente'),
('III', T, 'a70', 'Según el artículo 70.4, ¿cuál de los siguientes SÍ forma parte del expediente administrativo?', 'Los informes, preceptivos y facultativos, solicitados antes de la resolución que ponga fin al procedimiento',
 ['Los borradores', 'Las notas y opiniones', 'Los juicios de valor emitidos por las Administraciones Públicas'],
 'salvo que se trate de informes, preceptivos y facultativos, solicitados antes de la resolución administrativa'),
('III', T, 'a71', 'En el despacho de los expedientes se guardará el orden riguroso de incoación en asuntos de homogénea naturaleza, salvo:', 'Orden motivada en contrario del titular de la unidad administrativa, de la que quede constancia',
 ['Petición del interesado', 'Acuerdo verbal del instructor', 'Que el asunto sea de cuantía elevada'], 'salvo que por el titular de la unidad administrativa se dé orden motivada en contrario'),
('III', T, 'a74', 'Las cuestiones incidentales que se susciten en el procedimiento, incluso las referidas a la nulidad de actuaciones:', 'No suspenderán la tramitación del mismo, salvo la recusación',
 ['Suspenderán siempre la tramitación', 'No suspenderán la tramitación, salvo las relativas a la nulidad de actuaciones', 'Suspenderán la tramitación durante diez días'],
 'no suspenderán la tramitación del mismo, salvo la recusación'),
('III', P, 'a77', 'Período extraordinario de prueba que puede acordar el instructor a petición de los interesados', 'No superior a 10 días',
 ['No superior a 5 días', 'No superior a 15 días', 'No superior a 30 días'], 'un período extraordinario de prueba por un plazo no superior a diez días'),
('III', T, 'a77', 'El instructor del procedimiento sólo podrá rechazar las pruebas propuestas por los interesados cuando sean:', 'Manifiestamente improcedentes o innecesarias, mediante resolución motivada',
 ['Costosas para la Administración', 'Propuestas después del inicio del procedimiento', 'Testificales'], 'cuando sean manifiestamente improcedentes o innecesarias'),
('III', T, 'a77', 'En los procedimientos sancionadores, los hechos declarados probados por resoluciones judiciales penales firmes:', 'Vincularán a las Administraciones Públicas',
 ['No vinculan a la Administración', 'Solo vinculan si el interesado los alega', 'Solo vinculan si la sentencia es condenatoria'],
 'los hechos declarados probados por resoluciones judiciales penales firmes vincularán'),
('III', T, 'a77', 'Los documentos formalizados por funcionarios con condición de autoridad en los que se recojan hechos constatados por ellos, con los requisitos legales:', 'Harán prueba de éstos salvo que se acredite lo contrario',
 ['Hacen prueba plena que no admite prueba en contrario', 'Carecen de valor probatorio', 'Solo hacen prueba si los ratifica un superior'], 'harán prueba de éstos salvo que se acredite lo contrario'),
('III', T, 'a80', 'Salvo disposición expresa en contrario, los informes serán:', 'Facultativos y no vinculantes',
 ['Preceptivos y vinculantes', 'Preceptivos y no vinculantes', 'Facultativos y vinculantes'], 'Salvo disposición expresa en contrario, los informes serán facultativos y no vinculantes'),
('III', T, 'a80', 'Si no se emite en plazo un informe preceptivo:', 'Se podrá suspender el transcurso del plazo máximo legal para resolver el procedimiento',
 ['Se entenderá emitido en sentido favorable', 'Se entenderá emitido en sentido desfavorable', 'Se producirá la caducidad del procedimiento'],
 'salvo cuando se trate de un informe preceptivo, en cuyo caso se podrá suspender'),
('III', T, 'a81', 'En los procedimientos de responsabilidad patrimonial, es preceptivo el dictamen del Consejo de Estado u órgano consultivo autonómico cuando la indemnización reclamada sea de cuantía igual o superior a (salvo la cuantía que fije la legislación autonómica):', '50.000 euros',
 ['6.000 euros', '15.000 euros', '100.000 euros'], 'sean de cuantía igual o superior a 50.000 euros'),
('III', P, 'a81', 'Emisión del dictamen del Consejo de Estado u órgano consultivo autonómico en los procedimientos de responsabilidad patrimonial', '2 meses',
 ['1 mes', '3 meses', '6 meses'], 'El dictamen se emitirá en el plazo de dos meses'),
('III', P, 'a81', 'Emisión del informe del servicio cuyo funcionamiento haya ocasionado la presunta lesión indemnizable', 'No superior a 10 días',
 ['No superior a 5 días', 'No superior a 15 días', 'No superior a 20 días'], 'no pudiendo exceder de diez días el plazo de su emisión'),
('III', T, 'a82', 'Se podrá prescindir del trámite de audiencia cuando:', 'No figuren en el procedimiento ni sean tenidos en cuenta en la resolución otros hechos, alegaciones y pruebas que los aducidos por el interesado',
 ['El interesado no haya presentado alegaciones previas', 'El procedimiento se haya iniciado de oficio', 'Lo acuerde el instructor por razones de urgencia'], 'Se podrá prescindir del trámite de audiencia cuando no figuren'),
('III', T, 'a82', 'Según el artículo 82.1, la audiencia a los interesados será:', 'Anterior a la solicitud del informe del órgano de asesoramiento jurídico o del dictamen del Consejo de Estado u órgano equivalente',
 ['Posterior al dictamen del Consejo de Estado', 'Simultánea a la solicitud de los informes preceptivos', 'Posterior a la propuesta de resolución'], 'La audiencia a los interesados será anterior a la solicitud del informe'),
('III', T, 'a83', 'La comparecencia en el trámite de información pública:', 'No otorga, por sí misma, la condición de interesado',
 ['Otorga la condición de interesado', 'Es requisito para poder recurrir la resolución', 'Obliga a la Administración a estimar las alegaciones'],
 'La comparecencia en el trámite de información pública no otorga, por sí misma, la condición de interesado'),
('III', T, 'a84', '¿Cuál de los siguientes NO pone fin al procedimiento según el artículo 84.1?', 'La propuesta de resolución',
 ['El desistimiento', 'La declaración de caducidad', 'La renuncia al derecho, cuando no esté prohibida por el ordenamiento jurídico'], 'Pondrán fin al procedimiento la resolución, el desistimiento'),
('III', T, 'a85', 'En un procedimiento sancionador con sanción únicamente pecuniaria, el reconocimiento de responsabilidad o el pago voluntario conllevan reducciones de, al menos:', 'El 20 % sobre el importe de la sanción propuesta, acumulables entre sí',
 ['El 10 % sobre el importe de la sanción propuesta', 'El 30 % sobre el importe de la sanción propuesta', 'El 50 % sobre el importe de la sanción propuesta'],
 'aplicará reducciones de, al menos, el 20 % sobre el importe de la sanción propuesta'),
('III', T, 'a85', 'La efectividad de las reducciones de la sanción por reconocimiento de responsabilidad o pago voluntario está condicionada a:', 'El desistimiento o renuncia de cualquier acción o recurso en vía administrativa contra la sanción',
 ['Que no exista reincidencia', 'Que se trate de una infracción leve', 'Que el infractor lo solicite por escrito en diez días'],
 'su efectividad estará condicionada al desistimiento o renuncia de cualquier acción o recurso en vía administrativa'),
('III', P, 'a87', 'Práctica de las actuaciones complementarias acordadas antes de dictar resolución', 'No superior a 15 días',
 ['No superior a 7 días', 'No superior a 10 días', 'No superior a 30 días'], 'Las actuaciones complementarias deberán practicarse en un plazo no superior a quince días'),
('III', P, 'a87', 'Alegaciones de los interesados tras la finalización de las actuaciones complementarias', '7 días',
 ['5 días', '10 días', '15 días'], 'concediéndoseles un plazo de siete días'),
('III', T, 'a88', 'En los procedimientos tramitados a solicitud del interesado, la resolución será congruente con las peticiones formuladas por éste y:', 'En ningún caso podrá agravar su situación inicial',
 ['Podrá agravar su situación si lo justifica el interés público', 'Podrá resolver sobre cuestiones no planteadas sin oírle', 'Deberá ser siempre estimatoria'], 'sin que en ningún caso pueda agravar su situación inicial'),
('III', T, 'a88', 'So pretexto de silencio, oscuridad o insuficiencia de los preceptos legales aplicables, la Administración:', 'En ningún caso podrá abstenerse de resolver',
 ['Podrá abstenerse de resolver', 'Deberá suspender el procedimiento', 'Deberá elevar consulta al Consejo de Estado'],
 'En ningún caso podrá la Administración abstenerse de resolver so pretexto de silencio'),
('III', T, 'a89', '¿En cuál de los siguientes casos el instructor de un procedimiento sancionador resolverá su finalización, con archivo de las actuaciones, sin formular propuesta de resolución?', 'Cuando se concluya que ha prescrito la infracción',
 ['Cuando el interesado no presente alegaciones', 'Cuando la infracción sea leve', 'Cuando el interesado reconozca su responsabilidad'], r're:sin que sea necesaria la formulación de la propuesta de resolución.*?e\) Cuando se concluyera, en cualquier momento, que ha prescrito la infracción'),
('III', P, 'a90', 'Alegaciones del inculpado cuando el órgano competente para resolver considere que la infracción o la sanción revisten mayor gravedad que la propuesta', '15 días',
 ['5 días', '10 días', '20 días'], 'se notificará al inculpado para que aporte cuantas alegaciones estime convenientes en el plazo de quince días'),
('III', T, 'a90', 'La resolución que ponga fin a un procedimiento sancionador será ejecutiva:', 'Cuando no quepa contra ella ningún recurso ordinario en vía administrativa',
 ['Desde que se dicte', 'Cuando sea firme en vía judicial', 'Desde su notificación'], 'será ejecutiva cuando no quepa contra ella ningún recurso ordinario en vía administrativa'),
('III', P, 'a91', 'Transcurso, desde el inicio del procedimiento de responsabilidad patrimonial sin resolución ni acuerdo, tras el cual puede entenderse que la resolución es contraria a la indemnización', '6 meses',
 ['2 meses', '3 meses', '12 meses'], 'Transcurridos seis meses desde que se inició el procedimiento'),
('III', T, 'a92', 'En el ámbito de la Administración General del Estado, los procedimientos de responsabilidad patrimonial se resolverán, con carácter general, por:', 'El Ministro respectivo',
 ['El Subsecretario del Departamento', 'El Consejo de Ministros, en todo caso', 'El Delegado del Gobierno'], 'los procedimientos de responsabilidad patrimonial se resolverán por el Ministro respectivo'),
('III', T, 'a94', 'Si el escrito de iniciación se hubiera formulado por dos o más interesados, el desistimiento o la renuncia:', 'Sólo afectará a aquellos que la hubiesen formulado',
 ['Afectará a todos los interesados', 'Requiere la conformidad de todos ellos', 'Pone fin al procedimiento para todos'], 'el desistimiento o la renuncia sólo afectará a aquellos que la hubiesen formulado'),
('III', P, 'a94', 'Solicitud de continuación del procedimiento por terceros interesados personados, desde que fueron notificados del desistimiento o renuncia', '10 días',
 ['5 días', '15 días', '20 días'], 'instasen éstos su continuación en el plazo de diez días'),
('III', T, 'a95', 'Según el artículo 95.3, la caducidad del procedimiento:', 'No produce por sí sola la prescripción de las acciones, pero los procedimientos caducados no interrumpen el plazo de prescripción',
 ['Produce por sí sola la prescripción de las acciones', 'Interrumpe el plazo de prescripción', 'Impide iniciar un nuevo procedimiento con el mismo objeto'], 'La caducidad no producirá por sí sola la prescripción'),
('III', P, 'a96', 'Desestimación por el órgano de la solicitud de tramitación simplificada formulada por el interesado (transcurrido el cual se entiende desestimada)', '5 días',
 ['3 días', '10 días', '15 días'], 'podrá desestimar dicha solicitud, en el plazo de cinco días desde su presentación'),
('III', T, 'a96', 'En la tramitación simplificada del procedimiento, el trámite de audiencia se realiza:', 'Únicamente cuando la resolución vaya a ser desfavorable para el interesado',
 ['En todo caso', 'Nunca', 'Solo a petición del interesado'], 'Trámite de audiencia, únicamente cuando la resolución vaya a ser desfavorable para el interesado'),
('III', P, 'a96', 'Alegaciones formuladas al inicio del procedimiento en la tramitación simplificada', '5 días',
 ['3 días', '10 días', '15 días'], 'Alegaciones formuladas al inicio del procedimiento durante el plazo de cinco días'),
('III', T, 'a98', 'Los actos de las Administraciones Públicas sujetos al Derecho Administrativo son inmediatamente ejecutivos, salvo, entre otros supuestos, que:',
 'Se trate de una resolución sancionadora contra la que quepa algún recurso en vía administrativa, incluido el potestativo de reposición',
 ['El interesado manifieste su disconformidad', 'Se trate de un acto de gravamen', 'El acto no se haya publicado en el «Boletín Oficial del Estado»'],
 r're:serán inmediatamente ejecutivos, salvo que: a\).*?b\) Se trate de una resolución de un procedimiento de naturaleza sancionadora contra la que quepa algún recurso'),
('III', T, 'a100', '¿Cuál de los siguientes NO es un medio de ejecución forzosa según el artículo 100.1?', 'La sanción pecuniaria',
 ['La multa coercitiva', 'La ejecución subsidiaria', 'La compulsión sobre las personas'],
 r're:a\) Apremio sobre el patrimonio\. b\) Ejecución subsidiaria\. c\) Multa coercitiva\. d\) Compulsión sobre las personas'),
('III', T, 'a100', 'Si fueran varios los medios de ejecución forzosa admisibles, se elegirá:', 'El menos restrictivo de la libertad individual',
 ['El más rápido', 'El más económico para la Administración', 'El que elija el interesado'], 'se elegirá el menos restrictivo de la libertad individual'),
('III', T, 'a100', 'Si para la ejecución forzosa fuera necesario entrar en el domicilio del afectado, la Administración deberá obtener:', 'El consentimiento del afectado o, en su defecto, la oportuna autorización judicial',
 ['La autorización del Delegado del Gobierno', 'La orden del superior jerárquico', 'La presencia de un notario'],
 'deberán obtener el consentimiento del mismo o, en su defecto, la oportuna autorización judicial'),
('III', T, 'a102', 'Habrá lugar a la ejecución subsidiaria cuando se trate de actos:', 'Que, por no ser personalísimos, puedan ser realizados por sujeto distinto del obligado',
 ['Personalísimos de hacer', 'Que impongan una obligación personalísima de no hacer', 'Que impongan el pago de una cantidad líquida'],
 'cuando se trate de actos que por no ser personalísimos puedan ser realizados por sujeto distinto del obligado'),
('III', T, 'a103', 'Según el artículo 103.2, la multa coercitiva:', 'Es independiente de las sanciones que puedan imponerse con tal carácter y compatible con ellas',
 ['Sustituye a la sanción', 'Es incompatible con las sanciones', 'Solo puede imponerse una vez'], 'La multa coercitiva es independiente de las sanciones'),
('III', T, 'a105', 'Contra las actuaciones de los órganos administrativos realizadas en materia de su competencia y de acuerdo con el procedimiento legalmente establecido:', 'No se admitirán a trámite acciones posesorias',
 ['Caben acciones posesorias ante la jurisdicción civil', 'Cabe recurso extraordinario de revisión en todo caso', 'Cabe recurso de amparo directo'], 'No se admitirán a trámite acciones posesorias'),
('III', T, 'a106', 'Para declarar de oficio la nulidad de los actos administrativos (artículo 106.1) es necesario:', 'El dictamen favorable del Consejo de Estado u órgano consultivo equivalente de la Comunidad Autónoma, si lo hubiere',
 ['Una sentencia judicial previa', 'El informe de la Abogacía del Estado', 'La autorización del Consejo de Ministros'],
 'y previo dictamen favorable del Consejo de Estado u órgano consultivo equivalente de la Comunidad Autónoma, si lo hubiere, declararán de oficio la nulidad'),
('III', T, 'a106', '¿Cuándo pueden las Administraciones declarar de oficio la nulidad de los actos del artículo 47.1 que hayan puesto fin a la vía administrativa o no hayan sido recurridos en plazo?', 'En cualquier momento',
 ['Dentro de los cuatro años siguientes', 'Dentro del año siguiente', 'Dentro de los seis meses siguientes'], 'Las Administraciones Públicas, en cualquier momento, por iniciativa propia o a solicitud de interesado'),
('III', T, 'a107', 'Para impugnar ante el orden contencioso-administrativo los actos favorables para los interesados que sean anulables, la Administración debe previamente:', 'Declararlos lesivos para el interés público',
 ['Revisarlos de oficio con dictamen del Consejo de Estado', 'Revocarlos', 'Suspender su ejecución'], 'previa su declaración de lesividad para el interés público'),
('III', T, 'a107', 'Si el acto proviniera de las entidades que integran la Administración Local, la declaración de lesividad se adoptará por:', 'El Pleno de la Corporación o, en defecto de éste, el órgano colegiado superior de la entidad',
 ['El Alcalde', 'La Junta de Gobierno Local', 'El Secretario de la Corporación'], 'la declaración de lesividad se adoptará por el Pleno de la Corporación'),
('III', T, 'a107', 'La declaración de lesividad:', 'No es susceptible de recurso, aunque podrá notificarse a los interesados a efectos informativos',
 ['Es recurrible en alzada', 'Es recurrible en reposición', 'Es recurrible ante el Consejo de Estado'], 'la declaración de lesividad no será susceptible de recurso'),
('III', T, 'a109', 'Las Administraciones Públicas podrán revocar sus actos de gravamen o desfavorables:', 'Mientras no haya transcurrido el plazo de prescripción',
 ['En cualquier momento, sin límite temporal', 'Dentro de los cuatro años siguientes', 'Dentro del mes siguiente a su notificación'], 'podrán revocar, mientras no haya transcurrido el plazo de prescripción'),
('III', T, 'a109', 'Los errores materiales, de hecho o aritméticos existentes en los actos podrán ser rectificados:', 'En cualquier momento, de oficio o a instancia de los interesados',
 ['Solo dentro del plazo de recurso', 'Solo a instancia de los interesados', 'Solo de oficio y en el plazo de un año'],
 'rectificar en cualquier momento, de oficio o a instancia de los interesados, los errores materiales'),
('III', T, 'a111', 'En el ámbito estatal, ¿quién es competente para la revisión de oficio de los actos y disposiciones dictados por los Ministros?', 'El Consejo de Ministros',
 ['El propio Ministro', 'El Secretario de Estado', 'El Presidente del Gobierno'], 'respecto de sus propios actos y disposiciones y de los actos y disposiciones dictados por los Ministros'),
('III', T, 'a112', 'Contra las disposiciones administrativas de carácter general:', 'No cabrá recurso en vía administrativa',
 ['Cabe recurso de alzada', 'Cabe recurso potestativo de reposición', 'Cabe recurso extraordinario de revisión'],
 'Contra las disposiciones administrativas de carácter general no cabrá recurso en vía administrativa'),
('III', T, 'a112', '¿Contra qué actos de trámite caben los recursos de alzada y potestativo de reposición?',
 'Los que deciden directa o indirectamente el fondo del asunto, determinan la imposibilidad de continuar el procedimiento o producen indefensión o perjuicio irreparable',
 ['Contra todos los actos de trámite', 'Contra ningún acto de trámite', 'Solo contra los que acuerden la práctica de pruebas'],
 'Contra las resoluciones y los actos de trámite, si estos últimos deciden directa o indirectamente el fondo del asunto'),
('III', T, 'a114', 'Según el artículo 114.1, pone fin a la vía administrativa:', 'La resolución administrativa de los procedimientos de responsabilidad patrimonial, cualquiera que fuese el tipo de relación de que derive',
 ['La propuesta de resolución', 'El acuerdo de iniciación del procedimiento', 'La apertura del trámite de audiencia'], r're:Ponen fin a la vía administrativa: a\).*?e\) La resolución administrativa de los procedimientos de responsabilidad patrimonial'),
('III', T, 'a114', 'En el ámbito estatal, ¿ponen fin a la vía administrativa los actos de los órganos directivos con nivel de Director general o superior?', 'Sí, en relación con las competencias que tengan atribuidas en materia de personal',
 ['Sí, en todo caso', 'No, en ningún caso', 'Solo los dictados en materia de contratación'],
 r're:en el ámbito estatal ponen fin a la vía administrativa los actos y resoluciones siguientes:.*?c\) Los emanados de los órganos directivos con nivel de Director general o superior, en relación con las competencias que tengan atribuidas en materia de personal'),
('III', T, 'a115', 'El error o la ausencia de la calificación del recurso por parte del recurrente:', 'No será obstáculo para su tramitación, siempre que se deduzca su verdadero carácter',
 ['Determina su inadmisión', 'Obliga a requerir su subsanación en diez días', 'Determina su desestimación'],
 'El error o la ausencia de la calificación del recurso por parte del recurrente no será obstáculo para su tramitación'),
('III', T, 'a115', 'Los vicios y defectos que hagan anulable un acto:', 'No podrán ser alegados por quienes los hubieren causado',
 ['Solo pueden ser alegados por la Administración', 'Pueden ser alegados por cualquier persona', 'Solo pueden alegarse en vía judicial'], 'no podrán ser alegados por quienes los hubieren causado'),
('III', T, 'a116', '¿Cuál de las siguientes NO es causa de inadmisión de los recursos según el artículo 116?', 'El error en la calificación del recurso por el recurrente',
 ['Carecer de legitimación el recurrente', 'Haber transcurrido el plazo para la interposición del recurso', 'Carecer el recurso manifiestamente de fundamento'],
 r're:Serán causas de inadmisión las siguientes:.*?e\) Carecer el recurso manifiestamente de fundamento'),
('III', T, 'a117', 'La interposición de cualquier recurso, excepto en los casos en que una disposición establezca lo contrario:', 'No suspenderá la ejecución del acto impugnado',
 ['Suspenderá automáticamente la ejecución del acto', 'Suspenderá la ejecución durante un mes', 'Suspenderá la ejecución si el acto es de gravamen'], 'no suspenderá la ejecución del acto impugnado'),
('III', T, 'a118', 'En la resolución de los recursos, ¿se tendrán en cuenta los hechos, documentos o alegaciones del recurrente que, habiendo podido aportarlos en el trámite de alegaciones, no lo hizo?', 'No',
 ['Sí, siempre', 'Sí, si son relevantes para el fondo', 'Sí, si los aporta junto con el recurso'], 'No se tendrán en cuenta en la resolución de los recursos, hechos, documentos o alegaciones del recurrente'),
('III', T, 'a119', 'Cuando, existiendo vicio de forma, no se estime procedente resolver sobre el fondo del recurso:', 'Se ordenará la retroacción del procedimiento al momento en que el vicio fue cometido',
 ['Se estimará el recurso en todo caso', 'Se declarará la nulidad de todo el procedimiento', 'Se desestimará el recurso'], 'se ordenará la retroacción del procedimiento al momento en el que el vicio fue cometido'),
('III', T, 'a119', 'Según el artículo 119.3, la resolución del recurso:', 'Será congruente con las peticiones del recurrente, sin que en ningún caso pueda agravarse su situación inicial',
 ['Podrá agravar la situación del recurrente si lo exige el interés público', 'Solo podrá pronunciarse sobre las cuestiones alegadas por los interesados', 'Deberá ser siempre estimatoria, al menos en parte'],
 'sin que en ningún caso pueda agravarse su situación inicial'),
('III', T, 'a121', '¿Ante qué órgano puede interponerse el recurso de alzada?', 'Ante el órgano que dictó el acto que se impugna o ante el competente para resolverlo',
 ['Solo ante el órgano que dictó el acto', 'Solo ante el superior jerárquico', 'Ante el Consejo de Estado'],
 'El recurso podrá interponerse ante el órgano que dictó el acto que se impugna o ante el competente para resolverlo'),
('III', P, 'a121', 'Remisión del recurso de alzada al órgano competente para resolverlo, cuando se interpuso ante el órgano que dictó el acto', '10 días',
 ['5 días', '15 días', '20 días'], 'éste deberá remitirlo al competente en el plazo de diez días'),
('III', T, 'a121', 'A efectos del recurso de alzada, los Tribunales y órganos de selección del personal al servicio de las Administraciones se consideran dependientes de:', 'El órgano al que estén adscritos o, en su defecto, del que haya nombrado a su presidente',
 ['El Ministerio de Hacienda', 'El Instituto Nacional de Administración Pública, en todo caso', 'Ningún órgano, por su autonomía funcional'], 'se considerarán dependientes del órgano al que estén adscritos'),
('III', T, 'a122', 'Contra la resolución de un recurso de alzada:', 'No cabe ningún otro recurso administrativo, salvo el extraordinario de revisión en los casos del artículo 125.1',
 ['Cabe recurso potestativo de reposición', 'Cabe un segundo recurso de alzada', 'Cabe recurso ante el Consejo de Estado'], 'Contra la resolución de un recurso de alzada no cabrá ningún otro recurso administrativo'),
('III', T, 'a123', '¿Contra qué actos puede interponerse el recurso potestativo de reposición?', 'Contra los que pongan fin a la vía administrativa',
 ['Contra los que no pongan fin a la vía administrativa', 'Contra las disposiciones de carácter general', 'Solo contra los actos presuntos'],
 'Los actos administrativos que pongan fin a la vía administrativa podrán ser recurridos potestativamente en reposición'),
('III', T, 'a123', 'Interpuesto recurso de reposición, ¿cuándo puede interponerse recurso contencioso-administrativo?', 'Cuando aquel sea resuelto expresamente o se haya producido su desestimación presunta',
 ['Simultáneamente, sin esperar a su resolución', 'Al día siguiente de su interposición', 'Solo tras su resolución expresa'],
 'No se podrá interponer recurso contencioso-administrativo hasta que sea resuelto expresamente'),
('III', T, 'a124', 'Contra la resolución de un recurso de reposición:', 'No podrá interponerse de nuevo dicho recurso',
 ['Cabe recurso de alzada', 'Cabe un nuevo recurso de reposición', 'Cabe recurso ante el superior jerárquico'], 'Contra la resolución de un recurso de reposición no podrá interponerse de nuevo dicho recurso'),
('III', T, 'a125', '¿Ante qué órgano se interpone el recurso extraordinario de revisión?', 'Ante el órgano administrativo que dictó el acto, que también será el competente para resolverlo',
 ['Ante el superior jerárquico del que dictó el acto', 'Ante el Consejo de Estado', 'Ante la Sala de lo Contencioso-administrativo del Tribunal Supremo'],
 'ante el órgano administrativo que los dictó, que también será el competente para su resolución'),
('III', P, 'a126', 'Transcurso, desde la interposición del recurso extraordinario de revisión sin resolución notificada, tras el cual se entiende desestimado', '3 meses',
 ['1 mes', '2 meses', '6 meses'], 'Transcurrido el plazo de tres meses desde la interposición del recurso extraordinario de revisión'),
]
