# Lote 20 · LO 2/1979, del Tribunal Constitucional · bloque I (tema I.1: Tribunal Constitucional; garantía de
# los derechos fundamentales). Se evitan los datos ya preguntados desde la CE (arts. 159-164).
NORMA, LOTE, INICIO = 'LOTC', 'lote-020', 20001
T, P = 'test', 'plazo'
PREGUNTAS = [
('I', T, 'aprimero', 'Según su Ley Orgánica, el Tribunal Constitucional, como intérprete supremo de la Constitución, está sometido:', 'Sólo a la Constitución y a su Ley Orgánica',
 ['A la Constitución y a las leyes aprobadas por las Cortes Generales', 'A la Constitución y al Consejo General del Poder Judicial', 'A la Constitución y a la jurisprudencia del Tribunal Supremo'],
 'está sometido sólo a la Constitución y a la presente Ley Orgánica'),
('I', T, 'asegundo', 'Los reglamentos que el Tribunal Constitucional dicte sobre su propio funcionamiento y organización deben ser aprobados por:', 'El Tribunal en Pleno',
 ['El Presidente del Tribunal', 'La Sala Primera', 'Las Cortes Generales'], 'que deberán ser aprobados por el Tribunal en Pleno'),
('I', T, 'acuarto', 'Las resoluciones del Tribunal Constitucional:', 'No pueden ser enjuiciadas por ningún órgano jurisdiccional del Estado',
 ['Pueden recurrirse ante el Tribunal Supremo', 'Pueden recurrirse ante el Consejo General del Poder Judicial', 'Pueden revisarse por la Sala de lo Penal del Tribunal Supremo'],
 'Las resoluciones del Tribunal Constitucional no podrán ser enjuiciadas por ningún órgano jurisdiccional del Estado'),
('I', T, 'acuarto', 'Respecto del Tribunal Constitucional, la cuestión de jurisdicción o competencia:', 'No puede promoverse en ningún caso',
 ['Puede promoverla el Gobierno', 'Puede promoverla el Tribunal Supremo', 'Puede promoverse ante el Consejo de Estado'],
 'En ningún caso se podrá promover cuestión de jurisdicción o competencia al Tribunal Constitucional'),
('I', T, 'asexto', 'El Tribunal Constitucional actúa:', 'En Pleno, en Sala o en Sección',
 ['Solo en Pleno', 'En Pleno o en Comisión', 'En Pleno, en Sala o en Junta de Gobierno'], 'El Tribunal Constitucional actúa en Pleno, en Sala o en Sección'),
('I', T, 'aseptimo', 'Cada una de las Salas del Tribunal Constitucional está compuesta por:', 'Seis Magistrados nombrados por el Tribunal en Pleno',
 ['Cuatro Magistrados nombrados por el Presidente', 'Tres Magistrados elegidos por sorteo', 'Seis Magistrados nombrados por el Rey'],
 'Cada Sala está compuesta por seis Magistrados nombrados por el Tribunal en Pleno'),
('I', T, 'aseptimo', 'La Sala Primera del Tribunal Constitucional está presidida por:', 'El Presidente del Tribunal',
 ['El Vicepresidente del Tribunal', 'El Magistrado de mayor edad', 'El Magistrado más antiguo'],
 'El Presidente del Tribunal lo es también de la Sala Primera'),
('I', T, 'aseptimo', 'La Sala Segunda del Tribunal Constitucional está presidida por:', 'El Vicepresidente del Tribunal',
 ['El Presidente del Tribunal', 'El Magistrado más moderno', 'Un Magistrado elegido por la propia Sala'],
 'El Vicepresidente del Tribunal presidirá en la Sala Segunda'),
('I', T, 'aoctavo', 'Las Secciones del Tribunal Constitucional están compuestas por:', 'El respectivo Presidente o quien le sustituya y dos Magistrados',
 ['Tres Magistrados elegidos por sorteo', 'El Presidente del Tribunal y cuatro Magistrados', 'Seis Magistrados'],
 'constituirán Secciones compuestas por el respectivo Presidente o quien le sustituya y dos Magistrados'),
('I', T, 'anoveno', 'En la elección del Presidente del Tribunal Constitucional por el Pleno, en primera votación se requiere:', 'La mayoría absoluta',
 ['La mayoría de dos tercios', 'La mayoría de tres quintos', 'La mayoría de tres cuartas partes'], 'En primera votación se requerirá la mayoría absoluta'),
('I', T, 'anoveno', 'Si en la elección del Presidente del Tribunal Constitucional se repite el empate en la última votación, será propuesto:', 'El de mayor antigüedad en el cargo y, en caso de igualdad, el de mayor edad',
 ['El de mayor edad en todo caso', 'El que designe el Rey', 'El propuesto por el Gobierno'],
 'será propuesto el de mayor antigüedad en el cargo y en caso de igualdad el de mayor edad'),
('I', T, 'anoveno', 'Expirado su mandato, el Presidente del Tribunal Constitucional:', 'Puede ser reelegido por una sola vez',
 ['No puede ser reelegido', 'Puede ser reelegido indefinidamente', 'Puede ser reelegido dos veces'], 'expirado el cual podrá ser reelegido por una sola vez'),
('I', T, 'anoveno', 'Corresponde al Vicepresidente del Tribunal Constitucional:', 'Sustituir al Presidente en caso de vacante, ausencia u otro motivo legal y presidir la Sala Segunda',
 ['Presidir la Sala Primera', 'Ejercer la representación del Tribunal', 'Nombrar a los letrados del Tribunal'],
 'al que incumbe sustituir al Presidente en caso de vacante, ausencia u otro motivo legal y presidir la Sala Segunda'),
('I', T, 'adiez', '¿Cuál de los siguientes asuntos conoce el Tribunal Constitucional en Pleno?', 'La constitucionalidad o inconstitucionalidad de los tratados internacionales',
 ['Los recursos de amparo, en todo caso', 'Las cuestiones de inconstitucionalidad, en todo caso', 'Los recursos contencioso-administrativos contra reglamentos'],
 'a) De la constitucionalidad o inconstitucionalidad de los tratados internacionales'),
('I', T, 'adoce', 'La distribución de asuntos entre las Salas del Tribunal Constitucional se efectúa:', 'Según un turno establecido por el Pleno a propuesta de su Presidente',
 ['Por sorteo público', 'Según decida el Ministerio de Justicia', 'Por orden alfabético de los recurrentes'],
 'según un turno establecido por el Pleno a propuesta de su Presidente'),
('I', T, 'atrece', 'Cuando una Sala del Tribunal Constitucional considere necesario apartarse de la doctrina constitucional precedente, la cuestión:', 'Se somete a la decisión del Pleno',
 ['La resuelve la propia Sala', 'Se somete a la otra Sala', 'Se somete a la Sección correspondiente'], 'la cuestión se someterá a la decisión del Pleno'),
('I', T, 'acatorce', 'El Tribunal Constitucional en Pleno puede adoptar acuerdos cuando estén presentes, al menos:', 'Dos tercios de los miembros que en cada momento lo compongan',
 ['La mitad más uno de sus miembros', 'Tres quintos de sus miembros', 'Tres cuartas partes de sus miembros'],
 'cuando estén presentes, al menos, dos tercios de los miembros que en cada momento lo compongan'),
('I', T, 'aquince', 'Ejerce la representación del Tribunal Constitucional:', 'Su Presidente',
 ['Su Vicepresidente', 'El Secretario General', 'El Magistrado más antiguo'], 'El Presidente del Tribunal Constitucional ejerce la representación del Tribunal'),
('I', T, 'adieciseis', 'En las propuestas de nombramiento de Magistrados del Tribunal Constitucional, cada órgano proponente debe incluir como mínimo:', 'Un cuarenta por ciento de cada uno de los sexos',
 ['Un treinta por ciento de cada uno de los sexos', 'Un cincuenta por ciento de mujeres', 'Un veinticinco por ciento de cada uno de los sexos'],
 'incluyan como mínimo un cuarenta por ciento de cada uno de los sexos'),
('I', T, 'adieciseis', 'Los Magistrados del Tribunal Constitucional propuestos por el Senado son elegidos entre las candidaturas presentadas por:', 'Las Asambleas Legislativas de las comunidades autónomas',
 ['Los Grupos Parlamentarios del Senado', 'Los Gobiernos de las comunidades autónomas', 'El Consejo General del Poder Judicial'],
 'serán elegidos entre las candidaturas presentadas por las Asambleas Legislativas de las comunidades autónomas'),
('I', T, 'adieciseis', 'Antes de su nombramiento, los candidatos propuestos por el Congreso y por el Senado deben:', 'Comparecer previamente ante las correspondientes Comisiones',
 ['Superar un examen ante el Consejo General del Poder Judicial', 'Prestar juramento ante el Pleno de la Cámara', 'Obtener el informe favorable del Gobierno'],
 'deberán comparecer previamente ante las correspondientes Comisiones'),
('I', P, 'adiecisiete', 'Antelación, respecto de la expiración de los nombramientos, con la que el Presidente del Tribunal Constitucional solicita que se inicie el procedimiento para designar a los nuevos Magistrados', 'Antes de los cuatro meses previos',
 ['Antes de los dos meses previos', 'Antes de los seis meses previos', 'Antes del mes previo'],
 'Antes de los cuatro meses previos a la fecha de expiración de los nombramientos'),
('I', T, 'adiecisiete', 'Los Magistrados del Tribunal Constitucional cuyo mandato ha expirado:', 'Continúan en el ejercicio de sus funciones hasta que hayan tomado posesión quienes hubieren de sucederles',
 ['Cesan automáticamente el día de la expiración', 'Continúan en funciones un máximo de tres meses', 'Son sustituidos provisionalmente por letrados del Tribunal'],
 'continuarán en el ejercicio de sus funciones hasta que hayan tomado posesión quienes hubieren de sucederles'),
('I', T, 'adiecinueve', 'Según la LOTC, el cargo de Magistrado del Tribunal Constitucional es incompatible, entre otros, con:', 'El de Defensor del Pueblo',
 ['La condición de ciudadano español', 'La condición de Profesor de Universidad jubilado', 'La pertenencia a un partido político sin funciones directivas'],
 'Primero, con el de Defensor del Pueblo'),
('I', P, 'adiecinueve', 'Plazo, siguiente a la propuesta, para que quien sea propuesto como Magistrado del Tribunal Constitucional cese en la actividad incompatible (si no, se entiende que no acepta el cargo)', '10 días',
 ['15 días', '30 días', '1 mes'], 'Si no lo hiciere en el plazo de diez días siguientes a la propuesta'),
('I', T, 'aveinte', 'Los funcionarios públicos nombrados Magistrados del Tribunal Constitucional pasan, en su carrera de origen, a la situación de:', 'Servicios especiales',
 ['Excedencia voluntaria', 'Servicios en otras Administraciones públicas', 'Suspensión de funciones'], 'pasarán a la situación de servicios especiales en su carrera de origen'),
('I', T, 'aveintiuno', 'Los Magistrados del Tribunal Constitucional prestan juramento o promesa al asumir su cargo ante:', 'El Rey',
 ['El Presidente del Gobierno', 'Las Cortes Generales', 'El Presidente del Tribunal Supremo'], 'prestarán, al asumir su cargo ante el Rey, el siguiente juramento o promesa'),
('I', T, 'aveintitres', 'El cese de un Magistrado del Tribunal Constitucional por renuncia aceptada o por expiración del plazo de su nombramiento se decreta por:', 'El Presidente del Tribunal',
 ['El Tribunal en Pleno por mayoría simple', 'El Rey a propuesta del Gobierno', 'El Tribunal en Pleno por tres cuartas partes'],
 'en los casos primero y segundo, así como en el de fallecimiento, se decretará por el Presidente'),
('I', T, 'aveintitres', 'El cese de un Magistrado del Tribunal Constitucional por incompatibilidad sobrevenida lo decide el Tribunal en Pleno por:', 'Mayoría simple',
 ['Mayoría de las tres cuartas partes de sus miembros', 'Mayoría absoluta', 'Unanimidad'],
 'por mayoría simple en los casos tercero y cuarto'),
('I', T, 'aveinticuatro', 'La suspensión de un Magistrado del Tribunal Constitucional requiere el voto favorable de:', 'Las tres cuartas partes de los miembros del Tribunal reunido en Pleno',
 ['La mayoría simple del Pleno', 'Dos tercios de la Sala a la que pertenezca', 'La mayoría absoluta del Congreso'],
 'La suspensión requiere el voto favorable de las tres cuartas partes de los miembros del Tribunal reunido en Pleno'),
('I', T, 'aveinticinco', 'Tienen derecho a una remuneración de transición por un año los Magistrados del Tribunal Constitucional que hubieran desempeñado el cargo durante un mínimo de:', 'Tres años',
 ['Un año', 'Seis años', 'Nueve años'], 'durante un mínimo de tres años tendrán derecho a una remuneración de transición por un año'),
('I', T, 'aveintiseis', 'La responsabilidad criminal de los Magistrados del Tribunal Constitucional sólo es exigible ante:', 'La Sala de lo Penal del Tribunal Supremo',
 ['El propio Tribunal Constitucional en Pleno', 'La Audiencia Nacional', 'El Tribunal Superior de Justicia de Madrid'],
 'sólo será exigible ante la Sala de lo Penal del Tribunal Supremo'),
('I', T, 'atreinta', 'Como regla general, la admisión de un recurso o de una cuestión de inconstitucionalidad:', 'No suspende la vigencia ni la aplicación de la ley impugnada',
 ['Suspende automáticamente la vigencia de la ley', 'Suspende la ley durante cinco meses', 'Suspende la ley si lo solicitan cincuenta Diputados'],
 'no suspenderá la vigencia ni la aplicación de la Ley'),
('I', T, 'atreintaydos', 'Contra leyes del Estado que puedan afectar a su propio ámbito de autonomía, también están legitimados para interponer recurso de inconstitucionalidad:', 'Los órganos colegiados ejecutivos y las Asambleas de las Comunidades Autónomas, previo acuerdo adoptado al efecto',
 ['Los Ayuntamientos de las capitales de provincia', 'Los Delegados del Gobierno en las Comunidades Autónomas', 'Los Tribunales Superiores de Justicia'],
 'están también legitimados los órganos colegiados ejecutivos y las Asambleas de las Comunidades Autónomas, previo acuerdo adoptado al efecto'),
('I', P, 'atreintaytres', 'Plazo general para interponer el recurso de inconstitucionalidad, a partir de la publicación de la ley impugnada', '3 meses',
 ['9 meses', '2 meses', '30 días'], 'se formulará dentro del plazo de tres meses a partir de la publicación'),
('I', P, 'atreintaytres', 'Plazo ampliado para interponer el recurso de inconstitucionalidad cuando se haya reunido la Comisión Bilateral de Cooperación y acordado iniciar negociaciones', '9 meses',
 ['6 meses', '3 meses', '1 año'], 'podrán interponer el recurso de inconstitucionalidad en el plazo de nueve meses'),
('I', P, 'atreintaycuatro', 'Plazo para la personación y la formulación de alegaciones en el recurso de inconstitucionalidad, una vez admitida a trámite la demanda', '15 días',
 ['10 días', '20 días', '30 días'], 'La personación y la formulación de alegaciones deberán hacerse en el plazo de quince días'),
('I', T, 'atreintaycinco', 'El órgano judicial sólo puede plantear la cuestión de inconstitucionalidad:', 'Una vez concluso el procedimiento y dentro del plazo para dictar sentencia',
 ['En cualquier momento del procedimiento', 'Antes de admitir la demanda', 'Una vez dictada sentencia firme'],
 'sólo podrá plantear la cuestión una vez concluso el procedimiento y dentro del plazo para dictar sentencia'),
('I', P, 'atreintaycinco', 'Plazo común e improrrogable para que las partes y el Ministerio Fiscal aleguen sobre la pertinencia de plantear la cuestión de inconstitucionalidad', '10 días',
 ['15 días', '3 días', '20 días'], 'en el plazo común e improrrogable de 10 días'),
('I', T, 'atreintaycinco', 'El auto por el que el juez decide sobre el planteamiento de la cuestión de inconstitucionalidad:', 'No es susceptible de recurso de ninguna clase',
 ['Es recurrible en apelación', 'Es recurrible en amparo', 'Es recurrible en reposición'], 'Dicho auto no será susceptible de recurso de ninguna clase'),
('I', T, 'atreintaysiete', 'El Tribunal Constitucional puede rechazar en trámite de admisión una cuestión de inconstitucionalidad, mediante auto y sin otra audiencia que la de:', 'El Fiscal General del Estado',
 ['El Abogado del Estado', 'El juez que la planteó', 'El Presidente del Gobierno'], 'sin otra audiencia que la del Fiscal General del Estado'),
('I', T, 'atreintayocho', 'Las sentencias recaídas en procedimientos de inconstitucionalidad producen efectos generales desde:', 'La fecha de su publicación en el «Boletín Oficial del Estado»',
 ['La fecha en que se dictan', 'Su notificación a las partes', 'Los veinte días siguientes a su publicación'],
 'producirán efectos generales desde la fecha de su publicación en el «Boletín Oficial del Estado»'),
('I', T, 'atreintaynueve', 'El Tribunal Constitucional puede fundar la declaración de inconstitucionalidad en la infracción de:', 'Cualquier precepto constitucional, haya o no sido invocado en el curso del proceso',
 ['Solo los preceptos invocados por el recurrente', 'Solo los preceptos del Título I de la Constitución', 'Solo los preceptos citados en el auto de admisión'],
 'en la infracción de cualquier precepto constitucional, haya o no sido invocado en el curso del proceso'),
('I', T, 'acuarenta', 'Las sentencias que declaran la inconstitucionalidad de una ley permiten revisar procesos fenecidos con sentencia firme:', 'Solo en procesos penales o contencioso-administrativos sancionadores en que resulte una reducción de la pena o de la sanción, o una exclusión, exención o limitación de la responsabilidad',
 ['En todo caso', 'Nunca', 'Solo en procesos civiles'],
 'salvo en el caso de los procesos penales o contencioso-administrativos referentes a un procedimiento sancionador'),
('I', T, 'acuarentayuno', 'Además de los derechos de los artículos 14 a 29 de la Constitución, es susceptible de amparo constitucional:', 'La objeción de conciencia del artículo 30',
 ['El derecho a la vivienda', 'El derecho al trabajo', 'El derecho a la protección de la salud'],
 'Igual protección será aplicable a la objeción de conciencia reconocida en el artículo treinta de la Constitución'),
('I', P, 'acuarentaydos', 'Plazo para recurrir en amparo las decisiones o actos sin valor de ley de las Cortes o de las Asambleas legislativas autonómicas, desde que sean firmes', '3 meses',
 ['20 días', '30 días', '2 meses'], 'podrán ser recurridos dentro del plazo de tres meses'),
('I', P, 'acuarentaytres', 'Plazo para interponer recurso de amparo frente a violaciones originadas por actos del Gobierno o de la Administración, desde la notificación de la resolución del previo proceso judicial', '20 días',
 ['30 días', '3 meses', '10 días'], 'será el de los veinte días siguientes a la notificación de la resolución recaída en el previo proceso judicial'),
('I', P, 'acuarentaycuatro', 'Plazo para interponer recurso de amparo frente a violaciones originadas por un acto u omisión de un órgano judicial', '30 días',
 ['20 días', '3 meses', '15 días'], 'El plazo para interponer el recurso de amparo será de 30 días'),
('I', T, 'acuarentayseis', 'Frente a actos del Gobierno (artículo 43 LOTC), están legitimados para interponer el recurso de amparo:', 'Quienes hayan sido parte en el proceso judicial correspondiente, el Defensor del Pueblo y el Ministerio Fiscal',
 ['Solo la persona directamente afectada', 'Cincuenta Diputados o cincuenta Senadores', 'El Presidente del Gobierno y el Defensor del Pueblo'],
 'quienes hayan sido parte en el proceso judicial correspondiente, el Defensor del Pueblo y el Ministerio Fiscal'),
('I', T, 'acuarentaysiete', 'En los procesos de amparo, el Ministerio Fiscal:', 'Interviene en todos ellos',
 ['Solo interviene si lo pide el recurrente', 'Nunca interviene', 'Solo interviene en los amparos contra actos judiciales'],
 'El Ministerio Fiscal intervendrá en todos los procesos de amparo'),
('I', T, 'acuarentaynueve', 'La demanda de amparo debe justificar en todo caso:', 'La especial trascendencia constitucional del recurso',
 ['La cuantía del perjuicio sufrido', 'El agotamiento de la vía administrativa', 'La conformidad del Ministerio Fiscal'],
 'la demanda justificará la especial trascendencia constitucional del recurso'),
('I', T, 'acincuenta', 'La Sección acuerda mediante providencia la admisión del recurso de amparo:', 'Por unanimidad de sus miembros',
 ['Por mayoría simple', 'Por mayoría de dos tercios', 'Por decisión de su Presidente'], 'La Sección, por unanimidad de sus miembros, acordará mediante providencia la admisión'),
('I', T, 'acincuentaytres', 'Al conocer del fondo del recurso de amparo, la Sala o la Sección pronuncia en su sentencia:', 'Otorgamiento o denegación de amparo',
 ['Estimación parcial o inadmisión', 'Nulidad o anulabilidad', 'Condena o absolución'], 'a) Otorgamiento de amparo. b) Denegación de amparo'),
('I', T, 'acincuentayseis', 'La interposición del recurso de amparo:', 'No suspende los efectos del acto o sentencia impugnados',
 ['Suspende siempre los efectos del acto impugnado', 'Suspende el acto durante diez días', 'Suspende el acto si lo pide el Ministerio Fiscal'],
 'La interposición del recurso de amparo no suspenderá los efectos del acto o sentencia impugnados'),
('I', P, 'asesentaydos', 'Plazo para que el Gobierno formalice directamente ante el Tribunal Constitucional un conflicto positivo de competencia frente a una Comunidad Autónoma', '2 meses',
 ['3 meses', '1 mes', '20 días'], 'en el plazo de dos meses, el conflicto de competencia'),
('I', T, 'asesentayseis', 'La sentencia que resuelve un conflicto de competencia:', 'Declara la titularidad de la competencia controvertida',
 ['Se limita a declarar la nulidad del acto, sin pronunciarse sobre la competencia', 'Remite la decisión a las Cortes Generales', 'Solo tiene efectos entre las partes y no vincula a los demás poderes públicos'],
 'La sentencia declarará la titularidad de la competencia controvertida'),
]
