# Lote 29 · RD 203/2021, Reglamento de actuación y funcionamiento del sector público por medios
# electrónicos · bloque II (temas II.2 y II.3: registro y archivo; administración electrónica; Punto de
# Acceso General). Se evitan los nombres de ministerios, que han cambiado desde 2021.
NORMA, LOTE, INICIO = 'RDAE', 'lote-029', 29001
T, P = 'test', 'plazo'
PREGUNTAS = [
('II', P, 'a3', 'Plazo a partir del cual produce efectos la comunicación de una persona física no obligada de que quiere relacionarse (o dejar de relacionarse) electrónicamente con la Administración', 'Desde el 5.º día hábil siguiente a que el órgano tenga constancia',
 ['Desde el día siguiente', 'Desde el 10.º día hábil siguiente', 'Desde el mes siguiente'],
 'los efectos de la comunicación se producirán a partir del quinto día hábil siguiente'),
('II', T, 'a4', '¿Cuál de los siguientes canales de asistencia para el acceso a los servicios electrónicos figura expresamente en la enumeración del artículo 4 del RD 203/2021?', 'Las redes sociales',
 ['Las notarías', 'Los colegios profesionales', 'Las entidades bancarias'], 'b) Portales de internet y sedes electrónicas. c) Redes sociales'),
('II', T, 'a5', 'Según el RD 203/2021, el punto de acceso electrónico de titularidad pública que permite el acceso por internet a la información y, en su caso, a la sede electrónica, es:', 'El portal de internet',
 ['La sede electrónica asociada', 'La Dirección Electrónica Habilitada única', 'El Registro Electrónico General'],
 'se entiende por portal de internet el punto de acceso electrónico cuya titularidad corresponda a una Administración Pública'),
('II', T, 'a7', 'Según el RD 203/2021, las Administraciones Públicas contarán con:', 'Un Punto de Acceso General electrónico (PAGe)',
 ['Un único portal común para todas las Administraciones', 'Una sede electrónica por cada órgano', 'Un registro en papel por cada unidad'],
 'Las Administraciones Públicas contarán con un Punto de Acceso General electrónico (PAGe)'),
('II', T, 'a7', 'La Dirección Electrónica Habilitada única está alojada en:', 'La sede electrónica del PAGe de la Administración General del Estado',
 ['La sede electrónica de cada Ayuntamiento', 'El portal de cada Ministerio', 'El Registro Electrónico de Apoderamientos'],
 'En dicha sede electrónica está alojada la Dirección Electrónica Habilitada única'),
('II', T, 'a8', 'La Carpeta Ciudadana del sector público estatal es:', 'El área personalizada de las personas interesadas en su relación con el sector público estatal',
 ['Un registro de funcionarios habilitados', 'El archivo electrónico único', 'Un portal de transparencia'],
 'La Carpeta Ciudadana es el área personalizada de las personas interesadas'),
('II', T, 'a8', 'Además del interesado, puede acceder a su Carpeta Ciudadana:', 'Quien ostente un poder general otorgado por el interesado e inscrito en el Registro Electrónico de Apoderamientos',
 ['Cualquier empleado público', 'Cualquier familiar sin apoderamiento', 'Cualquier persona que conozca su DNI'],
 'b) Quien ostente un poder general previsto en el artículo 6.4.a) de la Ley 39/2015'),
('II', T, 'a9', 'Según el RD 203/2021, mediante la sede electrónica se realizan:', 'Todas las actuaciones y trámites que requieran la identificación de la Administración y, en su caso, la identificación o firma de los interesados',
 ['Solo actuaciones informativas sin identificación', 'Solo la publicación de normas', 'Solo los pagos de tasas'],
 'Mediante dicha sede electrónica se realizarán todas las actuaciones y trámites referidos a procedimientos o a servicios que requieran la identificación'),
('II', T, 'a1-2', 'La sede electrónica asociada:', 'Tiene consideración de sede electrónica a todos los efectos',
 ['Carece de validez jurídica propia', 'Solo puede contener información', 'Requiere autorización del Consejo de Ministros'],
 'La sede electrónica asociada tendrá consideración de sede electrónica a todos los efectos'),
('II', T, 'a1-2', 'En el caso de las entidades locales, el acto de creación de una sede electrónica se publica en:', 'El boletín oficial de la provincia a la que pertenezca la entidad',
 ['El Boletín Oficial del Estado', 'El tablón de anuncios municipal exclusivamente', 'El Diario Oficial de la Unión Europea'],
 'En el caso de las entidades locales, el boletín oficial será el de la provincia al que pertenezca la entidad'),
('II', T, 'a1-4', 'El responsable de la integridad, veracidad y actualización de la información y servicios accesibles a través de una sede electrónica es:', 'El titular de la sede electrónica',
 ['El proveedor tecnológico', 'Cada usuario que la consulta', 'La Agencia Española de Protección de Datos'],
 'El titular de la sede electrónica y, en su caso, de la sede electrónica asociada, será responsable de la integridad, veracidad y actualización'),
('II', T, 'a1-5', 'En el ámbito estatal, la determinación de una actuación administrativa como automatizada:', 'Se autoriza por resolución del titular del órgano competente y se publica en la sede electrónica',
 ['Se aprueba por ley', 'No necesita ninguna resolución', 'Se aprueba por el Consejo de Ministros en todo caso'],
 'se autorizará por resolución del titular del órgano administrativo competente por razón de la materia'),
('II', P, 'a1-6', 'Plazo para atender el requerimiento de subsanación cuando un obligado a relacionarse electrónicamente no ha usado medios electrónicos (si no, se le tiene por desistido)', '10 días',
 ['5 días', '15 días', '1 mes'], 'de no ser atendido el requerimiento en el plazo de diez días'),
('II', T, 'a1-6', 'Cuando un obligado a relacionarse electrónicamente presenta en papel una solicitud de iniciación y luego la subsana, se considera fecha de presentación:', 'La fecha de la subsanación',
 ['La fecha de la presentación en papel', 'La fecha de la resolución', 'La fecha del requerimiento'],
 'la fecha de la subsanación se considerará a estos efectos como fecha de presentación de la solicitud'),
('II', T, 'a3-3', 'En el Registro de Funcionarios Habilitados de la AGE constan inscritos, entre otros:', 'Los funcionarios habilitados para la expedición de copias auténticas',
 ['Todos los ciudadanos con certificado digital', 'Los apoderamientos de los interesados', 'Los representantes de empresas contratistas'],
 'b) El personal funcionario habilitado para la expedición de copias auténticas'),
('II', T, 'a3-9', 'Según el RD 203/2021, cada Administración dispondrá de:', 'Un Registro Electrónico General en el que se hará el asiento de todo documento presentado o recibido en cualquier órgano',
 ['Un registro en papel por cada órgano', 'Un registro solo para documentos normalizados', 'Un registro común con todas las demás Administraciones, sin registro propio'],
 'Cada Administración dispondrá de un Registro Electrónico General en el que hará el asiento de todo documento'),
('II', T, 'a3-10', 'Las anotaciones en el Registro General de la Administración General del Estado:', 'Tienen plena eficacia y validez para todas las Administraciones Públicas',
 ['Solo son válidas para la Administración General del Estado', 'Deben ratificarse en el registro de destino', 'Tienen valor meramente informativo'],
 'Las anotaciones en el Registro General de la Administración General del Estado tendrán plena eficacia y validez para todas las Administraciones Públicas'),
('II', T, 'a3-11', 'Los documentos en soporte no electrónico se presentan a través de:', 'Las oficinas de asistencia en materia de registros',
 ['La Carpeta Ciudadana', 'La Dirección Electrónica Habilitada única', 'Cualquier unidad administrativa sin registro'],
 'Los documentos en soporte no electrónico se presentarán a través de las oficinas de asistencia en materia de registros'),
('II', T, 'a4-2', 'Las Oficinas de asistencia en materia de registros de la AGE tienen naturaleza de:', 'Órgano administrativo',
 ['Unidad administrativa sin funciones', 'Organismo autónomo', 'Entidad privada colaboradora'],
 'Las Oficinas de asistencia en materia de registros tienen naturaleza de órgano administrativo'),
('II', T, 'a4-4', 'Si la notificación se pone a disposición en la sede electrónica y en la Dirección Electrónica Habilitada única, para el cómputo de plazos se toma:', 'La fecha y hora de acceso o rechazo en el sistema en que haya ocurrido en primer lugar',
 ['Siempre la fecha de la sede electrónica', 'Siempre la fecha de la Dirección Electrónica Habilitada única', 'La fecha más tardía de las dos'],
 'se tomará la fecha y hora de acceso al contenido o el rechazo de la notificación por el interesado o su representante en el sistema en el que haya ocurrido en primer lugar'),
('II', T, 'a4-5', 'La falta de práctica del aviso de puesta a disposición de la notificación:', 'No impide que la notificación sea considerada plenamente válida',
 ['Determina la nulidad de la notificación', 'Obliga a repetir la notificación en papel', 'Suspende los plazos del procedimiento'],
 'La falta de práctica de este aviso, de carácter meramente informativo, no impedirá que la notificación sea considerada plenamente válida'),
('II', P, 'a4-7', 'Plazo desde la puesta a disposición de una notificación en sede electrónica sin acceder a su contenido, tras el cual se presume rechazada', '10 días naturales',
 ['10 días hábiles', '15 días naturales', '5 días hábiles'], 'por haber transcurrido el plazo de diez días naturales desde la puesta a disposición'),
('II', T, 'a5-2', 'Cuando las normas reguladoras no establezcan la utilización de un sello electrónico cualificado de tiempo, los documentos administrativos electrónicos llevarán asociada:', 'Una marca de tiempo',
 ['Un código seguro de verificación', 'Una firma manuscrita digitalizada', 'Un sello de órgano en papel'],
 'La marca de tiempo será utilizada en todos aquellos casos en los que las normas reguladoras no establezcan la utilización de un sello electrónico cualificado de tiempo'),
('II', T, 'a5-3', 'El foliado de los expedientes administrativos electrónicos se lleva a cabo mediante:', 'Un índice electrónico autenticado',
 ['La numeración manual de cada página', 'Un sello de tiempo en cada documento', 'Un código de barras'],
 'El foliado de los expedientes administrativos electrónicos se llevará a cabo mediante un índice electrónico autenticado'),
('II', T, 'a5-3', 'Según el RD 203/2021, un mismo documento electrónico:', 'Puede formar parte de distintos expedientes administrativos',
 ['Solo puede formar parte de un expediente', 'Debe duplicarse para cada expediente', 'No puede incorporarse a expedientes de otra Administración'],
 'Un mismo documento electrónico podrá formar parte de distintos expedientes administrativos'),
('II', P, 'a5-5', 'Tiempo durante el que se conservan a disposición del interesado, una vez digitalizados, los documentos en papel que no se le pudieron devolver al presentarlos (salvo plazo reglamentario mayor)', '6 meses',
 ['3 meses', '1 año', '1 mes'], 'una vez digitalizados serán conservados a su disposición durante seis meses'),
]
