# Lote 16 · TREBEP (RDL 5/2015), segunda parte: artículos no cubiertos en el lote 7.
# Retribuciones (arts. 21-30) en el bloque V (tema V.4); el resto en el bloque IV (temas IV.1-IV.5).
NORMA, LOTE, INICIO = 'TREBEP', 'lote-016', 16001
T, P = 'test', 'plazo'
PREGUNTAS = [
# Retribuciones
('V', T, 'a21', 'Las cuantías de las retribuciones básicas y el incremento de las cuantías globales de las complementarias de los funcionarios deben reflejarse para cada ejercicio en:', 'La correspondiente ley de presupuestos',
 ['Un real decreto del Gobierno', 'El convenio colectivo', 'Una orden del Ministerio de Hacienda'], 'deberán reflejarse para cada ejercicio presupuestario en la correspondiente ley de presupuestos'),
'RETIRADA: duplicada del lote 7',
('V', T, 'a22', 'Las retribuciones que retribuyen las características de los puestos de trabajo, la carrera profesional o el desempeño, rendimiento o resultados del funcionario son las:', 'Retribuciones complementarias',
 ['Retribuciones básicas', 'Retribuciones diferidas', 'Indemnizaciones por razón del servicio'], 'Las retribuciones complementarias son las que retribuyen las características de los puestos de trabajo'),
('V', T, 'a22', 'Las pagas extraordinarias de los funcionarios serán:', 'Dos al año, cada una por el importe de una mensualidad de retribuciones básicas y de la totalidad de las complementarias, salvo las de rendimiento y servicios extraordinarios',
 ['Dos al año, solo por el importe del sueldo', 'Tres al año, por el importe del sueldo y trienios', 'Una al año, por el importe de una mensualidad completa'],
 'Las pagas extraordinarias serán dos al año'),
('V', T, 'a22', 'Según el artículo 22.5, los funcionarios NO podrán percibir:', 'Participación en tributos o premios en multas impuestas como contraprestación de servicios',
 ['Indemnizaciones por razón del servicio', 'Trienios', 'Complementos por servicios extraordinarios'],
 'No podrá percibirse participación en tributos o en cualquier otro ingreso de las Administraciones Públicas'),
('V', T, 'a23', 'Las retribuciones básicas de los funcionarios se fijan en:', 'La Ley de Presupuestos Generales del Estado',
 ['Las leyes de función pública de cada Administración', 'El convenio colectivo', 'La relación de puestos de trabajo'], 'Las retribuciones básicas, que se fijan en la Ley de Presupuestos Generales del Estado'),
('V', T, 'a23', 'Los trienios consisten en una cantidad igual para cada Subgrupo o Grupo de clasificación por cada:', 'Tres años de servicio',
 ['Dos años de servicio', 'Cinco años de servicio', 'Año de servicio'], 'por cada tres años de servicio'),
('V', T, 'a24', 'La cuantía y estructura de las retribuciones complementarias de los funcionarios se establecen por:', 'Las correspondientes leyes de cada Administración Pública',
 ['La Ley de Presupuestos Generales del Estado exclusivamente', 'El TREBEP directamente', 'Resolución del órgano de personal'],
 'se establecerán por las correspondientes leyes de cada Administración Pública'),
('V', T, 'a24', '¿Cuál de los siguientes NO es un factor de las retribuciones complementarias según el artículo 24 del TREBEP?', 'La pertenencia a un Subgrupo de clasificación profesional',
 ['La progresión alcanzada dentro del sistema de carrera administrativa', 'El grado de interés, iniciativa o esfuerzo y el rendimiento', 'Los servicios extraordinarios prestados fuera de la jornada normal'],
 r're:atendiendo, entre otros, a los siguientes factores: a\).*?d\) Los servicios extraordinarios prestados fuera de la jornada normal de trabajo'),
('V', T, 'a25', 'Los funcionarios interinos perciben, entre otras retribuciones:', 'Las básicas y las pagas extraordinarias de su Subgrupo o Grupo de adscripción',
 ['Solo el sueldo base', 'Las mismas retribuciones que el personal eventual', 'Solo las retribuciones complementarias'],
 'Los funcionarios interinos percibirán las retribuciones básicas y las pagas extraordinarias'),
'RETIRADA: duplicada del lote 7',
('V', T, 'a27', 'Las retribuciones del personal laboral se determinan de acuerdo con:', 'La legislación laboral, el convenio colectivo aplicable y el contrato de trabajo, respetando el artículo 21',
 ['Exclusivamente la Ley de Presupuestos', 'Las mismas reglas que los funcionarios', 'La relación de puestos de trabajo exclusivamente'],
 'Las retribuciones del personal laboral se determinarán de acuerdo con la legislación laboral'),
('V', T, 'a29', 'Las cantidades destinadas a financiar aportaciones a planes de pensiones o contratos de seguros colectivos con cobertura de jubilación tienen la consideración de:', 'Retribución diferida',
 ['Retribución complementaria', 'Indemnización por razón del servicio', 'Prestación social'], 'tendrán a todos los efectos la consideración de retribución diferida'),
('V', T, 'a30', 'La parte de jornada no realizada da lugar a la deducción proporcional de haberes, que:', 'No tiene carácter sancionador',
 ['Es una sanción disciplinaria leve', 'Requiere expediente disciplinario previo', 'Solo procede en caso de reincidencia'],
 'la parte de jornada no realizada dará lugar a la deducción proporcional de haberes, que no tendrá carácter sancionador'),
('V', T, 'a30', 'Quienes ejercen el derecho de huelga no devengan ni perciben las retribuciones del tiempo en huelga, y esa deducción de haberes:', 'No tiene carácter de sanción ni afecta al régimen de sus prestaciones sociales',
 ['Constituye una falta leve', 'Afecta a sus trienios', 'Les priva de las pagas extraordinarias'],
 'sin que la deducción de haberes que se efectúe tenga carácter de sanción'),
# Negociación y representación
('IV', T, 'a32', 'Los órganos de gobierno de las Administraciones pueden suspender o modificar convenios colectivos ya firmados del personal laboral:', 'Excepcionalmente, por causa grave de interés público derivada de una alteración sustancial de las circunstancias económicas',
 ['Libremente, cuando lo consideren oportuno', 'Nunca', 'Solo con acuerdo de la mayoría sindical'],
 'salvo cuando excepcionalmente y por causa grave de interés público derivada de una alteración sustancial de las circunstancias económicas'),
('IV', P, 'a34', 'Plazo máximo para iniciar el proceso de negociación en una Mesa, a falta de acuerdo, desde que lo promueva la mayoría de una de las partes legitimadas', '1 mes',
 ['15 días', '2 meses', '3 meses'], 'el proceso se iniciará en el plazo máximo de un mes desde que la mayoría de una de las partes legitimadas lo promueva'),
('IV', T, 'a36', 'Es específicamente objeto de negociación en la Mesa General de Negociación de las Administraciones Públicas:', 'El incremento global de las retribuciones del personal que deba incluirse en el Proyecto de Ley de Presupuestos Generales del Estado',
 ['La provisión de cada puesto de trabajo concreto', 'La potestad de autoorganización', 'El régimen disciplinario de cada funcionario'],
 'el incremento global de las retribuciones del personal al servicio de las Administraciones Públicas que corresponda incluir en el Proyecto de Ley de Presupuestos'),
('IV', T, 'a36', 'La Mesa General de Negociación de las Administraciones Públicas está presidida por:', 'La Administración General del Estado',
 ['La Federación Española de Municipios y Provincias', 'El sindicato más representativo', 'Las Comunidades Autónomas por turno rotatorio'],
 'estará presidida por la Administración General del Estado'),
('IV', T, 'a40', 'Las Juntas de Personal y los Delegados de Personal tienen derecho a ser informados de:', 'Todas las sanciones impuestas por faltas muy graves',
 ['Todas las sanciones, incluidas las leves', 'Solo las sanciones de separación del servicio', 'Ninguna sanción, por protección de datos'],
 'c) Ser informados de todas las sanciones impuestas por faltas muy graves'),
('IV', T, 'a43', '¿Quiénes NO pueden promover elecciones a Delegados y Juntas de Personal según el artículo 43?', 'La Administración Pública correspondiente',
 ['Los sindicatos más representativos a nivel estatal', 'Los funcionarios de la unidad electoral, por acuerdo mayoritario', 'Los sindicatos con al menos el 10 % en la unidad electoral'],
 r're:Podrán promover la celebración de elecciones a Delegados y Juntas de Personal.*?e\) Los funcionarios de la unidad electoral, por acuerdo mayoritario'),
('IV', T, 'a45', 'En los sistemas de solución extrajudicial de conflictos colectivos de los empleados públicos, la mediación:', 'Es obligatoria cuando lo solicite una de las partes, y sus propuestas pueden aceptarse o rechazarse libremente',
 ['Es siempre voluntaria para ambas partes', 'Tiene efectos vinculantes en todo caso', 'Está prohibida en materias de personal'],
 'La mediación será obligatoria cuando lo solicite una de las partes'),
# Deberes y código de conducta
('IV', T, 'a52', '¿Cuál de los siguientes NO figura entre los principios del artículo 52 del TREBEP que inspiran el Código de Conducta?', 'Rentabilidad',
 ['Ejemplaridad', 'Austeridad', 'Neutralidad'], r're:y deberán actuar con arreglo a los siguientes principios: objetividad.*?y respeto a la igualdad entre mujeres y hombres'),
'RETIRADA: duplicada del lote 7',
('IV', T, 'a53', 'Según los principios éticos del artículo 53, los empleados públicos deben abstenerse:', 'En los asuntos en que tengan un interés personal y de actividades privadas que puedan plantear conflictos de intereses',
 ['De participar en asociaciones', 'De ejercer el derecho de huelga', 'De afiliarse a sindicatos'],
 'Se abstendrán en aquellos asuntos en los que tengan un interés personal'),
('IV', T, 'a53', 'Según el artículo 53.12, los empleados públicos guardarán secreto de:', 'Las materias clasificadas u otras cuya difusión esté prohibida legalmente',
 ['Todos los expedientes administrativos sin excepción', 'Su propio salario', 'La identidad de su superior jerárquico'],
 'Guardarán secreto de las materias clasificadas u otras cuya difusión esté prohibida legalmente'),
# Pérdida de la condición, planificación, OEP, registros
('IV', T, 'a65', 'La pérdida de la nacionalidad tenida en cuenta para el nombramiento determina la pérdida de la condición de funcionario:', 'Salvo que simultáneamente se adquiera la nacionalidad de alguno de los Estados que permiten el acceso',
 ['En todo caso, sin excepción', 'Solo si el funcionario es interino', 'Solo tras un expediente disciplinario'],
 'determinará la pérdida de la condición de funcionario salvo que simultáneamente se adquiera la nacionalidad'),
('IV', T, 'a69', 'La planificación de los recursos humanos en las Administraciones Públicas tiene como objetivo:', 'Contribuir a la eficacia en la prestación de los servicios y a la eficiencia en la utilización de los recursos económicos',
 ['Reducir en todo caso el número de efectivos', 'Sustituir la Oferta de Empleo Público', 'Fijar las retribuciones básicas'],
 'tendrá como objetivo contribuir a la consecución de la eficacia en la prestación de los servicios'),
('IV', T, 'a70', 'La Oferta de empleo público comporta la obligación de convocar los procesos selectivos para las plazas comprometidas y hasta:', 'Un diez por cien adicional',
 ['Un cinco por cien adicional', 'Un veinte por cien adicional', 'Ninguna plaza adicional'], 'para las plazas comprometidas y hasta un diez por cien adicional'),
('IV', P, 'a70', 'Plazo improrrogable dentro del cual debe ejecutarse la Oferta de empleo público', '3 años',
 ['2 años', '4 años', '1 año'], 'deberá desarrollarse dentro del plazo improrrogable de tres años'),
('IV', T, 'a70', 'La Oferta de empleo público se aprueba:', 'Anualmente por los órganos de Gobierno de las Administraciones Públicas, y se publica en el Diario oficial correspondiente',
 ['Cada tres años por las Cortes Generales', 'Anualmente por la Mesa General de Negociación', 'Cada legislatura por el Consejo de Ministros'],
 'que se aprobará anualmente por los órganos de Gobierno de las Administraciones Públicas'),
('IV', T, 'a71', 'Según el artículo 71, cada Administración Pública constituirá:', 'Un Registro en el que se inscribirán los datos relativos a su personal',
 ['Un Tribunal de selección permanente', 'Una Mesa de Negociación propia', 'Un Consejo Rector de personal'],
 'Cada Administración Pública constituirá un Registro en el que se inscribirán los datos relativos al personal'),
('IV', T, 'a71', 'Los contenidos mínimos comunes de los Registros de personal se establecen mediante:', 'Convenio de Conferencia Sectorial',
 ['Ley orgánica', 'Real Decreto del Ministerio de Hacienda', 'Acuerdo de la Mesa General'], 'Mediante convenio de Conferencia Sectorial se establecerán los contenidos mínimos comunes'),
('IV', T, 'a73', 'Las Administraciones pueden asignar a su personal funciones distintas a las de su puesto cuando las necesidades del servicio lo justifiquen, siempre que:', 'Resulten adecuadas a su clasificación, grado o categoría, sin merma en las retribuciones',
 ['El funcionario lo acepte por escrito', 'Se le abone un complemento adicional', 'No superen tres meses'],
 'siempre que resulten adecuadas a su clasificación, grado o categoría'),
('IV', T, 'a77', 'El personal laboral de las Administraciones Públicas se clasifica:', 'De conformidad con la legislación laboral',
 ['En los mismos Grupos que los funcionarios', 'Según la relación de puestos de trabajo', 'Por la Ley de Presupuestos'], 'El personal laboral se clasificará de conformidad con la legislación laboral'),
# Movilidad y provisión
('IV', T, 'a81', 'En caso de urgente e inaplazable necesidad, los puestos de trabajo pueden proveerse:', 'Con carácter provisional, debiendo convocarse públicamente dentro del plazo que señalen las normas',
 ['Por libre designación definitiva', 'Por contratación laboral indefinida', 'Por promoción interna automática'],
 'En caso de urgente e inaplazable necesidad, los puestos de trabajo podrán proveerse con carácter provisional'),
('IV', T, 'a83', 'La provisión de puestos y movilidad del personal laboral se realiza conforme a:', 'Los convenios colectivos aplicables y, en su defecto, el sistema de provisión del personal funcionario de carrera',
 ['El Estatuto de los Trabajadores exclusivamente', 'La libre decisión del órgano de personal', 'El sistema de los funcionarios interinos'],
 'se realizará de conformidad con lo que establezcan los convenios colectivos que sean de aplicación'),
('IV', T, 'a84', 'Los funcionarios de carrera que obtienen destino en otra Administración mediante los procedimientos de movilidad quedan, respecto de su Administración de origen, en situación de:', 'Servicio en otras Administraciones Públicas',
 ['Servicio activo', 'Excedencia voluntaria por interés particular', 'Servicios especiales'],
 'quedarán respecto de su Administración de origen en la situación administrativa de servicio en otras Administraciones Públicas'),
('IV', P, 'a84', 'Plazo máximo, tras el cese en un puesto de libre designación obtenido en otra Administración, para que la Administración de destino acuerde la adscripción del funcionario a otro puesto', '1 mes',
 ['15 días', '2 meses', '3 meses'], 'en el plazo máximo de un mes a contar desde el día siguiente al del cese'),
('IV', T, 'a84', 'Si el funcionario no solicita el reingreso en su Administración de origen en el plazo indicado tras el cese por libre designación en la de destino, será declarado de oficio en:', 'Excedencia voluntaria por interés particular',
 ['Servicio activo', 'Suspensión de funciones', 'Excedencia forzosa'],
 'será declarado de oficio en situación de excedencia voluntaria por interés particular'),
# Situaciones
('IV', T, 'a86', 'Se hallan en situación de servicio activo quienes:', 'Presten servicios en su condición de funcionarios, cualquiera que sea la Administración u organismo de destino, y no les corresponda otra situación',
 ['Hayan superado el proceso selectivo, aunque no hayan tomado posesión', 'Estén en excedencia por cuidado de familiares', 'Ocupen un puesto de personal eventual'],
 r're:Se hallarán en situación de servicio activo quienes.*?no les corresponda quedar en otra situación'),
('IV', T, 'a88', 'El tiempo de servicio en la Administración de destino de los funcionarios en situación de servicio en otras Administraciones Públicas se les computa:', 'Como de servicio activo en su cuerpo o escala de origen',
 ['Solo a efectos de trienios', 'Solo a efectos de jubilación', 'No se computa'],
 'se les computará como de servicio activo en su cuerpo o escala de origen'),
('IV', T, 'a88', 'Los funcionarios transferidos a las comunidades autónomas se encuentran, en la Función Pública de la comunidad en que se integran, en situación de:', 'Servicio activo',
 ['Servicio en otras Administraciones Públicas', 'Excedencia voluntaria', 'Servicios especiales'],
 'hallándose en la situación de servicio activo en la Función Pública de la comunidad autónoma en la que se integran'),
('IV', T, 'a92', 'El personal laboral, en materia de situaciones, se rige por:', 'El Estatuto de los Trabajadores y los convenios colectivos aplicables',
 ['El capítulo de situaciones del TREBEP en todo caso', 'La normativa de funcionarios interinos', 'La Ley de Presupuestos'],
 'El personal laboral se regirá por el Estatuto de los Trabajadores y por los Convenios Colectivos'),
# Cooperación
('IV', T, 'a100', 'El órgano técnico y de trabajo, dependiente de la Conferencia Sectorial de Administración Pública, en el que se hace efectiva la coordinación de la política de personal entre Administraciones es:', 'La Comisión de Coordinación del Empleo Público',
 ['La Mesa General de Negociación', 'El Consejo Superior de la Función Pública', 'La Comisión Permanente de Selección'],
 'Se crea la Comisión de Coordinación del Empleo Público como órgano técnico y de trabajo dependiente de la Conferencia Sectorial de Administración Pública'),
]
