# Lote 12 · LOI (Ley Orgánica 3/2007, para la igualdad efectiva de mujeres y hombres) · bloque I
# (políticas de igualdad; asignación PROVISIONAL hasta confirmar el Anexo III, ver data/programa.md).
# Títulos I-II (arts. 1-22), planes de igualdad de las empresas (arts. 43-50), empleo público (arts. 51-68)
# e instituciones (arts. 76-78). Se evitan preguntas que dependan de denominaciones de ministerios no actualizadas.
NORMA, LOTE, INICIO = 'LOI', 'lote-012', 12001
T, P = 'test', 'plazo'
PREGUNTAS = [
('I', T, 'a1', 'La Ley Orgánica 3/2007 tiene por objeto hacer efectivo el derecho de igualdad de trato y de oportunidades entre mujeres y hombres en desarrollo de los artículos de la Constitución:', '9.2 y 14',
 ['1.1 y 10', '14 y 35', '9.3 y 103'], 'en el desarrollo de los artículos 9.2 y 14 de la Constitución'),
('I', T, 'a2', 'Las obligaciones de la Ley Orgánica 3/2007 son de aplicación a:', 'Toda persona, física o jurídica, que se encuentre o actúe en territorio español, cualquiera que fuese su nacionalidad, domicilio o residencia',
 ['Solo a los ciudadanos españoles', 'Solo a las Administraciones Públicas', 'Solo a las empresas de cincuenta o más trabajadores'],
 'Las obligaciones establecidas en esta Ley serán de aplicación a toda persona, física o jurídica'),
('I', T, 'a3', 'El principio de igualdad de trato entre mujeres y hombres supone la ausencia de toda discriminación, directa o indirecta, por razón de sexo, y especialmente las derivadas de:', 'La maternidad, la asunción de obligaciones familiares y el estado civil',
 ['La edad, la nacionalidad y la religión', 'La ideología y la afiliación sindical', 'El nivel de estudios y la renta'],
 'y, especialmente, las derivadas de la maternidad, la asunción de obligaciones familiares y el estado civil'),
('I', T, 'a4', 'Según el artículo 4, la igualdad de trato y de oportunidades entre mujeres y hombres es:', 'Un principio informador del ordenamiento jurídico, que se integrará en la interpretación y aplicación de las normas',
 ['Una mera recomendación dirigida a los poderes públicos', 'Un principio aplicable solo en el ámbito laboral', 'Un derecho que solo puede invocarse ante el Tribunal Constitucional'],
 'es un principio informador del ordenamiento jurídico'),
('I', T, 'a5', 'Una diferencia de trato en el acceso al empleo basada en una característica relacionada con el sexo NO constituye discriminación cuando:', 'Esa característica constituya un requisito profesional esencial y determinante, el objetivo sea legítimo y el requisito proporcionado',
 ['Lo acuerde la empresa por razones organizativas', 'Se trate de empleo privado', 'Lo prevea un convenio colectivo en cualquier caso'],
 'dicha característica constituya un requisito profesional esencial y determinante'),
('I', T, 'a6', 'La situación en que una persona es, ha sido o pudiera ser tratada, en atención a su sexo, de manera menos favorable que otra en situación comparable es:', 'Discriminación directa por razón de sexo',
 ['Discriminación indirecta por razón de sexo', 'Acoso por razón de sexo', 'Acción positiva'],
 'Se considera discriminación directa por razón de sexo la situación en que se encuentra una persona'),
('I', T, 'a6', 'Cuando una disposición, criterio o práctica aparentemente neutros pone a personas de un sexo en desventaja particular respecto de las del otro, sin justificación objetiva, se produce:', 'Discriminación indirecta por razón de sexo',
 ['Discriminación directa por razón de sexo', 'Acoso sexual', 'Una acción positiva lícita'],
 'Se considera discriminación indirecta por razón de sexo la situación en que una disposición, criterio o práctica aparentemente neutros'),
('I', T, 'a6', 'Según el artículo 6.3, toda orden de discriminar, directa o indirectamente, por razón de sexo:', 'Se considera en cualquier caso discriminatoria',
 ['Solo es discriminatoria si llega a ejecutarse', 'Es una infracción leve', 'No es discriminatoria si procede de un superior jerárquico'],
 'se considera discriminatoria toda orden de discriminar'),
('I', T, 'a7', 'Cualquier comportamiento, verbal o físico, de naturaleza sexual que tenga el propósito o produzca el efecto de atentar contra la dignidad de una persona constituye:', 'Acoso sexual',
 ['Acoso por razón de sexo', 'Discriminación indirecta', 'Acoso laboral'], 'constituye acoso sexual cualquier comportamiento, verbal o físico, de naturaleza sexual'),
('I', T, 'a7', 'Cualquier comportamiento realizado en función del sexo de una persona, con el propósito o el efecto de atentar contra su dignidad y de crear un entorno intimidatorio, degradante u ofensivo, constituye:', 'Acoso por razón de sexo',
 ['Acoso sexual', 'Discriminación indirecta', 'Represalia'], 'Constituye acoso por razón de sexo cualquier comportamiento realizado en función del sexo de una persona'),
('I', T, 'a8', 'Todo trato desfavorable a las mujeres relacionado con el embarazo o la maternidad constituye:', 'Discriminación directa por razón de sexo',
 ['Discriminación indirecta por razón de sexo', 'Acoso por razón de sexo', 'Una infracción administrativa leve'],
 'Constituye discriminación directa por razón de sexo todo trato desfavorable a las mujeres relacionado con el embarazo o la maternidad'),
('I', T, 'a9', 'Cualquier trato adverso que sufra una persona como consecuencia de haber presentado una queja o denuncia destinada a impedir su discriminación se considera:', 'Discriminación por razón de sexo',
 ['Una consecuencia lícita del ejercicio del poder de dirección', 'Acoso sexual', 'Una medida de acción positiva'],
 'También se considerará discriminación por razón de sexo cualquier trato adverso o efecto negativo'),
('I', T, 'a10', 'Los actos y cláusulas de los negocios jurídicos que constituyan o causen discriminación por razón de sexo se consideran:', 'Nulos y sin efecto',
 ['Anulables a instancia de parte', 'Válidos pero sancionables', 'Válidos si se indemniza a la persona perjudicada'],
 'se considerarán nulos y sin efecto'),
('I', T, 'a11', 'Las acciones positivas que adopten los Poderes Públicos en favor de las mujeres serán aplicables:', 'En tanto subsistan las situaciones patentes de desigualdad de hecho, y habrán de ser razonables y proporcionadas',
 ['De forma indefinida', 'Durante un máximo de cinco años', 'Solo en el empleo público'],
 'Tales medidas, que serán aplicables en tanto subsistan dichas situaciones, habrán de ser razonables y proporcionadas'),
('I', T, 'a11', '¿Pueden las personas físicas y jurídicas privadas adoptar medidas de acción positiva?', 'Sí, en los términos establecidos en la Ley',
 ['No, solo los Poderes Públicos', 'Solo las empresas de más de 250 trabajadores', 'Solo con autorización administrativa previa'],
 'También las personas físicas y jurídicas privadas podrán adoptar este tipo de medidas'),
('I', T, 'a12', 'En los litigios sobre acoso sexual y acoso por razón de sexo, la única legitimada es:', 'La persona acosada',
 ['Cualquier persona con interés legítimo', 'Los sindicatos más representativos', 'El Ministerio Fiscal'],
 'La persona acosada será la única legitimada en los litigios sobre acoso sexual y acoso por razón de sexo'),
('I', T, 'a12', 'La tutela judicial del derecho a la igualdad entre mujeres y hombres puede recabarse:', 'Incluso tras la terminación de la relación en la que supuestamente se produjo la discriminación',
 ['Solo mientras dure la relación', 'Solo en el plazo de un año desde la discriminación', 'Solo ante la jurisdicción social'],
 'incluso tras la terminación de la relación en la que supuestamente se ha producido la discriminación'),
('I', T, 'a13', 'En los procedimientos (no penales) en que la parte actora alegue actuaciones discriminatorias por razón de sexo, corresponde probar la ausencia de discriminación y su proporcionalidad a:', 'La persona demandada',
 ['La persona demandante', 'El Ministerio Fiscal', 'El órgano judicial de oficio'],
 'corresponderá a la persona demandada probar la ausencia de discriminación en las medidas adoptadas y su proporcionalidad'),
('I', T, 'a13', 'La inversión de la carga de la prueba prevista en el artículo 13.1 de la LO 3/2007:', 'No se aplica a los procesos penales',
 ['Se aplica a todos los procesos, incluidos los penales', 'Solo se aplica a los procesos penales', 'Solo se aplica en vía administrativa'],
 'Lo establecido en el apartado anterior no será de aplicación a los procesos penales'),
('I', T, 'a14', '¿Cuál de los siguientes es un criterio general de actuación de los Poderes Públicos según el artículo 14?', 'La implantación de un lenguaje no sexista en el ámbito administrativo',
 ['La reserva del 50 % de los puestos de trabajo públicos a mujeres', 'La supresión de los permisos de paternidad', 'La prohibición de las acciones positivas'],
 '11. La implantación de un lenguaje no sexista en el ámbito administrativo'),
('I', T, 'a14', 'Según el artículo 14, entre los criterios de actuación de los Poderes Públicos figura la participación equilibrada de mujeres y hombres en:', 'Las candidaturas electorales y en la toma de decisiones',
 ['Los órganos judiciales exclusivamente', 'Las asociaciones privadas', 'Los consejos escolares exclusivamente'],
 '4. La participación equilibrada de mujeres y hombres en las candidaturas electorales y en la toma de decisiones'),
('I', T, 'a15', 'El principio de igualdad de trato y oportunidades entre mujeres y hombres informará la actuación de todos los Poderes Públicos con carácter:', 'Transversal',
 ['Subsidiario', 'Excepcional', 'Facultativo'], 'informará, con carácter transversal, la actuación de todos los Poderes Públicos'),
('I', T, 'a16', 'En los nombramientos y designaciones de cargos de responsabilidad, los Poderes Públicos procurarán atender al principio de:', 'Presencia equilibrada de mujeres y hombres',
 ['Paridad absoluta', 'Preferencia de las mujeres en todo caso', 'Antigüedad'], 'procurarán atender al principio de presencia equilibrada de mujeres y hombres en los nombramientos'),
('I', T, 'a17', 'El Plan Estratégico de Igualdad de Oportunidades, en las materias de competencia del Estado, lo aprueba periódicamente:', 'El Gobierno',
 ['Las Cortes Generales', 'El Instituto de las Mujeres', 'La Conferencia Sectorial de Igualdad'], 'El Gobierno, en las materias que sean de la competencia del Estado, aprobará periódicamente un Plan Estratégico'),
('I', T, 'a18', 'Del informe periódico que elabora el Gobierno sobre sus actuaciones en relación con la efectividad del principio de igualdad se da cuenta a:', 'Las Cortes Generales',
 ['El Tribunal Constitucional', 'El Defensor del Pueblo', 'La Comisión Europea'], 'De este informe se dará cuenta a las Cortes Generales'),
('I', T, 'a19', 'Deben incorporar un informe sobre su impacto por razón de género:', 'Los proyectos de disposiciones de carácter general y los planes de especial relevancia que se sometan a la aprobación del Consejo de Ministros',
 ['Solo las leyes orgánicas', 'Solo los contratos públicos', 'Solo las convocatorias de subvenciones'],
 'deberán incorporar un informe sobre su impacto por razón de género'),
('I', T, 'a20', 'En la elaboración de sus estudios y estadísticas, los poderes públicos deberán, entre otras obligaciones:', 'Incluir sistemáticamente la variable de sexo en las estadísticas, encuestas y recogida de datos',
 ['Excluir la variable de sexo para evitar discriminaciones', 'Incluir la variable de sexo solo en las estadísticas laborales', 'Publicar los datos personales desagregados'],
 'a) Incluir sistemáticamente la variable de sexo en las estadísticas'),
('I', T, 'a21', 'Según el artículo 21, la AGE y las CCAA pueden adoptar planes y programas conjuntos de actuación en materia de igualdad en el seno de:', 'La Conferencia Sectorial de la Mujer',
 ['El Consejo de Política Fiscal y Financiera', 'La Comisión General de Comunidades Autónomas del Senado', 'El Consejo de Participación de la Mujer'],
 'En el seno de la Conferencia Sectorial de la Mujer podrán adoptarse planes y programas conjuntos'),
('I', T, 'a22', 'Con el fin de avanzar hacia un reparto equitativo de los tiempos, las corporaciones locales podrán establecer:', 'Planes Municipales de organización del tiempo de la ciudad',
 ['Planes de igualdad obligatorios para todas las empresas del municipio', 'Ordenanzas de horario comercial único', 'Consejos municipales de la mujer con potestad sancionadora'],
 'las corporaciones locales podrán establecer Planes Municipales de organización del tiempo de la ciudad'),
# Empresas
('I', T, 'a43', 'Mediante la negociación colectiva se podrán establecer:', 'Medidas de acción positiva para favorecer el acceso de las mujeres al empleo',
 ['Diferencias retributivas por razón de sexo', 'Exclusiones del permiso de paternidad', 'Sanciones por embarazo'],
 'mediante la negociación colectiva se podrán establecer medidas de acción positiva'),
('I', T, 'a45', 'Están obligadas a elaborar y aplicar un plan de igualdad las empresas de:', 'Cincuenta o más trabajadores',
 ['Doscientos cincuenta o más trabajadores', 'Cien o más trabajadores', 'Cualquier tamaño'], 'En el caso de las empresas de cincuenta o más trabajadores'),
('I', T, 'a46', 'Los planes de igualdad de las empresas son un conjunto ordenado de medidas adoptadas:', 'Después de realizar un diagnóstico de situación',
 ['Sin necesidad de diagnóstico previo', 'Después de una inspección de trabajo', 'Por imposición de la autoridad laboral'],
 'adoptadas después de realizar un diagnóstico de situación'),
('I', T, 'a46', '¿Cuál de las siguientes materias debe contener, al menos, el diagnóstico previo del plan de igualdad según el artículo 46.2?', 'Retribuciones',
 ['Política comercial', 'Estrategia de inversión', 'Relaciones con proveedores'],
 r're:que contendrá al menos las siguientes materias: a\) Proceso de selección y contratación\..*?h\) Retribuciones'),
('I', T, 'a47', 'Se garantiza el acceso a la información sobre el contenido de los planes de igualdad y la consecución de sus objetivos a:', 'La representación legal de los trabajadores o, en su defecto, a los propios trabajadores',
 ['Solo a la Inspección de Trabajo', 'Solo a la dirección de la empresa', 'A cualquier ciudadano que lo solicite'],
 'Se garantiza el acceso de la representación legal de los trabajadores y trabajadoras'),
('I', T, 'a49', 'Las medidas de fomento del Gobierno para impulsar la adopción voluntaria de planes de igualdad se dirigen especialmente a:', 'Las pequeñas y las medianas empresas',
 ['Las grandes empresas cotizadas', 'Las empresas públicas', 'Las cooperativas'], 'especialmente dirigidas a las pequeñas y las medianas empresas'),
('I', T, 'a50', 'El distintivo para empresas en materia de igualdad:', 'Puede utilizarse en el tráfico comercial de la empresa y con fines publicitarios',
 ['Solo pueden obtenerlo las empresas privadas', 'Es obligatorio para contratar con la Administración', 'No puede utilizarse con fines publicitarios'],
 'que podrá ser utilizado en el tráfico comercial de la empresa y con fines publicitarios'),
('I', T, 'a50', 'Pueden solicitar el distintivo de igualdad:', 'Cualquier empresa, sea de capital público o privado',
 ['Solo las empresas de capital privado', 'Solo las empresas con plan de igualdad obligatorio', 'Solo las empresas de más de 250 trabajadores'],
 'cualquier empresa, sea de capital público o privado'),
# Empleo público
('I', T, 'a51', '¿Cuál de los siguientes NO figura entre los criterios de actuación de las Administraciones públicas del artículo 51 de la LOI?', 'Reservar a mujeres la mitad de las plazas de cada oferta de empleo público',
 ['Promover la presencia equilibrada de mujeres y hombres en los órganos de selección y valoración', 'Establecer medidas efectivas de protección frente al acoso sexual y al acoso por razón de sexo', 'Evaluar periódicamente la efectividad del principio de igualdad'],
 r're:deberán: a\) Remover los obstáculos.*?g\) Evaluar periódicamente la efectividad del principio de igualdad en sus respectivos ámbitos de actuación'),
('I', T, 'a53', 'Los tribunales y órganos de selección del personal de la AGE y sus organismos públicos responderán al principio de presencia equilibrada de mujeres y hombres:', 'Salvo por razones fundadas y objetivas, debidamente motivadas',
 ['Sin excepción alguna', 'Solo en los procesos de promoción interna', 'Solo cuando haya más de cinco miembros'],
 'responderán al principio de presencia equilibrada de mujeres y hombres, salvo por razones fundadas y objetivas, debidamente motivadas'),
('I', T, 'a54', 'La AGE observará el principio de presencia equilibrada en los nombramientos que le corresponda efectuar en:', 'Los consejos de administración de las empresas en cuyo capital participe',
 ['Los consejos de administración de cualquier empresa privada', 'Las juntas directivas de los partidos políticos', 'Los órganos de gobierno de las Comunidades Autónomas'],
 'en los consejos de administración de las empresas en cuyo capital participe'),
('I', T, 'a55', 'La aprobación de convocatorias de pruebas selectivas para el acceso al empleo público debe acompañarse, salvo urgencia, de:', 'Un informe de impacto de género',
 ['Un informe de la Inspección de Trabajo', 'Un dictamen del Consejo de Estado', 'Un plan de igualdad específico'],
 'deberá acompañarse de un informe de impacto de género'),
('I', T, 'a57', 'En las bases de los concursos de provisión de puestos, el tiempo que las personas candidatas hayan permanecido en situaciones de protección de la maternidad y conciliación:', 'Se computará a efectos de valoración del trabajo desarrollado y de los méritos',
 ['No se computará en ningún caso', 'Se computará solo al 50 %', 'Se computará solo si lo prevé el convenio colectivo'],
 'se computará, a los efectos de valoración del trabajo desarrollado y de los correspondientes méritos'),
('I', T, 'a58', 'Durante la licencia por riesgo durante el embarazo de una funcionaria incluida en el mutualismo administrativo:', 'Se garantiza la plenitud de sus derechos económicos',
 ['Percibe el 75 % de sus retribuciones', 'No percibe retribuciones', 'Percibe solo las retribuciones básicas'],
 'se garantizará la plenitud de los derechos económicos de la funcionaria durante toda la duración de la licencia'),
('I', T, 'a59', 'Cuando el periodo de vacaciones coincida con una incapacidad temporal derivada del embarazo, parto o lactancia natural, la empleada pública:', 'Tiene derecho a disfrutar las vacaciones en fecha distinta, aunque haya terminado el año natural',
 ['Pierde las vacaciones coincidentes', 'Solo puede disfrutarlas dentro del mismo año natural', 'Recibe una compensación económica en lugar de las vacaciones'],
 'la empleada pública tendrá derecho a disfrutar las vacaciones en fecha distinta, aunque haya terminado el año natural al que correspondan'),
('I', T, 'a60', 'Quienes se reincorporan al servicio activo desde el permiso de maternidad o paternidad tienen preferencia en la adjudicación de plazas de cursos de formación durante:', 'Un año',
 ['Seis meses', 'Dos años', 'Tres meses'], 'se otorgará preferencia, durante un año, en la adjudicación de plazas'),
('I', T, 'a60', 'En las convocatorias de cursos de formación para facilitar el acceso de las empleadas públicas a puestos directivos en la AGE se reservará para ellas al menos:', 'Un 40 % de las plazas',
 ['Un 50 % de las plazas', 'Un 30 % de las plazas', 'Un 25 % de las plazas'], 'se reservará al menos un 40% de las plazas'),
('I', T, 'a61', 'Todas las pruebas de acceso al empleo público de la AGE y sus organismos contemplarán:', 'El estudio y la aplicación del principio de igualdad entre mujeres y hombres en los diversos ámbitos de la función pública',
 ['Un cupo de plazas reservado a mujeres', 'Una entrevista sobre igualdad con carácter eliminatorio', 'La acreditación de un curso de igualdad previo'],
 'contemplarán el estudio y la aplicación del principio de igualdad entre mujeres y hombres'),
('I', T, 'a62', 'El protocolo de actuación frente al acoso sexual y al acoso por razón de sexo en las Administraciones públicas:', 'Se negocia con la representación legal de los trabajadores y trabajadoras',
 ['Lo aprueba unilateralmente el Ministro', 'Lo elabora el Instituto de las Mujeres', 'Lo impone la Inspección de Trabajo'],
 'las Administraciones públicas negociarán con la representación legal de las trabajadoras y trabajadores, un protocolo de actuación'),
('I', T, 'a62', '¿Cuál de los siguientes principios debe comprender, al menos, el protocolo frente al acoso sexual y por razón de sexo?', 'El tratamiento reservado de las denuncias',
 ['La publicación de las denuncias en el tablón de anuncios', 'La mediación obligatoria entre las partes', 'La suspensión automática de la persona denunciante'],
 'c) El tratamiento reservado de las denuncias de hechos que pudieran ser constitutivos de acoso sexual'),
('I', T, 'a63', 'Los Departamentos Ministeriales y Organismos Públicos remiten información sobre la aplicación efectiva del principio de igualdad, con datos desagregados por sexo, con periodicidad:', 'Al menos anual',
 ['Al menos trimestral', 'Al menos semestral', 'Cada cuatro años'], 'remitirán, al menos anualmente'),
('I', T, 'a64', 'El Plan para la Igualdad entre mujeres y hombres en la AGE y sus organismos públicos lo aprueba el Gobierno:', 'Al inicio de cada legislatura',
 ['Cada año', 'Cada dos años', 'Al final de cada legislatura'], 'El Gobierno aprobará, al inicio de cada legislatura, un Plan para la Igualdad'),
('I', T, 'a64', 'El cumplimiento del Plan para la Igualdad en la AGE es evaluado:', 'Anualmente por el Consejo de Ministros',
 ['Cada legislatura por las Cortes Generales', 'Semestralmente por el Instituto de las Mujeres', 'Anualmente por el Defensor del Pueblo'],
 'su cumplimiento será evaluado anualmente por el Consejo de Ministros'),
('I', T, 'a66', 'Las normas sobre personal de las Administraciones públicas en materia de igualdad, protección contra la violencia de género y conciliación se aplican en las Fuerzas Armadas:', 'Con las adaptaciones necesarias y en los términos de su normativa específica',
 ['Sin ninguna adaptación', 'No se aplican', 'Solo al personal civil'],
 'serán de aplicación en las Fuerzas Armadas, con las adaptaciones que resulten necesarias'),
# Instituciones
('I', T, 'a76', 'El órgano colegiado responsable de la coordinación de las políticas de igualdad de los departamentos ministeriales es:', 'La Comisión Interministerial de Igualdad entre mujeres y hombres',
 ['El Consejo de Participación de la Mujer', 'La Conferencia Sectorial de la Mujer', 'La Comisión de Políticas de Gasto'],
 'La Comisión Interministerial de Igualdad entre mujeres y hombres es el órgano colegiado responsable de la coordinación'),
('I', T, 'a77', 'En todos los Ministerios, el desarrollo de las funciones relacionadas con el principio de igualdad (Unidades de Igualdad) se encomienda a:', 'Uno de sus órganos directivos',
 ['Una comisión de empleados elegidos', 'El Gabinete del Ministro', 'Una entidad externa contratada'],
 'En todos los Ministerios se encomendará a uno de sus órganos directivos el desarrollo de las funciones relacionadas con el principio de igualdad'),
('I', T, 'a77', '¿Cuál de las siguientes es una función de las Unidades de Igualdad de los Ministerios?', 'Asesorar a los órganos del Departamento en la elaboración del informe sobre impacto por razón de género',
 ['Imponer sanciones por discriminación', 'Resolver los recursos en materia de igualdad', 'Aprobar el Plan Estratégico de Igualdad'],
 'c) Asesorar a los órganos competentes del Departamento en la elaboración del informe sobre impacto por razón de género'),
('I', T, 'a78', 'El Consejo de Participación de la Mujer es:', 'Un órgano colegiado de consulta y asesoramiento',
 ['Un órgano con potestad sancionadora', 'Un organismo autónomo', 'Una autoridad administrativa independiente'],
 'como órgano colegiado de consulta y asesoramiento'),
]
