# Lote 31 · RDLeg 4/2000, texto refundido de la Ley sobre Seguridad Social de los Funcionarios Civiles del
# Estado (MUFACE) · bloque IV (tema IV.7: Seguridad Social de los funcionarios; MUFACE). Se evitan las
# referencias a ministerios con denominaciones ya superadas.
NORMA, LOTE, INICIO = 'MUFACE', 'lote-031', 31001
T, P = 'test', 'plazo'
PREGUNTAS = [
('IV', T, 'a2', 'El Régimen especial de la Seguridad Social de los Funcionarios Civiles del Estado queda integrado por los mecanismos de cobertura de:', 'El Régimen de Clases Pasivas del Estado y el Régimen del Mutualismo Administrativo',
 ['El Régimen General y el Régimen de Autónomos', 'MUFACE e ISFAS', 'Las mutuas colaboradoras y el Sistema Nacional de Salud'],
 'a) El Régimen de Clases Pasivas del Estado, de acuerdo con sus normas específicas. b) El Régimen del Mutualismo Administrativo'),
('IV', T, 'a2', 'Los funcionarios de carrera de la Administración Civil del Estado que hayan ingresado a partir del 1 de enero de 2011 quedan integrados, a los exclusivos efectos de pensiones, en:', 'El Régimen General de la Seguridad Social',
 ['El Régimen de Clases Pasivas del Estado', 'Un plan de pensiones privado', 'El Régimen Especial de Trabajadores Autónomos'],
 'quedarán integrados en el Régimen General de la Seguridad Social a los exclusivos efectos de pensiones'),
('IV', T, 'a3', 'Quedan obligatoriamente incluidos en el campo de aplicación del Régimen especial de los Funcionarios Civiles del Estado:', 'Los funcionarios de carrera de la Administración Civil del Estado',
 ['Los funcionarios de la Administración Local', 'Los funcionarios de la Administración de Justicia', 'Los funcionarios de la Administración Militar'],
 'a) Los funcionarios de carrera de la Administración Civil del Estado'),
('IV', T, 'a3', '¿Cuál de los siguientes colectivos queda EXCLUIDO del Régimen especial de la Seguridad Social de los Funcionarios Civiles del Estado?', 'Los funcionarios de la Administración Local',
 ['Los funcionarios de carrera de la Administración Civil del Estado', 'Los funcionarios en prácticas que aspiren a incorporarse a Cuerpos de la Administración Civil del Estado', 'Ninguno, todos están incluidos'],
 r're:Quedan excluidos de este Régimen especial y se regirán por sus normas específicas: a\) Los funcionarios de la Administración Local'),
('IV', T, 'a4', 'El sistema de mutualismo administrativo de los funcionarios civiles del Estado se gestiona y presta a través de:', 'La Mutualidad General de Funcionarios Civiles del Estado (MUFACE)',
 ['El Instituto Nacional de la Seguridad Social', 'El Instituto Social de las Fuerzas Armadas', 'La Tesorería General de la Seguridad Social'],
 'se gestionará y prestará a través de la Mutualidad General de Funcionarios Civiles del Estado (MUFACE)'),
('IV', T, 'a5', 'La Mutualidad General de Funcionarios Civiles del Estado es:', 'Un organismo público con personalidad jurídica pública diferenciada, patrimonio y tesorería propios y autonomía de gestión',
 ['Una mutua privada colaboradora', 'Un órgano sin personalidad del Ministerio', 'Una sociedad mercantil estatal'],
 'es un organismo público con personalidad jurídica pública diferenciada, patrimonio y tesorería propios y autonomía de gestión'),
('IV', T, 'a7', 'Los funcionarios de carrera de la Administración Civil del Estado se incorporan obligatoriamente como mutualistas a MUFACE:', 'En el momento de la toma de posesión de su cargo',
 ['Al año de su toma de posesión', 'Al superar el período de prácticas, a su elección', 'Solo si lo solicitan expresamente'],
 'en el momento de la toma de posesión de su cargo'),
('IV', T, 'a7', 'El funcionario de carrera de la Administración Civil del Estado conserva la condición de mutualista, con los mismos derechos que en servicio activo, cuando pasa a la situación de:', 'Excedencia por el cuidado de familiares',
 ['Excedencia voluntaria por interés particular, sin ejercer la opción de mantenerla', 'Pérdida de la condición de funcionario', 'Excedencia voluntaria por agrupación familiar, sin ejercer la opción de mantenerla'],
 'e) Excedencia por el cuidado de familiares'),
('IV', T, 'a8', 'Causan baja como mutualistas obligatorios, entre otros:', 'Los funcionarios que pierdan tal condición, cualquiera que sea la causa',
 ['Los funcionarios en situación de servicios especiales', 'Los funcionarios en excedencia forzosa', 'Los funcionarios suspensos provisionalmente'],
 'b) Los funcionarios que pierdan tal condición, cualquiera que sea la causa'),
('IV', T, 'a10', 'La cotización a MUFACE es obligatoria para todos los mutualistas, con excepción de:', 'Los mutualistas jubilados y quienes estén en excedencia voluntaria para el cuidado de hijos o familiares',
 ['Los funcionarios en prácticas', 'Los funcionarios del Subgrupo C2', 'Los mutualistas en servicios especiales'],
 'con excepción de los mutualistas jubilados y de quienes se encuentren en la situación de excedencia voluntaria para atender al cuidado de hijos o familiares'),
('IV', T, 'a10', 'La base de cotización a MUFACE es:', 'El haber regulador que anualmente se establezca en la Ley de Presupuestos Generales del Estado',
 ['El sueldo bruto mensual del funcionario', 'La base mínima del Régimen General', 'Las retribuciones complementarias'],
 'La base de cotización será la que anualmente se establezca como haber regulador en la Ley de Presupuestos Generales del Estado'),
('IV', T, 'a10', 'La cuota mensual de cotización a MUFACE se obtiene dividiendo la cantidad anual por catorce y se abona doblemente en los meses de:', 'Junio y diciembre',
 ['Enero y julio', 'Marzo y septiembre', 'Julio y diciembre'], 'se abonará doblemente en los meses de junio y diciembre'),
('IV', T, 'a17', 'La asistencia sanitaria de MUFACE se facilita directamente o por concierto con entidades públicas o privadas, estableciéndose estos conciertos preferentemente con:', 'Instituciones de la Seguridad Social',
 ['Compañías aseguradoras extranjeras', 'Colegios de médicos', 'Las Comunidades Autónomas exclusivamente'],
 'Estos conciertos se establecerán preferentemente con instituciones de la Seguridad Social'),
('IV', T, 'a21', 'En la incapacidad temporal del mutualista, el subsidio a cargo de MUFACE se percibe:', 'Desde el cuarto mes de licencia',
 ['Desde el primer día de licencia', 'Desde el decimosexto día de licencia', 'Desde el segundo año de licencia'],
 'b) Desde el cuarto mes percibirá las retribuciones básicas, la prestación por hijo a cargo, en su caso, y un subsidio por incapacidad temporal a cargo de la Mutualidad'),
('IV', T, 'a21', 'La cuantía del subsidio de incapacidad temporal a cargo de MUFACE es la mayor entre el 80 por ciento de las retribuciones básicas (más la sexta parte de una paga extra) y:', 'El 75 por ciento de las retribuciones complementarias del tercer mes de licencia',
 ['El 100 por ciento de las retribuciones complementarias', 'El 50 por ciento de las retribuciones totales', 'El 60 por ciento del complemento de destino'],
 '2.ª El 75 por ciento de las retribuciones complementarias devengadas en el tercer mes de licencia'),
('IV', T, 'a22', 'La situación de riesgo durante la lactancia natural protegida por MUFACE se refiere a hijos menores de:', '9 meses',
 ['12 meses', '6 meses', '18 meses'], 'durante la lactancia natural de hijos menores de 9 meses'),
('IV', T, 'a22', 'Las situaciones de riesgo durante el embarazo o la lactancia natural de las mutualistas tienen la misma consideración que la incapacidad temporal derivada de:', 'Enfermedad profesional, por lo que no requieren periodo de carencia',
 ['Enfermedad común, con 180 días de carencia', 'Accidente no laboral, con un año de carencia', 'Maternidad, con 90 días de carencia'],
 'tendrán la misma consideración que la situación de incapacidad temporal derivada de enfermedad profesional, por lo que no requerirán de periodo de carencia'),
('IV', T, 'a23', 'Según el RDLeg 4/2000, la incapacidad permanente del funcionario ha de derivarse, cualquiera que sea su causa, de:', 'La situación de incapacidad temporal',
 ['Un accidente en acto de servicio exclusivamente', 'Una sanción disciplinaria', 'La jubilación forzosa por edad'],
 'La incapacidad permanente habrá de derivarse, cualquiera que sea su causa, de la situación de incapacidad temporal'),
('IV', T, 'a24', 'El funcionario incapacitado permanente parcial:', 'Percibe la totalidad de los haberes que correspondan al puesto que efectivamente desempeñe',
 ['Es jubilado forzosamente', 'Percibe el 50 por ciento de sus haberes', 'Pasa a excedencia forzosa'],
 'El funcionario incapacitado permanente parcial percibirá la totalidad de los haberes que correspondan al puesto de trabajo que efectivamente desempeñe'),
('IV', T, 'a25', 'La incapacidad permanente total y la incapacidad permanente absoluta del funcionario dan lugar a:', 'Su jubilación, de acuerdo con la legislación en vigor',
 ['Su traslado forzoso a otro puesto', 'La suspensión de funciones', 'La excedencia voluntaria'],
 'darán lugar a la jubilación del funcionario de acuerdo con la legislación en vigor'),
('IV', T, 'a26', 'La gran invalidez del funcionario da derecho, además de a la jubilación, a una cantidad mensual destinada a remunerar a la persona encargada de su asistencia equivalente al:', '50 por 100 de la pensión de jubilación que le corresponda en Clases Pasivas',
 ['25 por 100 de la pensión', '100 por 100 de la pensión', '75 por 100 del último sueldo'],
 'dará derecho a una cantidad mensual equivalente al 50 por 100 de la pensión de jubilación que le corresponda con arreglo al Régimen de Clases Pasivas'),
('IV', T, 'a28', 'Las lesiones permanentes no invalidantes causadas por enfermedad profesional o en acto de servicio dan derecho a:', 'La percepción, por una sola vez, de las cantidades que se establezcan reglamentariamente',
 ['Una pensión vitalicia', 'La jubilación anticipada', 'Un subsidio mensual durante dos años'],
 'darán derecho a la percepción por una sola vez de las cantidades que se establezcan reglamentariamente'),
('IV', T, 'a33', 'El sistema financiero del Régimen especial de la Seguridad Social de los Funcionarios Civiles del Estado es, salvo excepciones:', 'De reparto, con cuota revisable periódicamente',
 ['De capitalización individual', 'De capitalización colectiva', 'Mixto, con cuentas individuales'],
 'el sistema financiero del mismo será de reparto y su cuota revisable periódicamente'),
('IV', T, 'a37', 'Con carácter general, los actos y resoluciones del Director general de MUFACE:', 'No ponen fin a la vía administrativa y pueden recurrirse en alzada',
 ['Ponen fin a la vía administrativa en todo caso', 'Solo son recurribles ante el Tribunal Supremo', 'No son recurribles'],
 'Los actos y resoluciones del Director general de la Mutualidad General de Funcionarios Civiles del Estado no ponen fin a la vía administrativa'),
]
