# Lote 32 · RDLeg 670/1987, texto refundido de Ley de Clases Pasivas del Estado · bloque IV (tema IV.7:
# clases pasivas).
NORMA, LOTE, INICIO = 'LCLP', 'lote-032', 32001
T, P = 'test', 'plazo'
PREGUNTAS = [
('IV', T, 'a1', 'A través del Régimen de Clases Pasivas, el Estado garantiza a su personal la protección frente a los riesgos de:', 'Vejez, incapacidad y muerte y supervivencia',
 ['Desempleo y cese de actividad', 'Enfermedad común y maternidad exclusivamente', 'Cargas familiares y dependencia'],
 'la protección frente a los riesgos de vejez, incapacidad y muerte y supervivencia'),
('IV', T, 'a2', '¿Cuál de los siguientes colectivos forma parte del ámbito personal de cobertura del Régimen de Clases Pasivas?', 'Los funcionarios de carrera de la Administración de Justicia',
 ['Los funcionarios de la Administración Local', 'El personal laboral de la Administración del Estado', 'Los trabajadores autónomos'],
 'c) Los funcionarios de carrera de la Administración de Justicia'),
('IV', T, 'a5', 'Pueden establecerse derechos pasivos distintos de los recogidos en el texto refundido de Clases Pasivas, o ampliarse o reducirse:', 'Solamente por Ley',
 ['Por real decreto del Gobierno', 'Por orden del Ministerio de Hacienda', 'Por convenio colectivo'],
 'Solamente por Ley podrán establecerse derechos pasivos distintos de los recogidos en este texto'),
('IV', T, 'a6', 'Según la Ley de Clases Pasivas, los derechos pasivos son:', 'Inembargables, irrenunciables e inalienables',
 ['Libremente transmisibles', 'Renunciables a favor de familiares', 'Embargables sin límite'],
 'Las derechos pasivos son inembargables, irrenunciables o inalienables'),
('IV', T, 'a6', 'Respecto de la prescripción, los derechos pasivos:', 'Son imprescriptibles, sin perjuicio de la caducidad de sus efectos',
 ['Prescriben a los cinco años', 'Prescriben a los cuatro años', 'Prescriben al año del hecho causante'],
 'Los derechos pasivos son imprescriptibles'),
('IV', P, 'a7', 'Retroactividad máxima de los efectos económicos del reconocimiento de prestaciones de Clases Pasivas, desde el día primero del mes siguiente a la solicitud', '3 meses',
 ['5 años', '1 año', '6 meses'], 'la retroactividad máxima de los efectos económicos de tal reconocimiento sea de tres meses'),
('IV', T, 'a17', 'Las declaraciones preventivas de derechos pasivos solicitadas antes de producirse el hecho causante:', 'No proceden en ningún caso',
 ['Proceden siempre', 'Proceden si el interesado tiene más de sesenta años', 'Proceden con autorización del Ministerio'],
 'En ningún caso procederán las declaraciones preventivas de derechos pasivos'),
('IV', T, 'a18', 'Las prestaciones del Régimen de Clases Pasivas son:', 'Exclusivamente de carácter económico y pago periódico',
 ['De asistencia sanitaria y farmacéutica', 'De pago único', 'Económicas y en especie'],
 'Tales prestaciones serán exclusivamente de carácter económico y pago periódico'),
('IV', T, 'a19', 'Las pensiones de Clases Pasivas son extraordinarias cuando su hecho causante se produce:', 'Por razón de lesión, muerte o desaparición producida en acto de servicio o como consecuencia del mismo',
 ['Antes de los sesenta años', 'Por jubilación voluntaria', 'En circunstancias ordinarias'],
 'por razón de lesión, muerte o desaparición producida en acto de servicio o como consecuencia del mismo'),
('IV', T, 'a19', 'Las pensiones que se reconocen en virtud de Ley a favor de persona determinada se denominan:', 'Pensiones excepcionales',
 ['Pensiones extraordinarias', 'Pensiones ordinarias', 'Pensiones no contributivas'], 'dará origen a pensiones excepcionales'),
('IV', T, 'a20', 'La pensión de jubilación o retiro de Clases Pasivas se devenga:', 'Desde el primer día del mes siguiente al de la jubilación o retiro',
 ['Desde el mismo día de la jubilación', 'Desde el día siguiente a la solicitud', 'A los tres meses de la jubilación'],
 'a) Desde el primer día del mes siguiente al de la jubilación o retiro del funcionario'),
('IV', T, 'a22', 'Además de las doce mensualidades ordinarias, el titular de una pensión de Clases Pasivas percibe dos mensualidades extraordinarias que se devengan el primer día de los meses de:', 'Junio y diciembre',
 ['Julio y diciembre', 'Enero y julio', 'Marzo y septiembre'], 'Se devengarán el primer día de los meses de junio y diciembre'),
('IV', T, 'a25', 'Es incompatible la percepción simultánea de más de cuántas pensiones ordinarias de Clases Pasivas causadas por diferente persona:', 'Tres',
 ['Dos', 'Una', 'Cuatro'], 'Es incompatible la percepción simultánea de más de tres pensiones ordinarias de Clases Pasivas'),
('IV', T, 'a26', 'Si por una única prestación de servicios se causa pensión en un Régimen de la Seguridad Social y en Clases Pasivas, el interesado:', 'Debe optar por la que considere más conveniente, sin poder percibir ambas',
 ['Percibe ambas pensiones íntegras', 'Percibe la suma de ambas con un límite del doble', 'Percibe solo la de Clases Pasivas'],
 'deberá optar por el percibo de la pensión que considere más conveniente, sin que pueda percibir ambas a la vez'),
('IV', T, 'a28', 'La jubilación voluntaria en Clases Pasivas puede declararse a instancia de parte cuando el interesado tenga cumplidos:', 'Sesenta años de edad y treinta años de servicios efectivos al Estado',
 ['Sesenta y cinco años y quince de servicios', 'Cincuenta y cinco años y veinte de servicios', 'Sesenta y dos años y veinticinco de servicios'],
 'siempre que el interesado tenga cumplidos los sesenta años de edad y reconocidos treinta años de servicios efectivos al Estado'),
('IV', T, 'a29', 'Para causar derecho a la pensión ordinaria de jubilación o retiro de Clases Pasivas se exige haber completado:', 'Quince años de servicios efectivos al Estado',
 ['Diez años de servicios', 'Veinte años de servicios', 'Treinta y cinco años de servicios'],
 'deberá haber completado quince años de servicios efectivos al Estado'),
('IV', T, 'a35', 'Para que se causen los derechos pasivos de los familiares (viudedad, orfandad, en favor de padres) del personal fallecido:', 'No es preciso que el causante haya completado ningún periodo mínimo de servicios',
 ['Se exigen quince años de servicios del causante', 'Se exigen cinco años de servicios del causante', 'Se exige que el causante estuviera jubilado'],
 'no será preciso que el causante de los mismos haya completado ningún periodo mínimo de prestación de servicios efectivos al Estado'),
('IV', T, 'a38', 'Si el fallecimiento deriva de enfermedad común no sobrevenida tras el matrimonio, para la pensión de viudedad se exige, con carácter general, que el matrimonio se hubiera celebrado con una antelación mínima a la fecha del fallecimiento de:', 'Un año',
 ['Seis meses', 'Dos años', 'Tres años'], 'se requerirá, además, que el matrimonio se hubiera celebrado con un año de antelación como mínimo a la fecha del fallecimiento'),
('IV', T, 'a41', 'Con carácter general, tienen derecho a pensión de orfandad en Clases Pasivas los hijos del causante menores de:', 'Veintiún años',
 ['Dieciocho años', 'Veinticinco años en todo caso', 'Veintitrés años'],
 'los hijos del causante de los derechos pasivos que fueran menores de veintiún años'),
]
