# Lote 22 · Ley 29/1998, reguladora de la Jurisdicción Contencioso-administrativa · bloque III (tema III.3:
# el recurso contencioso-administrativo): ámbito, órganos, partes, objeto, plazos, procedimiento,
# sentencia, recursos, ejecución y medidas cautelares.
NORMA, LOTE, INICIO = 'LJCA', 'lote-022', 22001
T, P = 'test', 'plazo'
PREGUNTAS = [
('III', T, 'a1', 'Los Juzgados y Tribunales del orden contencioso-administrativo conocen de las pretensiones relativas a los Decretos legislativos:', 'Cuando excedan los límites de la delegación',
 ['En todo caso', 'Nunca, porque corresponden siempre al Tribunal Constitucional', 'Solo si los impugna el Defensor del Pueblo'],
 'y con los Decretos legislativos cuando excedan los límites de la delegación'),
('III', T, 'a3', '¿Cuál de las siguientes cuestiones NO corresponde al orden jurisdiccional contencioso-administrativo?', 'Los conflictos de jurisdicción entre los Juzgados y Tribunales y la Administración pública',
 ['Los contratos administrativos', 'La responsabilidad patrimonial de las Administraciones públicas', 'Los actos y disposiciones de las Corporaciones de Derecho público adoptados en ejercicio de funciones públicas'],
 'c) Los conflictos de jurisdicción entre los Juzgados y Tribunales y la Administración pública'),
('III', T, 'a2', 'La responsabilidad patrimonial de las Administraciones públicas se exige ante el orden jurisdiccional:', 'Contencioso-administrativo, cualquiera que sea la naturaleza de la actividad o el tipo de relación de que derive',
 ['Civil, cuando concurran particulares en la producción del daño', 'Social, cuando el perjudicado sea un trabajador', 'Civil, cuando la Administración actúe en relaciones de derecho privado'],
 'e) La responsabilidad patrimonial de las Administraciones públicas, cualquiera que sea la naturaleza de la actividad o el tipo de relación de que derive'),
('III', T, 'a4', 'La decisión que el orden contencioso-administrativo pronuncie sobre una cuestión prejudicial no administrativa:', 'No produce efectos fuera del proceso en que se dicte',
 ['Vincula al orden jurisdiccional correspondiente', 'Produce efectos generales desde su publicación', 'Solo es válida si la confirma el Tribunal Supremo'],
 'La decisión que se pronuncie no producirá efectos fuera del proceso en que se dicte'),
('III', T, 'a5', 'Según la Ley 29/1998, la Jurisdicción Contencioso-administrativa es:', 'Improrrogable',
 ['Prorrogable por acuerdo de las partes', 'Voluntaria', 'Subsidiaria de la civil'], 'La Jurisdicción Contencioso-administrativa es improrrogable'),
('III', T, 'a12', 'Los recursos contra los actos y disposiciones del Consejo de Ministros los conoce en única instancia:', 'La Sala de lo Contencioso-administrativo del Tribunal Supremo',
 ['La Sala de lo Contencioso-administrativo de la Audiencia Nacional', 'Los Juzgados Centrales de lo Contencioso-administrativo', 'El Tribunal Constitucional'],
 'a) Los actos y disposiciones del Consejo de Ministros y de las Comisiones Delegadas del Gobierno'),
('III', T, 'a11', 'Con carácter general, los recursos contra las disposiciones generales y los actos de los Ministros y de los Secretarios de Estado los conoce en única instancia:', 'La Sala de lo Contencioso-administrativo de la Audiencia Nacional',
 ['La Sala de lo Contencioso-administrativo del Tribunal Supremo', 'Las Salas de lo Contencioso-administrativo de los Tribunales Superiores de Justicia', 'Los Juzgados de lo Contencioso-administrativo provinciales'],
 r're:La Sala de lo Contencioso-administrativo de la Audiencia Nacional conocerá en única instancia: a\) De los recursos que se deduzcan en relación con las disposiciones generales y los actos de los Ministros'),
('III', T, 'a10', 'Los recursos contra las disposiciones generales emanadas de las Comunidades Autónomas y de las Entidades locales los conocen en única instancia:', 'Las Salas de lo Contencioso-administrativo de los Tribunales Superiores de Justicia',
 ['Los Juzgados de lo Contencioso-administrativo', 'La Sala de lo Contencioso-administrativo de la Audiencia Nacional', 'Los Juzgados Centrales de lo Contencioso-administrativo'],
 'b) Las disposiciones generales emanadas de las Comunidades Autónomas y de las Entidades locales'),
('III', T, 'a19', 'Están legitimadas ante el orden jurisdiccional contencioso-administrativo, en general, las personas físicas o jurídicas que ostenten:', 'Un derecho o interés legítimo',
 ['La condición de vecino', 'Un interés simple en la legalidad', 'La nacionalidad española'], 'a) Las personas físicas o jurídicas que ostenten un derecho o interés legítimo'),
('III', T, 'a21', 'Las aseguradoras de las Administraciones públicas, en el proceso contencioso-administrativo:', 'Siempre son parte codemandada junto con la Administración a quien aseguren',
 ['Nunca pueden ser parte', 'Solo pueden intervenir como coadyuvantes del demandante', 'Son demandadas ante la jurisdicción civil'],
 'que siempre serán parte codemandada junto con la Administración a quien aseguren'),
('III', T, 'a23', 'En sus actuaciones ante órganos unipersonales, las partes:', 'Pueden conferir su representación a un Procurador y son asistidas, en todo caso, por Abogado',
 ['Deben conferir siempre su representación a un Procurador', 'No necesitan Abogado en ningún caso', 'Deben actuar por sí mismas'],
 'las partes podrán conferir su representación a un Procurador y serán asistidas, en todo caso, por Abogado'),
('III', T, 'a23', 'Los funcionarios públicos pueden comparecer por sí mismos en defensa de sus derechos estatutarios cuando se trate de:', 'Cuestiones de personal que no impliquen separación de empleados públicos inamovibles',
 ['Cualquier cuestión, incluida la separación del servicio', 'Solo recursos ante el Tribunal Supremo', 'Solo reclamaciones de responsabilidad patrimonial'],
 'cuando se refieran a cuestiones de personal que no impliquen separación de empleados públicos inamovibles'),
('III', T, 'a25', 'El recurso contencioso-administrativo es admisible en relación con los actos expresos y presuntos de la Administración que:', 'Pongan fin a la vía administrativa',
 ['Sean de trámite, en todo caso', 'No hayan sido notificados', 'Estén pendientes de recurso de alzada'],
 'con los actos expresos y presuntos de la Administración pública que pongan fin a la vía administrativa'),
('III', T, 'a25', 'Además de contra actos y disposiciones, el recurso contencioso-administrativo es admisible contra:', 'La inactividad de la Administración y sus actuaciones materiales que constituyan vía de hecho',
 ['Las leyes aprobadas por las Cortes Generales', 'Las sentencias del Tribunal Constitucional', 'Los actos políticos del Rey'],
 'También es admisible el recurso contra la inactividad de la Administración y contra sus actuaciones materiales que constituyan vía de hecho'),
('III', T, 'a26', 'La falta de impugnación directa de una disposición general:', 'No impide la impugnación de sus actos de aplicación fundada en que la disposición no es conforme a Derecho',
 ['Impide impugnar después sus actos de aplicación', 'Convalida la disposición definitivamente', 'Obliga a acudir al Tribunal Constitucional'],
 'La falta de impugnación directa de una disposición general o la desestimación del recurso que frente a ella se hubiera interpuesto no impiden la impugnación de los actos de aplicación'),
('III', T, 'a28', 'No es admisible el recurso contencioso-administrativo respecto de:', 'Los actos confirmatorios de actos consentidos por no haber sido recurridos en tiempo y forma',
 ['Los actos presuntos', 'Los actos que pongan fin a la vía administrativa', 'Las disposiciones de carácter general'],
 'y los confirmatorios de actos consentidos por no haber sido recurridos en tiempo y forma'),
('III', P, 'a29', 'Plazo desde la reclamación de una prestación concreta debida sin que la Administración la cumpla, tras el cual cabe recurso contencioso-administrativo contra su inactividad', '3 meses',
 ['1 mes', '2 meses', '6 meses'], 'Si en el plazo de tres meses desde la fecha de la reclamación, la Administración no hubiera dado cumplimiento'),
('III', P, 'a29', 'Plazo desde la petición de ejecución de un acto firme no ejecutado por la Administración, tras el cual cabe recurso contencioso-administrativo', '1 mes',
 ['3 meses', '10 días', '2 meses'], 'si ésta no se produce en el plazo de un mes desde tal petición'),
('III', P, 'a30', 'Plazo para que la Administración atienda el requerimiento de cesación de una vía de hecho, antes de poder recurrir directamente', '10 días',
 ['20 días', '1 mes', '5 días'], 'no fuere atendida dentro de los diez días siguientes a la presentación del requerimiento'),
('III', P, 'a46', 'Plazo para interponer el recurso contencioso-administrativo contra un acto expreso que pone fin a la vía administrativa', '2 meses',
 ['1 mes', '3 meses', '6 meses'], 'El plazo para interponer el recurso contencioso-administrativo será de dos meses'),
('III', P, 'a46', 'Plazo para interponer el recurso contencioso-administrativo cuando el acto no es expreso (acto presunto)', '6 meses',
 ['2 meses', '3 meses', '1 año'], 'Si no lo fuera, el plazo será de seis meses'),
('III', P, 'a46', 'Plazo para interponer el recurso contencioso-administrativo contra una vía de hecho cuando no hubo requerimiento previo', '20 días',
 ['10 días', '2 meses', '1 mes'], 'Si no hubiere requerimiento, el plazo será de veinte días desde el día en que se inició la actuación administrativa en vía de hecho'),
('III', P, 'a46', 'Plazo para interponer el recurso de lesividad, desde el día siguiente a la declaración de lesividad', '2 meses',
 ['4 años', '6 meses', '1 mes'], 'El plazo para interponer recurso de lesividad será de dos meses'),
('III', T, 'a45', 'Salvo que la Ley disponga otra cosa, el recurso contencioso-administrativo se inicia por:', 'Un escrito reducido a citar lo que se impugna y a solicitar que se tenga por interpuesto el recurso',
 ['Demanda con todos los hechos y fundamentos de Derecho', 'Comparecencia oral ante el Juez', 'Solicitud a la Administración autora del acto'],
 'El recurso contencioso-administrativo se iniciará por un escrito reducido a citar la disposición'),
('III', P, 'a48', 'Plazo improrrogable para que la Administración remita el expediente administrativo al órgano judicial', '20 días',
 ['10 días', '15 días', '1 mes'], 'El expediente deberá ser remitido en el plazo improrrogable de veinte días'),
('III', P, 'a49', 'Plazo para que los interesados emplazados por la Administración se personen como demandados', '9 días',
 ['5 días', '10 días', '15 días'], 'emplazándoles para que puedan personarse como demandados en el plazo de nueve días'),
('III', P, 'a52', 'Plazo para deducir la demanda una vez entregado el expediente al recurrente', '20 días',
 ['10 días', '30 días', '2 meses'], 'su entrega al recurrente para que se deduzca la demanda en el plazo de veinte días'),
('III', P, 'a54', 'Plazo para que las partes demandadas contesten la demanda', '20 días',
 ['10 días', '15 días', '30 días'], 'para que la contesten en el plazo de veinte días'),
('III', T, 'a54', 'Cuando hay varios demandados, la contestación a la demanda se formula:', 'Primero por la Administración demandada',
 ['Primero por los particulares codemandados', 'Por sorteo', 'Solo por la Administración'], 'La contestación se formulará primero por la Administración demandada'),
('III', T, 'a60', 'Si el objeto del recurso es una sanción administrativa o disciplinaria y existe disconformidad en los hechos, el proceso:', 'Se recibirá siempre a prueba',
 ['Nunca se recibe a prueba', 'Se recibe a prueba solo si lo pide la Administración', 'Se resuelve sin prueba por el procedimiento abreviado'],
 'el proceso se recibirá siempre a prueba cuando exista disconformidad en los hechos'),
('III', P, 'a60', 'Plazo para practicar la prueba en el proceso contencioso-administrativo', '30 días',
 ['20 días', '15 días', '2 meses'], 'siendo el plazo para practicarla de treinta días'),
('III', P, 'a67', 'Plazo para dictar sentencia desde que el pleito haya sido declarado concluso', '10 días',
 ['20 días', '30 días', '5 días'], 'La sentencia se dictará en el plazo de diez días desde que el pleito haya sido declarado concluso'),
('III', T, 'a68', 'La sentencia del proceso contencioso-administrativo pronuncia alguno de los fallos siguientes:', 'Inadmisibilidad, estimación o desestimación del recurso',
 ['Nulidad, anulabilidad o convalidación', 'Condena o absolución', 'Archivo, sobreseimiento o caducidad'],
 r're:a\) Inadmisibilidad del recurso contencioso-administrativo\. b\) Estimación o desestimación del recurso contencioso-administrativo'),
('III', T, 'a69', '¿Cuál de las siguientes es causa de inadmisibilidad del recurso según el artículo 69 de la Ley 29/1998?', 'Que se hubiera presentado el escrito inicial del recurso fuera del plazo establecido',
 ['Que el acto incurra en desviación de poder', 'Que el acto sea anulable', 'Que la Administración no haya contestado a la demanda'],
 'e) Que se hubiera presentado el escrito inicial del recurso fuera del plazo establecido'),
('III', T, 'a70', 'Según la Ley 29/1998, se entiende por desviación de poder:', 'El ejercicio de potestades administrativas para fines distintos de los fijados por el ordenamiento jurídico',
 ['La actuación de un órgano manifiestamente incompetente', 'La falta de motivación del acto', 'El retraso en resolver el procedimiento'],
 'Se entiende por desviación de poder el ejercicio de potestades administrativas para fines distintos de los fijados por el ordenamiento jurídico'),
('III', T, 'a71', 'Cuando anulan preceptos de una disposición general, los órganos jurisdiccionales:', 'No pueden determinar la forma en que han de quedar redactados los preceptos en sustitución de los anulados',
 ['Redactan los nuevos preceptos', 'Fijan el contenido discrecional de los nuevos actos', 'Remiten la nueva redacción a las Cortes'],
 'Los órganos jurisdiccionales no podrán determinar la forma en que han de quedar redactados los preceptos de una disposición general'),
('III', T, 'a72', 'La sentencia que declara la inadmisibilidad o la desestimación del recurso contencioso-administrativo:', 'Sólo produce efectos entre las partes',
 ['Produce efectos para todas las personas afectadas', 'Produce efectos generales desde su publicación', 'Carece de efectos'],
 'La sentencia que declare la inadmisibilidad o desestimación del recurso contencioso-administrativo sólo producirá efectos entre las partes'),
('III', T, 'a72', 'Las sentencias firmes que anulan una disposición general tienen efectos generales desde:', 'El día en que se publique su fallo y preceptos anulados en el mismo periódico oficial en que lo hubiera sido la disposición',
 ['El día en que se dictan', 'Su notificación a las partes', 'Los veinte días siguientes a su firmeza'],
 'tendrán efectos generales desde el día en que sea publicado su fallo y preceptos anulados en el mismo periódico oficial'),
('III', T, 'a78', 'Se tramitan por el procedimiento abreviado, entre otros, los asuntos de competencia de los Juzgados cuya cuantía no supere:', '30.000 euros',
 ['60.000 euros', '6.000 euros', '150.000 euros'], 'así como todas aquellas cuya cuantía no supere los 30.000 euros'),
('III', P, 'a79', 'Plazo para interponer recurso de reposición contra providencias y autos no susceptibles de apelación o casación', '5 días',
 ['10 días', '1 mes', '3 días'], 'El recurso de reposición se interpondrá en el plazo de cinco días'),
('III', T, 'a81', 'Las sentencias de los Juzgados de lo Contencioso-administrativo NO son susceptibles de recurso de apelación, salvo excepciones, en los asuntos cuya cuantía no exceda de:', '30.000 euros',
 ['60.000 euros', '3.000 euros', '600.000 euros'], 'a) Aquellos cuya cuantía no exceda de 30.000 euros'),
('III', T, 'a87bis', 'El recurso de casación ante la Sala de lo Contencioso-administrativo del Tribunal Supremo se limita, con carácter general, a:', 'Las cuestiones de derecho, con exclusión de las cuestiones de hecho',
 ['Las cuestiones de hecho', 'Las cuestiones de hecho y de derecho', 'La valoración de la prueba'],
 'se limitará a las cuestiones de derecho, con exclusión de las cuestiones de hecho'),
('III', T, 'a103', 'La potestad de hacer ejecutar las sentencias del orden contencioso-administrativo corresponde exclusivamente a:', 'Los juzgados y tribunales de este orden jurisdiccional',
 ['La Administración condenada', 'El Ministerio de Justicia', 'El Consejo General del Poder Judicial'],
 'corresponde exclusivamente a los juzgados y tribunales de este orden jurisdiccional'),
('III', T, 'a105', 'Respecto del cumplimiento del fallo de una sentencia contencioso-administrativa:', 'No puede suspenderse ni declararse la inejecución total o parcial del fallo',
 ['La Administración puede suspenderlo por razones de interés público', 'El Gobierno puede declarar su inejecución por decreto', 'Puede aplazarse indefinidamente'],
 'No podrá suspenderse el cumplimiento ni declararse la inejecución total o parcial del fallo'),
('III', P, 'a106', 'Plazo desde que la sentencia firme de condena al pago de cantidad se comunica al órgano que debe cumplirla, tras el cual se puede instar la ejecución forzosa', '3 meses',
 ['2 meses', '6 meses', '1 mes'], 'transcurridos tres meses desde que la sentencia firme sea comunicada al órgano que deba cumplirla, se podrá instar la ejecución forzosa'),
('III', T, 'a130', 'La medida cautelar en el proceso contencioso-administrativo puede acordarse únicamente cuando:', 'La ejecución del acto o la aplicación de la disposición pudieran hacer perder su finalidad legítima al recurso',
 ['Lo solicite el demandante, en todo caso', 'Lo acepte la Administración demandada', 'El acto impugnado sea de cuantía superior a 30.000 euros'],
 'la medida cautelar podrá acordarse únicamente cuando la ejecución del acto o la aplicación de la disposición pudieran hacer perder su finalidad legítima al recurso'),
('III', T, 'a131', 'El incidente cautelar se sustancia en pieza separada, con audiencia de la parte contraria por plazo no superior a diez días, y se resuelve por auto dentro de:', 'Los cinco días siguientes',
 ['Los diez días siguientes', 'El mes siguiente', 'Los tres días siguientes'], 'y será resuelto por auto dentro de los cinco días siguientes'),
('III', T, 'a135', 'Cuando se alegan circunstancias de especial urgencia, el juez o tribunal puede adoptar o denegar la medida cautelar sin oír a la parte contraria en el plazo de:', 'Dos días',
 ['Cinco días', 'Diez días', 'Veinticuatro horas'], 'el juez o tribunal sin oír a la parte contraria, en el plazo de dos días podrá mediante auto'),
]
