# Lote 6 · Ley 19/2013 (L19), de transparencia, acceso a la información pública y buen gobierno · bloque I
# Se evitan las preguntas que dependen de denominaciones ministeriales desfasadas y las ya incluidas en lote-001.
# Formato: (bloque, tipo, artículo, pregunta, respuesta correcta, [3 distractores], ancla de la cita en el texto del BOE)
NORMA, LOTE, INICIO = 'L19', 'lote-006', 6001
T, P = 'test', 'plazo'
PREGUNTAS = [
('I', T, 'a2', 'Según el artículo 2.1.g), el título I se aplica a las sociedades mercantiles en cuyo capital social la participación, directa o indirecta, de las entidades del artículo sea superior al:', '50 por 100',
 ['25 por 100', '40 por 100', '75 por 100'], 'sea superior al 50 por 100'),
('I', T, 'a2', 'A efectos del título I de la Ley 19/2013, se entiende por Administraciones Públicas los organismos y entidades incluidos en:', 'Las letras a) a d) del artículo 2.1',
 ['Todas las letras del artículo 2.1', 'Las letras a) a f) del artículo 2.1', 'Únicamente la letra a) del artículo 2.1'],
 'se entiende por Administraciones Públicas los organismos y entidades incluidos en las letras a) a d) del apartado anterior'),
('I', T, 'a2', 'Las corporaciones de Derecho Público están sujetas al título I de la Ley 19/2013:', 'En lo relativo a sus actividades sujetas a Derecho Administrativo',
 ['En todas sus actividades', 'En ningún caso', 'Solo en materia de contratos'], 'Las corporaciones de Derecho Público, en lo relativo a sus actividades sujetas a Derecho Administrativo'),
('I', T, 'a3', 'Las obligaciones de publicidad activa se aplican a las entidades privadas que perciban durante un año ayudas o subvenciones públicas por una cuantía superior a:', '100.000 euros',
 ['50.000 euros', '60.000 euros', '150.000 euros'], 'en una cuantía superior a 100.000 euros'),
('I', T, 'a3', 'También están sujetas a publicidad activa las entidades privadas en las que, al menos, cierto porcentaje del total de sus ingresos anuales tenga carácter de ayuda o subvención pública (con un mínimo de 5.000 euros). ¿Qué porcentaje?', 'El 40 %',
 ['El 25 %', 'El 30 %', 'El 50 %'], 'cuando al menos el 40 % del total de sus ingresos anuales'),
('I', T, 'a3', '¿Están sujetos a las obligaciones de publicidad activa los partidos políticos, las organizaciones sindicales y las organizaciones empresariales?', 'Sí, en todo caso, según el artículo 3',
 ['No', 'Solo los partidos políticos', 'Solo si perciben subvenciones superiores a 100.000 euros'],
 r're:serán también aplicables a: a\) Los partidos políticos, organizaciones sindicales y organizaciones empresariales'),
('I', T, 'a4', 'La obligación de suministrar información a la Administración (artículo 4) se extiende a los adjudicatarios de contratos del sector público:', 'En los términos previstos en el respectivo contrato',
 ['En todo caso y sin limitación', 'Solo si el contrato supera los 100.000 euros', 'Solo a petición del Consejo de Transparencia y Buen Gobierno'],
 'Esta obligación se extenderá a los adjudicatarios de contratos del sector público en los términos previstos en el respectivo contrato'),
('I', T, 'a5', 'Cuando la información sujeta a publicidad activa contenga datos especialmente protegidos, la publicidad:', 'Sólo se llevará a cabo previa disociación de los mismos',
 ['Está prohibida', 'Requiere la autorización del Consejo de Transparencia y Buen Gobierno', 'Se realizará íntegramente'], 'la publicidad sólo se llevará a cabo previa disociación de los mismos'),
('I', T, 'a5', 'Las entidades sin ánimo de lucro con fines exclusivamente sociales o culturales podrán cumplir sus obligaciones de transparencia con los medios electrónicos de la Administración de la que reciban la mayor parte de sus ayudas si su presupuesto es inferior a:', '50.000 euros',
 ['5.000 euros', '30.000 euros', '100.000 euros'], 'cuyo presupuesto sea inferior a 50.000 euros'),
('I', T, 'a5', 'Según el artículo 5.5, toda la información objeto de publicidad activa será:', 'Comprensible, de acceso fácil y gratuito',
 ['De acceso gratuito solo para los interesados', 'De acceso previo pago de una tasa', 'Accesible solo con certificado electrónico'], 'Toda la información será comprensible, de acceso fácil y gratuito'),
('I', T, 'a6', 'En el ámbito de la Administración General del Estado, ¿a quién corresponde evaluar el cumplimiento de los planes y programas anuales y plurianuales que deben publicarse?', 'A las inspecciones generales de servicios',
 ['Al Consejo de Transparencia y Buen Gobierno', 'Al Tribunal de Cuentas', 'A la Intervención General de la Administración del Estado'],
 'corresponde a las inspecciones generales de servicios la evaluación del cumplimiento de estos planes y programas'),
('I', T, 'a6', 'Según el artículo 6.1, el organigrama actualizado que deben publicar los sujetos obligados identificará:', 'A los responsables de los diferentes órganos y su perfil y trayectoria profesional',
 ['A todos los empleados públicos y sus retribuciones', 'Solo a los altos cargos con rango de Ministro', 'A los representantes sindicales'],
 'incluirán un organigrama actualizado que identifique a los responsables de los diferentes órganos y su perfil y trayectoria profesional'),
('I', T, 'a7', '¿Cuándo deben publicarse los Anteproyectos de Ley y los proyectos de Decretos Legislativos?', 'Cuando se soliciten los dictámenes a los órganos consultivos correspondientes (o en su aprobación, si no hay dictamen preceptivo)',
 ['Al iniciarse su elaboración, en todo caso', 'Tras su publicación en el «Boletín Oficial del Estado»', 'Tras la emisión de todos los dictámenes'],
 'Los Anteproyectos de Ley y los proyectos de Decretos Legislativos cuya iniciativa les corresponda, cuando se soliciten los dictámenes'),
('I', T, 'a7', 'Cuando sea preceptiva la solicitud de dictámenes, los proyectos de Reglamentos se publicarán:', 'Una vez solicitados los dictámenes, sin que ello suponga necesariamente la apertura de un trámite de audiencia pública',
 ['Tras su aprobación definitiva', 'Al inicio de su elaboración', 'Tras la emisión de los dictámenes'], 'la publicación se producirá una vez que estos hayan sido solicitados'),
('I', T, 'a8', 'La información relativa a los contratos menores podrá publicarse:', 'Trimestralmente',
 ['Mensualmente', 'Semestralmente', 'Anualmente'], 'La publicación de la información relativa a los contratos menores podrá realizarse trimestralmente'),
('I', T, 'a8', '¿Qué retribuciones deben hacerse públicas según el artículo 8.1.f)?', 'Las percibidas anualmente por los altos cargos y máximos responsables de las entidades',
 ['Las de todos los empleados públicos', 'Las de los funcionarios del subgrupo A1', 'Únicamente las de los miembros del Gobierno'], 'Las retribuciones percibidas anualmente por los altos cargos y máximos responsables'),
('I', T, 'a8', 'Al publicar las declaraciones anuales de bienes y actividades de los representantes locales:', 'Se omitirán los datos relativos a la localización concreta de los bienes inmuebles',
 ['Se publicará la dirección exacta de los inmuebles', 'Se omitirá el valor de los bienes', 'Solo se publicarán si el representante lo consiente'], 'se omitirán los datos relativos a la localización concreta de los bienes inmuebles'),
('I', T, 'a8', 'Según el artículo 8.3, las Administraciones Públicas publicarán la relación de:', 'Los bienes inmuebles que sean de su propiedad o sobre los que ostenten algún derecho real',
 ['Todos sus bienes muebles', 'Sus vehículos oficiales', 'Los bienes inmuebles arrendados a particulares'], 'Las Administraciones Públicas publicarán la relación de los bienes inmuebles que sean de su propiedad'),
('I', T, 'a9', 'El cumplimiento por la Administración General del Estado de las obligaciones de publicidad activa será objeto de control por:', 'El Consejo de Transparencia y Buen Gobierno',
 ['El Defensor del Pueblo', 'El Tribunal de Cuentas', 'La Agencia Española de Protección de Datos'], 'será objeto de control por parte del Consejo de Transparencia y Buen Gobierno'),
('I', T, 'a9', 'El incumplimiento reiterado de las obligaciones de publicidad activa tendrá la consideración de:', 'Infracción grave a efectos del régimen disciplinario',
 ['Infracción leve', 'Infracción muy grave', 'Mera irregularidad sin consecuencias'],
 'El incumplimiento reiterado de las obligaciones de publicidad activa reguladas en este capítulo tendrá la consideración de infracción grave'),
('I', T, 'a10', 'Según el artículo 10.2, el Portal de la Transparencia incluirá la información de la Administración General del Estado:', 'Cuyo acceso se solicite con mayor frecuencia',
 ['Únicamente de carácter económico', 'Únicamente relativa a los altos cargos', 'Que determine el Defensor del Pueblo'],
 'la información de la Administración General del Estado, cuyo acceso se solicite con mayor frecuencia'),
('I', T, 'a11', '¿Cuál de los siguientes NO es uno de los principios técnicos del Portal de la Transparencia enumerados en el artículo 11?', 'Confidencialidad',
 ['Accesibilidad', 'Interoperabilidad', 'Reutilización'], r're:deberán adecuarse a los siguientes principios: a\) Accesibilidad.*?c\) Reutilización'),
('I', T, 'a12', '¿Quiénes tienen derecho a acceder a la información pública según el artículo 12?', 'Todas las personas',
 ['Solo los ciudadanos españoles', 'Solo los interesados en un procedimiento', 'Solo los mayores de edad nacionales de la Unión Europea'], 'Todas las personas tienen derecho a acceder a la información pública'),
('I', T, 'a12', 'El derecho de acceso a la información pública se ejerce en los términos previstos en el artículo de la Constitución:', '105.b)',
 ['20.1.d)', '23.1', '103.1'], 'en los términos previstos en el artículo 105.b) de la Constitución Española'),
('I', T, 'a13', 'Según el artículo 13, se entiende por información pública:', 'Los contenidos o documentos, en cualquier formato o soporte, que obren en poder de los sujetos obligados y hayan sido elaborados o adquiridos en el ejercicio de sus funciones',
 ['Solo los documentos en formato electrónico', 'Solo los documentos publicados en el «Boletín Oficial del Estado»', 'Solo los documentos de procedimientos ya finalizados'],
 'Se entiende por información pública los contenidos o documentos'),
('I', T, 'a14', '¿Cuál de los siguientes NO figura entre los límites al derecho de acceso del artículo 14.1?', 'La eficacia de la gestión administrativa',
 ['La seguridad pública', 'Los intereses económicos y comerciales', 'La protección del medio ambiente'],
 r're:El derecho de acceso podrá ser limitado cuando acceder a la información suponga un perjuicio para: a\).*?l\) La protección del medio ambiente'),
('I', T, 'a14', 'Según el artículo 14.2, la aplicación de los límites al derecho de acceso será:', 'Justificada y proporcionada a su objeto y finalidad de protección, atendiendo a las circunstancias del caso concreto',
 ['Automática cuando concurra cualquiera de ellos', 'Discrecional del órgano, sin necesidad de motivación', 'Acordada siempre por el Consejo de Transparencia y Buen Gobierno'],
 'La aplicación de los límites será justificada y proporcionada'),
('I', T, 'a15', 'Si la información solicitada contuviera datos personales que revelen la ideología, afiliación sindical, religión o creencias, el acceso únicamente se podrá autorizar:',
 'Con el consentimiento expreso y por escrito del afectado, salvo que este hubiese hecho manifiestamente públicos los datos antes de la solicitud',
 ['Si lo ampara una norma con rango de ley', 'Previa ponderación del interés público en la divulgación', 'En ningún caso'],
 'el acceso únicamente se podrá autorizar en caso de que se contase con el consentimiento expreso y por escrito del afectado'),
('I', T, 'a15', 'Con carácter general, se concederá el acceso a la información que contenga datos:', 'Meramente identificativos relacionados con la organización, funcionamiento o actividad pública del órgano',
 ['Relativos a la salud de los empleados públicos', 'De carácter económico de los particulares', 'Relativos a la comisión de infracciones administrativas'], 'se concederá el acceso a información que contenga datos meramente identificativos'),
('I', T, 'a15', 'Las cautelas del artículo 15 sobre datos personales no serán aplicables si el acceso se efectúa:', 'Previa disociación de los datos personales, de modo que se impida la identificación de las personas afectadas',
 ['Por vía electrónica', 'Con autorización del superior jerárquico', 'Por un investigador acreditado'], 'si el acceso se efectúa previa disociación de los datos de carácter personal'),
('I', T, 'a16', 'Cuando la aplicación de alguno de los límites del artículo 14 no afecte a la totalidad de la información:', 'Se concederá el acceso parcial, previa omisión de la información afectada, salvo que resulte una información distorsionada o sin sentido',
 ['Se denegará el acceso a toda la información', 'Se concederá el acceso total', 'Se suspenderá el procedimiento'], 'se concederá el acceso parcial previa omisión de la información afectada por el límite'),
('I', T, 'a17', '¿Está obligado el solicitante a motivar su solicitud de acceso a la información?', 'No, aunque puede exponer sus motivos, que podrán tenerse en cuenta al resolver',
 ['Sí, en todo caso', 'Sí, cuando la información afecte a terceros', 'Sí, si es una persona jurídica'], 'El solicitante no está obligado a motivar su solicitud de acceso a la información'),
('I', T, 'a17', '¿A quién debe dirigirse la solicitud de acceso a la información pública?', 'Al titular del órgano administrativo o entidad que posea la información',
 ['Al Consejo de Transparencia y Buen Gobierno', 'Al Portal de la Transparencia, en todo caso', 'Al Defensor del Pueblo'], 'que deberá dirigirse al titular del órgano administrativo o entidad que posea la información'),
('I', T, 'a17', 'La ausencia de motivación de la solicitud de acceso:', 'No será por sí sola causa de rechazo de la solicitud',
 ['Es causa de inadmisión', 'Obliga a requerir su subsanación', 'Determina su desestimación'], 'la ausencia de motivación no será por si sola causa de rechazo de la solicitud'),
('I', T, 'a18', '¿Cuál de las siguientes NO es una causa de inadmisión de las solicitudes de acceso del artículo 18, sino un límite del artículo 14?', 'Que el acceso suponga un perjuicio para la seguridad pública',
 ['Que se refiera a información en curso de elaboración o de publicación general', 'Que la solicitud sea manifiestamente repetitiva o tenga un carácter abusivo', 'Que la divulgación requiera una acción previa de reelaboración'],
 r're:Se inadmitirán a trámite, mediante resolución motivada, las solicitudes: a\).*?e\) Que sean manifiestamente repetitivas'),
('I', T, 'a18', 'Si se inadmite una solicitud por dirigirse a un órgano en cuyo poder no obra la información y se desconoce el competente, la resolución deberá:', 'Indicar el órgano que, a juicio del que inadmite, es competente para conocer de la solicitud',
 ['Remitir la solicitud al Consejo de Transparencia y Buen Gobierno', 'Archivar sin más la solicitud', 'Requerir al solicitante que identifique el órgano competente'],
 'deberá indicar en la resolución el órgano que, a su juicio, es competente'),
('I', P, 'a19', 'Concreción por el solicitante de la información pedida, cuando la solicitud no la identifique suficientemente', '10 días',
 ['5 días', '15 días', '20 días'], 'se pedirá al solicitante que la concrete en un plazo de diez días'),
('I', P, 'a19', 'Alegaciones de los terceros cuyos derechos o intereses pudieran verse afectados por la información solicitada', '15 días',
 ['5 días', '10 días', '20 días'], 'se les concederá un plazo de quince días para que puedan realizar las alegaciones'),
('I', T, 'a20', 'El plazo para resolver la solicitud de acceso podrá ampliarse:', 'Por otro mes, si el volumen o la complejidad de la información lo hacen necesario, previa notificación al solicitante',
 ['Por quince días más', 'Por tres meses más', 'No puede ampliarse en ningún caso'], 'Este plazo podrá ampliarse por otro mes'),
('I', T, 'a20', 'Transcurrido el plazo máximo para resolver una solicitud de acceso sin resolución expresa notificada, la solicitud se entenderá:', 'Desestimada',
 ['Estimada', 'Caducada', 'Archivada por desistimiento'], 'se entenderá que la solicitud ha sido desestimada'),
('I', T, 'a20', 'Las resoluciones dictadas en materia de acceso a la información pública:', 'Son recurribles directamente ante la jurisdicción contencioso-administrativa, sin perjuicio de la reclamación potestativa del artículo 24',
 ['Solo son recurribles en alzada', 'No son recurribles', 'Solo son recurribles ante el Defensor del Pueblo'], 'son recurribles directamente ante la Jurisdicción Contencioso-administrativa'),
('I', T, 'a20', 'El incumplimiento reiterado de la obligación de resolver en plazo las solicitudes de acceso tendrá la consideración de:', 'Infracción grave a efectos del régimen disciplinario',
 ['Infracción leve', 'Infracción muy grave', 'Mera irregularidad sin consecuencias'], 'El incumplimiento reiterado de la obligación de resolver en plazo tendrá la consideración de infracción grave'),
('I', T, 'a20', '¿Cuál de las siguientes resoluciones de acceso NO tiene que ser motivada según el artículo 20.2?', 'La que conceda el acceso total, en la modalidad solicitada y sin oposición de terceros',
 ['La que deniegue el acceso', 'La que conceda el acceso parcial', 'La que permita el acceso habiendo oposición de un tercero'], 'Serán motivadas las resoluciones que denieguen el acceso'),
('I', T, 'a22', 'El acceso a la información se realizará:', 'Preferentemente por vía electrónica, salvo cuando no sea posible o el solicitante haya señalado expresamente otro medio',
 ['Siempre en papel', 'Siempre de forma presencial', 'Por correo certificado'], 'El acceso a la información se realizará preferentemente por vía electrónica'),
('I', P, 'a22', 'Otorgamiento del acceso a la información cuando no pueda darse en el momento de la notificación de la resolución', 'No superior a 10 días',
 ['No superior a 5 días', 'No superior a 15 días', 'No superior a 20 días'], 'deberá otorgarse, en cualquier caso, en un plazo no superior a diez días'),
('I', T, 'a22', 'Según el artículo 22.4, el acceso a la información pública es:', 'Gratuito, aunque la expedición de copias o la trasposición a otro formato puede dar lugar a exacciones',
 ['Sujeto siempre al pago de una tasa', 'Gratuito solo para las personas físicas', 'Gratuito, incluida en todo caso la expedición de copias'], r're:El acceso a la información será gratuito\. No obstante, la expedición de copias o la trasposición de la información a un formato diferente al original podrá dar lugar a la exigencia de exacciones'),
('I', T, 'a22', 'Si ha existido oposición de tercero, el acceso a la información:', 'Sólo tendrá lugar cuando haya transcurrido el plazo para interponer recurso contencioso-administrativo sin que se haya formalizado, o haya sido resuelto confirmando el derecho',
 ['Se producirá en el momento de la notificación', 'Requiere el consentimiento del tercero', 'Se producirá a los diez días de la resolución'], 'Si ha existido oposición de tercero, el acceso sólo tendrá lugar cuando'),
('I', T, 'a22', 'Si la información solicitada ya ha sido publicada, la resolución:', 'Podrá limitarse a indicar al solicitante cómo puede acceder a ella',
 ['Deberá inadmitir la solicitud', 'Deberá entregar en todo caso una copia certificada', 'Deberá desestimar la solicitud'], 'la resolución podrá limitarse a indicar al solicitante cómo puede acceder a ella'),
('I', T, 'a23', 'La reclamación ante el Consejo de Transparencia y Buen Gobierno tiene la consideración de:', 'Sustitutiva de los recursos administrativos',
 ['Recurso de alzada impropio', 'Complementaria del recurso de reposición', 'Requisito obligatorio previo al recurso contencioso-administrativo'], 'tendrá la consideración de sustitutiva de los recursos administrativos'),
('I', T, 'a23', 'Contra las resoluciones en materia de acceso dictadas por los órganos del artículo 2.1.f) (Casa del Rey, Congreso, Senado, Tribunal Constitucional, CGPJ, etc.):', 'Sólo cabe recurso contencioso-administrativo',
 ['Cabe reclamación ante el Consejo de Transparencia y Buen Gobierno', 'Cabe recurso de alzada', 'No cabe recurso alguno'], 'sólo cabrá la interposición de recurso contencioso-administrativo'),
('I', T, 'a24', 'La reclamación ante el Consejo de Transparencia y Buen Gobierno tiene carácter:', 'Potestativo y previo a la impugnación en vía contencioso-administrativa',
 ['Obligatorio', 'Posterior al recurso contencioso-administrativo', 'Subsidiario del recurso de alzada'], 'con carácter potestativo y previo a su impugnación en vía contencioso-administrativa'),
('I', T, 'a24', '¿A quién comunica el Presidente del Consejo de Transparencia y Buen Gobierno las resoluciones que dicte sobre reclamaciones?', 'Al Defensor del Pueblo',
 ['Al Tribunal de Cuentas', 'A la Agencia Española de Protección de Datos', 'Al Ministerio Fiscal'], 'comunicará al Defensor del Pueblo las resoluciones'),
('I', T, 'a25', 'A efectos del título II (buen gobierno), se consideran altos cargos de la Administración General del Estado:', 'Los que tengan tal consideración en aplicación de la normativa en materia de conflictos de intereses',
 ['Todos los funcionarios del subgrupo A1', 'Los que determine el Consejo de Transparencia y Buen Gobierno', 'Los Subdirectores generales, en todo caso'],
 'se considerarán altos cargos los que tengan tal consideración en aplicación de la normativa en materia de conflictos de intereses'),
('I', T, 'a26', 'Según el artículo 26.2.b), los altos cargos no aceptarán para sí regalos que:', 'Superen los usos habituales, sociales o de cortesía',
 ['Superen los 100 euros', 'Procedan de otras Administraciones', 'No hayan sido declarados al Consejo de Transparencia y Buen Gobierno'], 'No aceptarán para sí regalos que superen los usos habituales, sociales o de cortesía'),
('I', T, 'a26', 'Los obsequios de mayor relevancia institucional recibidos por los altos cargos:', 'Se incorporarán al patrimonio de la Administración Pública correspondiente',
 ['Deberán devolverse al donante', 'Podrán conservarse si se declaran', 'Se subastarán con fines benéficos'], 'se procederá a su incorporación al patrimonio de la Administración Pública correspondiente'),
('I', T, 'a26', '¿Cuál de los siguientes figura entre los principios generales de buen gobierno del artículo 26.2.a)?', 'Respetar el principio de imparcialidad, con un criterio independiente y ajeno a todo interés particular',
 ['Seguir las instrucciones de su partido político', 'Priorizar los intereses de su propio departamento', 'Guardar reserva frente a los órganos de control'], 'Respetarán el principio de imparcialidad'),
('I', T, 'a28', 'Los compromisos de gastos, reconocimiento de obligaciones y ordenación de pagos sin crédito suficiente constituyen, cuando sean culpables:', 'Infracciones muy graves',
 ['Infracciones graves', 'Infracciones leves', 'Faltas disciplinarias leves'],
 r're:Constituyen infracciones muy graves las siguientes conductas cuando sean culpables: a\).*?c\) Los compromisos de gastos, reconocimiento de obligaciones y ordenación de pagos sin crédito suficiente para realizarlos'),
('I', T, 'a29', 'Según el artículo 29, el incumplimiento del deber de respeto a la Constitución y a los Estatutos de Autonomía en el ejercicio de sus funciones es una infracción:', 'Muy grave',
 ['Grave', 'Leve', 'En materia de conflicto de intereses'], r're:Son infracciones muy graves: a\) El incumplimiento del deber de respeto a la Constitución'),
('I', T, 'a29', 'Según el artículo 29, el abuso de autoridad en el ejercicio del cargo es una infracción:', 'Grave',
 ['Muy grave', 'Leve', 'En materia de gestión económico-presupuestaria'], r're:Son infracciones graves: a\) El abuso de autoridad en el ejercicio del cargo'),
('I', T, 'a29', 'Según el artículo 29, la intervención de un alto cargo en un procedimiento administrativo cuando concurra alguna causa de abstención es una infracción:', 'Grave',
 ['Muy grave', 'Leve', 'No tipificada en la Ley 19/2013'],
 r're:Son infracciones graves: a\).*?b\) La intervención en un procedimiento administrativo cuando se dé alguna de las causas de abstención legalmente señaladas'),
('I', T, 'a29', 'Según el artículo 29, la incorrección con los superiores, compañeros o subordinados es una infracción:', 'Leve',
 ['Grave', 'Muy grave', 'No tipificada en la Ley 19/2013'], r're:Son infracciones leves: a\) La incorrección con los superiores, compañeros o subordinados'),
('I', T, 'a30', 'Las infracciones leves del título II de la Ley 19/2013 serán sancionadas con:', 'Una amonestación',
 ['Una multa', 'La destitución del cargo', 'La declaración del incumplimiento y su publicación en el «Boletín Oficial del Estado»'], 'Las infracciones leves serán sancionadas con una amonestación'),
('I', P, 'a30', 'Período durante el cual los sancionados por una infracción muy grave no podrán ser nombrados alto cargo o asimilado', 'Entre 5 y 10 años',
 ['Entre 1 y 3 años', 'Entre 3 y 5 años', 'Entre 10 y 15 años'], 'durante un periodo de entre cinco y diez años'),
('I', T, 'a30', 'Cuando las infracciones del título II pudieran ser constitutivas de delito, la Administración:', 'Pondrá los hechos en conocimiento del Fiscal General del Estado y se abstendrá de seguir el procedimiento mientras no termine el proceso penal',
 ['Continuará el procedimiento sancionador en paralelo', 'Remitirá los hechos al Consejo de Transparencia y Buen Gobierno', 'Archivará definitivamente el procedimiento'],
 'la Administración pondrá los hechos en conocimiento del Fiscal General del Estado'),
('I', T, 'a31', 'En los procedimientos sancionadores del título II dirigidos contra altos cargos de la Administración General del Estado, la instrucción corresponde a:', 'La Oficina de Conflictos de Intereses',
 ['El Consejo de Transparencia y Buen Gobierno', 'La Inspección General de Servicios', 'El Tribunal de Cuentas'], 'la instrucción de los correspondientes procedimientos corresponderá a la Oficina de Conflictos de Intereses'),
('I', T, 'a31', 'Cuando el alto cargo sea miembro del Gobierno o Secretario de Estado, la imposición de las sanciones del título II corresponde a:', 'El Consejo de Ministros',
 ['El Presidente del Gobierno', 'El Tribunal Supremo', 'El Consejo de Transparencia y Buen Gobierno'], 'a) Al Consejo de Ministros cuando el alto cargo tenga la condición de miembro del Gobierno o Secretario de Estado'),
('I', T, 'a31', 'Las resoluciones dictadas en el procedimiento sancionador del título II son recurribles ante:', 'El orden jurisdiccional contencioso-administrativo',
 ['El Consejo de Transparencia y Buen Gobierno', 'El Tribunal Constitucional', 'El Consejo de Ministros, en alzada'], 'serán recurribles ante el orden jurisdiccional contencioso-administrativo'),
('I', P, 'a32', 'Prescripción de las infracciones muy graves de buen gobierno (Ley 19/2013)', '5 años',
 ['2 años', '3 años', '4 años'], 'será de cinco años para las infracciones muy graves'),
('I', P, 'a32', 'Prescripción de las infracciones graves de buen gobierno (Ley 19/2013)', '3 años',
 ['1 año', '2 años', '5 años'], 'tres años para las graves y un año para las leves'),
('I', P, 'a32', 'Prescripción de las infracciones leves de buen gobierno (Ley 19/2013)', '1 año',
 ['2 años', '3 años', '5 años'], 'cinco años para las infracciones muy graves, tres años para las graves y un año para las leves'),
('I', T, 'a33', 'Según el artículo 33.2, el Consejo de Transparencia y Buen Gobierno:', 'Tiene personalidad jurídica propia y plena capacidad de obrar, y actúa con autonomía y plena independencia',
 ['Es un órgano sin personalidad jurídica integrado en un Ministerio', 'Depende jerárquicamente del Defensor del Pueblo', 'Es un órgano de las Cortes Generales'], r're:tiene personalidad jurídica propia y plena capacidad de obrar\. Actúa con autonomía y plena independencia'),
('I', T, 'a35', '¿Qué órganos componen el Consejo de Transparencia y Buen Gobierno?', 'La Comisión de Transparencia y Buen Gobierno y el Presidente',
 ['El Pleno y la Comisión Permanente', 'El Presidente y el Vicepresidente', 'El Consejo Rector y el Director'],
 r're:estará compuesto por los siguientes órganos: a\) La Comisión de Transparencia y Buen Gobierno\. b\) El Presidente'),
('I', T, 'a36', '¿Cuál de los siguientes NO forma parte de la Comisión de Transparencia y Buen Gobierno según el artículo 36.2?', 'Un representante del Consejo General del Poder Judicial',
 ['Un Diputado', 'Un representante de la Agencia Española de Protección de Datos', 'Un representante del Tribunal de Cuentas'],
 r're:Dicha Comisión estará compuesta por: a\) El Presidente.*?h\) Un representante de la Autoridad Independiente de Responsabilidad Fiscal'),
('I', T, 'a36', 'La condición de miembro de la Comisión de Transparencia y Buen Gobierno:', 'No exige dedicación exclusiva ni da derecho a remuneración, salvo lo previsto para el Presidente',
 ['Exige dedicación exclusiva', 'Da derecho a una retribución fijada por ley para todos sus miembros', 'Es incompatible con cualquier otro cargo público'], 'no exigirá dedicación exclusiva ni dará derecho a remuneración'),
('I', T, 'a36', '¿Con qué periodicidad mínima convoca la Comisión de Transparencia y Buen Gobierno a los representantes de los organismos autonómicos con funciones similares?', 'Al menos una vez al año',
 ['Al menos una vez al trimestre', 'Al menos dos veces al año', 'Una vez por legislatura'], 'Al menos una vez al año, la Comisión de Transparencia y Buen Gobierno convocará'),
('I', P, 'a37', 'Mandato, no renovable, del Presidente del Consejo de Transparencia y Buen Gobierno', '5 años',
 ['3 años', '4 años', '6 años'], 'será nombrado por un período no renovable de cinco años'),
('I', T, 'a37', 'La Comisión competente del Congreso refrenda el nombramiento del Presidente del Consejo de Transparencia y Buen Gobierno por:', 'Mayoría absoluta',
 ['Mayoría simple', 'Mayoría de tres quintos', 'Mayoría de dos tercios'], 'por acuerdo adoptado por mayoría absoluta, deberá refrendar el nombramiento'),
('I', T, 'a38', 'Según el artículo 38.2, ¿a quién corresponde conocer de las reclamaciones que se presenten en aplicación del artículo 24?', 'Al Presidente del Consejo de Transparencia y Buen Gobierno',
 ['A la Comisión de Transparencia y Buen Gobierno', 'Al Defensor del Pueblo', 'Al Consejo de Estado'],
 r're:El Presidente del Consejo de Transparencia y Buen Gobierno ejercerá las siguientes funciones:.*?c\) Conocer de las reclamaciones'),
('I', T, 'a38', 'La memoria anual en la que el Consejo de Transparencia y Buen Gobierno evalúa el grado de aplicación de la Ley se presenta ante:', 'Las Cortes Generales',
 ['El Gobierno', 'El Defensor del Pueblo', 'El Tribunal de Cuentas'], 'que será presentada ante las Cortes Generales'),
('I', T, 'a38', '¿Qué función tiene el Consejo de Transparencia y Buen Gobierno respecto de los proyectos normativos estatales que desarrollen la Ley 19/2013 o estén relacionados con su objeto?', 'Informarlos preceptivamente',
 ['Aprobarlos', 'Informarlos con carácter facultativo', 'Vetarlos'], 'Informar preceptivamente los proyectos normativos de carácter estatal'),
]
