# Lote 14 · LOPDGDD (Ley Orgánica 3/2018, de Protección de Datos Personales y garantía de los derechos digitales)
# · bloque II (asignación PROVISIONAL hasta confirmar el Anexo III, ver data/programa.md).
# Títulos I-VII (arts. 1-51) y régimen sancionador (arts. 64-78).
NORMA, LOTE, INICIO = 'LOPDGDD', 'lote-014', 14001
T, P = 'test', 'plazo'
PREGUNTAS = [
('II', T, 'a1', 'El derecho fundamental de las personas físicas a la protección de datos personales está amparado por el artículo de la Constitución:', '18.4',
 ['20.1', '105.b)', '16.2'], 'amparado por el artículo 18.4 de la Constitución'),
('II', T, 'a2', '¿A cuál de los siguientes tratamientos NO es de aplicación la LOPDGDD según su artículo 2.2?', 'A los tratamientos sometidos a la normativa sobre protección de materias clasificadas',
 ['A los tratamientos automatizados de datos de clientes de una empresa', 'A los tratamientos realizados por la Administración General del Estado', 'A los tratamientos no automatizados de datos destinados a un fichero'],
 'c) A los tratamientos sometidos a la normativa sobre protección de materias clasificadas'),
('II', T, 'a3', 'Las personas vinculadas al fallecido o sus herederos NO podrán acceder a sus datos personales cuando:', 'La persona fallecida lo hubiese prohibido expresamente o así lo establezca una ley',
 ['Hayan transcurrido seis meses desde el fallecimiento', 'No sean herederos forzosos', 'El fallecido fuera menor de edad'],
 'cuando la persona fallecida lo hubiese prohibido expresamente o así lo establezca una ley'),
('II', T, 'a3', 'La prohibición expresa del fallecido de acceder a sus datos NO afecta al derecho de los herederos a acceder:', 'A los datos de carácter patrimonial del causante',
 ['A los datos de salud del causante', 'A las comunicaciones privadas del causante', 'A cualquier dato del causante'],
 'Dicha prohibición no afectará al derecho de los herederos a acceder a los datos de carácter patrimonial del causante'),
('II', T, 'a5', 'El deber de confidencialidad de quienes intervienen en el tratamiento de datos:', 'Se mantiene aun cuando haya finalizado la relación del obligado con el responsable o encargado',
 ['Termina al finalizar la relación con el responsable', 'Dura dos años tras finalizar la relación', 'Solo afecta al responsable del tratamiento'],
 'se mantendrán aun cuando hubiese finalizado la relación del obligado con el responsable o encargado del tratamiento'),
('II', T, 'a6', 'Se entiende por consentimiento del afectado toda manifestación de voluntad:', 'Libre, específica, informada e inequívoca',
 ['Libre y presunta', 'Expresa y por escrito en todo caso', 'Tácita, salvo oposición'], 'toda manifestación de voluntad libre, específica, informada e inequívoca'),
('II', T, 'a6', 'La ejecución de un contrato:', 'No puede supeditarse a que el afectado consienta el tratamiento de sus datos para finalidades no relacionadas con la relación contractual',
 ['Puede condicionarse libremente al consentimiento para cualquier finalidad', 'Exige siempre el consentimiento para fines publicitarios', 'Requiere autorización de la AEPD'],
 'No podrá supeditarse la ejecución del contrato a que el afectado consienta el tratamiento'),
('II', T, 'a7', 'El tratamiento de los datos personales de un menor de edad solo puede fundarse en su propio consentimiento cuando sea mayor de:', 'Catorce años',
 ['Dieciséis años', 'Doce años', 'Dieciocho años'], 'únicamente podrá fundarse en su consentimiento cuando sea mayor de catorce años'),
('II', T, 'a8', 'El tratamiento fundado en el cumplimiento de una obligación legal exige que así lo prevea:', 'Una norma de Derecho de la Unión Europea o una norma con rango de ley',
 ['Una orden ministerial', 'Un acuerdo del Consejo de Ministros', 'Una instrucción de la AEPD'],
 'cuando así lo prevea una norma de Derecho de la Unión Europea o una norma con rango de ley'),
('II', T, 'a9', 'Para levantar la prohibición del tratamiento de datos cuya finalidad principal sea identificar la ideología, afiliación sindical, religión, orientación sexual, creencias u origen racial o étnico:', 'No basta el solo consentimiento del afectado',
 ['Basta el consentimiento verbal del afectado', 'Basta la autorización del responsable', 'Basta con informar al afectado'],
 'el solo consentimiento del afectado no bastará para levantar la prohibición'),
('II', T, 'a1-3', 'Cuando los datos se obtengan del afectado, la información básica que se le facilite deberá contener, al menos:', 'La identidad del responsable, la finalidad del tratamiento y la posibilidad de ejercer los derechos de los artículos 15 a 22 del RGPD',
 ['Solo la identidad del responsable', 'El número de registro de la base de datos en la AEPD', 'El nombre del delegado de protección de datos exclusivamente'],
 r're:La información básica a la que se refiere el apartado anterior deberá contener, al menos: a\) La identidad del responsable.*?c\) La posibilidad de ejercer los derechos'),
('II', T, 'a1-4', 'Los derechos reconocidos en los artículos 15 a 22 del RGPD pueden ejercerse:', 'Directamente o por medio de representante legal o voluntario',
 ['Solo personalmente', 'Solo mediante abogado', 'Solo a través de la AEPD'], 'podrán ejercerse directamente o por medio de representante legal o voluntario'),
('II', T, 'a1-4', 'La prueba del cumplimiento del deber de responder a la solicitud de ejercicio de derechos del afectado recae sobre:', 'El responsable del tratamiento',
 ['El afectado', 'La AEPD', 'El encargado del tratamiento en todo caso'], 'recaerá sobre el responsable'),
('II', T, 'a1-4', 'Las actuaciones del responsable del tratamiento para atender las solicitudes de ejercicio de derechos son, con carácter general:', 'Gratuitas',
 ['Sujetas a un canon fijo', 'Sujetas a tasa', 'De pago si la solicitud es electrónica'], 'Serán gratuitas las actuaciones llevadas a cabo por el responsable del tratamiento'),
('II', P, 'a1-5', 'Período dentro del cual el ejercicio del derecho de acceso en más de una ocasión puede considerarse repetitivo, salvo causa legítima', '6 meses',
 ['3 meses', '12 meses', '1 mes'], 'en más de una ocasión durante el plazo de seis meses'),
('II', T, 'a1-5', 'El derecho de acceso se entenderá otorgado si el responsable facilita al afectado:', 'Un sistema de acceso remoto, directo y seguro a los datos que garantice de modo permanente el acceso a su totalidad',
 ['Una copia en papel por correo ordinario', 'Un resumen anual de sus datos', 'Una cita presencial en sus oficinas'],
 'El derecho de acceso se entenderá otorgado si el responsable del tratamiento facilitara al afectado un sistema de acceso remoto, directo y seguro'),
('II', T, 'a1-6', 'Al ejercer el derecho de rectificación, el afectado deberá indicar en su solicitud:', 'A qué datos se refiere y la corrección que haya de realizarse',
 ['Solo su identidad', 'El motivo por el que desea la supresión', 'La finalidad del tratamiento'], 'el afectado deberá indicar en su solicitud a qué datos se refiere y la corrección que haya de realizarse'),
('II', T, 'a1-7', 'Cuando la supresión derive del ejercicio del derecho de oposición a la mercadotecnia directa, el responsable podrá conservar:', 'Los datos identificativos necesarios para impedir tratamientos futuros con esos fines',
 ['Todos los datos del afectado durante cinco años', 'Ningún dato del afectado', 'Los datos de facturación exclusivamente'],
 'el responsable podrá conservar los datos identificativos del afectado necesarios con el fin de impedir tratamientos futuros para fines de mercadotecnia directa'),
('II', T, 'a1-8', 'El hecho de que el tratamiento de los datos personales esté limitado:', 'Debe constar claramente en los sistemas de información del responsable',
 ['Debe comunicarse a la AEPD', 'Debe publicarse en el BOE', 'No requiere ninguna constancia'],
 'debe constar claramente en los sistemas de información del responsable'),
('II', T, 'a2-2', 'Los datos relativos al incumplimiento de obligaciones dinerarias en sistemas comunes de información crediticia solo pueden mantenerse mientras persista el incumplimiento, con el límite máximo de:', 'Cinco años desde el vencimiento de la obligación',
 ['Seis años desde la inclusión', 'Tres años desde el vencimiento', 'Diez años desde la inclusión'],
 'con el límite máximo de cinco años desde la fecha de vencimiento de la obligación dineraria'),
('II', P, 'a2-4', 'Plazo máximo, desde su captación, para suprimir las imágenes de videovigilancia, salvo que deban conservarse para acreditar actos contra personas, bienes o instalaciones', '1 mes',
 ['15 días', '3 meses', '1 año'], 'Los datos serán suprimidos en el plazo máximo de un mes desde su captación'),
('II', P, 'a2-4', 'Plazo máximo para poner a disposición de la autoridad competente las imágenes de videovigilancia que acrediten actos contra la integridad de personas, bienes o instalaciones', '72 horas',
 ['24 horas', '48 horas', '96 horas'], 'en un plazo máximo de setenta y dos horas desde que se tuviera conocimiento de la existencia de la grabación'),
('II', T, 'a2-4', 'El deber de información en los tratamientos de videovigilancia se entiende cumplido mediante:', 'La colocación de un dispositivo informativo en lugar suficientemente visible',
 ['La notificación individual a cada persona grabada', 'La publicación en el BOE', 'La inscripción en un registro de la AEPD'],
 'se entenderá cumplido mediante la colocación de un dispositivo informativo en lugar suficientemente visible'),
('II', T, 'a2-4', 'Según el artículo 22.5, se considera excluido del ámbito de aplicación del RGPD el tratamiento por una persona física de imágenes que solamente capten:', 'El interior de su propio domicilio',
 ['La vía pública frente a su domicilio', 'Las zonas comunes del edificio', 'El interior de su lugar de trabajo'],
 'el tratamiento por una persona física de imágenes que solamente capten el interior de su propio domicilio'),
('II', T, 'a2-5', 'Quienes pretendan realizar comunicaciones de mercadotecnia directa deberán previamente:', 'Consultar los sistemas de exclusión publicitaria que pudieran afectar a su actuación',
 ['Obtener autorización de la AEPD', 'Inscribirse en el Registro Mercantil', 'Comunicarlo al Ministerio de Consumo'],
 'deberán previamente consultar los sistemas de exclusión publicitaria'),
('II', T, 'a2-8', 'El tratamiento por las Administraciones Públicas de datos con fines de archivo en interés público:', 'Es lícito, con las especialidades de la legislación de patrimonio histórico y archivos',
 ['Está prohibido', 'Requiere el consentimiento de cada afectado', 'Solo es lícito para datos de personas fallecidas'],
 r're:Será lícito el tratamiento por las Administraciones Públicas de datos con fines de archivo en interés público.*?del Patrimonio Histórico Español'),
('II', T, 'a3-3', 'Los sujetos del artículo 77.1 de la LOPDGDD (entre ellos las Administraciones Públicas) deben hacer público, accesible por medios electrónicos:', 'Un inventario de sus actividades de tratamiento',
 ['El nombre de todos los afectados', 'Las contraseñas de acceso a sus sistemas', 'Sus evaluaciones de impacto completas'],
 'harán público un inventario de sus actividades de tratamiento accesible por medios electrónicos'),
('II', T, 'a3-4', 'El responsable del tratamiento está obligado a bloquear los datos cuando:', 'Proceda a su rectificación o supresión',
 ['Los transfiera a un encargado', 'Reciba una solicitud de acceso', 'Realice una copia de seguridad'], 'estará obligado a bloquear los datos cuando proceda a su rectificación o supresión'),
('II', T, 'a3-4', 'El bloqueo de los datos consiste en:', 'Su identificación y reserva para impedir su tratamiento, salvo su puesta a disposición de jueces, Ministerio Fiscal o Administraciones competentes',
 ['Su destrucción inmediata', 'Su cifrado y transferencia a la AEPD', 'Su publicación con acceso restringido'],
 r're:El bloqueo de los datos consiste en la identificación y reserva de los mismos.*?el Ministerio Fiscal o las Administraciones Públicas competentes'),
('II', T, 'a3-5', 'El acceso por un encargado del tratamiento a los datos necesarios para prestar un servicio al responsable:', 'No se considera comunicación de datos, si se cumple la normativa',
 ['Se considera cesión de datos sujeta a consentimiento', 'Está prohibido', 'Requiere autorización previa de la AEPD'],
 'no se considerará comunicación de datos'),
('II', T, 'a3-5', 'Quien figurando como encargado del tratamiento utiliza los datos para sus propias finalidades tiene la consideración de:', 'Responsable del tratamiento',
 ['Encargado del tratamiento', 'Tercero autorizado', 'Delegado de protección de datos'],
 'Tendrá asimismo la consideración de responsable del tratamiento quien figurando como encargado utilizase los datos para sus propias finalidades'),
('II', T, 'a3-6', '¿Cuál de las siguientes entidades está obligada en todo caso a designar un delegado de protección de datos según el artículo 34.1?', 'Los centros docentes y las Universidades públicas y privadas',
 ['Cualquier comercio minorista', 'Los profesionales de la salud que ejerzan a título individual', 'Las comunidades de propietarios'],
 'b) Los centros docentes que ofrezcan enseñanzas en cualquiera de los niveles'),
('II', P, 'a3-6', 'Plazo para comunicar a la AEPD o autoridad autonómica las designaciones, nombramientos y ceses de los delegados de protección de datos', '10 días',
 ['15 días', '1 mes', '5 días'], 'comunicarán en el plazo de diez días a la Agencia Española de Protección de Datos'),
('II', T, 'a3-8', 'El delegado de protección de datos que sea persona física integrada en la organización:', 'No puede ser removido ni sancionado por desempeñar sus funciones salvo dolo o negligencia grave',
 ['Puede ser cesado libremente por el responsable', 'Depende jerárquicamente del encargado del tratamiento', 'Solo puede ser sancionado por la AEPD'],
 'no podrá ser removido ni sancionado por el responsable o el encargado por desempeñar sus funciones salvo que incurriera en dolo o negligencia grave'),
('II', T, 'a3-8', 'En el ejercicio de sus funciones, el delegado de protección de datos tendrá acceso a los datos personales y procesos de tratamiento:', 'Sin que pueda oponérsele ningún deber de confidencialidad o secreto',
 ['Solo con autorización judicial', 'Solo a los datos no sensibles', 'Previa autorización de la AEPD'],
 'no pudiendo oponer a este acceso el responsable o el encargado del tratamiento la existencia de cualquier deber de confidencialidad o secreto'),
('II', P, 'a3-9', 'Plazo máximo para que el delegado de protección de datos comunique al afectado la decisión adoptada sobre la reclamación que este le dirija antes de acudir a la AEPD', '2 meses',
 ['1 mes', '3 meses', '15 días'], 'en el plazo máximo de dos meses a contar desde la recepción de la reclamación'),
('II', P, 'a3-9', 'Plazo para que el delegado de protección de datos responda a la reclamación que le remita la AEPD', '1 mes',
 ['2 meses', '15 días', '3 meses'], 'a fin de que este responda en el plazo de un mes'),
('II', T, 'a3-10', 'Los códigos de conducta regulados por el RGPD:', 'Son vinculantes para quienes se adhieran a ellos',
 ['Son meramente orientativos para todos', 'Son obligatorios para todas las empresas del sector', 'Solo vinculan a las Administraciones Públicas'],
 'serán vinculantes para quienes se adhieran a los mismos'),
('II', T, 'a3-10', 'Los códigos de conducta son aprobados por:', 'La Agencia Española de Protección de Datos o, en su caso, la autoridad autonómica competente',
 ['El Comité Europeo de Protección de Datos exclusivamente', 'El Ministerio de Justicia', 'Las asociaciones empresariales que los promuevan'],
 'Los códigos de conducta serán aprobados por la Agencia Española de Protección de Datos'),
('II', T, 'a3-11', 'La acreditación de las instituciones de certificación del artículo 43.1 del RGPD puede llevarla a cabo:', 'La Entidad Nacional de Acreditación (ENAC)',
 ['El Ministerio de Industria', 'AENOR', 'El Consejo de Transparencia y Buen Gobierno'],
 'podrá ser llevada a cabo por la Entidad Nacional de Acreditación (ENAC)'),
('II', P, 'a4-3', 'Duración máxima del procedimiento de aprobación de normas corporativas vinculantes por la AEPD', '9 meses',
 ['6 meses', '12 meses', '3 meses'], 'tendrá una duración máxima de nueve meses'),
('II', T, 'a4-6', 'La Agencia Española de Protección de Datos es:', 'Una autoridad administrativa independiente de ámbito estatal',
 ['Un organismo autónomo', 'Una entidad pública empresarial', 'Una agencia estatal'], 'La Agencia Española de Protección de Datos es una autoridad administrativa independiente de ámbito estatal'),
('II', T, 'a4-6', 'La Agencia Española de Protección de Datos se relaciona con el Gobierno a través de:', 'El Ministerio de Justicia',
 ['El Ministerio del Interior', 'El Ministerio de Hacienda', 'La Presidencia del Gobierno'], 'Se relaciona con el Gobierno a través del Ministerio de Justicia'),
('II', T, 'a4-6', 'En el Comité Europeo de Protección de Datos, el representante común de las autoridades españolas de protección de datos es:', 'La Agencia Española de Protección de Datos',
 ['La autoridad autonómica más antigua', 'El Ministerio de Justicia', 'El Consejo General del Poder Judicial'],
 'tendrá la condición de representante común de las autoridades de protección de datos del Reino de España en el Comité Europeo de Protección de Datos'),
('II', T, 'a4-8', 'La Presidencia de la AEPD puede autorizar modificaciones presupuestarias que no incrementen los gastos de personal hasta un:', 'Tres por ciento de la cifra inicial de su presupuesto total de gastos',
 ['Cinco por ciento', 'Diez por ciento', 'Uno por ciento'], 'que impliquen hasta un tres por ciento de la cifra inicial de su presupuesto total de gastos'),
('II', T, 'a4-8', 'El personal al servicio de la Agencia Española de Protección de Datos será:', 'Funcionario o laboral',
 ['Exclusivamente funcionario', 'Exclusivamente laboral', 'Personal eventual'], 'El personal al servicio de la Agencia Española de Protección de Datos será funcionario o laboral'),
('II', T, 'a4-10', 'La Presidencia de la AEPD está auxiliada por un Adjunto en el que puede delegar sus funciones, excepto:', 'Las relacionadas con los procedimientos regulados por el título VIII de la ley',
 ['Las de representación de la Agencia', 'Las de gestión de personal', 'Las de elaboración del presupuesto'],
 'a excepción de las relacionadas con los procedimientos regulados por el título VIII de esta ley orgánica'),
('II', T, 'a4-10', 'La propuesta de Presidencia y Adjunto de la AEPD debe ser ratificada por la Comisión de Justicia del Congreso en primera votación por mayoría de:', 'Tres quintos de sus miembros',
 ['Dos tercios de sus miembros', 'Mayoría simple', 'Cuatro quintos de sus miembros'], 'en votación pública por mayoría de tres quintos de sus miembros en primera votación'),
('II', P, 'a4-10', 'Duración del mandato de la Presidencia y del Adjunto de la AEPD (renovable por otro período igual)', '5 años',
 ['4 años', '6 años', '3 años'], 'tiene una duración de cinco años y puede ser renovado para otro período de igual duración'),
('II', T, 'a4-10', 'Los actos y disposiciones de la Presidencia de la AEPD ponen fin a la vía administrativa y son recurribles directamente ante:', 'La Sala de lo Contencioso-administrativo de la Audiencia Nacional',
 ['El Tribunal Supremo', 'El Ministro de Justicia en alzada', 'Los Juzgados centrales de lo contencioso-administrativo'],
 'siendo recurribles, directamente, ante la Sala de lo Contencioso-administrativo de la Audiencia Nacional'),
('II', T, 'a4-11', 'El Consejo Consultivo de la AEPD se reúne cuando lo disponga la Presidencia y, en todo caso:', 'Una vez al semestre',
 ['Una vez al mes', 'Una vez al trimestre', 'Una vez al año'], 'y, en todo caso, una vez al semestre'),
('II', T, 'a4-11', 'Las decisiones tomadas por el Consejo Consultivo de la AEPD:', 'No tienen en ningún caso carácter vinculante',
 ['Son vinculantes para la Presidencia', 'Son vinculantes si se adoptan por unanimidad', 'Son vinculantes para las autoridades autonómicas'],
 'Las decisiones tomadas por el Consejo Consultivo no tendrán en ningún caso carácter vinculante'),
('II', T, 'a4-11', 'Los miembros del Consejo Consultivo de la AEPD son nombrados por:', 'Orden del Ministro de Justicia publicada en el BOE',
 ['Real Decreto del Consejo de Ministros', 'La Presidencia de la AEPD', 'Las Cortes Generales'], 'serán nombrados por orden del Ministro de Justicia'),
('II', T, 'a5-3', 'Los funcionarios que desarrollan actividades de investigación de la AEPD tienen la consideración de:', 'Agentes de la autoridad en el ejercicio de sus funciones',
 ['Policía judicial', 'Personal eventual', 'Peritos judiciales'], 'tendrán la consideración de agentes de la autoridad en el ejercicio de sus funciones'),
# Procedimiento y régimen sancionador
('II', P, 'a6-6', 'Plazo para resolver el procedimiento por falta de atención de una solicitud de ejercicio de derechos, desde la notificación al reclamante del acuerdo de admisión a trámite (si vence, puede considerarla estimada)', '6 meses',
 ['3 meses', '12 meses', '9 meses'], 'el plazo para resolver el procedimiento será de seis meses'),
('II', P, 'a6-6', 'Duración máxima del procedimiento sancionador ante la AEPD por posible infracción, desde el acuerdo de inicio (transcurrida, caduca)', '12 meses',
 ['6 meses', '9 meses', '18 meses'], 'El procedimiento tendrá una duración máxima de doce meses a contar desde la fecha del acuerdo de inicio'),
('II', P, 'a6-7', 'Plazo para notificar al reclamante la decisión sobre la admisión o inadmisión a trámite de su reclamación ante la AEPD', '3 meses',
 ['1 mes', '6 meses', '2 meses'], 'deberá notificarse al reclamante en el plazo de tres meses'),
('II', T, 'a7-2', 'Según el artículo 70.2, el régimen sancionador de la LOPDGDD NO es de aplicación a:', 'El delegado de protección de datos',
 ['Los responsables de los tratamientos', 'Los encargados de los tratamientos', 'Las entidades de certificación'],
 'No será de aplicación al delegado de protección de datos el régimen sancionador establecido en este Título'),
('II', P, 'a7-4', 'Plazo de prescripción de las infracciones muy graves de la LOPDGDD', '3 años',
 ['2 años', '1 año', '5 años'], 'se consideran muy graves y prescribirán a los tres años'),
('II', P, 'a7-5', 'Plazo de prescripción de las infracciones graves de la LOPDGDD', '2 años',
 ['3 años', '1 año', '6 meses'], 'se consideran graves y prescribirán a los dos años'),
('II', P, 'a7-6', 'Plazo de prescripción de las infracciones leves de la LOPDGDD', '1 año',
 ['6 meses', '2 años', '3 años'], 'Se consideran leves y prescribirán al año'),
('II', T, 'a7-8', 'Se publica en el BOE la identidad del infractor, la infracción y el importe de la sanción cuando, siendo competente la AEPD, la sanción supere el millón de euros y el infractor sea:', 'Una persona jurídica',
 ['Una persona física', 'Una Administración Pública', 'Un menor de edad'], 'la sanción fuese superior a un millón de euros y el infractor sea una persona jurídica'),
('II', T, 'a7-9', 'Cuando una Administración Pública comete una infracción de la LOPDGDD, la autoridad de protección de datos dicta resolución:', 'Declarando la infracción y estableciendo las medidas para que cese la conducta o se corrijan sus efectos',
 ['Imponiendo en todo caso una multa económica', 'Archivando el procedimiento por tratarse de una Administración', 'Remitiendo el asunto al Tribunal de Cuentas'],
 'dictará resolución declarando la infracción y estableciendo, en su caso, las medidas que proceda adoptar'),
('II', P, 'a7-10', 'Plazo de prescripción de las sanciones por importe igual o inferior a 40.000 euros', '1 año',
 ['2 años', '3 años', '6 meses'], 'a) Las sanciones por importe igual o inferior a 40.000 euros, prescriben en el plazo de un año'),
('II', P, 'a7-10', 'Plazo de prescripción de las sanciones por importe comprendido entre 40.001 y 300.000 euros', '2 años',
 ['1 año', '3 años', '4 años'], 'b) Las sanciones por importe comprendido entre 40.001 y 300.000 euros prescriben a los dos años'),
('II', P, 'a7-10', 'Plazo de prescripción de las sanciones por importe superior a 300.000 euros', '3 años',
 ['2 años', '5 años', '4 años'], 'c) Las sanciones por un importe superior a 300.000 euros prescriben a los tres años'),
]
