# Lote 26 · Ley 15/2022, integral para la igualdad de trato y la no discriminación · bloque III (tema III.7:
# políticas de igualdad y no discriminación).
NORMA, LOTE, INICIO = 'LIGT', 'lote-026', 26001
T, P = 'test', 'plazo'
PREGUNTAS = [
('III', T, 'a1', 'La Ley 15/2022 tiene por objeto garantizar y promover el derecho a la igualdad de trato y no discriminación en desarrollo de los artículos de la Constitución:', '9.2, 10 y 14',
 ['1.1, 9.3 y 103', '14, 23 y 35', '10, 53 y 149'], 'en desarrollo de los artículos 9.2, 10 y 14 de la Constitución'),
('III', T, 'a2', 'Según la Ley 15/2022, el derecho de toda persona a la igualdad de trato y no discriminación se reconoce:', 'Con independencia de su nacionalidad, de su edad y de si disfruta o no de residencia legal',
 ['Solo a las personas de nacionalidad española', 'Solo a las personas mayores de edad', 'Solo a quienes tengan residencia legal en España'],
 'con independencia de su nacionalidad, de si son menores o mayores de edad o de si disfrutan o no de residencia legal'),
('III', T, 'a2', 'Según la Ley 15/2022, la enfermedad puede amparar diferencias de trato:', 'Solo las que deriven del propio proceso de tratamiento, de las limitaciones objetivas que imponga o de razones de salud pública',
 ['En cualquier caso, si lo decide el empleador', 'Nunca, ni siquiera por razones de salud pública', 'Siempre que la enfermedad dure más de un año'],
 'La enfermedad no podrá amparar diferencias de trato distintas de las que deriven del propio proceso de tratamiento de la misma'),
('III', T, 'a4', 'Según la Ley 15/2022, no se considera discriminación la diferencia de trato que:', 'Pueda justificarse objetivamente por una finalidad legítima y como medio adecuado, necesario y proporcionado para alcanzarla',
 ['Se base en la mera conveniencia económica de quien la aplica', 'Se aplique a personas sin residencia legal', 'Se limite al ámbito privado'],
 'que pueda justificarse objetivamente por una finalidad legítima y como medio adecuado, necesario y proporcionado para alcanzarla'),
('III', T, 'a4', 'Según la Ley 15/2022, el derecho a la igualdad de trato y la no discriminación es:', 'Un principio informador del ordenamiento jurídico que se integra con carácter transversal en la interpretación y aplicación de las normas',
 ['Un derecho que solo vincula a los poderes públicos', 'Un mandato dirigido exclusivamente al legislador', 'Un principio aplicable solo en el ámbito laboral'],
 'es un principio informador del ordenamiento jurídico y, como tal, se integrará y observará con carácter transversal'),
('III', T, 'a6', 'Según la Ley 15/2022, existe discriminación por asociación cuando una persona es objeto de trato discriminatorio:', 'Debido a su relación con otra persona sobre la que concurre alguna causa de discriminación',
 ['Por pertenecer a una asociación inscrita', 'Por dos o más causas de forma simultánea', 'Por una apreciación incorrecta de sus características'],
 'debido a su relación con otra sobre la que concurra alguna de las causas previstas'),
('III', T, 'a6', 'Según la Ley 15/2022, se produce discriminación múltiple cuando una persona es discriminada:', 'De manera simultánea o consecutiva por dos o más causas de las previstas en la ley',
 ['Por varias personas a la vez', 'Varias veces por la misma causa', 'En varios ámbitos territoriales'],
 'Se produce discriminación múltiple cuando una persona es discriminada de manera simultánea o consecutiva por dos o más causas'),
('III', T, 'a6', 'Según la Ley 15/2022, la inducción a discriminar, para ser discriminatoria, ha de ser:', 'Concreta, directa y eficaz',
 ['Pública y reiterada', 'Escrita y firmada', 'Remunerada'], 'La inducción ha de ser concreta, directa y eficaz'),
('III', T, 'a2-8', 'Las disposiciones, actos o cláusulas de los negocios jurídicos que causen discriminación por alguno de los motivos de la Ley 15/2022 son:', 'Nulos de pleno derecho',
 ['Anulables', 'Válidos pero sancionables', 'Irregulares no invalidantes'], 'Son nulos de pleno derecho las disposiciones, actos o cláusulas de los negocios jurídicos'),
('III', T, 'a2-9', 'Según la Ley 15/2022, acreditada la discriminación:', 'Se presume la existencia de daño moral',
 ['Debe probarse siempre el daño moral', 'No cabe indemnización por daño moral', 'El daño moral se fija en una cuantía única por ley'],
 'Acreditada la discriminación se presumirá la existencia de daño moral'),
('III', T, 'a3-2', 'La regla de la Ley 15/2022 sobre inversión de la carga de la prueba en casos de discriminación NO se aplica a:', 'Los procesos penales ni a los procedimientos administrativos sancionadores',
 ['Los procesos civiles', 'Los procesos laborales', 'Los procesos contencioso-administrativos no sancionadores'],
 'no será de aplicación a los procesos penales ni a los procedimientos administrativos sancionadores'),
('III', T, 'a4-2', 'La Autoridad Independiente para la Igualdad de Trato y la No Discriminación puede actuar como órgano de mediación o conciliación, con el consentimiento expreso de las partes, salvo en violaciones con contenido:', 'Penal o laboral',
 ['Civil o mercantil', 'Administrativo', 'Educativo o sanitario'], 'excepción hecha de las que tengan contenido penal o laboral'),
('III', T, 'a4-2', 'Las decisiones que tome la Autoridad Independiente para la Igualdad de Trato en los procedimientos de mediación o conciliación son:', 'Vinculantes para las partes',
 ['Meras recomendaciones', 'Vinculantes solo para la Administración', 'Revisables por el Defensor del Pueblo'],
 'Las decisiones que tome la Autoridad Independiente en los procedimientos de mediación o conciliación tendrán carácter vinculante para las partes'),
('III', T, 'a4-2', 'Si una situación de discriminación investigada por la Autoridad Independiente reviste carácter de infracción penal, la Autoridad debe:', 'Cesar en la investigación y remitir el tanto de culpa al Ministerio Fiscal o a la autoridad judicial',
 ['Continuar la investigación y sancionar', 'Archivar sin más trámite', 'Remitir el asunto al Defensor del Pueblo'],
 'deberá cesar en la investigación y remitir el tanto de culpa al Ministerio Fiscal o a la autoridad judicial'),
('III', T, 'a4-3', 'La Autoridad Independiente para la Igualdad de Trato y la No Discriminación es:', 'Una entidad de derecho público del artículo 109 de la Ley 40/2015, con personalidad jurídica propia',
 ['Un órgano del Ministerio de Igualdad sin personalidad jurídica', 'Un organismo autónomo dependiente del Defensor del Pueblo', 'Una sociedad mercantil estatal'],
 'es una entidad de derecho público, de las previstas en el artículo 109 de la Ley 40/2015'),
('III', T, 'a4-3', 'La persona que preside la Autoridad Independiente para la Igualdad de Trato y la No Discriminación es nombrada:', 'Por el Gobierno mediante Real Decreto, previa comparecencia ante las comisiones correspondientes del Congreso y del Senado',
 ['Por el Congreso por mayoría de tres quintos', 'Por el Rey a propuesta del Consejo General del Poder Judicial', 'Por el Defensor del Pueblo'],
 'que será nombrada por el Gobierno mediante Real Decreto'),
('III', P, 'a4-3', 'Duración del mandato de la persona que preside la Autoridad Independiente para la Igualdad de Trato (sin posibilidad de renovación)', '5 años',
 ['4 años', '6 años', '9 años'], 'Su mandato será de cinco años sin posibilidad de renovación'),
('III', T, 'a4-7', 'La Autoridad Independiente para la Igualdad de Trato ejerce sus funciones, respecto del Defensor del Pueblo:', 'Sin perjuicio de sus competencias, pudiendo celebrar convenios de colaboración con él',
 ['Bajo su dependencia jerárquica', 'Sustituyéndolo en materia de discriminación', 'Con facultades para revisar sus resoluciones'],
 'ejercerá las funciones que tiene atribuidas en esta ley sin perjuicio de las competencias del Defensor del Pueblo'),
('III', T, 'a4-9', 'Según la Ley 15/2022, los actos u omisiones que constituyan discriminación múltiple son infracción:', 'Muy grave',
 ['Leve', 'Grave', 'Solo penal'], 'tendrán la consideración de infracciones muy graves: a) Los actos u omisiones que constituyan discriminación múltiple'),
('III', T, 'a4-9', 'Según la Ley 15/2022, toda conducta de represalia es infracción:', 'Grave',
 ['Leve', 'Muy grave', 'No constituye infracción'], 'b) Toda conducta de represalia en los términos previstos en el artículo 6 de la presente ley'),
('III', T, 'a4-10', 'Las infracciones de la Ley 15/2022 se sancionan con multas que van de:', '300 a 500.000 euros',
 ['200 a 150.000 euros', '600 a 1.000.000 de euros', '100 a 60.000 euros'], 'serán sancionadas con multas que irán de 300 a 500.000 euros'),
('III', T, 'a4-10', 'Las infracciones graves de la Ley 15/2022 se sancionan con multa de:', '10.001 a 40.000 euros',
 ['300 a 10.000 euros', '40.001 a 500.000 euros', '2.001 a 10.000 euros'], 'b) Infracciones graves entre 10.001 y 40.000 euros'),
('III', P, 'a5-3', 'Plazo de prescripción de las infracciones muy graves de la Ley 15/2022', '4 años',
 ['3 años', '5 años', '2 años'], 'y las calificadas como muy graves a los cuatro años'),
('III', P, 'a5-4', 'Plazo máximo para notificar la resolución del procedimiento sancionador de la Ley 15/2022', '6 meses',
 ['3 meses', '1 año', '9 meses'], 'El plazo máximo en que deberá notificarse la resolución del procedimiento sancionador será de seis meses'),
('III', T, 'a5-4', 'En la AGE, cuando se trate de infracciones muy graves de la Ley 15/2022 y la sanción impuesta exceda de 300.000 euros, se requiere:', 'Acuerdo del Consejo de Ministros',
 ['Autorización de las Cortes', 'Informe del Defensor del Pueblo', 'Resolución de la Autoridad Independiente'],
 'y el importe de la sanción impuesta exceda los 300.000 euros, se requerirá acuerdo del Consejo de Ministros'),
]
