# Lote 24 · Ley 38/2003, General de Subvenciones, arts. 1-44 · bloque V (tema V.6: gestión económica y
# financiera de las subvenciones): concepto, principios, bases, procedimiento, justificación, pago,
# reintegro y control financiero.
NORMA, LOTE, INICIO = 'LGS', 'lote-024', 24001
T, P = 'test', 'plazo'
PREGUNTAS = [
('V', T, 'a2', 'Uno de los requisitos para que una disposición dineraria sea subvención según la Ley 38/2003 es que la entrega se realice:', 'Sin contraprestación directa de los beneficiarios',
 ['A cambio de una contraprestación equivalente', 'Siempre a favor de personas privadas', 'Mediante contrato administrativo'],
 'a) Que la entrega se realice sin contraprestación directa de los beneficiarios'),
('V', T, 'a4', '¿Cuál de los siguientes queda excluido del ámbito de aplicación de la Ley General de Subvenciones?', 'Los premios que se otorguen sin la previa solicitud del beneficiario',
 ['Las subvenciones concedidas por las entidades locales', 'Las subvenciones concedidas en régimen de concurrencia competitiva', 'Las subvenciones nominativas de los Presupuestos Generales del Estado'],
 'a) Los premios que se otorguen sin la previa solicitud del beneficiario'),
('V', T, 'a8', 'Con carácter previo al establecimiento de subvenciones, los órganos que las propongan deben concretar sus objetivos, plazos, costes y fuentes de financiación en:', 'Un plan estratégico de subvenciones',
 ['La Base de Datos Nacional de Subvenciones', 'La memoria de análisis de impacto normativo', 'El presupuesto por programas'],
 'deberán concretar en un plan estratégico de subvenciones los objetivos y efectos que se pretenden con su aplicación'),
('V', T, 'a8', '¿Cuál de los siguientes NO figura entre los principios de gestión de las subvenciones del artículo 8.3 de la Ley 38/2003?', 'Discrecionalidad en la selección de beneficiarios',
 ['Publicidad, transparencia y concurrencia', 'Eficacia en el cumplimiento de los objetivos', 'Eficiencia en la asignación y utilización de los recursos públicos'],
 r're:a\) Publicidad, transparencia, concurrencia, objetividad, igualdad y no discriminación\. b\) Eficacia.*?c\) Eficiencia en la asignación y utilización de los recursos públicos'),
('V', T, 'a9', 'Con carácter previo al otorgamiento de las subvenciones deben aprobarse:', 'Las normas que establezcan las bases reguladoras de concesión',
 ['Las resoluciones de reintegro', 'Las cuentas justificativas', 'Los convenios con todos los beneficiarios'],
 'deberán aprobarse las normas que establezcan las bases reguladoras de concesión'),
('V', T, 'a10', 'En la Administración General del Estado son órganos competentes para conceder subvenciones, en sus respectivos ámbitos y previa consignación presupuestaria:', 'Los Ministros y los Secretarios de Estado',
 ['Los Subdirectores Generales', 'Los Delegados del Gobierno', 'Solo el Consejo de Ministros'],
 'Los Ministros y los Secretarios de Estado en la Administración General del Estado'),
('V', T, 'a10', 'La concesión de subvenciones de cuantía superior a 12 millones de euros requiere la previa autorización de:', 'El Consejo de Ministros o, si así lo establece su normativa reguladora, la Comisión Delegada del Gobierno para Asuntos Económicos',
 ['El Ministro de Hacienda', 'Las Cortes Generales', 'La Intervención General de la Administración del Estado'],
 'la concesión de subvenciones de cuantía superior a 12 millones de euros requerirá la previa autorización del Consejo de Ministros'),
('V', T, 'a11', 'Según la Ley 38/2003, tiene la consideración de beneficiario de subvenciones:', 'La persona que haya de realizar la actividad que fundamentó su otorgamiento o que se encuentre en la situación que legitima su concesión',
 ['La entidad que entrega y distribuye los fondos en nombre del órgano concedente', 'El órgano que instruye el procedimiento', 'Cualquier persona que presente solicitud'],
 'Tendrá la consideración de beneficiario de subvenciones la persona que haya de realizar la actividad que fundamentó su otorgamiento'),
('V', T, 'a12', 'Los fondos públicos que la entidad colaboradora entrega y distribuye a los beneficiarios:', 'En ningún caso se consideran integrantes de su patrimonio',
 ['Se integran en su patrimonio', 'Se integran en su patrimonio hasta que se justifiquen', 'Pasan a ser ingresos propios de la entidad'],
 'Estos fondos, en ningún caso, se considerarán integrantes de su patrimonio'),
('V', T, 'a14', 'La obtención de otras subvenciones que financien las actividades subvencionadas debe comunicarse por el beneficiario:', 'Tan pronto como se conozca y, en todo caso, antes de la justificación de la aplicación dada a los fondos',
 ['Solo al finalizar la actividad', 'En el plazo de un año', 'No es necesario comunicarla'],
 'Esta comunicación deberá efectuarse tan pronto como se conozca y, en todo caso, con anterioridad a la justificación'),
('V', T, 'a14', 'El beneficiario debe acreditar que se halla al corriente de sus obligaciones tributarias y frente a la Seguridad Social:', 'Con anterioridad a dictarse la propuesta de resolución de concesión',
 ['Después de cobrar la subvención', 'Solo si se lo pide la Intervención', 'Al presentar la cuenta justificativa'],
 'Acreditar con anterioridad a dictarse la propuesta de resolución de concesión que se halla al corriente'),
('V', P, 'a16', 'Plazo máximo de vigencia inicial del convenio de colaboración entre el órgano concedente y la entidad colaboradora', '4 años',
 ['6 años', '2 años', '5 años'], 'El convenio de colaboración no podrá tener un plazo de vigencia superior a cuatro años'),
('V', P, 'a16', 'Duración total máxima del convenio de colaboración con la entidad colaboradora, incluidas sus prórrogas (salvo subsidiación de préstamos)', '6 años',
 ['4 años', '8 años', '10 años'], 'sin que en conjunto la duración total del convenio de colaboración pueda exceder de seis años'),
('V', T, 'a17', 'En la Administración General del Estado, las bases reguladoras de la concesión de subvenciones se aprueban por:', 'Orden ministerial',
 ['Real Decreto-ley', 'Ley ordinaria', 'Resolución de la Intervención General'], 'Las citadas bases se aprobarán por orden ministerial'),
('V', T, 'a18', 'Opera como sistema nacional de publicidad de subvenciones:', 'La Base de Datos Nacional de Subvenciones',
 ['El Portal de la Transparencia exclusivamente', 'El Registro Central de Personal', 'La Plataforma de Contratación del Sector Público'],
 'La Base de Datos Nacional de Subvenciones operará como sistema nacional de publicidad de subvenciones'),
('V', T, 'a19', 'El importe de las subvenciones, aisladamente o en concurrencia con otras ayudas o ingresos:', 'En ningún caso puede superar el coste de la actividad subvencionada',
 ['Puede superar el coste hasta en un 10 por ciento', 'Puede superar el coste si lo prevén las bases', 'Debe ser igual al 50 por ciento del coste'],
 'en ningún caso podrá ser de tal cuantía que, aisladamente o en concurrencia con otras subvenciones, ayudas, ingresos o recursos, supere el coste de la actividad subvencionada'),
('V', T, 'a20', 'El órgano responsable de la administración y custodia de la Base de Datos Nacional de Subvenciones es:', 'La Intervención General de la Administración del Estado',
 ['El Tribunal de Cuentas', 'La Agencia Estatal de Administración Tributaria', 'La Dirección General de Presupuestos'],
 'La Intervención General de la Administración del Estado es el órgano responsable de la administración y custodia de la BDNS'),
('V', T, 'a22', 'El procedimiento ordinario de concesión de subvenciones se tramita en régimen de:', 'Concurrencia competitiva',
 ['Concesión directa', 'Adjudicación negociada', 'Sorteo público'], 'El procedimiento ordinario de concesión de subvenciones se tramitará en régimen de concurrencia competitiva'),
('V', T, 'a22', 'En régimen de concurrencia competitiva, la propuesta de concesión se formula al órgano concedente por:', 'Un órgano colegiado a través del órgano instructor',
 ['El propio solicitante', 'La Intervención Delegada', 'La entidad colaboradora'], 'la propuesta de concesión se formulará al órgano concedente por un órgano colegiado a través del órgano instructor'),
('V', T, 'a22', 'Pueden concederse de forma directa, entre otras, las subvenciones:', 'Previstas nominativamente en los Presupuestos',
 ['Cuyo importe supere los 12 millones de euros', 'Que soliciten más de diez interesados', 'Convocadas en el Boletín Oficial del Estado'],
 'a) Las previstas nominativamente en los Presupuestos Generales del Estado'),
('V', T, 'a23', 'El procedimiento para la concesión de subvenciones se inicia:', 'Siempre de oficio',
 ['Siempre a solicitud del interesado', 'De oficio o a solicitud, indistintamente', 'Por denuncia'], 'El procedimiento para la concesión de subvenciones se inicia siempre de oficio'),
('V', P, 'a24', 'Plazo general de emisión de los informes pedidos durante la instrucción del procedimiento de concesión de subvenciones', '10 días',
 ['15 días', '1 mes', '2 meses'], 'El plazo para su emisión será de 10 días'),
('V', P, 'a25', 'Plazo máximo para resolver y notificar el procedimiento de concesión de subvenciones, salvo ley o normativa de la Unión Europea que establezca otro mayor', '6 meses',
 ['3 meses', '1 año', '2 meses'], 'El plazo máximo para resolver y notificar la resolución del procedimiento no podrá exceder de seis meses'),
('V', T, 'a25', 'El vencimiento del plazo máximo sin haberse notificado la resolución de concesión de la subvención:', 'Legitima a los interesados para entenderla desestimada por silencio administrativo',
 ['Supone la concesión de la subvención por silencio positivo', 'Produce la caducidad del procedimiento', 'Obliga a conceder la subvención por el importe solicitado'],
 'legitima a los interesados para entender desestimada por silencio administrativo la solicitud de concesión'),
('V', T, 'a28', 'El instrumento habitual para canalizar las subvenciones previstas nominativamente en los Presupuestos Generales del Estado es:', 'El convenio',
 ['El contrato de servicios', 'La orden de bases', 'La encomienda de gestión'], 'Los convenios serán el instrumento habitual para canalizar las subvenciones previstas nominativamente'),
('V', T, 'a29', 'Si las bases reguladoras no fijan otro porcentaje, el beneficiario puede subcontratar la actividad subvencionada hasta:', 'El 50 por ciento del importe de la actividad subvencionada',
 ['El 20 por ciento', 'El 100 por ciento', 'El 25 por ciento'],
 'el beneficiario podrá subcontratar hasta un porcentaje que no exceda del 50 por ciento del importe de la actividad subvencionada'),
('V', T, 'a29', 'La subcontratación debe celebrarse por escrito y autorizarse previamente por la entidad concedente cuando exceda del 20 por ciento del importe de la subvención y dicho importe sea superior a:', '60.000 euros',
 ['15.000 euros', '30.000 euros', '100.000 euros'], 'Cuando la actividad concertada con terceros exceda del 20 por ciento del importe de la subvención y dicho importe sea superior a 60.000 euros'),
('V', T, 'a30', 'La justificación de una subvención puede revestir la forma de:', 'Cuenta justificativa del gasto realizado, módulos o estados contables, según la normativa reguladora',
 ['Solo declaración responsable del beneficiario', 'Solo certificado del Alcalde', 'Únicamente informe de auditoría'],
 'pudiendo revestir la forma de cuenta justificativa del gasto realizado o acreditarse dicho gasto por módulos o mediante la presentación de estados contables'),
('V', P, 'a30', 'Plazo máximo de presentación de la cuenta justificativa, a falta de previsión en las bases, desde la finalización del plazo para realizar la actividad', '3 meses',
 ['1 mes', '6 meses', '2 meses'], 'su presentación se realizará, como máximo, en el plazo de tres meses desde la finalización del plazo para la realización de la actividad'),
('V', T, 'a31', 'Cuando las bases no establecen plazo concreto, los gastos subvencionables deben realizarse:', 'Antes de que finalice el año natural en que se haya concedido la subvención',
 ['En los cuatro años siguientes a la concesión', 'Antes de presentar la solicitud', 'En el plazo de un mes desde la concesión'],
 'los gastos deberán realizarse antes de que finalice el año natural en que se haya concedido la subvención'),
('V', T, 'a31', 'El coste de adquisición de los gastos subvencionables:', 'En ningún caso puede ser superior al valor de mercado',
 ['Puede superar el valor de mercado hasta un 20 por ciento', 'Lo fija libremente el beneficiario', 'Debe ser inferior al 50 por ciento del valor de mercado'],
 'En ningún caso el coste de adquisición de los gastos subvencionables podrá ser superior al valor de mercado'),
('V', T, 'a31', 'Cuando el gasto subvencionable supera las cuantías del contrato menor, el beneficiario debe solicitar con carácter previo, como regla general, como mínimo:', 'Tres ofertas de diferentes proveedores',
 ['Dos ofertas', 'Cinco ofertas', 'Una oferta y un informe técnico'], 'el beneficiario deberá solicitar como mínimo tres ofertas de diferentes proveedores'),
('V', T, 'a34', 'La resolución de concesión de la subvención conlleva:', 'El compromiso del gasto correspondiente',
 ['La aprobación del gasto', 'El reconocimiento de la obligación', 'La ordenación del pago'], 'La resolución de concesión de la subvención conllevará el compromiso del gasto correspondiente'),
('V', T, 'a34', 'Con carácter general, el pago de la subvención se realiza:', 'Previa justificación por el beneficiario de la realización de la actividad',
 ['Siempre por anticipado', 'En el momento de la solicitud', 'Al año de la concesión, sin justificación'],
 'El pago de la subvención se realizará previa justificación, por el beneficiario, de la realización de la actividad'),
('V', T, 'a36', 'Es causa de nulidad de la resolución de concesión de una subvención, además de las generales de nulidad:', 'La carencia o insuficiencia de crédito',
 ['La falta de publicación en la BDNS', 'La subcontratación del 30 por ciento de la actividad', 'El retraso en la justificación'],
 'b) La carencia o insuficiencia de crédito'),
('V', T, 'a37', '¿Cuál de las siguientes es causa de reintegro de la subvención?', 'El incumplimiento de la obligación de justificación o la justificación insuficiente',
 ['La concesión por concurrencia competitiva', 'El cobro de la subvención mediante transferencia', 'La comunicación de otras ayudas antes de la justificación'],
 'c) Incumplimiento de la obligación de justificación o la justificación insuficiente'),
('V', T, 'a38', 'Las cantidades a reintegrar en materia de subvenciones tienen la consideración de:', 'Ingresos de derecho público',
 ['Ingresos de derecho privado', 'Deudas civiles entre particulares', 'Tasas'], 'Las cantidades a reintegrar tendrán la consideración de ingresos de derecho público'),
('V', T, 'a38', 'Salvo que la Ley de Presupuestos establezca otro, el interés de demora aplicable en materia de subvenciones es:', 'El interés legal del dinero incrementado en un 25 por ciento',
 ['El interés legal del dinero sin incremento', 'El interés legal del dinero incrementado en un 10 por ciento', 'El doble del interés legal del dinero'],
 'será el interés legal del dinero incrementado en un 25 por ciento'),
('V', P, 'a39', 'Plazo de prescripción del derecho de la Administración a reconocer o liquidar el reintegro de una subvención', '4 años',
 ['5 años', '2 años', '10 años'], 'Prescribirá a los cuatro años el derecho de la Administración a reconocer o liquidar el reintegro'),
('V', T, 'a40', 'Los administradores de las sociedades mercantiles que consintieran los incumplimientos responden de la obligación de reintegro:', 'Subsidiariamente',
 ['Solidariamente', 'Mancomunadamente', 'No responden en ningún caso'], 'Responderán subsidiariamente de la obligación de reintegro los administradores de las sociedades mercantiles'),
('V', T, 'a41', 'Es competente para exigir el reintegro de subvenciones mediante la resolución del procedimiento:', 'El órgano concedente',
 ['La Intervención General de la Administración del Estado', 'El Tribunal de Cuentas', 'La Agencia Tributaria'],
 'El órgano concedente será el competente para exigir del beneficiario o entidad colaboradora el reintegro'),
('V', P, 'a42', 'Plazo máximo para resolver y notificar el procedimiento de reintegro de subvenciones, desde el acuerdo de iniciación', '12 meses',
 ['6 meses', '3 meses', '4 años'], 'El plazo máximo para resolver y notificar la resolución del procedimiento de reintegro será de 12 meses'),
('V', T, 'a42', 'Si transcurre el plazo para resolver el procedimiento de reintegro sin resolución expresa notificada:', 'Se produce la caducidad del procedimiento',
 ['Se entiende estimado el reintegro', 'Se entiende condonada la deuda definitivamente', 'Se prorroga automáticamente seis meses'],
 'se producirá la caducidad del procedimiento'),
('V', T, 'a42', 'La resolución del procedimiento de reintegro de subvenciones:', 'Pone fin a la vía administrativa',
 ['Es recurrible en alzada ante el Ministro', 'Requiere ratificación del Consejo de Ministros', 'Solo es eficaz tras su aprobación por el Tribunal de Cuentas'],
 'La resolución del procedimiento de reintegro pondrá fin a la vía administrativa'),
('V', T, 'a44', 'La competencia para el ejercicio del control financiero de las subvenciones de la Administración General del Estado corresponde a:', 'La Intervención General de la Administración del Estado',
 ['El órgano concedente exclusivamente', 'La Dirección General del Tesoro', 'El Defensor del Pueblo'],
 'La competencia para el ejercicio del control financiero de subvenciones corresponderá a la Intervención General de la Administración del Estado'),
]
