# Lote 28 · LO 6/1985, del Poder Judicial · bloque I (tema I.4: el Poder Judicial; el CGPJ: designación,
# organización y funciones; el Tribunal Supremo; la organización judicial española). Se evitan los datos
# ya preguntados desde la CE (arts. 117-127).
NORMA, LOTE, INICIO = 'LOPJ', 'lote-028', 28001
T, P = 'test', 'plazo'
PREGUNTAS = [
('I', T, 'aprimero', 'Según la LOPJ, los Jueces y Magistrados integrantes del Poder Judicial son:', 'Independientes, inamovibles, responsables y sometidos únicamente a la Constitución y al imperio de la ley',
 ['Independientes, temporales y sometidos al Gobierno', 'Elegidos por sufragio y sometidos al Parlamento', 'Inamovibles e irresponsables'],
 'independientes, inamovibles, responsables y sometidos únicamente a la Constitución y al imperio de la ley'),
('I', T, 'acuarto', 'Según la LOPJ, la jurisdicción se extiende:', 'A todas las personas, a todas las materias y a todo el territorio español',
 ['Solo a los ciudadanos españoles', 'Solo a las materias civiles y penales', 'Solo al territorio peninsular'],
 'La jurisdicción se extiende a todas las personas, a todas las materias y a todo el territorio español'),
('I', T, 'aquinto', 'Según la LOPJ, procede plantear la cuestión de inconstitucionalidad cuando:', 'Por vía interpretativa no sea posible la acomodación de la norma al ordenamiento constitucional',
 ['Lo solicite cualquiera de las partes, en todo caso', 'La norma sea un reglamento', 'El juez discrepe de la jurisprudencia del Tribunal Supremo'],
 'cuando por vía interpretativa no sea posible la acomodación de la norma al ordenamiento constitucional'),
('I', T, 'anoveno', 'Los Tribunales del orden civil conocen, además de las materias que les son propias, de:', 'Todas aquellas que no estén atribuidas a otro orden jurisdiccional',
 ['Los recursos contra reglamentos', 'Las causas criminales leves', 'Los conflictos laborales colectivos'],
 'de todas aquellas que no estén atribuidas a otro orden jurisdiccional'),
('I', T, 'adoce', 'Los Jueces y Tribunales, los órganos de gobierno de los mismos o el CGPJ, sobre la aplicación o interpretación del ordenamiento jurídico que hagan sus inferiores en el ejercicio de su función jurisdiccional:', 'No pueden dictar instrucciones, de carácter general o particular',
 ['Pueden dictar instrucciones generales', 'Pueden dictar instrucciones particulares si las publican', 'Pueden dictar instrucciones con autorización del Ministro de Justicia'],
 'Tampoco podrán los Jueces y Tribunales, órganos de gobierno de los mismos o el Consejo General del Poder Judicial dictar instrucciones'),
('I', T, 'acatorce', 'Los Jueces y Magistrados que se consideren inquietados o perturbados en su independencia lo pondrán en conocimiento de:', 'El Consejo General del Poder Judicial',
 ['El Ministro de Justicia', 'El Tribunal Constitucional', 'El Defensor del Pueblo'],
 'lo pondrán en conocimiento del Consejo General del Poder Judicial'),
('I', T, 'aveintiseis', '¿Cuál de los siguientes NO figura entre los Tribunales a los que la LOPJ atribuye el ejercicio de la potestad jurisdiccional?', 'El Tribunal de Cuentas',
 ['Los Tribunales de Instancia', 'Las Audiencias Provinciales', 'El Tribunal Central de Instancia'],
 r're:a\) Jueces y juezas de paz\. b\) Tribunales de Instancia\. c\) Audiencias Provinciales\. d\) Tribunales Superiores de Justicia\. e\) Tribunal Central de Instancia\. f\) Audiencia Nacional\. g\) Tribunal Supremo'),
('I', T, 'atreinta', 'A efectos judiciales, el Estado se organiza territorialmente en:', 'Municipios, Partidos, Provincias y Comunidades Autónomas',
 ['Municipios, Comarcas y Provincias', 'Distritos, Provincias y Regiones', 'Partidos y Circunscripciones'],
 'El Estado se organiza territorialmente, a efectos judiciales, en Municipios, Partidos, Provincias y Comunidades Autónomas'),
('I', T, 'acincuentaytres', 'El Tribunal Supremo es el órgano jurisdiccional superior en todos los órdenes:', 'Salvo lo dispuesto en materia de garantías constitucionales',
 ['Sin excepción alguna', 'Salvo en materia penal', 'Salvo en materia de derecho foral'],
 'es el órgano jurisdiccional superior en todos los órdenes, salvo lo dispuesto en materia de garantías Constitucionales'),
('I', T, 'acincuentaycinco', 'La Sala Tercera del Tribunal Supremo es la Sala:', 'De lo Contencioso-Administrativo',
 ['De lo Penal', 'De lo Social', 'De lo Militar'], 'Tercera: De lo Contencioso-Administrativo'),
('I', T, 'acincuentaycinco', 'La Sala Quinta del Tribunal Supremo es la Sala:', 'De lo Militar',
 ['De lo Social', 'De lo Civil', 'De Apelación'], 'Quinta: De lo Militar'),
('I', T, 'acincuentaysiete', 'La instrucción y enjuiciamiento de las causas contra el Presidente del Gobierno, los Diputados y Senadores corresponde a:', 'La Sala de lo Penal del Tribunal Supremo',
 ['La Sala de lo Penal de la Audiencia Nacional', 'El Tribunal Superior de Justicia de Madrid', 'El Tribunal Constitucional'],
 r're:La Sala de lo Penal del Tribunal Supremo conocerá:.*?De la instrucción y enjuiciamiento de las causas contra el Presidente del Gobierno'),
('I', T, 'asesentayuno', 'Los procesos de declaración de ilegalidad y consecuente disolución de los partidos políticos los conoce:', 'Una Sala especial del Tribunal Supremo formada por su Presidente, los Presidentes de Sala y el Magistrado más antiguo y el más moderno de cada una',
 ['La Sala de lo Penal de la Audiencia Nacional', 'El Tribunal Constitucional en Pleno', 'La Sala de lo Contencioso-Administrativo del Tribunal Superior de Justicia de Madrid'],
 r're:Una Sala formada por el Presidente del Tribunal Supremo, los Presidentes de Sala y el Magistrado más antiguo y el más moderno de cada una de ellas conocerá:.*?6\.º De los procesos de declaración de ilegalidad y consecuente disolución de los partidos políticos'),
('I', T, 'asesentaydos', 'La Audiencia Nacional, con sede en Madrid, tiene jurisdicción:', 'En toda España',
 ['Solo en la Comunidad de Madrid', 'Solo en los delitos cometidos en el extranjero', 'Solo en el orden penal'],
 'La Audiencia Nacional, con sede en la villa de Madrid, tiene jurisdicción en toda España'),
('I', T, 'asesentaycuatro', '¿Cuál de las siguientes Salas NO integra la Audiencia Nacional?', 'De lo Civil',
 ['De Apelación', 'De lo Penal', 'De lo Social'],
 'La Audiencia Nacional estará integrada por las siguientes Salas: De Apelación. De lo Penal. De lo Contencioso-Administrativo. De lo Social'),
('I', T, 'asetentaydos', 'El Tribunal Superior de Justicia está integrado por las Salas:', 'De lo Civil y Penal, de lo Contencioso-Administrativo y de lo Social',
 ['De lo Civil, de lo Penal y de lo Militar', 'De Apelación y de lo Penal', 'De lo Civil y Penal y de lo Mercantil'],
 'El Tribunal Superior de Justicia estará integrado por las siguientes Salas: de lo Civil y Penal, de lo Contencioso-Administrativo y de lo Social'),
('I', T, 'asetentaydos', 'El Presidente del Tribunal Superior de Justicia, mientras desempeñe el cargo, tiene la consideración de:', 'Magistrado del Tribunal Supremo',
 ['Consejero de la Comunidad Autónoma', 'Vocal del Consejo General del Poder Judicial', 'Presidente de Audiencia Provincial'],
 'y tendrá la consideración de Magistrado del Tribunal Supremo mientras desempeñe el cargo'),
('I', T, 'aochenta', 'Las Audiencias Provinciales tienen su sede en:', 'La capital de la provincia, de la que toman su nombre',
 ['La capital de la Comunidad Autónoma', 'El municipio más poblado del partido judicial', 'Madrid'],
 'Las Audiencias Provinciales, que tendrán su sede en la capital de la provincia, de la que tomarán su nombre'),
('I', T, 'aochentaycuatro', 'Según la LOPJ, habrá un Tribunal de Instancia en cada:', 'Partido judicial, con sede en su capital',
 ['Provincia', 'Comunidad Autónoma', 'Municipio de más de 20.000 habitantes'],
 'Habrá un Tribunal de Instancia en cada partido judicial, con sede en su capital'),
('I', T, 'aquinientoscincuentayocho', 'El gobierno del Poder Judicial corresponde a:', 'El Consejo General del Poder Judicial',
 ['El Ministerio de Justicia', 'El Tribunal Supremo', 'Las Salas de Gobierno de los Tribunales Superiores de Justicia'],
 'El gobierno del Poder Judicial corresponde al Consejo General del Poder Judicial'),
('I', T, 'aquinientossesentaysiete', 'Cada una de las Cámaras elige a diez Vocales del CGPJ por mayoría de:', 'Tres quintos de sus miembros',
 ['Mayoría absoluta', 'Dos tercios de sus miembros', 'Mayoría simple'],
 'Cada una de las Cámaras elegirá, por mayoría de tres quintos de sus miembros, a diez Vocales'),
('I', T, 'aquinientossesentaysiete', 'De los diez Vocales del CGPJ que elige cada Cámara:', 'Cuatro son juristas de reconocida competencia y seis corresponden al turno judicial',
 ['Cinco son juristas y cinco jueces', 'Seis son juristas y cuatro jueces', 'Todos son jueces en activo'],
 'a diez Vocales, cuatro entre juristas de reconocida competencia con más de quince años de ejercicio en su profesión y seis correspondientes al turno judicial'),
('I', T, 'aquinientossesentaysiete', 'Para ser Vocal del CGPJ por el turno de juristas de reconocida competencia se exige más de:', 'Quince años de ejercicio en su profesión',
 ['Diez años de ejercicio', 'Veinte años de ejercicio', 'Veinticinco años de ejercicio'],
 'cuatro entre juristas de reconocida competencia con más de quince años de ejercicio en su profesión'),
('I', T, 'aquinientossesentayocho', 'El proceso de renovación del CGPJ se prepara disponiendo el Presidente del Tribunal Supremo la remisión de datos y la apertura del plazo de candidaturas judiciales:', 'Cuatro meses antes de la expiración del mandato',
 ['Seis meses antes de la expiración del mandato', 'Un mes antes de la expiración del mandato', 'El mismo día de la expiración del mandato'],
 'cuatro meses antes de la expiración del mencionado plazo'),
('I', T, 'aquinientossetenta', 'Si ninguna de las dos Cámaras ha designado en plazo a los Vocales del nuevo CGPJ:', 'El Consejo saliente continúa en funciones hasta la toma de posesión del nuevo',
 ['El Gobierno designa Vocales provisionales', 'El Tribunal Supremo asume sus funciones', 'Se disuelve el Consejo y sus funciones pasan al Ministerio de Justicia'],
 'el Consejo saliente continuará en funciones hasta la toma de posesión del nuevo'),
('I', T, 'aquinientossetentaynueve', 'Los Vocales del CGPJ que sean funcionarios públicos quedan en la situación administrativa de:', 'Servicios especiales',
 ['Servicio activo', 'Excedencia voluntaria', 'Servicios en otras Administraciones'],
 'La situación administrativa para los que sean funcionarios públicos, tanto judiciales como no judiciales, será la de servicios especiales'),
('I', T, 'aquinientosochentayuno', 'Los Vocales del Consejo General del Poder Judicial:', 'No están ligados por mandato imperativo',
 ['Están sujetos a las instrucciones de la Cámara que los eligió', 'Representan a las asociaciones judiciales que los propusieron', 'Deben seguir las indicaciones del Ministro de Justicia'],
 'Los Vocales del Consejo General del Poder Judicial no estarán ligados por mandato imperativo'),
('I', T, 'aquinientosochentaydos', 'El cese de un Vocal del CGPJ por incapacidad, incompatibilidad o incumplimiento grave de sus deberes lo aprecia el Pleno por:', 'Mayoría de tres quintos',
 ['Mayoría absoluta', 'Mayoría simple', 'Unanimidad'],
 'apreciadas por el Pleno del Consejo General del Poder Judicial mediante mayoría de tres quintos'),
('I', T, 'aquinientosochentaycuatro', 'Mientras dure su mandato, los Vocales del CGPJ:', 'No pueden ser promovidos a Magistrado del Tribunal Supremo ni del Tribunal Constitucional',
 ['Pueden ser promovidos a Magistrado del Tribunal Supremo', 'Pueden ser nombrados Presidente de Tribunal Superior de Justicia', 'Pueden ser nombrados para cargos de libre designación en la carrera judicial'],
 'no podrán ser promovidos mientras dure su mandato a la categoría de Magistrado del Tribunal Supremo o a Magistrado del Tribunal Constitucional'),
('I', T, 'aquinientosochentaycinco', 'La primera autoridad judicial de la Nación es:', 'El Presidente del Tribunal Supremo y del Consejo General del Poder Judicial',
 ['El Ministro de Justicia', 'El Presidente del Tribunal Constitucional', 'El Fiscal General del Estado'],
 'El Presidente del Tribunal Supremo y del Consejo General del Poder Judicial es la primera autoridad judicial de la Nación'),
('I', T, 'aquinientosochentayseis', 'Para ser elegido Presidente del Tribunal Supremo y del CGPJ siendo jurista de reconocida competencia se exige una antigüedad en el ejercicio de la profesión de más de:', 'Veinticinco años',
 ['Quince años', 'Veinte años', 'Treinta años'], 'o bien ser un jurista de reconocida competencia con más de veinticinco años de antigüedad en el ejercicio de su profesión'),
('I', T, 'aquinientosochentayseis', 'El Presidente del Tribunal Supremo y del CGPJ es elegido por el Pleno en votación nominal por mayoría de:', 'Tres quintos de los miembros del Pleno',
 ['Mayoría absoluta de los miembros del Pleno', 'Dos tercios de los miembros del Pleno', 'Mayoría simple de los presentes'],
 'siendo elegido quien en votación nominal obtenga el apoyo de la mayoría de tres quintos de los miembros del Pleno'),
('I', T, 'aquinientosochentayseis', 'El nombramiento del Presidente del Tribunal Supremo por el Rey se hace mediante Real Decreto refrendado por:', 'El Presidente del Gobierno',
 ['El Ministro de Justicia', 'El Presidente del Congreso', 'El Vicepresidente del Tribunal Supremo'],
 'El Presidente del Tribunal Supremo será nombrado por el Rey mediante Real Decreto refrendado por el Presidente del Gobierno'),
('I', T, 'aquinientosochentaysiete', 'El Presidente del Tribunal Supremo y del CGPJ puede ser reelegido:', 'Por una sola vez, para un nuevo mandato',
 ['Indefinidamente', 'No puede ser reelegido', 'Dos veces como máximo'],
 'podrá ser reelegido y nombrado, por una sola vez, para un nuevo mandato'),
('I', T, 'aquinientosnoventa', 'En los casos de cese anticipado del Presidente del Tribunal Supremo y del CGPJ, ejerce el cargo en funciones hasta el nombramiento de uno nuevo:', 'El Vicepresidente del Tribunal Supremo',
 ['El Vocal de más edad', 'El Presidente de la Sala Primera', 'El Secretario General del Consejo'],
 'El Vicepresidente ejercerá, en funciones, el cargo de Presidente del Tribunal Supremo'),
('I', T, 'aquinientosnoventaycinco', '¿Cuál de las siguientes NO es una de las Comisiones del CGPJ previstas en la LOPJ?', 'La Comisión de Nombramientos Judiciales',
 ['La Comisión Permanente', 'La Comisión Disciplinaria', 'La Comisión de Igualdad'],
 'existirán las siguientes Comisiones: Permanente, de Calificación, Disciplinaria, de Asuntos Económicos, de Igualdad y de Supervisión y Control de Protección de Datos'),
('I', T, 'aseiscientos', 'El Pleno del CGPJ se reúne en sesión ordinaria:', 'Una vez al mes',
 ['Una vez a la semana', 'Una vez al trimestre', 'Dos veces al año'], 'El Pleno se reunirá en sesión ordinaria, a convocatoria del Presidente, una vez al mes'),
('I', T, 'aseiscientos', 'Fuera de la elección de su Presidente, para la válida constitución del Pleno del CGPJ es necesaria como mínimo la presencia de:', 'Diez Vocales y el Presidente',
 ['Doce Vocales', 'La mitad más uno de los Vocales', 'Quince Vocales y el Presidente'],
 'será siempre necesaria, como mínimo, la presencia de diez Vocales y el Presidente'),
('I', T, 'aseiscientosuno', 'La Comisión Permanente del CGPJ está compuesta por el Presidente y:', 'Siete Vocales: cuatro del turno judicial y tres del turno de juristas',
 ['Cinco Vocales del turno judicial', 'Diez Vocales elegidos por sorteo', 'Tres Vocales de cada turno'],
 'y otros siete Vocales: cuatro de los nombrados por el turno judicial y tres de los designados por el turno de juristas de reconocida competencia'),
('I', T, 'aseiscientostres', 'El mandato de los Vocales integrantes de la Comisión Disciplinaria del CGPJ, salvo sustituciones, es de:', 'Cinco años',
 ['Un año', 'Tres años', 'Dos años'], 'El Pleno elegirá a los Vocales integrantes de la Comisión Disciplinaria, cuyo mandato, salvo las sustituciones que procedan, será de cinco años'),
('I', T, 'aseiscientossiete', 'La instrucción de los expedientes disciplinarios a Jueces y Magistrados corresponde a:', 'El Promotor de la Acción Disciplinaria',
 ['La Comisión Permanente', 'El Ministerio Fiscal', 'El Presidente del Tribunal Superior de Justicia'],
 'Corresponde al Promotor de la Acción Disciplinaria la instrucción de los expedientes disciplinarios'),
('I', T, 'aseiscientosdiez', 'La Comisión de Igualdad del CGPJ está integrada por:', 'Tres Vocales',
 ['Cinco Vocales', 'Siete Vocales', 'Todos los Vocales de origen judicial'], 'La Comisión de Igualdad estará integrada por tres Vocales'),
('I', T, 'aseiscientostreinta', 'Como regla general, los acuerdos de los órganos colegiados del CGPJ se adoptan por:', 'Mayoría absoluta de los miembros presentes',
 ['Mayoría de tres quintos en todo caso', 'Unanimidad', 'Mayoría simple de los Vocales del turno judicial'],
 'serán adoptados por mayoría absoluta de los miembros presentes'),
]
